import type { BreakDefinition } from "./types";

export const BREAKS: readonly BreakDefinition[] = [
  {
    index: 0,
    name: "Cowell's",
    sizeCopy: "2–3 ft, mellow",
    beachSlug: "cowell-beach-santa-cruz-ca",
    beachPath: "/beaches",
    usesBeachFallback: true,
    sectionLabel: "slow",
    sectionSpeed: 0.045,
    throwCadence: "never",
    threshold: 8,
    heatSeconds: 90,
    maxWaves: 3,
    palette: {
      skyTop: "#D98B9E",
      skyBottom: "#F2C94C",
      sun: "#F5EEDC",
      water: "#7FA7B8",
      waterDeep: "#0B3A75",
    },
  },
  {
    index: 1,
    name: "Steamer Lane",
    sizeCopy: "4–6 ft, long walls",
    beachSlug: "steamer-lane-santa-cruz-ca",
    beachPath: "/ca/santa-cruz/steamer-lane-santa-cruz-ca",
    usesBeachFallback: false,
    sectionLabel: "medium",
    sectionSpeed: 0.06,
    throwCadence: "rare",
    threshold: 11,
    heatSeconds: 88,
    maxWaves: 3,
    palette: {
      skyTop: "#252D6B",
      skyBottom: "#D98B9E",
      sun: "#F2C94C",
      water: "#507E91",
      waterDeep: "#0B3A75",
    },
  },
  {
    index: 2,
    name: "Trestles",
    sizeCopy: "4–6 ft, rippable",
    beachSlug: "lower-trestles",
    beachPath: "/ca/san-onofre/lower-trestles",
    usesBeachFallback: false,
    sectionLabel: "medium, ramps",
    sectionSpeed: 0.066,
    throwCadence: "rare",
    threshold: 13,
    heatSeconds: 86,
    maxWaves: 3,
    palette: {
      skyTop: "#252D6B",
      skyBottom: "#F78E42",
      sun: "#F2C94C",
      water: "#7FA7B8",
      waterDeep: "#0B3A75",
    },
  },
  {
    index: 3,
    name: "Ocean Beach",
    sizeCopy: "6–8 ft, heavy",
    beachSlug: "ocean-beach-middle-san-francisco-ca",
    beachPath: "/ca/san-francisco/ocean-beach-middle-san-francisco-ca",
    usesBeachFallback: false,
    sectionLabel: "fast",
    sectionSpeed: 0.082,
    throwCadence: "sometimes",
    threshold: 14.5,
    heatSeconds: 82,
    maxWaves: 3,
    palette: {
      skyTop: "#394654",
      skyBottom: "#7FA7B8",
      sun: "#E5D4B3",
      water: "#496F70",
      waterDeep: "#1A3543",
    },
  },
  {
    index: 4,
    name: "Pipeline",
    sizeCopy: "8–10 ft, hollow",
    beachSlug: "pipeline",
    beachPath: "/hi/haleiwa/pipeline",
    usesBeachFallback: false,
    sectionLabel: "fast",
    sectionSpeed: 0.094,
    throwCadence: "often",
    threshold: 16,
    heatSeconds: 78,
    maxWaves: 3,
    palette: {
      skyTop: "#B91C1C",
      skyBottom: "#F2C94C",
      sun: "#F5EEDC",
      water: "#287C8B",
      waterDeep: "#0B3A75",
    },
  },
  {
    index: 5,
    name: "Mavericks",
    sizeCopy: "25 ft, the fifty-year swell",
    beachSlug: "mavericks-half-moon-bay-ca",
    beachPath: "/ca/half-moon-bay/mavericks-half-moon-bay-ca",
    usesBeachFallback: false,
    sectionLabel: "very fast",
    sectionSpeed: 0.112,
    throwCadence: "once",
    threshold: 9,
    heatSeconds: 60,
    maxWaves: 1,
    palette: {
      skyTop: "#1A2430",
      skyBottom: "#627283",
      sun: "#D9C49C",
      water: "#334C61",
      waterDeep: "#0D1020",
    },
  },
] as const;

export function getBreak(index: number): BreakDefinition {
  return BREAKS[index] ?? BREAKS[0];
}
