import { NextRequest, NextResponse } from "next/server";
import {
  createSuccessResponse,
  createErrorResponse,
  createForecastUpdateResponse,
} from "@/lib/api-response-utils";
import {
  updateBeachForecast,
  updateAllBeachForecasts,
} from "@/lib/utils/forecast-service-utils";

// API endpoint to update enhanced forecasts for all beaches
export async function POST(request: NextRequest) {
  try {
    console.log("Starting enhanced forecast update process");

    // Check if we should update a specific beach or all beaches
    const { beachId } = await request.json().catch(() => ({ beachId: null }));

    if (beachId) {
      // Update a specific beach
      console.log(`Updating enhanced forecasts for beach: ${beachId}`);

      const data = await updateBeachForecast(beachId);

      return createSuccessResponse(
        {
          message: `Enhanced forecasts updated for ${data.beach}`,
          forecastsCount: data.forecastsGenerated,
        },
        "Beach forecast update completed"
      );
    } else {
      // Update all beaches
      const result = await updateAllBeachForecasts();

      return createForecastUpdateResponse(
        result.results || [],
        "Enhanced forecasts update complete"
      );
    }
  } catch (error) {
    console.error("❌ Error updating enhanced forecasts:", error);
    console.error("❌ Error stack:", error instanceof Error ? error.stack : "No stack trace");
    console.error("❌ Error details:", {
      message: error instanceof Error ? error.message : "Unknown error",
      name: error instanceof Error ? error.name : "Unknown",
      cause: error instanceof Error ? error.cause : undefined,
    });
    return createErrorResponse(
      "Failed to update enhanced forecasts",
      error instanceof Error ? error.message : "Unknown error"
    );
  }
}

// API endpoint to get enhanced forecasts for a beach
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const beachId = searchParams.get("beachId");
    const rawDays = searchParams.get("days");
    let days = 10;
    if (rawDays != null) {
      const parsed = parseInt(rawDays as string, 10);
      if (!Number.isNaN(parsed) && parsed > 0 && parsed <= 30) {
        days = parsed;
      }
    }

    if (!beachId) {
      return createErrorResponse("Beach ID is required", null, 400);
    }

    const { fetchBeachForecasts, updateBeachForecast } = await import(
      "@/lib/utils/forecast-service-utils"
    );

    // PERFORMANCE OPTIMIZATION: Always return cached data immediately
    // Never block page load on forecast generation (moved to background job)
    let data = (await fetchBeachForecasts(beachId, days)) || { forecasts: [] };

    // Check if data is stale or missing
    const hasData = data.forecasts && data.forecasts.length > 0;
    let isStale = false;
    let dataAge = "unknown";

    if (hasData) {
      // Check if the most recent forecast is older than 6 hours (NOAA update cycle)
      const mostRecent = data.forecasts[0];
      const lastUpdated = new Date(mostRecent.updated_at);
      const sixHoursAgo = new Date(Date.now() - 6 * 60 * 60 * 1000);
      isStale = lastUpdated < sixHoursAgo;

      // Calculate age for logging
      const ageMs = Date.now() - lastUpdated.getTime();
      const ageHours = Math.floor(ageMs / (1000 * 60 * 60));
      dataAge = `${ageHours}h old`;
    }

    // Log data status but DO NOT generate forecasts on page load
    if (!hasData) {
      console.log(
        `⚠️ No cached forecasts for beach ${beachId}. Should be pre-generated by background job.`
      );
    } else if (isStale) {
      console.log(
        `ℹ️ Returning cached forecasts for beach ${beachId} (${dataAge}, considered stale). Background job should refresh.`
      );
    } else {
      console.log(
        `✅ Using fresh cached data for beach ${beachId} (${dataAge}, ${data.forecasts.length} forecasts)`
      );
    }

    // PERFORMANCE OPTIMIZATION: Add Cache-Control headers
    // Cache for 10 minutes (600s) with stale-while-revalidate for 1 hour
    // This allows browsers/CDN to serve cached data while fetching fresh data in background
    const response = createSuccessResponse({
      beachId,
      days,
      ...data,
    });

    // Add caching headers
    response.headers.set(
      "Cache-Control",
      "public, s-maxage=600, stale-while-revalidate=3600"
    );

    return response;
  } catch (error) {
    console.error("❌ Error fetching enhanced forecasts:", error);
    console.error("❌ Error stack:", error instanceof Error ? error.stack : "No stack trace");
    console.error("❌ Error details:", {
      message: error instanceof Error ? error.message : "Unknown error",
      name: error instanceof Error ? error.name : "Unknown",
      cause: error instanceof Error ? error.cause : undefined,
    });
    return createErrorResponse(
      "Failed to fetch enhanced forecasts",
      error instanceof Error ? error.message : "Unknown error"
    );
  }
}
