export const PLAY_PALETTE = {
  deepBlue: "#0B5FA5",
  oceanBlue: "#127CC1",
  cyan: "#29C7F6",
  mint: "#75E3E1",
  sky: "#B8F1FF",
  trough: "#0B6C82",
  pocket: "#0F8EA3",
  face: "#1DB6C9",
  sunlit: "#4FE1E7",
  glow: "#8EF7F2",
  foam: "#F8FEFF",
  foamCool: "#E6F9FF",
  foamShadow: "#B7ECF8",
  foamBlue: "#7ED0E8",
  sun: "#FFF0B0",
  peach: "#FFBE8A",
  coral: "#FF8D73",
  pink: "#F57CB3",
  lavender: "#7D7CCF",
  yellow: "#FFD447",
  orange: "#FF9A3D",
  hotCoral: "#FF5C6C",
  green: "#43D87D",
  wipeout: "#D93B72",
  woodLight: "#B9844A",
  wood: "#8E5E34",
  woodDark: "#5F3B1F",
  navy: "#12324A",
  shadow: "#0A1D2B",
  skin: "#F7C29B",
  skinMid: "#DD9B73",
  skinShadow: "#A65D44",
  hair: "#4B2B1E",
  hairLight: "#6A3D2A",
  shorts: "#1C4970",
  shortsBlue: "#2B6A9E",
  surferCoral: "#FF6A67",
  board: "#FFFDF4",
  boardShadow: "#C9E6F3",
} as const;

export const PIXEL_COLOURS: Readonly<Record<string, string>> = {
  n: PLAY_PALETTE.shadow,
  N: PLAY_PALETTE.navy,
  w: PLAY_PALETTE.board,
  q: PLAY_PALETTE.boardShadow,
  c: PLAY_PALETTE.cyan,
  a: PLAY_PALETTE.mint,
  f: PLAY_PALETTE.foam,
  F: PLAY_PALETTE.foamShadow,
  s: PLAY_PALETTE.skin,
  m: PLAY_PALETTE.skinMid,
  d: PLAY_PALETTE.skinShadow,
  h: PLAY_PALETTE.hair,
  H: PLAY_PALETTE.hairLight,
  b: PLAY_PALETTE.shorts,
  B: PLAY_PALETTE.shortsBlue,
  r: PLAY_PALETTE.surferCoral,
  y: PLAY_PALETTE.yellow,
  o: PLAY_PALETTE.orange,
  p: PLAY_PALETTE.pink,
  l: PLAY_PALETTE.lavender,
  t: PLAY_PALETTE.trough,
  u: PLAY_PALETTE.pocket,
  v: PLAY_PALETTE.face,
  x: PLAY_PALETTE.sunlit,
  g: PLAY_PALETTE.glow,
  L: PLAY_PALETTE.woodLight,
  M: PLAY_PALETTE.wood,
  D: PLAY_PALETTE.woodDark,
};

export interface PixelTextureDefinition {
  key: string;
  rows: readonly string[];
}

function rows(value: string): readonly string[] {
  return value.trim().split("\n");
}

function riderOnly(textureRows: readonly string[]): readonly string[] {
  const boardStart = textureRows.findIndex((row) => /n{8}/.test(row));
  if (boardStart < 0) return textureRows;

  let bodyEnd = boardStart;
  while (bodyEnd > 0 && /^\.+$/.test(textureRows[bodyEnd - 1])) bodyEnd -= 1;
  return textureRows.slice(0, bodyEnd);
}

const TRIM = rows(`
.......hhh..............
......hHHh..............
.......sss..............
......mssm..............
.....mmrrmmm............
......rbbd..............
.....mbBBbm.............
....mm.b..mm............
...ss..b...ss...........
.......b................
......m.m...............
.....m...m..............
....s.....s.............
........................
...nnnnnnnnnnnnnn.......
..nwwwwwwwwwwwwwwn......
.nwwwwcccwwwwwwwwwn.....
..nqqqqqqqqqqqqqqn......
...nnnnnnnnnnnnnn.......
`);

const PUMP = rows(`
........hhh.............
.......hHHh.............
........sss.............
......mmssmmm...........
....sssrrdddss..........
......rbbbb.............
.....mbBBBbm............
....m..b...mm...........
...s...b....s...........
.......b................
.....mm.mm..............
....s....s..............
........................
..nnnnnnnnnnnnnnnn......
.nwwwwwwwwwwwwwwwwn.....
nwwwwwcccwwwwwwwwwwn....
.nqqqqqqqqqqqqqqqqn.....
..nnnnnnnnnnnnnnnn......
`);

const LOW = rows(`
............hhh.........
...........hHHh.........
............sss.........
........mmmssm..........
.....sssmrrdmmm.........
........rbbbbm..........
......mmBBBBbss.........
....sss..b..mm..........
.........b..............
......mmm.mmm...........
....sss.....sss.........
........................
..nnnnnnnnnnnnnnnnn.....
.nwwwwwwwwwwwwwwwwwn....
nwwwwwcccwwwwwwwwwwwn...
.nqqqqqqqqqqqqqqqqqn....
..nnnnnnnnnnnnnnnnn.....
`);

const TURN = rows(`
..............hhh.......
.............hHHh.......
..............sss.......
............mmssm.......
........mmmmrrdmm.......
.....ssss..rbbbbm.......
...........bBBBbm.......
.......mmm.b..m.........
....ssss...b...s........
...........b............
.........mm.mm..........
.......ss....ss.........
........................
.....nnnnnnnnnnnnnnn....
...nnwwwwwwwwwwwwwwn....
.nnwwwwwcccwwwwwwwwn....
nqqqqqqqqqqqqqqqqqn.....
.nnnnnnnnnnnnnnnnn......
`);

const CUTBACK = rows(`
.....hhh................
....hHHh................
.....sss................
...mmssmmm..............
sssmrrd...sss...........
....rbbbbm..............
...mbBBBbmmm............
..m...b....sss..........
.s....b.................
......b.................
...mmm.mmm..............
..s.......s.............
........................
....nnnnnnnnnnnnnnn.....
...nwwwwwwwwwwwwwwwn....
..nwwwwwcccwwwwwwwwwn...
...nqqqqqqqqqqqqqqqn....
....nnnnnnnnnnnnnnn.....
`);

const TUCK = rows(`
...........hhh..........
..........hHHh..........
...........sss..........
........mmssm...........
......mmrrdddmm.........
....ss..rbbbb..ss.......
........bBBBb...........
......mmb...bmm.........
....ss..b...b.ss........
........m...m...........
.......s.....s..........
........................
..nnnnnnnnnnnnnnnnn.....
.nwwwwwwwwwwwwwwwwwn....
nwwwwwcccwwwwwwwwwwwn...
.nqqqqqqqqqqqqqqqqqn....
..nnnnnnnnnnnnnnnnn.....
`);

const AIR = rows(`
........hhh.............
.......hHHh.............
........sss.............
.....mmmssmmm...........
...ss..rrd..sss.........
.......rbbbb.............
......mbBBBbm............
.....m..b..m.............
....s...b...s............
.......m.m................
......s...s...............
..........................
......nnnnnnnnnnnnnn......
....nnwwwwwwwwwwwwwwnn....
..nnwwwwwcccwwwwwwwwwwnn..
.nqqqqqqqqqqqqqqqqqqqqqn.
..nnnnnnnnnnnnnnnnnnnnn..
`);

const GRAB = rows(`
..........hhh...........
.........hHHh...........
..........sss...........
.......mmmssm...........
.....ssmrrdmmm..........
........rbbbb.ss........
.......mbBBBbm..........
......m..b..m...........
.....s...b...s..........
........m...m...........
.......s...ss...........
..........s.............
.....nnnnnnnnnnnnnn.....
...nnwwwwwwwwwwwwwwnn...
.nnwwwwwcccwwwwwwwwwwnn.
nqqqqqqqqqqqqqqqqqqqqqn
.nnnnnnnnnnnnnnnnnnnnn.
`);

const WIPEOUT_A = rows(`
..........hhh...........
.........hHHh...........
..........sss...........
......mmmssmmm..........
....ss..rrd..ss.........
........rbbbb............
.......mbBBBbm...........
.....ss..b..m...........
.........b...s..........
.......mm.m.............
......s....s............
`);

const WIPEOUT_B = rows(`
..........s.............
......mmm.m.............
....ss..mbbbb...........
.........BBBr...........
.......mmmrrmmm.........
.....sss.dss..sss.......
..........sss...........
.........hHHh...........
..........hhh...........
`);

const BOARD = rows(`
..nnnnnnnnnnnnnnnnnn....
.nwwwwwwwwwwwwwwwwwwn...
nwwwwwwcccwwwwwwwwwwwn..
.nqqqqqqqqqqqqqqqqqqn...
..nnnnnnnnnnnnnnnnnn....
`);

const FOAM = rows(`
.....f..................
..f.FF.f...f............
.fFFFFF.F.FFf...........
fFFfFFFFFfFFFFf.........
.FFFFFFFFFFFFF..........
..FFFFFFFFFFF...........
`);

const SPRAY = rows(`
.........f..............
......f.....f...........
...f....F.......f.......
.....F.....f.F..........
..f.....F.......f.......
`);

const WAKE = rows(`
fFFff...................
..fFFFFff...............
......fFFFFFff..........
............fFFFff......
`);

const SPARKLE = rows(`
..f..
.fff.
fffff
.fff.
..f..
`);

const CLOUD = rows(`
.....fff........
..ffffffffff....
.fffffffffffff..
fffffffffffffff.
`);

const PALM = rows(`
......NNN.......
..NNN.NNN.NNN...
...NNNNNNNN.....
.....NNNN.......
......D.........
.....MD.........
.....MD.........
....M.D.........
`);

const MOUNTAIN = rows(`
.......l........
......lll.......
....lllllll.....
..llpppppplll...
llpppNNNpppppll.
NNNNNNNNNNNNNNNN
`);

const SUN = rows(`
..yyyyy..
.yyyyyyy.
yyyyyyyyy
yyyyyyyyy
yyyyyyyyy
.yyyyyyy.
..yyyyy..
`);

const GULL_UP = rows(`
..nn.......nn..
...nfff..ffn...
....ffffff.....
......fffo.....
`);

const GULL_DOWN = rows(`
.....nfffn.....
...nfffffffn...
..nn.......nn..
`);

const PIER = rows(`
LLLLLLLL
LMMMMMML
MDDMMDDM
MDDMMDDM
MDDMMDDM
MDDMMDDM
MDDMMDDM
MDDMMDDM
MDDMMDDM
MDDMMDDM
MDDMMDDM
MDDMMDDM
`);

const BRACE = rows(`
LLL..........LLL
MMMMD......DMMMM
MDDM.MD..DM.MDDM
MDDM..DMM D..MDDM
MDDM..DMM D..MDDM
MDDM.DM..MD.MDDM
MDDMD......DMMDDM
`);

const BUOY = rows(`
....y....
...yyy...
....N....
...NNN...
..rrrrr..
..rwwwr..
..rrrrr..
...rrr...
....r....
`);

const POSE_FRAMES: readonly [string, readonly string[]][] = [
  ["surfer-idle-0", TRIM], ["surfer-idle-1", PUMP],
  ["surfer-pump-0", TRIM], ["surfer-pump-1", PUMP], ["surfer-pump-2", LOW], ["surfer-pump-3", PUMP],
  ["surfer-low-0", LOW], ["surfer-low-1", TUCK],
  ["surfer-bottom-turn-0", LOW], ["surfer-bottom-turn-1", TURN], ["surfer-bottom-turn-2", TRIM],
  ["surfer-top-turn-0", TRIM], ["surfer-top-turn-1", TURN], ["surfer-top-turn-2", CUTBACK],
  ["surfer-cutback-init-0", TURN], ["surfer-cutback-init-1", CUTBACK],
  ["surfer-cutback-rebound-0", CUTBACK], ["surfer-cutback-rebound-1", LOW],
  ["surfer-barrel-0", TUCK], ["surfer-barrel-1", LOW],
  ["surfer-air-takeoff-0", TURN], ["surfer-air-takeoff-1", AIR],
  ["surfer-air-straight-0", AIR], ["surfer-air-straight-1", TRIM],
  ["surfer-air-grab-0", GRAB], ["surfer-air-grab-1", AIR],
  ["surfer-landing-0", AIR], ["surfer-landing-1", LOW],
  ["surfer-wobble-0", TURN], ["surfer-wobble-1", CUTBACK],
  ["surfer-wipeout-0", WIPEOUT_A], ["surfer-wipeout-1", WIPEOUT_B],
  ["surfer-wipeout-2", WIPEOUT_A], ["surfer-wipeout-3", WIPEOUT_B],
];

export const PIXEL_TEXTURES: readonly PixelTextureDefinition[] = [
  ...POSE_FRAMES.map(([key, textureRows]) => ({
    key,
    rows: key.startsWith("surfer-wipeout") ? textureRows : riderOnly(textureRows),
  })),
  { key: "surfboard", rows: BOARD },
  { key: "foam-chunk", rows: FOAM },
  { key: "spray-burst", rows: SPRAY },
  { key: "wake-streak", rows: WAKE },
  { key: "sparkle", rows: SPARKLE },
  { key: "cloud", rows: CLOUD },
  { key: "palm", rows: PALM },
  { key: "mountain", rows: MOUNTAIN },
  { key: "sun", rows: SUN },
  { key: "seagull-0", rows: GULL_UP },
  { key: "seagull-1", rows: GULL_DOWN },
  { key: "pier-post", rows: PIER },
  { key: "pier-brace", rows: BRACE },
  { key: "buoy", rows: BUOY },
] as const;
