BEGIN;
SET LOCAL ROLE service_role;
DO $$
DECLARE
  u uuid := '11111111-1111-4111-8111-111111111111';
  result jsonb;
  attempt uuid;
BEGIN
  result := claim_email_contact(u, 'surfer@example.com', 'trial_invitation');
  ASSERT result->>'reason' = 'disabled';
  UPDATE email_contact_controls SET enabled = true;
  result := claim_email_contact(u, 'wrong@example.com', 'trial_invitation');
  ASSERT result->>'reason' = 'ineligible_profile';
  result := claim_email_contact(u, 'surfer@example.com', 'trial_invitation');
  ASSERT result->>'reason' = 'missing_consent_or_review';
  INSERT INTO email_contact_state(user_id, approved_campaign, marketing_consent_at, consent_reference, history_reviewed_at)
    VALUES (u, 'test', now(), 'fixture-only', now());
  result := claim_email_contact(u, 'surfer@example.com', 'trial_invitation');
  ASSERT result->>'reason' = 'trial_eligibility_unverified';
  UPDATE email_contact_state SET trial_eligible_until = now() + interval '1 day', trial_eligibility_reference = 'fixture-only' WHERE user_id = u;
  INSERT INTO email_suppression_list VALUES ('surfer@example.com');
  result := claim_email_contact(u, 'surfer@example.com', 'trial_invitation');
  ASSERT result->>'reason' = 'suppressed';
  DELETE FROM email_suppression_list WHERE email = 'surfer@example.com';
  INSERT INTO user_entitlements(user_id) VALUES (u);
  result := claim_email_contact(u, 'surfer@example.com', 'trial_invitation');
  ASSERT result->>'reason' = 'entitlement';
  DELETE FROM user_entitlements WHERE user_id = u;
  INSERT INTO email_send_log VALUES (u, 'welcome', 'prior-receipt', now() - interval '1 day');
  result := claim_email_contact(u, 'surfer@example.com', 'trial_invitation');
  ASSERT result->>'reason' = 'contact_cooldown';
  DELETE FROM email_send_log WHERE user_id = u;
  result := claim_email_contact(u, 'SURFER@example.com', 'trial_invitation');
  ASSERT result->>'allowed' = 'true';
  attempt := (result->>'attempt_id')::uuid;
  result := claim_email_contact(u, 'surfer@example.com', 'trial_invitation');
  ASSERT result->>'reason' = 'already_attempted';
  result := claim_email_contact(u, 'surfer@example.com', 'weekly_recap');
  ASSERT result->>'reason' = 'unresolved_attempt';
  PERFORM finish_email_contact(attempt, 'provider-1');
  PERFORM finish_email_contact(attempt, 'provider-1');
  ASSERT (SELECT count(*) FROM email_contact_attempts WHERE provider_id = 'provider-1') = 1;
  result := claim_email_contact(u, 'surfer@example.com', 'weekly_recap');
  ASSERT result->>'reason' = 'contact_cooldown';
  UPDATE email_contact_attempts SET claimed_at = now() - interval '4 days' WHERE id = attempt;
  result := claim_email_contact(u, 'surfer@example.com', 'weekly_recap');
  ASSERT result->>'allowed' = 'true';
  PERFORM record_email_reply('reply-1', 'svix-1', 'SURFER@example.com', now());
  PERFORM record_email_reply('reply-1', 'svix-2', 'SURFER@example.com', now());
  ASSERT (SELECT count(*) FROM email_reply_events) = 1;
  ASSERT (SELECT paused_at IS NOT NULL FROM email_contact_state WHERE user_id = u);
  result := claim_email_contact(u, 'surfer@example.com', 'session_prompt');
  ASSERT result->>'reason' = 'reply_paused';
  ASSERT NOT has_table_privilege('authenticated', 'public.email_contact_state', 'SELECT');
  ASSERT NOT has_function_privilege('anon', 'public.claim_email_contact(uuid,text,text)', 'EXECUTE');
  ASSERT (SELECT relrowsecurity FROM pg_class WHERE oid = 'public.email_reply_events'::regclass);
  INSERT INTO auth.users VALUES ('22222222-2222-4222-8222-222222222222');
  INSERT INTO profiles VALUES ('22222222-2222-4222-8222-222222222222', 'second@example.com', true, true);
  UPDATE email_contact_controls SET daily_cap = 1;
  result := claim_email_contact('22222222-2222-4222-8222-222222222222', 'second@example.com', 'weekly_recap');
  ASSERT result->>'reason' = 'daily_cap';
  UPDATE email_contact_controls SET daily_cap = 15;
  result := claim_email_contact('22222222-2222-4222-8222-222222222222', 'second@example.com', 'trial_started');
  ASSERT result->>'reason' = 'trial_not_active';
END;
$$;
ROLLBACK;
