interface FigurePosterProps {
  kind: "period-morph" | "origin-fetch";
}

/**
 * Static SVG snapshot of a figure. Serves two jobs:
 *  1. next/dynamic loading fallback (never blocks LCP — this is the initial paint)
 *  2. prefers-reduced-motion static state
 */
export function FigurePoster({ kind }: FigurePosterProps) {
  const summary =
    kind === "period-morph"
      ? "Groundswell has long, evenly spaced, clean wave lines; wind swell has short, choppy, closely spaced lines. Swell period is the number that tells them apart."
      : "Groundswell is generated by a distant storm and travels thousands of miles as clean lines; wind swell is generated by local wind close to shore and arrives as short chop.";

  return (
    <div
      className="relative overflow-hidden rounded-lg border-[1.5px] border-[#11100D] bg-[#e2e9e8]"
      role="img"
      aria-label={summary}
    >
      <span className="sr-only">
        {kind === "period-morph"
          ? "Swell period separates long clean lines from short choppy lines. Read period first."
          : `${summary} Read period first.`}
      </span>
      <svg viewBox="0 0 680 230" className="block h-[230px] w-full" aria-hidden="true">
        <rect x="0" y="0" width="680" height="230" fill="#e2e9e8" />
        {/* beach strip */}
        <rect x="586" y="0" width="94" height="230" fill="#D9C49C" />
        <rect x="583" y="0" width="3" height="230" fill="rgba(255,255,255,0.55)" />
        {kind === "period-morph"
          ? // left half: choppy wind swell; right half: clean groundswell lines
            [...Array(18)].map((_, i) => {
              const ground = i > 8;
              const x = 20 + i * (ground ? 34 : 20);
              const stroke = ground ? "#0B3A75" : "#7FA7B8";
              const w = ground ? 3 : 1.4;
              return (
                <path
                  key={i}
                  d={`M ${x} -4 C ${x + (ground ? 2 : 8)} 60, ${x - (ground ? 2 : 8)} 170, ${x} 234`}
                  stroke={stroke}
                  strokeWidth={w}
                  fill="none"
                  opacity={0.85}
                />
              );
            })
          : [...Array(9)].map((_, i) => {
              const x = 40 + i * 60;
              return <path key={i} d={`M ${x} -4 C ${x + 3} 60, ${x - 3} 170, ${x} 234`} stroke="#0B3A75" strokeWidth={3} fill="none" opacity={0.8} />;
            })}
      </svg>
      <div className="absolute left-2 top-2 rotate-[-2deg] rounded-[3px] bg-[#11100D] px-2 py-1 font-display text-[13px] font-black tracking-wider text-[#F4EBD8]">
        {kind === "period-morph" ? "GROUNDSWELL vs WIND SWELL" : "STORM → SHORE"}
      </div>
    </div>
  );
}
