interface FigurePosterProps {
  kind:
    | "period-morph"
    | "origin-fetch"
    | "wave-height-reference"
    | "tide-window";
}

/**
 * Static SVG snapshot of a figure. Serves two jobs:
 *  1. next/dynamic loading fallback (never blocks LCP — this is the initial paint)
 *  2. prefers-reduced-motion static state
 */
export function FigurePoster({ kind }: FigurePosterProps) {
  const summaries: Record<FigurePosterProps["kind"], string> = {
    "period-morph":
      "Groundswell has long, evenly spaced, clean wave lines; wind swell has short, choppy, closely spaced lines. Swell period is the number that tells them apart.",
    "origin-fetch":
      "Groundswell is generated by a distant storm and travels thousands of miles as clean lines; wind swell is generated by local wind close to shore and arrives as short chop.",
    "wave-height-reference":
      "A three-foot significant wave-height forecast can produce a four-and-a-half to six-foot breaking face, while the Hawaiian scale call is roughly half the face.",
    "tide-window":
      "A static tide curve rises from low to high and falls back to low over twelve hours and twenty-five minutes, with spring tides swinging farther than neap tides.",
  };
  const badges: Record<FigurePosterProps["kind"], string> = {
    "period-morph": "GROUNDSWELL vs WIND SWELL",
    "origin-fetch": "STORM → SHORE",
    "wave-height-reference": "ONE SWELL / THREE RULERS",
    "tide-window": "LOW → HIGH → LOW",
  };
  const summary = summaries[kind];

  return (
    <div
      className="relative overflow-hidden rounded-lg border-[1.5px] border-[#11100D] bg-[#e2e9e8]"
      role="img"
      aria-label={summary}
    >
      <span className="sr-only">{summary}</span>
      <svg viewBox="0 0 680 230" className="block h-[230px] w-full" aria-hidden="true">
        <rect x="0" y="0" width="680" height="230" fill="#e2e9e8" />
        {kind === "period-morph" || kind === "origin-fetch" ? (
          <>
            <rect x="586" y="0" width="94" height="230" fill="#D9C49C" />
            <rect
              x="583"
              y="0"
              width="3"
              height="230"
              fill="rgba(255,255,255,0.55)"
            />
          </>
        ) : null}
        {kind === "period-morph" ? (
          <>
            {/* left half: choppy wind swell; right half: clean groundswell lines */}
            {[...Array(18)].map((_, i) => {
              const ground = i > 8;
              const x = 20 + i * (ground ? 34 : 20);
              const stroke = ground ? "#0B3A75" : "#7FA7B8";
              const w = ground ? 3 : 1.4;
              return (
                <path
                  key={i}
                  d={`M ${x} -4 C ${x + (ground ? 2 : 8)} 60, ${x - (ground ? 2 : 8)} 170, ${x} 234`}
                  stroke={stroke}
                  strokeWidth={w}
                  fill="none"
                  opacity={0.85}
                />
              );
            })}
          </>
        ) : null}
        {kind === "origin-fetch"
          ? [...Array(9)].map((_, i) => {
              const x = 40 + i * 60;
              return (
                <path
                  key={i}
                  d={`M ${x} -4 C ${x + 3} 60, ${x - 3} 170, ${x} 234`}
                  stroke="#0B3A75"
                  strokeWidth={3}
                  fill="none"
                  opacity={0.8}
                />
              );
            })
          : null}
        {kind === "wave-height-reference" ? (
          <>
            <rect x="570" y="0" width="110" height="230" fill="#D9C49C" />
            <path
              d="M20 188 C88 179 142 193 220 184 C274 178 313 185 348 184"
              fill="none"
              stroke="#7FA7B8"
              strokeWidth="3"
            />
            <path
              d="M70 184 C101 150 139 150 170 184"
              fill="none"
              stroke="#0B3A75"
              strokeWidth="5"
            />
            <path
              d="M310 194 C365 188 387 148 414 91 C441 39 499 43 548 81 C504 73 471 98 465 126 C504 135 531 157 546 188 C480 202 391 203 310 194Z"
              fill="#0B3A75"
              opacity="0.92"
            />
            <path
              d="M414 91 C449 54 501 54 548 81 C505 74 475 98 465 126 C444 112 429 100 414 91Z"
              fill="#F4EBD8"
              opacity="0.9"
            />
            <line
              x1="111"
              y1="143"
              x2="111"
              y2="185"
              stroke="#F78E42"
              strokeWidth="3"
            />
            <line
              x1="101"
              y1="143"
              x2="121"
              y2="143"
              stroke="#F78E42"
              strokeWidth="3"
            />
            <line
              x1="101"
              y1="185"
              x2="121"
              y2="185"
              stroke="#F78E42"
              strokeWidth="3"
            />
            <text x="130" y="160" fill="#11100D" fontSize="15" fontWeight="900">
              3 FT Hs
            </text>
            <text x="433" y="33" fill="#11100D" fontSize="15" fontWeight="900">
              4.5–6 FT FACE
            </text>
          </>
        ) : null}
        {kind === "tide-window" ? (
          <>
            <rect x="32" y="42" width="616" height="158" fill="#D8E3E2" />
            <rect
              x="32"
              y="150"
              width="616"
              height="50"
              fill="#D9C49C"
              opacity="0.5"
            />
            {[42, 95, 150, 200].map((y) => (
              <line
                key={y}
                x1="32"
                y1={y}
                x2="648"
                y2={y}
                stroke="#11100D"
                strokeWidth="1"
                strokeDasharray="5 7"
                opacity="0.25"
              />
            ))}
            <path
              d="M 32 200 C 132 200 210 61 340 61 C 470 61 548 200 648 200 L 648 200 L 32 200 Z"
              fill="#7FA7B8"
              opacity="0.35"
            />
            <path
              d="M 32 200 C 132 200 210 61 340 61 C 470 61 548 200 648 200"
              fill="none"
              stroke="#0B3A75"
              strokeWidth="5"
              strokeLinecap="round"
            />
            <circle
              cx="236"
              cy="101"
              r="9"
              fill="#F78E42"
              stroke="#11100D"
              strokeWidth="3"
            />
            <text x="32" y="221" fill="#11100D" fontSize="13" fontWeight="900">
              LOW
            </text>
            <text x="320" y="53" fill="#11100D" fontSize="13" fontWeight="900">
              HIGH
            </text>
            <text x="614" y="221" fill="#11100D" fontSize="13" fontWeight="900">
              LOW
            </text>
          </>
        ) : null}
      </svg>
      <div className="absolute left-2 top-2 rotate-[-2deg] rounded-[3px] bg-[#11100D] px-2 py-1 font-display text-[13px] font-black tracking-wider text-[#F4EBD8]">
        {badges[kind]}
      </div>
    </div>
  );
}
