"use client";

import { useEffect, useRef, useState } from "react";
import { FigureFrame } from "./figure-frame";
import { FigurePoster } from "./figure-poster";

export default function SwellOriginFetch() {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [reduced, setReduced] = useState(true); // static until we confirm motion is allowed (SSR-safe default)

  useEffect(() => {
    const prefersReduced =
      !window.matchMedia || window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    setReduced(prefersReduced);
    if (prefersReduced) return;

    const canvas = canvasRef.current;
    const ctx = canvas?.getContext("2d");
    if (!canvas || !ctx) return;

    let raf = 0;
    let phase = 0;
    const dpr = Math.max(1, Math.min(2, window.devicePixelRatio || 1));
    const resize = () => {
      const w = canvas.clientWidth || 680;
      const h = canvas.clientHeight || 230;
      canvas.width = w * dpr;
      canvas.height = h * dpr;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    };
    resize();
    window.addEventListener("resize", resize);

    const draw = () => {
      const w = canvas.clientWidth || 680;
      const h = canvas.clientHeight || 230;
      ctx.clearRect(0, 0, w, h);
      ctx.fillStyle = "#e2e9e8";
      ctx.fillRect(0, 0, w, h);
      // storm marker top-left
      ctx.fillStyle = "rgba(37,45,107,0.9)";
      ctx.beginPath();
      ctx.arc(56, 46, 22, 0, Math.PI * 2);
      ctx.fill();
      // long clean groundswell lines travelling storm -> shore (right)
      for (let i = 0; i < 7; i++) {
        const x = ((i * 96 + phase) % (w + 96)) - 48;
        ctx.beginPath();
        ctx.lineWidth = 3;
        ctx.strokeStyle = "rgba(11,58,117,0.8)";
        for (let y = -4; y <= h + 4; y += 8) ctx[y <= -4 ? "moveTo" : "lineTo"](x + Math.sin(y * 0.04) * 2, y);
        ctx.stroke();
      }
      // local wind chop bottom band
      for (let i = 0; i < 40; i++) {
        const x = ((i * 20 + phase * 1.6) % (w + 20)) - 10;
        ctx.beginPath();
        ctx.lineWidth = 1;
        ctx.strokeStyle = "rgba(127,167,184,0.5)";
        ctx.moveTo(x, h - 46);
        ctx.lineTo(x + 8, h - 30 + Math.sin(i) * 4);
        ctx.stroke();
      }
      phase += 0.5;
      if (phase > 1e6) phase = 0;
      raf = requestAnimationFrame(draw);
    };
    draw();

    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("resize", resize);
    };
  }, []);

  return (
    <FigureFrame
      kicker="Where it comes from"
      title="Storm → Shore"
      summary="Groundswell travels across the basin as clean lines; wind swell is generated by local wind close to shore and arrives as short chop."
      caption="Distant storm energy = long clean lines. Local wind = short chop."
    >
      {reduced ? (
        <FigurePoster kind="origin-fetch" />
      ) : (
        <div className="relative overflow-hidden rounded-lg border-[1.5px] border-[#11100D] bg-[#e2e9e8]">
          <canvas ref={canvasRef} className="block h-[230px] w-full" />
        </div>
      )}
    </FigureFrame>
  );
}
