export interface UserOwnedTable {
  column: string;
  refColumn: string;
  refSchema: "auth" | "public";
  refTable: "profiles" | "users";
  schema: "auth" | "public";
  table: string;
}

export const USER_OWNED_TABLES: UserOwnedTable[] = [
  { schema: "auth", table: "identities", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "auth", table: "mfa_factors", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "auth", table: "oauth_authorizations", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "auth", table: "oauth_consents", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "auth", table: "one_time_tokens", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "auth", table: "sessions", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "activation_push_log", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "admin_audit_log", column: "admin_user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "alert_deliveries", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "alert_delivery_attempts", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "alert_queue", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "alert_rules", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "beach_photos_history", column: "changed_by", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "beach_review_likes", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "beach_reviews", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "beach_reviews_history", column: "changed_by", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "beaches", column: "owner_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "comments", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "content_reports", column: "moderator_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "content_reports", column: "reporter_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "content_reports", column: "target_owner_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "custom_spots", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "email_send_log", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "favorite_beaches", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "forecast_accuracy_votes", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "forecast_alert_deliveries", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "intel_post_confirmations", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "intel_posts", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "intel_reports", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "intel_votes", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "notification_events", column: "actor_user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "notification_events", column: "recipient_user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "notification_send_log", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "notifications", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "pending_alert_captures", column: "consumed_user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "personalization_milestones", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "push_notification_log", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "recommendation_session_contexts", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "referrals", column: "referee_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "referrals", column: "referrer_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "roadmap_item_submissions", column: "submitter_user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "roadmap_votes", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "saved_windows", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "session_forecast_snapshots", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "session_invitations", column: "invitee_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "session_invitations", column: "inviter_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "session_likes", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "session_logs", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "session_media", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "session_media_history", column: "changed_by", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "session_share_links", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "session_shares", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "sessions", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "spot_feedback", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "storage_usage", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "trial_ending_push_log", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "user_activities", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "user_badges", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "user_beach_affinity", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "user_blocks", column: "blocked_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "user_blocks", column: "blocker_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "user_devices", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "user_email_prefs", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "user_entitlements", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "user_events", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "user_follows", column: "follower_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "user_follows", column: "following_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "user_implicit_preferences", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "user_surf_preferences", column: "user_id", refSchema: "public", refTable: "profiles", refColumn: "id" },
  { schema: "public", table: "user_surf_preferences", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "user_xp", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
  { schema: "public", table: "xp_events", column: "user_id", refSchema: "auth", refTable: "users", refColumn: "id" },
];
