-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.beach_recommendation_calibration (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  beach_id uuid NOT NULL,
  window_start date NOT NULL,
  window_end date NOT NULL,
  samples_count integer NOT NULL DEFAULT 0,
  best_swell_dir_deg_min smallint,
  best_swell_dir_deg_max smallint,
  best_wind_offshore_deg smallint,
  best_wind_tol_deg smallint,
  best_tide_ft_min numeric,
  best_tide_ft_max numeric,
  skill_level_inferred text,
  method text NOT NULL DEFAULT 'default_seed'::text,
  metrics jsonb,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  cal_window daterange DEFAULT daterange(window_start, window_end, '[]'::text),
  CONSTRAINT beach_recommendation_calibration_pkey PRIMARY KEY (id),
  CONSTRAINT beach_recommendation_calibration_beach_id_fkey FOREIGN KEY (beach_id) REFERENCES public.beaches(id)
);
CREATE TABLE public.beach_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  beach_id uuid NOT NULL,
  user_id uuid NOT NULL,
  overall_rating integer NOT NULL CHECK (overall_rating >= 1 AND overall_rating <= 5),
  wave_quality_rating integer NOT NULL CHECK (wave_quality_rating >= 1 AND wave_quality_rating <= 5),
  crowd_density_rating integer NOT NULL CHECK (crowd_density_rating >= 1 AND crowd_density_rating <= 5),
  parking_rating integer NOT NULL CHECK (parking_rating >= 1 AND parking_rating <= 5),
  accessibility_rating integer NOT NULL CHECK (accessibility_rating >= 1 AND accessibility_rating <= 5),
  title character varying NOT NULL,
  content text NOT NULL,
  visit_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT beach_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT beach_reviews_beach_id_fkey FOREIGN KEY (beach_id) REFERENCES public.beaches(id),
  CONSTRAINT beach_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.beaches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  location text NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  coordinates USER-DEFINED DEFAULT (st_setsrid(st_makepoint((longitude)::double precision, (latitude)::double precision), 4326))::geography,
  description text NOT NULL,
  wave_quality_rating numeric,
  crowd_density_rating numeric,
  parking_rating numeric,
  accessibility_rating numeric,
  owner_id uuid,
  is_private boolean NOT NULL DEFAULT false,
  break_type text,
  shoreline_aspect_deg smallint CHECK (shoreline_aspect_deg >= 0 AND shoreline_aspect_deg < 360),
  swell_window_min_deg smallint CHECK (swell_window_min_deg >= 0 AND swell_window_min_deg < 360),
  swell_window_max_deg smallint CHECK (swell_window_max_deg >= 0 AND swell_window_max_deg < 360),
  wind_offshore_deg smallint CHECK (wind_offshore_deg >= 0 AND wind_offshore_deg < 360),
  wind_offshore_tol_deg smallint CHECK (wind_offshore_tol_deg >= 0 AND wind_offshore_tol_deg <= 90),
  wind_cross_shore_ok_kt smallint CHECK (wind_cross_shore_ok_kt >= 0),
  wind_onshore_bad_kt smallint CHECK (wind_onshore_bad_kt >= 0),
  preferred_tide_ft_min numeric,
  preferred_tide_ft_max numeric,
  skill_level text,
  best_swell_cardinals ARRAY,
  best_wind_cardinals ARRAY,
  preference_model jsonb,
  w_wind numeric DEFAULT 0.300 CHECK (w_wind >= 0::numeric AND w_wind <= 1::numeric),
  w_swell numeric DEFAULT 0.250 CHECK (w_swell >= 0::numeric AND w_swell <= 1::numeric),
  w_tide numeric DEFAULT 0.200 CHECK (w_tide >= 0::numeric AND w_tide <= 1::numeric),
  w_period numeric DEFAULT 0.150 CHECK (w_period >= 0::numeric AND w_wind <= 1::numeric),
  w_height numeric DEFAULT 0.100 CHECK (w_height >= 0::numeric AND w_height <= 1::numeric),
  cdip_station text,
  ndbc_station text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT beaches_pkey PRIMARY KEY (id),
  CONSTRAINT beaches_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.boards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  board_type text NOT NULL,
  dimensions text NOT NULL,
  description text,
  image_url text,
  session_count integer DEFAULT 0,
  size text,
  volume numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT boards_pkey PRIMARY KEY (id),
  CONSTRAINT boards_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.buoys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  buoy_uuid text NOT NULL,
  buoy_name text,
  kind text DEFAULT 'buoy'::text CHECK (kind = ANY (ARRAY['buoy'::text, 'station'::text])),
  active boolean DEFAULT true,
  measurement_units text DEFAULT 'metric'::text CHECK (measurement_units = ANY (ARRAY['metric'::text, 'imperial'::text])),
  air_temperature numeric,
  water_temperature numeric,
  wave_period numeric,
  wave_height numeric,
  wind_speed numeric,
  wind_gust numeric,
  wind_direction integer,
  tides jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deactivated_at timestamp with time zone,
  CONSTRAINT buoys_pkey PRIMARY KEY (id)
);
CREATE TABLE public.check_ins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  beach_id uuid NOT NULL,
  checked_in_at timestamp with time zone NOT NULL DEFAULT now(),
  wave_height numeric CHECK (wave_height >= 0::numeric AND wave_height <= 50::numeric),
  wind_speed numeric CHECK (wind_speed >= 0::numeric AND wind_speed <= 150::numeric),
  wind_direction text CHECK (wind_direction = ANY (ARRAY['N'::text, 'NE'::text, 'E'::text, 'SE'::text, 'S'::text, 'SW'::text, 'W'::text, 'NW'::text, 'OFFSHORE'::text, 'ONSHORE'::text, 'CROSS'::text])),
  water_temp numeric CHECK (water_temp >= 32::numeric AND water_temp <= 100::numeric),
  crowd_level integer CHECK (crowd_level >= 1 AND crowd_level <= 5),
  vibe text,
  forecast_accuracy_rating text NOT NULL CHECK (forecast_accuracy_rating = ANY (ARRAY['accurate'::text, 'somewhat'::text, 'inaccurate'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT check_ins_pkey PRIMARY KEY (id),
  CONSTRAINT check_ins_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT check_ins_beach_id_fkey FOREIGN KEY (beach_id) REFERENCES public.beaches(id)
);
CREATE TABLE public.comments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  parent_comment uuid,
  user_id uuid NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT comments_pkey PRIMARY KEY (id),
  CONSTRAINT comments_parent_comment_fkey FOREIGN KEY (parent_comment) REFERENCES public.comments(id),
  CONSTRAINT comments_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id),
  CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.favorite_beaches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  beach_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT favorite_beaches_pkey PRIMARY KEY (id),
  CONSTRAINT favorite_beaches_beach_id_fkey FOREIGN KEY (beach_id) REFERENCES public.beaches(id),
  CONSTRAINT favorite_beaches_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.intel_post_confirmations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  intel_post_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT intel_post_confirmations_pkey PRIMARY KEY (id),
  CONSTRAINT intel_post_confirmations_intel_post_id_fkey FOREIGN KEY (intel_post_id) REFERENCES public.intel_posts(id),
  CONSTRAINT intel_post_confirmations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.intel_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  tag text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  photo_url text,
  photo_storage_path text,
  confirmations_count integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  wave_height numeric,
  wind_speed numeric,
  wind_direction text,
  water_temp numeric,
  crowd_level integer,
  wave_types ARRAY,
  forecast_accuracy text,
  CONSTRAINT intel_posts_pkey PRIMARY KEY (id),
  CONSTRAINT intel_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.marine_forecasts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  beach_id uuid NOT NULL,
  ts timestamp with time zone NOT NULL,
  wave_height_m numeric,
  wave_period_s numeric,
  wave_direction_deg numeric,
  wind_speed_ms numeric,
  wind_direction_deg numeric,
  source text NOT NULL CHECK (source = ANY (ARRAY['open-meteo'::text, 'cdip'::text, 'ndbc'::text])),
  is_observed boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT marine_forecasts_pkey PRIMARY KEY (id),
  CONSTRAINT marine_forecasts_beach_id_fkey FOREIGN KEY (beach_id) REFERENCES public.beaches(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text,
  avatar_url text,
  bio text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  location text,
  experience_level text,
  favorite_spot text,
  instagram text,
  twitter text,
  email text,
  phone_number text,
  default_beach_id uuid,
  notification_session_reminders boolean DEFAULT true,
  notification_community_replies boolean DEFAULT true,
  followers_count integer DEFAULT 0,
  following_count integer DEFAULT 0,
  email_session_invites boolean NOT NULL DEFAULT true,
  inapp_session_invites boolean NOT NULL DEFAULT true,
  digest_session_invites boolean NOT NULL DEFAULT false,
  is_admin boolean NOT NULL DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_default_beach_id_fkey FOREIGN KEY (default_beach_id) REFERENCES public.beaches(id),
  CONSTRAINT profiles_auth_users_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.session_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  inviter_id uuid NOT NULL,
  invitee_id uuid,
  invitee_email text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'revoked'::text])),
  message text,
  created_at timestamp with time zone DEFAULT now(),
  responded_at timestamp with time zone,
  idempotency_key text,
  CONSTRAINT session_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT session_invitations_inviter_id_fkey FOREIGN KEY (inviter_id) REFERENCES public.profiles(id),
  CONSTRAINT session_invitations_invitee_id_fkey FOREIGN KEY (invitee_id) REFERENCES public.profiles(id),
  CONSTRAINT session_invitations_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE public.session_likes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT session_likes_pkey PRIMARY KEY (id),
  CONSTRAINT session_likes_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id),
  CONSTRAINT session_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.session_media (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid,
  user_id uuid,
  media_type character varying DEFAULT 'photo'::character varying CHECK (media_type::text = ANY (ARRAY['photo'::character varying, 'video'::character varying]::text[])),
  storage_path text NOT NULL,
  public_url text NOT NULL,
  thumbnail_url text,
  caption text,
  file_size integer,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT session_media_pkey PRIMARY KEY (id),
  CONSTRAINT session_media_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT session_media_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE public.session_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'going'::text CHECK (status = ANY (ARRAY['going'::text, 'maybe'::text, 'not_going'::text])),
  joined_at timestamp with time zone DEFAULT now(),
  notes text,
  CONSTRAINT session_participants_pkey PRIMARY KEY (id),
  CONSTRAINT session_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT session_participants_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id)
);
CREATE TABLE public.sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  beach_id uuid NOT NULL,
  board_id uuid,
  arrival_time timestamp with time zone NOT NULL,
  duration_minutes integer NOT NULL DEFAULT 60,
  goals ARRAY NOT NULL DEFAULT '{}'::text[],
  notes text,
  invitee_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  status text DEFAULT 'planned'::text,
  beach_name text,
  rating smallint CHECK (rating >= 1 AND rating <= 5),
  description text,
  image_url text,
  likes_count integer NOT NULL DEFAULT 0 CHECK (likes_count >= 0),
  comments_count integer NOT NULL DEFAULT 0 CHECK (comments_count >= 0),
  crowd_level integer,
  wave_quality integer,
  water_temp numeric,
  parking_ease integer,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_board_id_fkey FOREIGN KEY (board_id) REFERENCES public.boards(id),
  CONSTRAINT sessions_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT sessions_beach_id_fkey FOREIGN KEY (beach_id) REFERENCES public.beaches(id)
);
CREATE TABLE public.sun_times (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  beach_id uuid NOT NULL,
  date date NOT NULL,
  sunrise_utc timestamp with time zone,
  sunset_utc timestamp with time zone,
  source text NOT NULL CHECK (source = 'open-meteo'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sun_times_pkey PRIMARY KEY (id),
  CONSTRAINT sun_times_beach_id_fkey FOREIGN KEY (beach_id) REFERENCES public.beaches(id)
);
CREATE TABLE public.tide_forecasts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  beach_id uuid NOT NULL,
  ts timestamp with time zone NOT NULL,
  tide_height_m numeric,
  tide_phase text,
  source text NOT NULL CHECK (source = ANY (ARRAY['open-meteo'::text, 'noaa'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tide_forecasts_pkey PRIMARY KEY (id),
  CONSTRAINT tide_forecasts_beach_id_fkey FOREIGN KEY (beach_id) REFERENCES public.beaches(id)
);
CREATE TABLE public.user_follows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  follower_id uuid NOT NULL,
  following_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_follows_pkey PRIMARY KEY (id),
  CONSTRAINT user_follows_following_id_fkey FOREIGN KEY (following_id) REFERENCES public.profiles(id),
  CONSTRAINT user_follows_follower_id_fkey FOREIGN KEY (follower_id) REFERENCES public.profiles(id)
);
