-- Add 21 East Coast surf spots: NY, NJ, RI, MA, NH, ME
-- Safe, idempotent insert using ON CONFLICT

BEGIN;

INSERT INTO public.beaches (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private
) VALUES
  -- 1. Rockaway Beach – 90th St (Queens, NY)
  (
    '7e7b38b1-767f-4213-9314-538f51ab5084',
    'Rockaway Beach – 90th St',
    'Queens',
    'NY',
    'USA',
    40.588095,
    -73.813499,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'rocks', 'jetties', 'pollution', 'crowds'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Concession stands', 'Beginner friendly', 'Consistent waves', 'Jetty protection'],
    90,
    180,
    290,
    45,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 135, "period_s": 10}, "notes": "Hurricane swells in late summer and fall provide the best waves; winter nor''easters can also deliver fun sessions."}'::jsonb,
    110,
    135,
    45,
    ARRAY[8,9,10,11,2,3],
    'rockaway-beach-90th-st-queens-ny',
    'Long Island',
    'Beach 90th Street in Rockaway is a bustling beach‑break with jetties creating punchy lefts and rights. The zone draws everyone from novice longboarders to seasoned shortboarders and gets its best shape on south‑ and east‑swell hurricane pulses with an offshore west or northwest breeze.',
    'There is a parking lot at Beach 90th and limited street spots; arrive early because spaces fill quickly in summer. Public transit via the subway makes access easier and avoids parking headaches.',
    'Walk directly from the boardwalk or the subway stop; jetties mark the surfing zones so choose a peak and paddle straight out.',
    'Sit near the groins to catch wedgy peaks; on southeast swells the left off the west jetty peels nicely while bigger hurricane swells produce long right walls.',
    'Expect a heavy crowd on good days; spread out along the multiple peaks or surf early mornings to find a corner.',
    'Low–mid tide, NW wind, 3–6 ft SE–S swell',
    ARRAY['Strong currents during swells', 'Crowded lineups'],
    'Locals are friendly but protective—don''t drop in and wait your turn in the busy lineups.',
    'very_high',
    ARRAY['🅿️ Street parking fills fast', '🌊 Low–mid tide gives peeling peaks', '🌬️ NW wind cleans up SE swells'],
    false
  ),

  -- 2. Rockaway Beach – 98th St (Queens, NY)
  (
    '1a7ac53d-f3ac-4f78-a89a-8befb2fa69b7',
    'Rockaway Beach – 98th St',
    'Queens',
    'NY',
    'USA',
    40.585441,
    -73.820186,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'rocks', 'jetties', 'pollution', 'crowds'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Concession stands', 'Beginner friendly', 'Consistent waves', 'Jetty protection'],
    90,
    180,
    290,
    45,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 135, "period_s": 10}, "notes": "Late summer hurricane swells provide the most reliable surf; smaller winter nor''easters can be fun too."}'::jsonb,
    110,
    135,
    45,
    ARRAY[8,9,10,11,2,3],
    'rockaway-beach-98th-st-queens-ny',
    'Long Island',
    'Just down the boardwalk from 90th Street, Beach 98th has similar punchy peaks. Jetties create multiple take‑off spots and the wave suits lower‑intermediate to advanced surfers on south and east swells with light offshore winds.',
    'Street parking is scarce—take the A train to Beach 98 or ride a bike to avoid tickets and crowded lots.',
    'Paddle out between the groins; the paddle can be tricky at low tide due to rip currents.',
    'Look for channels next to the jetties to paddle out; on bigger swells the lefts off the east jetty are hollow and fast.',
    'Similar to 90th Street, the peaks pack out—spread out along the beach or surf early to avoid the crush.',
    'Low–mid tide, W–NW wind, 3–6 ft SE swell',
    ARRAY['Strong currents during swells', 'Crowded lineups'],
    'Respect locals and avoid dropping in; high fives go further than attitude.',
    'very_high',
    ARRAY['🚇 Subway stop at Beach 98 makes access easy', '🌊 Low–mid tide sandbars fire', '🌬️ NW wind cleans up hurricane swells'],
    false
  ),

  -- 3. Long Beach (Long Beach, NY)
  (
    '03dc4aef-c5e3-48a6-9563-39e0fe08c9b5',
    'Long Beach',
    'Long Beach',
    'NY',
    'USA',
    40.5895,
    -73.6665,
    'beach',
    'intermediate',
    ARRAY['rip currents', 'jetties', 'crowds', 'pollution'],
    ARRAY['Parking nearby', 'Restrooms', 'Boardwalk', 'Showers', 'Consistent waves'],
    90,
    190,
    300,
    45,
    12,
    8,
    0.5,
    5.0,
    '{"tide": "all", "primary_swell": {"dir_deg": 140, "period_s": 10}, "notes": "Works year‑round; fall hurricane swells and winter storms create the best surf."}'::jsonb,
    120,
    140,
    50,
    ARRAY[8,9,10,11,2,3],
    'long-beach-long-beach-ny',
    'Long Island',
    'Long Beach is a stretch of sandy shoreline punctuated by jetties that focus swells into hollow peaks. It''s a classic beach break that can serve up tubing sections on south‑ and southeast‑swell days with offshore north winds.',
    'Metered parking runs along the boardwalk; non‑residents must pay for access and spaces fill by mid‑morning in summer.',
    'Enter via the boardwalk ramps; watch for exposed rocks near the jetties when walking along the sand.',
    'The peaks adjacent to the jetties are most consistent; on smaller days ride a longboard and move around to find the best sandbars.',
    'Weekend crowds and contests are common; surf dawn patrol or off‑season for more room.',
    'All tides, N wind, 3–6 ft SE–S swell',
    ARRAY['Strong rip currents around jetties', 'Crowded in summer'],
    'Locals share the vibe but value respect—yield to the person closest to the peak and be cautious near the jetties.',
    'very_high',
    ARRAY['🅿️ Pay parking at the boardwalk', '🌬️ North wind grooms SE–S swells', '🌊 Barrels on lower tide'],
    false
  ),

  -- 4. Ditch Plains (Montauk, NY)
  (
    '632e0e1c-a256-4d1f-8c6a-c1cbbc6ff2b6',
    'Ditch Plains',
    'Montauk',
    'NY',
    'USA',
    41.0394783,
    -71.9170081,
    'reef',
    'lower-intermediate',
    ARRAY['rocks', 'rip currents', 'crowds', 'cold water'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Concession stand', 'Consistent waves'],
    110,
    190,
    315,
    45,
    12,
    8,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 150, "period_s": 10}, "notes": "Best during summer and fall hurricane swells; smaller winter swells can be fun."}'::jsonb,
    135,
    150,
    40,
    ARRAY[8,9,10,11,2,3],
    'ditch-plains-montauk-ny',
    'Long Island',
    'Ditch Plains is Montauk''s famed reef break: a rocky bottom produces long peeling A‑frame waves that break both left and right. It''s suitable for longboards and funboards and works best on south‑to‑southeast swells with mid to high tides; summer and fall see friendly crowds but locals still hold priority.',
    'Parking at Ditch Plains requires a Town of East Hampton permit; visitors must park at lots outside town and bike or walk in during summer.',
    'Enter between the rock groins; watch your footing on the cobblestones and paddle wide to avoid the rocks.',
    'At mid tide the A‑frame peaks peel nicely; line up outside the rock outcropping for the longest rides.',
    'Dawn patrol and off‑season sessions reduce crowds; share waves and don''t snake locals.',
    'Mid–high tide, NW wind, 3–5 ft S–SE swell',
    ARRAY['Sharky area', 'Crowded in summer'],
    'Respect the lineup hierarchy; smile, say hi, and avoid dropping in on someone deeper.',
    'high',
    ARRAY['🅿️ Permit parking only—get a pass', '🌊 Long left and right A‑frames', '🌬️ NW wind cleans up south swells'],
    false
  ),

  -- 5. Turtle Cove (Montauk, NY)
  (
    'fad234b3-4c14-4c02-a0fe-db1ba6e67bbe',
    'Turtle Cove',
    'Montauk',
    'NY',
    'USA',
    41.071,
    -71.8571,
    'reef',
    'advanced',
    ARRAY['boulders', 'rip currents', 'strong currents', 'sharks'],
    ARRAY['State park access', 'Scenic cliffs', 'Remote', 'Expert surfers only'],
    130,
    180,
    320,
    45,
    12,
    8,
    1.5,
    4.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 155, "period_s": 10}, "notes": "This spot lights up only on large southeast swells and is dangerous due to submerged boulders and rip currents."}'::jsonb,
    140,
    155,
    25,
    ARRAY[8,9,10,11,2,3],
    'turtle-cove-montauk-ny',
    'Long Island',
    'Turtle Cove, tucked in Camp Hero below the Montauk Point Lighthouse, is a rocky cove that only fires on large southeast swells. The wave breaks over boulders, producing powerful slabs and rip currents; only experienced surfers should attempt this spot.',
    'Park at Camp Hero State Park (fee) and walk down the trail toward the cove; parking spots are limited and enforced.',
    'A steep trail leads to the rocky shoreline—wear booties and carefully pick your way over boulders before paddling out.',
    'Wait for a strong SE swell and time your paddle between sets; the take‑off is heavy and quick, so position deep and commit.',
    'Few surfers venture here due to difficulty, so crowds are low; respect any locals and give plenty of space.',
    'Mid tide, NNW wind, 4–8 ft SE swell',
    ARRAY['Hazardous rocky entrance', 'Only for expert surfers'],
    'Only advanced surfers should surf here—give right of way and look out for each other in the hazardous lineup.',
    'low',
    ARRAY['🪨 Navigate boulders with care', '🌊 Needs large SE swell to break', '🌬️ NNW wind makes it clean'],
    false
  ),

  -- 6. Manasquan Inlet (Manasquan, NJ)
  (
    'fb4fa0e0-328c-442b-b17a-82f95fbb6af5',
    'Manasquan Inlet',
    'Manasquan',
    'NJ',
    'USA',
    40.10278,
    -74.035,
    'jetty',
    'upper-intermediate',
    ARRAY['rip currents', 'rocks', 'jetties', 'strong currents', 'crowds'],
    ARRAY['Parking nearby', 'Boardwalk', 'Consistent waves', 'Jetty protection'],
    110,
    190,
    295,
    45,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 150, "period_s": 10}, "notes": "Hurricane and winter storm swells provide the best waves; clean conditions require offshore northwest winds."}'::jsonb,
    115,
    150,
    40,
    ARRAY[8,9,10,11,2,3],
    'manasquan-inlet-manasquan-nj',
    'Jersey Shore',
    'Manasquan Inlet is renowned as one of the East Coast''s premier jetty breaks. The inlet amplifies south swells into long, powerful right‑hand walls, and competitions are held here when conditions line up.',
    'Parking is limited near the inlet; arrive before dawn to secure a spot or park farther away and walk.',
    'Enter via the beach next to the north jetty; paddle through the channel to avoid the heaviest whitewater.',
    'Sit just outside the jetty to line up the right‑handers; on large south swells the wave barrels and offers long rides.',
    'The break attracts many experienced surfers and bodyboarders—respect the lineup hierarchy and expect a competitive vibe.',
    'Low–mid tide, W–NW wind, 4–8 ft S swell',
    ARRAY['Powerful right‑handers off the jetty', 'Strong currents at the inlet'],
    'Localism can be strong—do not paddle around people and be prepared to wait your turn.',
    'high',
    ARRAY['🅿️ Limited lot—come early', '🧭 Rights reel off the jetty', '🌬️ NW wind improves south swells'],
    false
  ),

  -- 7. Belmar (Belmar, NJ)
  (
    'fb0ee60f-a269-47ed-b244-e8dc64fff891',
    'Belmar',
    'Belmar',
    'NJ',
    'USA',
    40.18,
    -74.024,
    'beach',
    'intermediate',
    ARRAY['rip currents', 'crowds', 'pollution'],
    ARRAY['Parking nearby', 'Boardwalk', 'Consistent waves', 'Lifeguard', 'Showers'],
    90,
    180,
    290,
    45,
    12,
    8,
    0.5,
    6.0,
    '{"tide": "all", "primary_swell": {"dir_deg": 135, "period_s": 10}, "notes": "Winter swells can be epic when summer crowds thin."}'::jsonb,
    110,
    135,
    45,
    ARRAY[8,9,10,11,2,3],
    'belmar-belmar-nj',
    'Jersey Shore',
    'Belmar''s 16th Street break is a classic beach break with shifting sandbars and peaks that break both left and right. It suits intermediate surfers and works on any tide with south‑to‑east swells and offshore west winds.',
    'Metered parking runs along Ocean Avenue; arrive early or ride a bike during summer to avoid tickets.',
    'Walk over the boardwalk and head to 16th Street; choose a sandbar and paddle out through the channel.',
    'On larger swells sit farther outside; look for A‑frame peaks and watch for rip currents near the jetties.',
    'Weekends and holidays bring heavy crowds—surf early or in winter for more space.',
    'All tides, W wind, 3–5 ft SE–S swell',
    ARRAY['Heavy crowds on summer weekends'],
    'Share waves and respect beginners; move down the beach if it''s packed.',
    'high',
    ARRAY['🅿️ 16th‑St lot fills quickly', '🌬️ W wind cleans up peaks', '🌊 Works on all tides'],
    false
  ),

  -- 8. Asbury Park (Asbury Park, NJ)
  (
    '1279cf64-8ef0-4bb9-b786-6dd77fc2c201',
    'Asbury Park',
    'Asbury Park',
    'NJ',
    'USA',
    40.22039,
    -74.012085,
    'beach',
    'intermediate',
    ARRAY['rip currents', 'rocks', 'crowds', 'pollution'],
    ARRAY['Parking nearby', 'Boardwalk', 'Restrooms', 'Showers', 'Lifeguard'],
    90,
    160,
    290,
    45,
    12,
    8,
    0.0,
    2.0,
    '{"tide": "low", "primary_swell": {"dir_deg": 125, "period_s": 10}, "notes": "Best late summer–fall; south swells with westerly winds are ideal."}'::jsonb,
    110,
    125,
    35,
    ARRAY[8,9,10,11,2,3],
    'asbury-park-asbury-park-nj',
    'Jersey Shore',
    'Asbury Park comprises several beach breaks around jetties, offering rights off the groins and a fun left at The Cove. It works best with southeast‑to‑east swells and offshore west winds late summer through fall.',
    'Parking lots and metered street parking line the boardwalk—rates vary and fill quickly in peak season.',
    'Use the boardwalk stairs; choose between the northern Cove or the jetties and paddle out through the rip currents.',
    'At low tide the sandbars are hollow; look for rights off the jetties and lefts at The Cove.',
    'Surf early mornings or in shoulder seasons to avoid crowds; The Cove can be packed on good swells.',
    'Low tide, W wind, 3–5 ft SE–E swell',
    ARRAY['Heavy crowds, especially at The Cove'],
    'Be patient and courteous—there are many beginners and longboarders; rotate sets and respect locals.',
    'high',
    ARRAY['🅿️ Paid parking on the boardwalk', '🌬️ W wind best; SE–E swell', '🌊 Low tide favoured'],
    false
  ),

  -- 9. Long Branch (Long Branch, NJ)
  (
    'f84767c3-4c79-42ed-9e77-2351ab80d20e',
    'Long Branch',
    'Long Branch',
    'NJ',
    'USA',
    40.31369,
    -73.984871,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'jellyfish', 'stingrays', 'crowds'],
    ARRAY['Promenade', 'Restrooms', 'Showers', 'Restaurants', 'Lifeguards'],
    70,
    160,
    275,
    45,
    12,
    8,
    2.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 115, "period_s": 10}, "notes": "Late summer hurricane swells combined with westerly winds create the best surf; north winds can also groom the waves."}'::jsonb,
    95,
    115,
    45,
    ARRAY[8,9,10,11,2,3],
    'long-branch-long-branch-nj',
    'Jersey Shore',
    'Long Branch features a wide sand beach backed by a bustling promenade and restaurants. Its sandbars produce mellow peaks for lower‑intermediate surfers, but strong rip currents and occasional jellyfish and stingrays mean caution is needed.',
    'There are large pay lots and street parking along the boardwalk; fees apply during the summer season.',
    'Enter from the promenade via stairs or accessible mats; lifeguards supervise designated swimming and surfing areas.',
    'Look for shifting sandbars; mid tide often provides the best shape while high tide can fatten the waves.',
    'Expect crowds on summer weekends; surf early or during off‑season months for more room.',
    'Mid tide, W wind, 2–4 ft ENE–SE swell',
    ARRAY['Aquatic hazards such as jellyfish and stingrays', 'No dogs or alcohol on beach'],
    'Follow posted beach rules and respect lifeguards; avoid swimming areas when surfing.',
    'high',
    ARRAY['🅿️ Plenty of pay parking', '🚫 Follow beach rules—no dogs/drones', '🌊 Works on mid tide'],
    false
  ),

  -- 10. Sandy Hook (Sandy Hook, NJ)
  (
    '0e550715-3367-4829-8671-8f38bd5be34f',
    'Sandy Hook',
    'Sandy Hook',
    'NJ',
    'USA',
    40.4529,
    -73.9952,
    'point',
    'upper-intermediate',
    ARRAY['rip currents', 'rocks', 'jetties', 'sharks'],
    ARRAY['Parking nearby', 'Lifeguards', 'Scenic park', 'Jetty protection', 'Consistent waves'],
    130,
    190,
    240,
    45,
    12,
    8,
    0.0,
    2.0,
    '{"tide": "low", "primary_swell": {"dir_deg": 160, "period_s": 10}, "notes": "This spot turns on during large south swells; it is sheltered and needs west winds to be clean."}'::jsonb,
    60,
    160,
    30,
    ARRAY[8,9,10,11,2,3],
    'sandy-hook-sandy-hook-nj',
    'Jersey Shore',
    'Sandy Hook''s Cove is a rare New Jersey point break where sandbars and jetties wrap southeast swells into long right‑hand walls. The spot works best on big south swells with west to northwest winds and low tide.',
    'Parking is available inside Gateway National Recreation Area for a fee; spaces fill quickly on summer weekends.',
    'From the lot, walk north along the beach to The Cove; paddle around the point and watch for rocks.',
    'Line up behind the jetty and wait for sets to wrap; the first section can barrel before forming a long wall.',
    'On good swells crowds descend; surf early or in winter for more solitude.',
    'Low tide, W–NW wind, 4–8 ft S–SE swell',
    ARRAY['Crowded on weekends', 'Limited beach space at The Cove'],
    'Respect the lineup and give space; yield to the surfer deepest on the point.',
    'high',
    ARRAY['🏞️ National park access fee', '🌊 Rights wrap around the point', '🌬️ W–NW wind best'],
    false
  ),

  -- 11. Narragansett Town Beach (Narragansett, RI)
  (
    '662cc0f6-4488-48dc-a820-47768a2e285b',
    'Narragansett Town Beach',
    'Narragansett',
    'RI',
    'USA',
    41.4373244,
    -71.451167,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'sunken barge', 'old pier', 'crowds'],
    ARRAY['Parking lot', 'Restrooms', 'Showers', 'Food vendors'],
    80,
    180,
    310,
    45,
    12,
    8,
    2.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 130, "period_s": 10}, "notes": "Best when hurricane or nor''easter swells combine with northwest winds."}'::jsonb,
    130,
    130,
    50,
    ARRAY[8,9,10,11,2,3],
    'narragansett-town-beach-narragansett-ri',
    'Rhode Island Coast',
    'Narragansett Town Beach faces southeast and offers consistent beach‑break waves that tend to close out. It performs best on 4–6 ft swells with 10‑second periods and northwest winds; hazards include a sunken barge and old pier near the North Pavilion that become exposed at low tide.',
    'Parking requires a fee and is restricted to residents during peak season—arrive early or park off‑site and walk.',
    'Enter from the main pavilion; watch for the remains of the barge and pier when wading out at low tide.',
    'Surf south of the pier for longer rides; at high tide the shorebreak is mellow, while low tide can produce shorepound.',
    'Summer crowds are large and can create drop‑in chaos; surf in the off‑season or early mornings.',
    'Mid tide, NW wind, 4–6 ft SE swell',
    ARRAY['Parking expensive', 'Crowded in summer'],
    'Share peaks and be mindful of swimmers; avoid surfing near the lifeguard‑protected swim zones.',
    'high',
    ARRAY['🏖️ Resident‑only parking mid‑season', '🌬️ NW wind best', '⚠️ Avoid the barge and pier at low tide'],
    false
  ),

  -- 12. Matunuck (South Kingstown, RI)
  (
    'da7dc3e8-51c7-46a7-86f6-c3a90f4da036',
    'Matunuck',
    'South Kingstown',
    'RI',
    'USA',
    41.3737,
    -71.5408,
    'reef',
    'upper-intermediate',
    ARRAY['rocks', 'rip currents', 'undertow', 'cold water'],
    ARRAY['Free parking', 'Port-a-restrooms', 'Consistent waves', 'Long rides'],
    120,
    170,
    315,
    45,
    12,
    8,
    0.0,
    4.0,
    '{"tide": "low", "primary_swell": {"dir_deg": 145, "period_s": 10}, "notes": "Fall hurricane swells with long periods make this wave shine; winter nor''easters also produce quality surf."}'::jsonb,
    135,
    145,
    25,
    ARRAY[8,9,10,11,2,3],
    'matunuck-south-kingstown-ri',
    'Rhode Island Coast',
    'Matunuck (Deep Hole) is a sheltered reef/point break that serves up long peeling waves ideal for longboards. It works best on southeast swells with north‑northwest winds; hazards include rocks, rip currents and undertow.',
    'Free parking is available near Deep Hole along Matunuck Beach Road; there are portable restrooms but limited facilities.',
    'Walk across the cobblestones and time your paddle to avoid sets; booties help protect your feet from the rocky bottom.',
    'Position just off the point for the longest rights; inside sections can offer shorter lefts but beware of submerged rocks.',
    'Localism can be strong—be respectful, don''t paddle around, and give priority to locals.',
    'Low–mid tide, NNW wind, 3–6 ft SE swell',
    ARRAY['Wear booties on rocky bottom', 'Locals can be protective'],
    'Mind the lineup hierarchy and yield to those sitting deepest; keep conversations friendly.',
    'moderate',
    ARRAY['🪨 Rocky bottom—booties needed', '🌊 Reef offers long rides', '🌬️ NNW wind best on SE swell'],
    false
  ),

  -- 13. Point Judith (Narragansett, RI)
  (
    '64cb1fb1-e5aa-4306-a6eb-87b9afd14e99',
    'Point Judith',
    'Narragansett',
    'RI',
    'USA',
    41.3615,
    -71.4814,
    'point',
    'advanced',
    ARRAY['jagged rocks', 'submerged boulders', 'strong currents', 'sharks'],
    ARRAY['Free parking (limited)', 'Scenic lighthouse', 'Long rides', 'Consistent waves'],
    130,
    190,
    330,
    45,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 160, "period_s": 10}, "notes": "Needs solid south‑swell energy and offshore northwest winds to shine."}'::jsonb,
    150,
    160,
    30,
    ARRAY[8,9,10,11,2,3],
    'point-judith-narragansett-ri',
    'Rhode Island Coast',
    'Point Judith is a classic right‑hand point break at Rhode Island''s southern tip. A series of reefs produces fast, hollow right walls on south‑to‑southeast swells, but the rocky entry and strong currents mean it''s for experienced surfers only.',
    'Park at Rose Nulman Park or nearby street spots; parking bans are enforced on some roads.',
    'Walk down the rocks near the lighthouse and time your entry through the boulder field; wear booties to protect your feet.',
    'Line up outside and pick off the wrapping rights; the first section barrels then mellows into a long wall.',
    'Locals dominate the peak—respect the pecking order and don''t snake. Crowds thin in winter.',
    'Low–mid tide, NW wind, 4–8 ft S–SE swell',
    ARRAY['Experts only', 'Wear booties and helmet'],
    'Only confident surfers should paddle out; be courteous and watch out for each other in the heavy lineup.',
    'moderate',
    ARRAY['🪨 Rocky entrance—careful entry', '🏄‍♂️ Long right‑hand point', '🌬️ NW wind best on S swells'],
    false
  ),

  -- 14. Nauset Beach (Orleans, MA)
  (
    '9eeb258d-2fb7-4e72-a6a4-4451882dedb6',
    'Nauset Beach',
    'Orleans',
    'MA',
    'USA',
    41.840583,
    -69.952083,
    'beach',
    'intermediate',
    ARRAY['rip currents', 'sharks', 'cold water', 'crowds'],
    ARRAY['Parking lot', 'Restrooms', 'Showers', 'Snack bar', 'Off‑road vehicle access', 'Lifeguard'],
    120,
    180,
    295,
    45,
    12,
    8,
    2.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 150, "period_s": 10}, "notes": "Late summer and fall hurricane swells provide the most consistent surf; winter storms can also be epic."}'::jsonb,
    115,
    150,
    30,
    ARRAY[8,9,10,11,2,3],
    'nauset-beach-orleans-ma',
    'Cape Cod',
    'Nauset Beach is an exposed beach break on outer Cape Cod known for its consistency and power. It works best on southeast swells with offshore west winds and offers both left and right peaks; strong rip currents and occasional great white shark sightings add to the drama.',
    'Parking requires a seasonal permit or day pass; spaces near the beach fill quickly in summer, and an overflow lot serves off‑road vehicle users.',
    'From the parking lot, follow the boardwalk over the dunes; the beach is long so walk to find a sandbar away from crowds.',
    'Look for shifting sandbars that produce A‑frame peaks; mid tide often provides the best shape.',
    'Families and tourists crowd the beach in summer—surf at dawn or in shoulder seasons to score cleaner peaks.',
    'Mid tide, W wind, 4–6 ft SE swell',
    ARRAY['Strong rip currents', 'Sharky area'],
    'Follow shark advisories, respect lifeguards and fishermen, and share waves kindly.',
    'high',
    ARRAY['🅿️ Parking permit required', '🦈 Sharks frequent the area', '🌬️ W wind best on SE swells'],
    false
  ),

  -- 15. Coast Guard Beach (Eastham, MA)
  (
    '7c9ac9f8-a836-4ee4-b5bb-5fe5936d54b4',
    'Coast Guard Beach',
    'Eastham',
    'MA',
    'USA',
    41.843433,
    -69.947033,
    'beach',
    'beginner',
    ARRAY['rip currents', 'erosion', 'cold water'],
    ARRAY['Parking lot', 'Visitor center', 'Boardwalk', 'Restrooms', 'Lifeguard'],
    60,
    150,
    265,
    45,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "low", "primary_swell": {"dir_deg": 105, "period_s": 10}, "notes": "Popular in summer for gentle waves; bigger surf occurs in fall and winter storms."}'::jsonb,
    85,
    105,
    45,
    ARRAY[8,9,10,11,2,3],
    'coast-guard-beach-eastham-ma',
    'Cape Cod',
    'Part of the Cape Cod National Seashore, Coast Guard Beach offers mellow waves over shifting sandbars and is popular with beginners and families. The break works best on northeast‑to‑southeast swells with southwest to west‑northwest winds and low to mid tides.',
    'Parking is at a separate lot inland with shuttle service to the beach; on busy days the lot fills early.',
    'Ride the shuttle to the boardwalk; walk over the dunes to the beach and pick a sandbar.',
    'At low to mid tide the small waves are perfect for learning; experienced surfers head to Nauset for more power.',
    'Expect crowds of swimmers in summer—surf early mornings or off‑season.',
    'Low–mid tide, SW–WNW wind, 2–4 ft NE–SE swell',
    ARRAY['Small surf in summer', 'Check for erosion closures'],
    'Share the beach with swimmers and beachgoers; respect National Park Service rules and closures.',
    'moderate',
    ARRAY['🅿️ Remote parking with shuttle', '🏄‍♂️ Great for beginners', '🌬️ SW–WNW wind best'],
    false
  ),

  -- 16. Nantasket Beach (Hull, MA)
  (
    '6693188e-80a0-4877-a618-d733ab4809b2',
    'Nantasket Beach',
    'Hull',
    'MA',
    'USA',
    42.29167,
    -70.87444,
    'beach',
    'beginner',
    ARRAY['rip currents', 'crowds', 'cold water', 'wildlife'],
    ARRAY['Parking lot', 'Restrooms', 'Promenade', 'Family friendly', 'Consistent waves'],
    40,
    130,
    250,
    45,
    12,
    8,
    3.0,
    6.0,
    '{"tide": "high", "primary_swell": {"dir_deg": 85, "period_s": 10}, "notes": "Most consistent during winter and spring storms; summer offers smaller waves good for learning."}'::jsonb,
    70,
    85,
    45,
    ARRAY[8,9,10,11,2,3],
    'nantasket-beach-hull-ma',
    'Massachusetts Bay',
    'Nantasket Beach in Hull is a long, flat beach break facing northeast on the southern end and southeast on the northern end. It handles winter storm swells and offers forgiving waves for beginners; best conditions include northeast swells and southwest winds at high tide.',
    'Pay parking lots line the beach; get there early on summer days to secure a space.',
    'Access is easy from the promenade; follow the boardwalk and choose a less crowded peak.',
    'High tide helps the waves break farther from shore; on northeast swells the south end offers the best peaks.',
    'Families and beachgoers crowd the sand; surf early mornings or outside summer months.',
    'High tide, SW wind, 2–4 ft NE swell',
    ARRAY['Protect piping plover habitat', 'Beach can flood at high tide'],
    'Respect protected bird nesting areas and adhere to lifeguard instructions.',
    'moderate',
    ARRAY['🅿️ Paid parking along the beach', '🌊 Best on high tide with NE swell', '🐦 Respect protected wildlife'],
    false
  ),

  -- 17. Hampton Beach (Hampton, NH)
  (
    '8160745c-6322-45b0-8bad-81319574008b',
    'Hampton Beach',
    'Hampton',
    'NH',
    'USA',
    42.904331,
    -70.807164,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'rocks', 'crowds', 'cold water'],
    ARRAY['Parking nearby', 'Boardwalk', 'Restrooms', 'Showers', 'Lifeguard'],
    50,
    140,
    260,
    45,
    12,
    8,
    2.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 95, "period_s": 10}, "notes": "Fall and winter storms bring the best swells; water temperatures are cold year‑round."}'::jsonb,
    80,
    95,
    45,
    ARRAY[8,9,10,11,2,3],
    'hampton-beach-hampton-nh',
    'New Hampshire Coast',
    'Hampton Beach is a fun sand‑bottom beach break with peaks up to 100 m and a reef around the headland producing fast lefts. Best conditions occur with offshore northwest winds and swells from the east, northeast or southeast, working at mid to high tide.',
    'Parking meters and lots line Ocean Boulevard; arrive early and bring coins or a credit card.',
    'Walk across the boardwalk and pick a peak; reef waves near the headland require a longer paddle out.',
    'On mid to high tide the sandbars align; for faster, hollower waves, head to the reef around the headland.',
    'Summer tourist crowds can be intense; shoulder season and dawn patrol sessions are less crowded.',
    'Mid–high tide, NW wind, 3–5 ft E–NE swell',
    ARRAY['Sharks occasionally', 'Heavy tourist crowds'],
    'Share waves, respect local surfers and swimmers, and adhere to lifeguard zones.',
    'high',
    ARRAY['🅿️ Metered parking on the strip', '🌊 Mid–high tide best', '🌬️ NW wind grooms waves'],
    false
  ),

  -- 18. Higgins Beach (Scarborough, ME)
  (
    'adcd7128-424e-46d3-b8d1-f3aad6dd5edb',
    'Higgins Beach',
    'Scarborough',
    'ME',
    'USA',
    43.567,
    -70.283,
    'beach',
    'lower-intermediate',
    ARRAY['rocks', 'cold water', 'rip currents', 'localism'],
    ARRAY['Parking lot', 'Restrooms', 'Rocky point & beach break', 'Surf lessons'],
    80,
    150,
    315,
    45,
    12,
    8,
    2.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 115, "period_s": 10}, "notes": "Fall and winter produce the best swells; summer surf is smaller but enjoyable."}'::jsonb,
    135,
    115,
    35,
    ARRAY[8,9,10,11,2,3],
    'higgins-beach-scarborough-me',
    'Maine Coast',
    'Higgins Beach is a southeast‑facing stretch that picks up tropical storm and nor''easter swells. It features both beach‑break peaks and a rocky point; the bottom is sand and rock, and local surfers are protective but welcoming to respectful visitors.',
    'There is a small 75‑vehicle parking lot purchased by the town; it fills quickly, and residents limit non‑resident access in summer.',
    'Walk down the path to the beach; wear booties if surfing the point and watch for the shipwreck and submerged rocks at low tide.',
    'On SE swells the point holds bigger waves and offers longer rides; the beach peaks are fun for beginners and work best on mid tide.',
    'Limited parking keeps numbers down, but the lineup can still be competitive; respect locals and rotate waves.',
    'Mid tide, NW wind, 3–5 ft SE swell',
    ARRAY['Limited parking', 'Submerged rocks at low tide'],
    'Respect local surfers and homeowners; keep noise down and follow parking rules.',
    'moderate',
    ARRAY['🅿️ Small lot—arrive early', '🪨 Point holds bigger swells', '🌬️ NW wind polishes SE swells'],
    false
  ),

  -- 19. Scarborough Beach (Scarborough, ME)
  (
    'a1566585-0143-4a1d-983f-c7fd195c5e55',
    'Scarborough Beach',
    'Scarborough',
    'ME',
    'USA',
    43.595406,
    -70.352226,
    'beach',
    'beginner',
    ARRAY['rip currents', 'strong currents', 'cold water'],
    ARRAY['State park facilities', 'Restrooms', 'Parking', 'Lifeguards'],
    120,
    190,
    330,
    45,
    12,
    8,
    0.0,
    5.0,
    '{"tide": "all", "primary_swell": {"dir_deg": 155, "period_s": 10}, "notes": "Summer offers warm water and small waves; fall and winter storms bring bigger swells."}'::jsonb,
    150,
    155,
    35,
    ARRAY[8,9,10,11,2,3],
    'scarborough-beach-scarborough-me',
    'Maine Coast',
    'Scarborough Beach State Park offers a long sandy surf break just south of Higgins. It is managed by the Maine Bureau of Parks and Lands and produces fun lefts and rights on southeast or south swells with west or northwest winds. Rip currents occur daily, so swim and surf in the designated areas.',
    'Parking is limited to 285 on-site spots plus 125 off-site spaces; the lot often fills by noon on summer weekends.',
    'Walk a short path from the lot to the beach; follow signs and stay within park boundaries.',
    'The beach offers fun peaks at all tides; on southeast swells the sandbars produce mellow rides suitable for all levels.',
    'Arrive early to beat the crowds and secure a parking spot; evenings can also be quieter.',
    'All tides, W–NW wind, 2–4 ft SE–S swell',
    ARRAY['Daily rip currents', 'Parking fills by noon'],
    'Obey park rules, surf in designated areas, and be mindful of swimmers.',
    'moderate',
    ARRAY['🅿️ Only 285 on-site spaces', '🌊 SE–S swell with W wind', '⚠️ Swim in lifeguard zone'],
    false
  ),

  -- 20. Ogunquit Beach (Ogunquit, ME)
  (
    '4836065b-e9a9-4568-912d-41ca148ddce0',
    'Ogunquit Beach',
    'Ogunquit',
    'ME',
    'USA',
    43.24889,
    -70.59917,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'sandbars shifting', 'strong currents at river', 'cold water'],
    ARRAY['Parking', 'Restrooms', 'Shops & restaurants', 'Long beach'],
    80,
    170,
    295,
    45,
    12,
    8,
    1.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 125, "period_s": 10}, "notes": "Fall and winter produce powerful swells; summer surf is smaller but the beach offers a fun vibe."}'::jsonb,
    115,
    125,
    45,
    ARRAY[8,9,10,11,2,3],
    'ogunquit-beach-ogunquit-me',
    'Maine Coast',
    'Ogunquit Beach is a long, sandy beach that catches swells from multiple directions and has numerous peaks allowing surfers to spread out. The river mouth influences currents and sandbars, producing strong rip currents; the town offers parking, food and facilities nearby.',
    'Large municipal lots serve the beach, but they fill quickly in tourist season—arrive early or park in town and walk.',
    'Follow the paths from the parking area to the beach; the sand is flat but expect a longer walk to the water at low tide.',
    'Look for sandbars near the river for peaky waves; rip currents indicate deeper channels for paddling out. Winter surfers should wear thick wetsuits as water temperatures drop into the 30s.',
    'During summer the beach is packed with tourists, but there are many peaks to spread out; winter is quieter but much colder.',
    'Mid tide, W wind, 3–6 ft S–SE swell',
    ARRAY['Tourist crowds', 'Strong rips near river'],
    'Share the numerous peaks and respect swimmers; avoid surfing near flagged swim zones.',
    'high',
    ARRAY['🅿️ Ample parking but fills quickly', '🌊 Multiple peaks spread crowds', '🌬️ W wind cleans up S–SE swell'],
    false
  )

ON CONFLICT (id) DO NOTHING;

COMMIT;


