-- Add 27 Southeast, Florida & Gulf Coast surf spots: NC, SC, GA, FL, TX
-- Safe, idempotent insert using ON CONFLICT

BEGIN;

INSERT INTO public.beaches (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private
) VALUES
  -- 1. Cape Hatteras Lighthouse (Buxton, NC)
  (
    'd264fbf8-0525-4d31-adb5-9a0742eaeb7e',
    'Cape Hatteras Lighthouse',
    'Buxton',
    'NC',
    'USA',
    35.228417,
    -75.527533,
    'jetty',
    'advanced',
    ARRAY['rip currents', 'undertow', 'sharks', 'shallow sandbars', 'jetty rocks'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Consistent waves'],
    45,
    170,
    300,
    45,
    12,
    8,
    1.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 110, "period_s": 12}, "notes": "Thrives on NE–SE hurricane swells; localism is intense."}'::jsonb,
    120,
    107,
    62,
    ARRAY[8,9,10,11,2,3,4],
    'cape-hatteras-lighthouse-buxton-nc',
    'Outer Banks',
    'At Cape Hatteras Lighthouse, jetties and sandbars focus Atlantic swells into one of the most powerful waves on the East Coast. Long, ripable lefts and dredging tubes break over shifting sandbars by the groins. The wave is fast and heavy with strong currents, making it suitable for advanced surfers only.',
    'Parking is available at the lighthouse lot; off‑season you can drive on the beach with a permit. Arrive early on good swells as the area fills quickly.',
    'Follow the boardwalk from the parking lot and walk toward the metal groins. Beware of slippery rocks when crossing the jetty.',
    'Best peaks form next to the groins—sit deep and commit. Hurricane and nor''easter swells produce long lefts; incoming tide helps.',
    'Expect heavy crowds of locals and traveling pros on any good swell. Dawn patrol or stormy days are your best chance for space.',
    'Mid tide, SW wind, 5–8 ft NE‑SE swell',
    ARRAY['Strong currents near groins', 'Watch for metal jetty', 'Heavy localism'],
    'Respect the tight local crew and wait your turn. Never drop in on someone in the tube or cut across the jetty channel.',
    'very_high',
    ARRAY['🚗 Beach driving permit required', '🌊 Long lefts and dredging tubes', '⚠️ Experts only'],
    false
  ),

  -- 2. S‑Turns (Rodanthe, NC)
  (
    '4c29c993-e769-414b-8539-7867c7e04772',
    'S‑Turns',
    'Rodanthe',
    'NC',
    'USA',
    35.607833,
    -75.4649,
    'beach',
    'upper-intermediate',
    ARRAY['urchins', 'rip currents', 'undertow', 'sharks'],
    ARRAY['Limited parking', 'Remote feel', 'Consistent waves'],
    45,
    170,
    280,
    45,
    12,
    8,
    0.5,
    3.5,
    '{"tide": "low", "primary_swell": {"dir_deg": 125, "period_s": 11}, "notes": "Best on SE hurricane swells with offshore W wind."}'::jsonb,
    100,
    107,
    62,
    ARRAY[8,9,10,11,3,4],
    's-turns-rodanthe-nc',
    'Outer Banks',
    'S‑Turns is a powerful hollow beach break on Pea Island just north of Rodanthe. Sandbars sculpt fast lefts and rights that crank during hurricane season and nor''easters. It''s a regional classic for upper‑intermediate surfers seeking barrels.',
    'A small pull‑off along NC‑12 provides limited parking—get there before sunrise. Overflow parking requires a longer walk over dunes.',
    'Hike over the dunes on a sandy trail to reach the beach. Bring only essentials as the walk can be long in soft sand.',
    'Look for defined peaks along the S‑curve of the shoreline. Low to mid‑tide with rising water is best; W winds groom the face.',
    'Less crowded than other Outer Banks spots but can fill up during hurricanes. Spread out along the long beach to find your own peak.',
    'Low–mid tide, W wind, 4–7 ft SE swell',
    ARRAY['Parking is scarce due to construction', 'Strong rips', 'Sharks sometimes present'],
    'Friendly vibe but respect the locals and don''t hog peaks. Give space to fishermen.',
    'moderate',
    ARRAY['🚧 Small dirt lot—arrive early', '🌊 Powerful hollow beach break', '🐟 Beware of urchins'],
    false
  ),

  -- 3. Nags Head (Nags Head, NC)
  (
    '872fdb8c-6e6b-459e-813c-e8fc6a9561bd',
    'Nags Head',
    'Nags Head',
    'NC',
    'USA',
    35.9258,
    -75.609,
    'beach',
    'intermediate',
    ARRAY['rip currents', 'sharks', 'shorebreak'],
    ARRAY['Parking nearby', 'Beach access', 'Surf shops nearby'],
    45,
    170,
    265,
    45,
    12,
    8,
    0.5,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 100, "period_s": 10}, "notes": "Fun on any NE–SE swell with gentle offshore winds."}'::jsonb,
    85,
    107,
    62,
    ARRAY[8,9,10,11,2,3,4],
    'nags-head-nags-head-nc',
    'Outer Banks',
    'Nags Head offers a stretch of east‑facing Outer Banks beach with numerous peaks. Sandbars create fun lefts and rights that break best on moderate swells. It''s a go‑to spot for intermediate surfers looking for variety and less intimidating surf than Hatteras.',
    'Public beach accesses in Nags Head have free parking and showers. Arrive early during summer to secure a spot.',
    'Walk straight from the parking lot over short dunes. Access is easy and board‑walk friendly.',
    'Check different access points for the best sandbar. Mid tides with light offshore winds offer the longest rides.',
    'Crowds peak on summer weekends. Spread out along miles of beach or surf during off‑season for fewer people.',
    'Mid tide, W wind, 3–6 ft E‑SE swell',
    ARRAY['Rip currents strong during storms', 'Occasional shark sightings', 'Can be windy in winter'],
    'Normal surf etiquette applies; smile and share waves. Respect swimmers and fishermen.',
    'moderate',
    ARRAY['🏖️ Long sandy beach', '🌪️ Handles multiple swell directions', '🐟 Watch for rips'],
    false
  ),

  -- 4. Kill Devil Hills (Kill Devil Hills, NC)
  (
    'fea10ecf-6b55-4cc9-b29b-f215f923759d',
    'Kill Devil Hills',
    'Kill Devil Hills',
    'NC',
    'USA',
    36.022,
    -75.6687,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'sharks', 'shorebreak'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Surf shops nearby'],
    45,
    170,
    265,
    45,
    12,
    8,
    0.5,
    4.0,
    '{"tide": "falling", "primary_swell": {"dir_deg": 100, "period_s": 9}, "notes": "Works on NE–SE swells with light west winds."}'::jsonb,
    85,
    107,
    62,
    ARRAY[8,9,10,11,2,3,4],
    'kill-devil-hills-kill-devil-hills-nc',
    'Outer Banks',
    'Kill Devil Hills features multiple sandbar peaks along a gently sloping beach. The waves are generally softer than Hatteras, making it a great training ground for lower‑intermediate surfers. Swells from NE to SE light up the peaks, and winter nor''easters can produce overhead surf.',
    'Public access lots along Highway 12 offer free parking. Arrive before midday to avoid beach‑goer crowds.',
    'Short boardwalks lead over the dune to the beach. Carrying boards is easy and ADA ramps are available at some accesses.',
    'Look for outside sandbars on falling tide; rights and lefts are available. Light SW winds groom the faces.',
    'Summer crowds can be heavy near the most popular accesses. Walk a block or two north or south to find space.',
    'Falling tide, W wind, 3–5 ft E swell',
    ARRAY['Rips can be strong', 'Occasional jellyfish', 'Busy during summer'],
    'Friendly vibe—share waves and don''t hog peaks. Respect swimmers and families.',
    'high',
    ARRAY['🚗 Easy access', '🌊 Fun peaks for intermediates', '👪 Family‑friendly beach'],
    false
  ),

  -- 5. Avalon Pier (Kill Devil Hills, NC)
  (
    'a797dcac-2507-4b2b-9d37-1f92dfd6af89',
    'Avalon Pier',
    'Kill Devil Hills',
    'NC',
    'USA',
    36.03,
    -75.667,
    'pier',
    'advanced',
    ARRAY['pier pilings', 'rip currents', 'sharks', 'localism'],
    ARRAY['Pier access', 'Parking nearby', 'Consistent waves'],
    45,
    170,
    265,
    45,
    12,
    8,
    0.5,
    4.5,
    '{"tide": "incoming", "primary_swell": {"dir_deg": 100, "period_s": 10}, "notes": "Fires on NE–SE swells with clean west winds."}'::jsonb,
    85,
    107,
    62,
    ARRAY[8,9,10,11,2,3,4],
    'avalon-pier-kill-devil-hills-nc',
    'Outer Banks',
    'Avalon Pier is an iconic Outer Banks surf spot in the heart of Kill Devil Hills. The sand near the pier produces powerful, hollow peaks on both sides, drawing some of the region''s best surfers. The crowd and localism can be intense, so this wave is for advanced riders who know pier etiquette.',
    'Park at the pier''s lot for a fee or find street parking nearby. Get there early for dawn patrol sessions.',
    'Walk down the beach to either side of the pier; paddle out just away from the pilings to avoid fishermen.',
    'Sit just outside of the pier pilings for the best takeoff zone. Rights are longer on south swells; lefts line up on north swells.',
    'Expect a packed lineup of local rippers on any swell. Avoid dropping in and wait for your turn. Off‑season weekdays are quieter.',
    'Incoming tide, W wind, 4–6 ft NE swell',
    ARRAY['Watch out for pier pilings', 'Heavy local crew', 'Sharky waters'],
    'High level of respect required—never paddle through the inside when someone is riding, and yield to locals.',
    'very_high',
    ARRAY['🎣 Iconic Outer Banks pier', '🌊 Hollow peaks adjacent to pilings', '🚫 Experts only due to crowds'],
    false
  ),

  -- 6. Wrightsville Beach (Wrightsville Beach, NC)
  (
    '4b88f10a-c794-4144-b17a-133af9fee9f9',
    'Wrightsville Beach',
    'Wrightsville Beach',
    'NC',
    'USA',
    34.21331,
    -77.78669,
    'pier',
    'intermediate',
    ARRAY['rip currents', 'pier pilings', 'jellyfish'],
    ARRAY['Parking nearby', 'Restrooms', 'Surf schools', 'Lifeguard'],
    45,
    160,
    260,
    45,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 100, "period_s": 10}, "notes": "Handles NE–SE swells well; south end favours longer periods."}'::jsonb,
    80,
    102,
    57,
    ARRAY[8,9,10,11,3,4],
    'wrightsville-beach-wrightsville-beach-nc',
    'North Carolina Coast',
    'Wrightsville Beach is a classic North Carolina surf town with a supportive surf community and multiple breaks. Crystal Pier offers reliable peaks for beginners, the South End catches larger swells and long rides, and Johnny Mercer''s Pier dishes out stronger waves for advanced surfers. Water stays warm much of the year, and surf schools abound.',
    'Paid parking is available along the beach and near the piers; bring a credit card for meters. Arrive before sunrise for free street spots.',
    'Use beach access points to reach the sand. The pier entrances are clearly marked; avoid restricted fishing zones when paddling out.',
    'Crystal Pier works best on small swells and mid tide. The South End loves long-period swells and offers lefts and rights. Mercer''s Pier is heavier—stay clear of the pilings.',
    'Summer and weekends bring crowds; surf early or during colder months for room. Spread out among the many peaks to avoid congestion.',
    'Mid tide, W wind, 3–6 ft E‑NE swell',
    ARRAY['Crowded near Johnny Mercer''s Pier', 'Occasional jellyfish', 'Parking fills early'],
    'Be courteous to beginners at surf schools and obey pier rules. Give fishermen wide berth.',
    'high',
    ARRAY['🏖️ Family‑friendly surf town', '🏄 Several breaks—Crystal Pier, South End, Mercer''s', '🌅 Best early morning'],
    false
  ),

  -- 7. Folly Beach (Folly Beach, SC)
  (
    '76057acb-e6b4-46c0-ae0e-4110cd7a19d1',
    'Folly Beach',
    'Folly Beach',
    'SC',
    'USA',
    32.65,
    -79.94,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'stingrays', 'localism'],
    ARRAY['Parking nearby', 'Pier/jetty protection', 'Beginner friendly', 'Restrooms'],
    60,
    150,
    285,
    45,
    12,
    8,
    1.5,
    4.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 105, "period_s": 10}, "notes": "Works on SE–NE hurricane swells; NW offshore winds clean it up."}'::jsonb,
    105,
    105,
    45,
    ARRAY[8,9,10,11,3,4],
    'folly-beach-folly-beach-sc',
    'South Carolina',
    'Folly Beach is a long barrier island south of Charleston with several fun breaks. The Washout—a stretch blown open by Hurricane Hugo—produces punchy peaks on SE‑NE swells, while the Folly Beach Pier offers long lefts on the south side. It''s friendly for beginners when small but can handle good size during hurricane season.',
    'Metered parking lines the streets, and a large lot near the pier charges a fee. Watch for towing in residential areas.',
    'Beach accesses are plentiful. Walk down the sand to the Washout or around the pier to find your peak.',
    'Mid to high tide is best. The Washout likes NE swells and NW winds; the pier picks up SE swells. Peak hurricane season brings the biggest waves.',
    'Crowds peak on summer weekends; early morning or off‑season sessions are quieter. Spread out along the beach to escape the crowd.',
    'Mid‑high tide, NW wind, 3–6 ft SE‑NE swell',
    ARRAY['Stay 200 ft from the pier', 'Strong currents at The Washout', 'Crowded on hurricane swells'],
    'Respect locals and give right of way at the Washout. Stay outside the pier''s restricted zone.',
    'high',
    ARRAY['🌴 Chill surf town', '🍍 The Washout pumps on hurricane swells', '⚠️ Keep distance from pier'],
    false
  ),

  -- 8. Isle of Palms (Isle of Palms, SC)
  (
    'd15efc29-c4cb-407c-99b8-be92914473f4',
    'Isle of Palms',
    'Isle of Palms',
    'SC',
    'USA',
    32.819412,
    -79.734383,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'stingrays', 'sharks'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Beginner friendly'],
    60,
    150,
    280,
    45,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 100, "period_s": 9}, "notes": "Better on SE hurricane swells; gentle winds improve wave shape."}'::jsonb,
    100,
    105,
    45,
    ARRAY[8,9,10,11,3,4],
    'isle-of-palms-isle-of-palms-sc',
    'South Carolina',
    'Isle of Palms (IOP) is a mellow beach break just north of Charleston. It picks up less north swell than Folly due to its slightly southerly orientation but still provides consistent waves for beginners and lower‑intermediate surfers. During late summer and early fall, tropical storm swells provide punchier surf and more push.',
    'Public lots and street parking are available but fill quickly in summer. Pay attention to signage and avoid blocking driveways.',
    'Use one of the many beach accesses; a short boardwalk leads over the dunes. Look for quiet sandbars away from the pier.',
    'Small summer swells are best for learning. Intermediate surfers should target late summer hurricane swells at mid tide with NW winds.',
    'IOP is less crowded than Folly but still busy in peak season. Surf mid‑week or early morning for more space.',
    'Mid tide, NW wind, 2–4 ft SE‑E swell',
    ARRAY['Crowds near pier', 'Less north swell than Folly', 'Always wear leash'],
    'Be courteous and yield to longboarders and surf schools. Avoid dropping in near the pier.',
    'moderate',
    ARRAY['🏖️ Spacious beach', '🌊 Consistent summer surf', '🌀 Hurricane swells best late summer'],
    false
  ),

  -- 9. Tybee Island (Tybee Island, GA)
  (
    'd3740aa5-3c96-4575-a60c-d8200023affe',
    'Tybee Island',
    'Tybee Island',
    'GA',
    'USA',
    32.004,
    -80.842,
    'pier',
    'lower-intermediate',
    ARRAY['rip currents', 'jellyfish', 'stingrays', 'localism'],
    ARRAY['Pier/jetty protection', 'Parking nearby', 'Restrooms'],
    60,
    150,
    285,
    45,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 105, "period_s": 9}, "notes": "Relies on SE hurricane swells; mid tide wedges produce the best shape."}'::jsonb,
    105,
    105,
    45,
    ARRAY[8,9,10,11,3,4],
    'tybee-island-tybee-island-ga',
    'Georgia Coast',
    'Tybee Island''s pier and sandbars produce wedgy right and left peaks when E/SE swells hit at mid tide. The spot relies on tropical hurricanes and winter nor''easters for consistent surf but can turn on in the fall with chest‑high waves. It''s a fun, mellow wave for lower‑intermediate surfers.',
    'Parking lots near the pier require a fee; use the meter or app. Avoid busy weekends when spaces are scarce.',
    'Walk from the parking lot to the pier; surfers must stay clear of fishing zones. Choose an empty sandbar north or south of the pier to avoid crowds.',
    'Aim for mid tide on an E/SE swell. Look for sandbars that wedge incoming swell against the pier, creating short but punchy rights and lefts.',
    'The pier area is popular with tourists and fisherfolk. Surf early morning or in colder months to avoid the masses.',
    'Mid tide, W wind, 3–4 ft E‑SE swell',
    ARRAY['Busy near the pier', 'Small mushy waves when swell is weak', 'Check for hidden pilings'],
    'Respect fishermen and avoid surfing directly under the pier. Locals appreciate a friendly attitude.',
    'moderate',
    ARRAY['🎢 Wedgy peaks at pier', '🍂 Best in fall–winter', '🚫 Check surf before driving'],
    false
  ),

  -- 10. Sebastian Inlet (Melbourne Beach, FL)
  (
    'd0f77b47-ec94-4188-8dde-d52a10b7be49',
    'Sebastian Inlet',
    'Melbourne Beach',
    'FL',
    'USA',
    27.86,
    -80.4483,
    'inlet',
    'intermediate',
    ARRAY['inlet currents', 'rocks', 'sharks', 'localism', 'shallow inside'],
    ARRAY['Parking nearby', 'Restrooms', 'Consistent waves', 'World‑class wave'],
    30,
    150,
    255,
    45,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "incoming", "primary_swell": {"dir_deg": 70, "period_s": 12}, "notes": "Best on clean NE groundswell with period 10 s+. Hurricane swells can be epic but extremely crowded."}'::jsonb,
    75,
    90,
    60,
    ARRAY[8,9,10,11,12,1,2,3],
    'sebastian-inlet-melbourne-beach-fl',
    'Space Coast',
    'Florida''s most consistent and high‑performance wave, Sebastian Inlet fires when groundswell wraps around the jetty. First Peak delivers fast, hollow rights over a shallow rock‑sand bottom, while Monster Hole (a shoal 1/3 mile offshore) holds bigger, more powerful surf. Intermediate surfers can score world‑class rides when they respect the lineup.',
    'Pay the state park entrance fee ($8) and park on the north side for First Peak. The lot fills early on good swells—arrive before sunrise.',
    'Walk north along the rock jetty to reach First Peak; use caution on slippery rocks. Paddling to Monster Hole requires a long paddle across the inlet.',
    'Sit deep near the jetty for the heaviest rights. Monster Hole works on bigger swells and outgoing tide. NW to W winds groom the face.',
    'Expect very high crowds and intense localism. Weekdays or rainstorms provide slight reprieve. Always show respect and patience.',
    'Incoming tide, W wind, 4–8 ft E‑NE swell',
    ARRAY['Strong inlet currents', 'Shallow rocks on north side', 'Heavy localism on good days'],
    'Sebastian is known for heavy localism—never snake or drop in. Wait your turn and respect the pecking order.',
    'very_high',
    ARRAY['🅿️ $8 state park fee', '🌊 Florida''s best wave—respect the lineup', '⚠️ Watch for rocks at First Peak'],
    false
  ),

  -- 11. Spanish House (Melbourne Beach, FL)
  (
    '53e8654a-a2bb-46a9-8153-83661af98fb1',
    'Spanish House',
    'Melbourne Beach',
    'FL',
    'USA',
    27.8763,
    -80.4559,
    'reef',
    'upper-intermediate',
    ARRAY['shallow reef', 'rip currents', 'sharks', 'localism'],
    ARRAY['Parking nearby', 'Restrooms', 'Consistent waves'],
    40,
    150,
    260,
    45,
    12,
    8,
    0.5,
    3.5,
    '{"tide": "low", "primary_swell": {"dir_deg": 90, "period_s": 11}, "notes": "Strong E to SE swell with offshore winds yields the best barrels."}'::jsonb,
    80,
    95,
    55,
    ARRAY[8,9,10,11,12,1,2,3],
    'spanish-house-melbourne-beach-fl',
    'Space Coast',
    'Spanish House is the first parking area north of Sebastian Inlet and is named after a long‑demolished Spanish‑style home. A shallow coquina reef and sandbar give the wave extra push, producing punchy top‑to‑bottom barrels on strong swell. It''s a challenging wave suited to upper‑intermediate surfers.',
    'Look for a dirt lot with a bulletin board north of Bonsteel Park; parking is free but limited. Arrive early as spaces fill quickly on good swell.',
    'Cross Highway A1A carefully and follow the sandy trail through the vegetation to the beach. Beware of heavy mosquito population after rains.',
    'Low tide and offshore breeze produce hollow barrels. Sit over the inside reef for fast tubes; step deeper for longer walls.',
    'Popular with local rippers—lineups are tight when it''s pumping. Surf on smaller days or during off hours to avoid crowds.',
    'Low tide, W wind, 3–6 ft E‑SE swell',
    ARRAY['Shallow inside bar', 'Crowded on good swells', 'Watch for rocks'],
    'Respect the locals and don''t drop in; wait for your turn. Watch the reef when kicking out.',
    'high',
    ARRAY['🅿️ Dirt lot north of Sebastian', '🤙 Top‑to‑bottom barrels', '⚠️ Shallow reef adds push'],
    false
  ),

  -- 12. Cocoa Beach Pier (Cocoa Beach, FL)
  (
    '99e50d6b-a1cf-458b-8fff-c199cd55b23c',
    'Cocoa Beach Pier',
    'Cocoa Beach',
    'FL',
    'USA',
    28.367648,
    -80.602777,
    'pier',
    'beginner',
    ARRAY['pier pilings', 'rip currents', 'jellyfish'],
    ARRAY['Parking nearby', 'Restrooms', 'Shops and restaurants', 'Pier observation deck'],
    40,
    150,
    260,
    45,
    12,
    8,
    0.5,
    3.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 90, "period_s": 10}, "notes": "Fun for learning; north swells provide the most power."}'::jsonb,
    80,
    95,
    55,
    ARRAY[8,9,10,11,12,1,2,3],
    'cocoa-beach-pier-cocoa-beach-fl',
    'Space Coast',
    'The Cocoa Beach Pier is Florida''s most famous surf landmark and home to legends like Kelly Slater. The pier breaks on almost every type of swell, with chest‑ to head‑high north swells producing the best waves. It''s a mellow wave well suited to beginners and longboarders but can offer punchier sections when hurricane swells wrap in.',
    'Parking at the pier costs around $10; pay at the kiosk. Additional metered parking can be found along Meade Avenue.',
    'Walk down the pier or along the beach to your preferred takeoff zone. Surfers must stay clear of the fishing area on the pier.',
    'Focus on the sandbars just north or south of the pier for longer rides. Early mornings offer glassy conditions with light offshore winds.',
    'Always busy with tourists and surf schools. Dawn patrol sessions or winter swells offer slightly more room.',
    'Mid tide, W wind, 2–4 ft NE swell',
    ARRAY['Stay clear of fishermen', 'Small mushy waves when swell is weak', 'Parking fees'],
    'Be kind to beginners and give plenty of space. Respect the fishermen on the pier.',
    'very_high',
    ARRAY['🎡 Surf a historic landmark', '🌊 Works on most swells', '💵 Pay to park and walk the pier'],
    false
  ),

  -- 13. New Smyrna Beach (NSB) Inlet (New Smyrna Beach, FL)
  (
    'f5eec6e8-844a-41be-b3bf-4c47e0615545',
    'New Smyrna Beach (NSB) Inlet',
    'New Smyrna Beach',
    'FL',
    'USA',
    29.06333,
    -80.91583,
    'inlet',
    'intermediate',
    ARRAY['sharks', 'rip currents', 'localism', 'jetty rocks'],
    ARRAY['Parking nearby', 'Restrooms', 'Surf shops nearby', 'Long rides'],
    45,
    135,
    260,
    45,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "high", "primary_swell": {"dir_deg": 80, "period_s": 11}, "notes": "NE groundswell with offshore winds yields long, peeling rights."}'::jsonb,
    80,
    90,
    45,
    ARRAY[8,9,10,11,12,1,2,3],
    'new-smyrna-beach-nsb-inlet-new-smyrna-beach-fl',
    'Central Florida',
    'The south side of Ponce Inlet at New Smyrna Beach is renowned for consistent, peeling waves and is a mecca for Florida surfers. Rock ledges offshore create excellent wave shape while protecting swimmers from undertow. Both accomplished surfers and beginners enjoy long rides, though shark encounters are more common here than anywhere else in the U.S.',
    'Park at the inlet lot (fee required) on the south side of the bridge. Arrive early on weekends as the lot fills quickly.',
    'Walk down the paved path to the beach and paddle out near the jetty. Stay outside the swim zone.',
    'Surf near the jetty for long right‑hand peelers. High tide covers the outer sandbar, allowing longer rides; NE swells are ideal.',
    'Always crowded with locals and visitors. Early mornings and chilly winter days provide slightly fewer people.',
    'High tide, W wind, 3–6 ft NE swell',
    ARRAY['Shark bite capital of the world', 'Crowded on good days', 'Strong currents by the jetty'],
    'Be respectful, don''t drop in, and stay aware of others. Keep your feet up when paddling to avoid sharks.',
    'very_high',
    ARRAY['🦈 Shark bite capital—stay alert', '🌊 Long, peeling jetty waves', '🚗 Parking fills early'],
    false
  ),

  -- 14. Ponce Inlet (Ponce Inlet, FL)
  (
    '9c6bdc37-68c3-4101-9c2f-d188384528b6',
    'Ponce Inlet',
    'Ponce Inlet',
    'FL',
    'USA',
    29.06333,
    -80.91583,
    'jetty',
    'intermediate',
    ARRAY['rip currents', 'jetty rocks', 'sharks', 'localism'],
    ARRAY['Parking nearby', 'Restrooms', 'Long rights'],
    45,
    135,
    265,
    45,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "high", "primary_swell": {"dir_deg": 80, "period_s": 11}, "notes": "Loves NE hurricane swells; high tide and west winds create long peelers."}'::jsonb,
    85,
    90,
    45,
    ARRAY[8,9,10,11,12,1,2,3],
    'ponce-inlet-ponce-inlet-fl',
    'Central Florida',
    'The north side of Ponce Inlet features a jetty‑shaped wave that can handle huge swells. A right peeler bends off the jetty while shifting sandbars south of the inlet offer ever‑changing peaks. The spot can get heavy and crowded but rewards surfers with long rides.',
    'Park in the lot near the jetty (fee). Bring cash or card for the meters and arrive early to secure a spot on big swells.',
    'Walk along the jetty to choose your takeoff zone. Stay clear of fishermen and slippery rocks.',
    'High tide pushes water over the outer sandbar and allows longer rides. Aim for NE swells with W winds.',
    'Locals travel long distances to surf here; expect a packed lineup. Surf midweek or in cold weather to avoid crowds.',
    'High tide, W wind, 4–8 ft NE swell',
    ARRAY['Strong currents around the jetty', 'Crowded with locals', 'Changing sandbars'],
    'Respect the hierarchy; don''t back‑paddle or snake. Give fishermen space and pack your trash.',
    'very_high',
    ARRAY['🐟 Jetty produces long peeling rights', '🏄 Best at high tide', '⚠️ Respect locals'],
    false
  ),

  -- 15. Flagler Beach (Flagler Beach, FL)
  (
    '9ca1fa2f-2b90-4aa3-8784-48721e5463bb',
    'Flagler Beach',
    'Flagler Beach',
    'FL',
    'USA',
    29.47498,
    -81.127,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'sharks', 'jellyfish', 'pier pilings', 'shorepound'],
    ARRAY['Parking nearby', 'Restrooms', 'Lifeguard', 'Surf shops nearby'],
    45,
    135,
    270,
    45,
    12,
    8,
    0.5,
    3.0,
    '{"tide": "incoming", "primary_swell": {"dir_deg": 90, "period_s": 9}, "notes": "Performs best on E groundswell with west winds; coquina sand creates thumping peaks."}'::jsonb,
    90,
    90,
    45,
    ARRAY[8,9,10,11,3,4],
    'flagler-beach-flagler-beach-fl',
    'Central Florida',
    'Flagler Beach is a long coquina‑sand beach known for its thumping shorebreak and friendly surf culture. On low incoming tide the second sandbar produces fun rights and lefts when west winds and swell align. The area near the pier can get crowded and powerful; novices should surf a few blocks away.',
    'Street parking along A1A is free. Additional parking lots are near the pier. Arrive early on weekends.',
    'Multiple beach accesses lead directly to the sand. Stay away from the pier''s 150‑ft no‑surf zone.',
    'Best waves come on low incoming tide with west winds. The pier area breaks heavier; move down the beach for mellower peaks.',
    'Surf near the pier can get crowded, especially when local pros are training. Head a few blocks north or south for space.',
    'Low incoming tide, W wind, 3–5 ft E swell',
    ARRAY['150‑ft no‑surf zone around the pier', 'Riptides everywhere', 'Coquina sand is sticky'],
    'Respect the locals and share waves. Keep clear of the lifeguard area and pick up trash.',
    'high',
    ARRAY['🐠 Coquina sand produces thumping shorebreak', '🐬 Watch for rips and jellyfish', '🚷 No surfing within 150 ft of the pier'],
    false
  ),

  -- 16. Jacksonville Beach Pier (Jacksonville Beach, FL)
  (
    'a4472f56-626e-4905-b909-5f1dc27174a9',
    'Jacksonville Beach Pier',
    'Jacksonville Beach',
    'FL',
    'USA',
    30.29306,
    -81.39046,
    'pier',
    'beginner',
    ARRAY['pier pilings', 'rip currents', 'sharks'],
    ARRAY['Parking nearby', 'Restrooms', 'Fishing pier', 'Surf shops nearby'],
    45,
    135,
    265,
    45,
    12,
    8,
    0.5,
    3.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 95, "period_s": 10}, "notes": "Fun on any NE–SE swell; hurricane season brings the best waves."}'::jsonb,
    85,
    90,
    45,
    ARRAY[8,9,10,11,12,1,2,3],
    'jacksonville-beach-pier-jacksonville-beach-fl',
    'North Florida',
    'Jacksonville Beach Pier juts into the Atlantic and collects swell on both sides. The sandbars around the pier produce forgiving peaks that are perfect for learning and longboarding, though they can pack a punch during hurricane season. It''s a community gathering spot with a friendly vibe.',
    'Paid parking lots and meters line the beachfront. Use the ParkMobile app and avoid parking in residential areas without permits.',
    'Walk along the beach to the north or south side of the pier; avoid paddling under the pier where lines and hooks dangle.',
    'Target mid tide for the best shape. Hurricane swells light up the pier with chest‑ to head‑high peaks; NE winds groom the face.',
    'Often crowded with beginners and surf schools. Surf early or during winter to find space.',
    'Mid tide, W wind, 2–5 ft E‑NE swell',
    ARRAY['Stay clear of fishermen', 'Small waves when swell is weak', 'Crowded on weekends'],
    'Be patient with learners and give space around the pilings. Fishermen have right of way on the pier.',
    'high',
    ARRAY['🎣 Long pier collects swell', '🏄 Great for beginners', '🚗 Parking can be tricky'],
    false
  ),

  -- 17. Satellite Beach (Satellite Beach, FL)
  (
    '307d7cb3-f235-4b32-9b42-8a375ac9f54f',
    'Satellite Beach',
    'Satellite Beach',
    'FL',
    'USA',
    28.1707,
    -80.5913,
    'reef',
    'intermediate',
    ARRAY['shallow reef', 'rocks', 'rip currents', 'sharks'],
    ARRAY['Parking nearby', 'Restrooms', 'Consistent waves'],
    45,
    135,
    260,
    45,
    12,
    8,
    0.5,
    3.0,
    '{"tide": "low", "primary_swell": {"dir_deg": 90, "period_s": 11}, "notes": "Coquina shelf makes this a heavy, hollow left on E–SE swells."}'::jsonb,
    80,
    90,
    45,
    ARRAY[8,9,10,11,12,1,2,3],
    'satellite-beach-satellite-beach-fl',
    'Space Coast',
    'Satellite Beach sits on a barrier island and features a coquina sand shelf and shifting ocean floor. When E‑SE swells hit, the wave produces long, hollow lefts over a shallow reef, but exposed rocks and shallow water pose hazards. Intermediate surfers will enjoy its power when conditions align.',
    'Street parking is available near public accesses. Look for small lots with showers and restrooms along A1A.',
    'Walk through the dune paths to the beach. At low tide, watch for exposed rocks on the shoreline.',
    'Low to mid tide with W winds provides the cleanest barrels. Sit over the reef for the hollowest lefts; rights are shorter.',
    'Moderately crowded on good swells. Local rippers dominate the lineup—respect their space.',
    'Low–mid tide, W wind, 3–5 ft E‑SE swell',
    ARRAY['Exposed rocks at low tide', 'Shallow waters', 'Strong rips'],
    'Don''t drop in on locals and never throw your board near exposed rocks. Respect fishermen along the shore.',
    'moderate',
    ARRAY['🪨 Coquina reef creates hollow lefts', '⚠️ Beware of exposed rocks', '🎯 Best at low to mid tide'],
    false
  ),

  -- 18. Deerfield Beach Pier (Deerfield Beach, FL)
  (
    '1bd4ef4d-eb8e-4833-8679-8a13095a97d6',
    'Deerfield Beach Pier',
    'Deerfield Beach',
    'FL',
    'USA',
    26.31647,
    -80.07618,
    'pier',
    'lower-intermediate',
    ARRAY['rip currents', 'localism', 'pollution', 'sharks'],
    ARRAY['Parking nearby', 'Restrooms', 'Pier/jetty protection', 'Beginner friendly'],
    40,
    100,
    280,
    45,
    12,
    10,
    0.5,
    3.0,
    '{"tide": "any", "primary_swell": {"dir_deg": 70, "period_s": 9}, "notes": "NE swells with light NW winds produce the best waves north of the pier."}'::jsonb,
    100,
    70,
    30,
    ARRAY[8,9,10,11,12,1,2,3],
    'deerfield-beach-pier-deerfield-beach-fl',
    'South Florida',
    'Deerfield Beach Pier offers a small, often mushy wave that''s popular with locals and tourists. Surfing is only allowed north of the pier, where high‑performance waves break in the hot zone; south of lifeguard tower 7 has softer waves for learners. Hazards include rip currents, pollution, theft and the occasional shark.',
    'Park on the south side of the pier and walk north with your board. Metered parking is available; keep valuables out of sight.',
    'Use the boardwalk to reach the north side of the pier. A leash is mandatory and the city enforces surf zones strictly.',
    'Look for sandbars north of the pier that wedge incoming NE swells. All tides work but incoming tide offers more push.',
    'Crowded during weekends and hot‑zone sessions. Surf early mornings or weekdays to avoid crowds.',
    'All tides, NW wind, 2–4 ft NE swell',
    ARRAY['Surf only allowed north of the pier', 'Hot zones have high‑performance waves', 'Theft occurs in parking areas'],
    'Respect the designated surf zones and avoid dropping in. Keep an eye on beginners and fishermen.',
    'high',
    ARRAY['🦈 Sharky waters—stay alert', '🌊 Soft waves south of tower 7', '🎟️ Leash mandatory'],
    false
  ),

  -- 19. Boynton Inlet (Boynton Beach, FL)
  (
    'c06c6bd7-dbce-4df7-8479-73c44c1cb905',
    'Boynton Inlet',
    'Boynton Beach',
    'FL',
    'USA',
    26.545733,
    -80.04395,
    'inlet',
    'intermediate',
    ARRAY['rip currents', 'shallow sandbars', 'sharks', 'localism'],
    ARRAY['Parking nearby', 'Restrooms', 'Jetty protection', 'Long rides'],
    40,
    100,
    295,
    45,
    12,
    10,
    0.5,
    3.0,
    '{"tide": "low", "primary_swell": {"dir_deg": 70, "period_s": 10}, "notes": "NE swells with offshore winds create the best lefts; low tide is key."}'::jsonb,
    115,
    70,
    30,
    ARRAY[8,9,10,11,12,1,2,3],
    'boynton-inlet-boynton-beach-fl',
    'South Florida',
    'Boynton Inlet features a beach break and jetty with an outside sandbar that produces long hollow lefts when NE swell hits at low tide. The north side has clean, empty peaks, while the south side near the jetty offers punchy waves. It''s a fun spot for intermediate surfers seeking challenging waves.',
    'Limited parking in county lots—arrive early and pay the meter. Watch for strict parking enforcement in surrounding neighborhoods.',
    'Paddle through the inlet channel to reach the outside sandbar (about 1/4 mile). Always check for boat traffic and wear a leash.',
    'Low tide is crucial for the outer bar. NE swells and W winds produce long lefts; small SE swells create playful peaks closer to shore.',
    'Moderate crowd on good swells. Locals know the tides—join them or surf during off hours for fewer people.',
    'Low tide, W wind, 3–5 ft NE swell',
    ARRAY['Outside sandbar is 1/4 mile offshore', 'Currents in the inlet can be strong', 'Parking tickets common'],
    'Respect anglers on the jetty and yield to surfers on the peak. Don''t block the boat ramp when parking.',
    'moderate',
    ARRAY['🏄 Long hollow lefts on NE swells', '🚤 Outside bar is far—be prepared', '⚠️ Best at low tide'],
    false
  ),

  -- 20. South Beach (Miami Beach, FL)
  (
    '55cc5dfa-6963-4e17-abfd-d2022a2dcd36',
    'South Beach',
    'Miami Beach',
    'FL',
    'USA',
    25.782721,
    -80.140556,
    'beach',
    'upper-intermediate',
    ARRAY['rip currents', 'sharks', 'hard‑packed sand', 'crowds'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Lifeguard'],
    0,
    80,
    315,
    45,
    12,
    10,
    1.0,
    4.0,
    '{"tide": "rising", "primary_swell": {"dir_deg": 40, "period_s": 10}, "notes": "Needs strong N/NE swell; rare but offers perfect barrels when it happens."}'::jsonb,
    135,
    40,
    40,
    ARRAY[8,9,10,11,12,1,2,3],
    'south-beach-miami-beach-fl',
    'South Florida',
    'South Beach is better known for its vibrant nightlife than surfing, but when a strong N/NE swell sneaks around the Bahamas, this urban beach produces overhead hollow waves. Waves crash onto hard‑packed sand with serious power, making it a challenging spot for upper‑intermediate surfers. Outside of rare swells, the break is mushy or flat.',
    'Parking garages and metered spots line Ocean Drive. Expect high fees and traffic; public transit or biking is a good alternative.',
    'Walk from the boardwalk through designated beach entrances. Surf away from swimmers and avoid lifeguard‑only zones.',
    'Needs a strong N/NE swell to wrap around the Bahamas. Rising tide and WNW winds clean up the face. Sit deep to catch the hollowest sections.',
    'When it''s on, the lineup is crowded with locals and visiting chargers. Otherwise, it''s mostly beachgoers and tourists.',
    'Rising tide, WNW wind, 4–8 ft N‑NE swell',
    ARRAY['Fickle wave—needs strong N/NE swell', 'Waves slam onto hard packed sand', 'Crowded with beachgoers'],
    'Respect lifeguard rules and watch for swimmers. Share waves and keep the vibe positive in this rare Miami surf spot.',
    'very_high',
    ARRAY['👙 Better for people watching', '🌊 Perfect barrels on rare NE swells', '🏝️ One of few breaks in Miami'],
    false
  ),

  -- 21. Pensacola Pier (Pensacola Beach, FL)
  (
    '3433ea8e-6528-4c18-8b16-c830bf642568',
    'Pensacola Pier',
    'Pensacola Beach',
    'FL',
    'USA',
    30.40333,
    -87.23,
    'pier',
    'beginner',
    ARRAY['rip currents', 'jellyfish', 'stingrays', 'localism'],
    ARRAY['Parking nearby', 'Restrooms', 'Lifeguard', 'Surf schools'],
    150,
    240,
    15,
    45,
    12,
    10,
    0.5,
    3.0,
    '{"tide": "any", "primary_swell": {"dir_deg": 195, "period_s": 8}, "notes": "Relies on tropical storms and winter fronts for size; early mornings are best."}'::jsonb,
    195,
    195,
    45,
    ARRAY[6,7,8,9,10,11,12,1,2,3],
    'pensacola-pier-pensacola-beach-fl',
    'Florida Panhandle',
    'Pensacola Beach Pier is the Panhandle''s most popular surf break. Moderate 1–3 ft waves are perfect for beginners and longboarders, while bigger waves arrive during hurricane season and winter cold fronts. Sandbars north of the pier shape waves nicely for long rides and a relaxed atmosphere.',
    'Free parking is available at Casino Beach near the pier. Arrive early during tourist season to secure a spot.',
    'Walk down the sand to either side of the pier; avoid the fishing zone. Surf schools operate on the inside sandbar.',
    'Look for sandbars north of the pier for longer rides. Early morning sessions with light offshore winds offer the cleanest conditions.',
    'The pier is busy, but nearby Casino Beach and Fort Pickens offer more space. Surf off‑season or on weekdays for fewer people.',
    'Any tide, N wind, 2–4 ft S‑SW swell',
    ARRAY['Crowded near the pier', 'Small waves outside hurricane season', 'Jellyfish stings'],
    'Share waves with beginners and respect surf schools. Keep clear of fishermen on the pier.',
    'high',
    ARRAY['🏖️ Ideal for beginners', '🍂 Fall and winter offer consistency', '🌅 Dawn patrol yields clean conditions'],
    false
  ),

  -- 22. Navarre Beach Pier (Navarre, FL)
  (
    '3b948da8-26a0-43f6-8ad3-e99e9cc5174b',
    'Navarre Beach Pier',
    'Navarre',
    'FL',
    'USA',
    30.3767,
    -86.865,
    'pier',
    'beginner',
    ARRAY['rip currents', 'jellyfish', 'stingrays'],
    ARRAY['Parking nearby', 'Restrooms', 'Lifeguard', 'Beginner friendly'],
    150,
    240,
    10,
    45,
    12,
    10,
    0.5,
    3.0,
    '{"tide": "low", "primary_swell": {"dir_deg": 195, "period_s": 8}, "notes": "Works best on SE–SW swells; great learning wave for all ages."}'::jsonb,
    190,
    195,
    45,
    ARRAY[6,7,8,9,10,11,12,1,2,3],
    'navarre-beach-pier-navarre-fl',
    'Florida Panhandle',
    'Navarre Beach is a long, mostly mushy beach break that''s ideal for beginners of all ages. Sandbars between the pier and the park provide plenty of room to spread out. Waves are best at low tide on SE–SW swells, with light NW winds cleaning up the face.',
    'Large public parking lots line the beach near the pier. Parking is free and easy most days.',
    'Walk down boardwalks to reach the sand. Stay clear of fishermen on the pier when paddling out.',
    'Low tide brings more push to the sandbars. Seek SE–SW swells with NW winds for the cleanest waves.',
    'Crowds are moderate—spread out along the long beach to find your own peak. Families often gather near the pier.',
    'Low tide, NW wind, 2–4 ft SE‑SW swell',
    ARRAY['Mushy waves most of the year', 'Watch for sea life', 'Strong afternoon sea breezes'],
    'Be courteous to beginners and beachgoers. Keep the beach clean and respect wildlife.',
    'moderate',
    ARRAY['🐢 Great for beginners', '🌊 Mushy but fun sandbars', '🌬️ NW winds clean it up'],
    false
  ),

  -- 23. South Padre Island – Isla Blanca Park (South Padre Island, TX)
  (
    'fa19107a-a276-4257-872d-c5331264d01b',
    'South Padre Island – Isla Blanca Park',
    'South Padre Island',
    'TX',
    'USA',
    26.07174,
    -97.16025,
    'jetty',
    'advanced',
    ARRAY['strong currents', 'jetty rocks', 'localism', 'sharks'],
    ARRAY['Parking nearby', 'Restrooms', 'World‑class waves', 'Surf shops nearby'],
    90,
    180,
    290,
    45,
    15,
    12,
    0.5,
    3.5,
    '{"tide": "low", "primary_swell": {"dir_deg": 135, "period_s": 11}, "notes": "Performs on E–SE swells; outside sandbar needs 6+ ft."}'::jsonb,
    110,
    135,
    45,
    ARRAY[6,7,8,9,10,11,12,1,2,3],
    'south-padre-island-isla-blanca-park-south-padre-island-tx',
    'Texas Gulf Coast',
    'Isla Blanca Park at the south end of South Padre Island hosts the premiere wave in Texas. Deep water offshore funnels swell into the inside sandbar less than 100 yards from shore, producing long, fast waves that can hold surf up to 8–10 ft. An outside sandbar breaks when waves reach 6–8 ft and can get 12–15 ft in tropical storms. Paddle‑outs are challenging and rips are strong.',
    'Pay the park''s entry fee (about $4 per vehicle) and park in the first lot by the jetties—the gathering spot for local surfers. Arrive early on big swells.',
    'Walk down the beach to the base of the jetties; paddle out between sets using the channel. Always wear a leash and be prepared for strong currents.',
    'The inside sandbar produces long, lined‑up waves on E or SE swells. When the surf is 6–8 ft, the outside sandbar breaks and offers bigger peaks. SE‑S winds are fine; SW–W winds are offshore.',
    'Texas surfers flock here on big swells. The lineup is intense but friendly if you know the rules. Mid‑week sessions offer more space.',
    'Low–mid tide, SW wind, 6–10 ft E–SE swell',
    ARRAY['Strong rips near the jetties', 'Long paddle‑outs', 'Entry fee to park'],
    'Respect the locals and don''t snake. Give fishermen on the jetties space and pack out your trash.',
    'high',
    ARRAY['🌊 Texas''s biggest and most powerful wave', '🧱 Jetties focus swell into long peelers', '💵 $4 entry fee'],
    false
  ),

  -- 24. Surfside Beach (Surfside Beach, TX)
  (
    '466b9671-93c6-402c-9de6-627367d9de6c',
    'Surfside Beach',
    'Surfside Beach',
    'TX',
    'USA',
    28.9521,
    -95.2844,
    'jetty',
    'intermediate',
    ARRAY['rip currents', 'jetty rocks', 'sharks'],
    ARRAY['Parking nearby', 'Restrooms', 'Pier/jetty protection', 'Consistent waves'],
    90,
    180,
    290,
    45,
    15,
    12,
    0.5,
    3.5,
    '{"tide": "any", "primary_swell": {"dir_deg": 135, "period_s": 10}, "notes": "Jetty‑protected break that works on SE–S swells; deep water helps waves hold size."}'::jsonb,
    110,
    135,
    45,
    ARRAY[6,7,8,9,10,11,12,1,2,3],
    'surfside-beach-surfside-beach-tx',
    'Texas Gulf Coast',
    'Surfside Beach produces some of the most consistent surf on the upper Texas coast. Deep water close to shore and long jetties allow the wave to hold double‑overhead surf, while small swells remain rideable. The best surf is about half‑mile north of the jetty near Texas Street, where the jetty blocks side‑shore winds and allows swell to wrap cleanly.',
    'Park along the beach or at small lots near Texas Street. Beach driving permits are required on some sections—check local rules.',
    'Walk north along the beach from the jetty to reach the main peak. Use caution around slippery rocks and strong currents near the jetty.',
    'Works on small swells and handles double overhead. SE–S swells with SW winds produce the cleanest waves. Strong NE/E/SE winds create overhead surf but choppy faces.',
    'Can be busy when it''s firing but generally has space due to the long stretch. Surf mid‑week for fewer people.',
    'Any tide, SW wind, 3–8 ft SE swell',
    ARRAY['Strong S/SW winds can be blocked by the jetty', 'NE/E/SE winds make it choppy', 'Currents around the jetty'],
    'Respect anglers and follow beach driving rules. Don''t litter and be mindful of other surfers.',
    'moderate',
    ARRAY['🌊 Best and most consistent surf on upper Texas coast', '🛡️ Jetty blocks side‑shore winds', '🚗 Short walk north to the peak'],
    false
  ),

  -- 25. Matagorda (Matagorda, TX)
  (
    'd2d0b946-da8b-40ea-86ee-5ca2075d7851',
    'Matagorda',
    'Matagorda',
    'TX',
    'USA',
    28.5947877,
    -95.979953,
    'jetty',
    'advanced',
    ARRAY['rip currents', 'jetty rocks', 'sharks', 'strong currents'],
    ARRAY['Parking nearby', 'Restrooms', 'Camping allowed', 'World‑class wave'],
    90,
    180,
    0,
    45,
    15,
    12,
    0.5,
    3.5,
    '{"tide": "low", "primary_swell": {"dir_deg": 135, "period_s": 11}, "notes": "Works on S–E swells; deep water gives waves extra power."}'::jsonb,
    180,
    135,
    45,
    ARRAY[6,7,8,9,10,11,12,1,2,3],
    'matagorda-matagorda-tx',
    'Texas Gulf Coast',
    'Matagorda is Texas''s premier surf destination where the Colorado River meets the Gulf of Mexico. Deep offshore waters meet shallow sandbars to produce powerful waves and a long left point break near the river mouth. Fast, explosive beach breaks at the jetties can pound over shallow areas and are best suited to advanced surfers.',
    'Drive south on FM 2031 to Jetty Park, which dead‑ends at the Colorado River mouth. Free paved parking and beach parking are available; camping is allowed.',
    'Walk along the beach to the jetties or river mouth. Beware of algae‑covered rocks and heed no‑swim zones due to dangerous currents.',
    'Low tide is best. S, SE and E swells produce long lefts off the river mouth and fast beach breaks at the jetties. N and NW winds groom the face.',
    'Matagorda sees less crowd than Surfside or Padre but still draws surfers on big swells. Spread out along the jetties for room.',
    'Low tide, NW wind, 4–8 ft S‑SE swell',
    ARRAY['Dangerous currents at the river mouth', 'No swimming zone near the jetties', 'Shallow sandbars pound in shallow areas'],
    'Respect the power of the river mouth and obey posted no‑swim zones. Pack out your trash and leave no trace.',
    'moderate',
    ARRAY['💥 Fast, explosive beach break', '🏄 Long left point near river mouth', '⚠️ Strong currents—use caution'],
    false
  ),

  -- 26. Port Aransas – Horace Caldwell Pier (Port Aransas, TX)
  (
    '13febd14-22c1-41a8-a78d-09c436194c9f',
    'Port Aransas – Horace Caldwell Pier',
    'Port Aransas',
    'TX',
    'USA',
    27.826,
    -97.051,
    'pier',
    'intermediate',
    ARRAY['pier pilings', 'crowded lineup', 'strong currents'],
    ARRAY['Parking nearby', 'Restrooms', 'Surf shops nearby', 'Lessons available'],
    90,
    180,
    295,
    45,
    15,
    12,
    0.5,
    3.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 135, "period_s": 10}, "notes": "Works on SE swells; inside break is forgiving while T‑head is punchy."}'::jsonb,
    115,
    135,
    45,
    ARRAY[6,7,8,9,10,11,12,1,2,3],
    'port-aransas-horace-caldwell-pier-port-aransas-tx',
    'Texas Gulf Coast',
    'Horace Caldwell Pier in Port Aransas offers waves for all levels. The T‑head at the end of the pier is suited for advanced surfers who can handle busy lineups, while the inside break on either side is great for beginners and intermediates. Water temperatures hover in the mid‑60s in spring and the pier is a focal point for local surf camps.',
    'Public parking and a small fee apply at the pier. Arrive early during spring and summer to secure a spot; overflow parking is available along the beach.',
    'Walk down the pier and choose to paddle out on either side. Beginners should stay on the inside break and avoid the busy T‑head at the end.',
    'E and SE swells wrap around the pier, producing long rides. Choose the T‑head for more power or the inside for mellow peaks. NW winds groom the faces.',
    'A popular vacation spot, the pier is busy with surfers, anglers, and families. Surf early or outside peak tourism months for fewer crowds.',
    'Mid tide, NW wind, 3–6 ft SE swell',
    ARRAY['T‑head at end is for advanced surfers', 'Inside break is for beginners', 'Watch for fishing lines'],
    'Give right of way to surfers on the T‑head and stay clear of fishermen. Respect surf lessons and beginners in the water.',
    'high',
    ARRAY['🎣 Popular fishing pier', '🌊 Fun waves for all levels', '🧑‍🎓 Surf lessons available'],
    false
  )

ON CONFLICT (id) DO NOTHING;

COMMIT;


