-- Add 29 beaches: Ventura, Santa Barbara, Central Coast, San Francisco, North Coast
-- Safe, idempotent insert using ON CONFLICT

BEGIN;

INSERT INTO public.beaches (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private
) VALUES
  -- VENTURA COUNTY (4)
  
  -- 1. C Street / Ventura Point
  (
    '486dc095-4b21-4edb-838c-97f68b40d1df',
    'C Street / Ventura Point',
    'Ventura',
    'CA',
    'USA',
    34.2744463,
    -119.2976122,
    'point',
    'intermediate',
    ARRAY['rip currents', 'rocks', 'localism', 'strong currents'],
    ARRAY['Parking nearby', 'Consistent waves', 'Restrooms', 'Showers', 'Lifeguard'],
    190,
    300,
    45,
    35,
    12,
    8,
    1.5,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 245, "period_s": 12}, "notes": "Works best with a moderate WSW swell and light offshore winds"}'::jsonb,
    260,
    245,
    55,
    ARRAY[10,11,12,1,2,3],
    'c-street-ventura-ca',
    'Ventura',
    'A long right-hand point break that peels down several sections with room for shortboards and longboards. Multiple take-off peaks mean it can handle a crowd, but it''s often busy with locals and traveling surfers. Good for intermediate riders who can navigate cobblestones and shifting peaks.',
    'Park in the Harbor Boulevard lots or nearby street parking; arrive early as spaces fill up quickly on good swell days.',
    'Walk down the beach from the parking lot to the take-off zone just seaward of the jetty.',
    'Sit wide to pick off the longer rights and watch for sets swinging wide from the outside; the inside reforms are fun for longboarders.',
    'Expect crowds year-round – paddle out early or toward the Fairgrounds for more space. Be respectful of locals.',
    'Mid tide, light NE wind, 3-6 ft W-WSW swell',
    ARRAY['Rocks', 'Strong currents', 'Localism'],
    'Respect the lineup hierarchy and don''t snake locals; spread out along the various peaks.',
    'high',
    ARRAY['🅿️ Park early near the Ventura Fairgrounds', '🌬️ Offshore NE winds are best', '🌊 Look for the outside sets for longest rides'],
    false
  ),

  -- 2. Emma Wood
  (
    '21eae8b9-387c-438c-b144-55796bab5caa',
    'Emma Wood',
    'Ventura',
    'CA',
    'USA',
    34.28528,
    -119.32556,
    'reef',
    'upper-intermediate',
    ARRAY['rip currents', 'shallow reef', 'rocks', 'strong currents'],
    ARRAY['Parking nearby', 'Consistent waves', 'Restrooms'],
    190,
    300,
    45,
    35,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid-low", "primary_swell": {"dir_deg": 245, "period_s": 13}, "notes": "Performs best on W-SW swells with medium periods and lower tides"}'::jsonb,
    250,
    245,
    55,
    ARRAY[10,11,12,1,2,3],
    'emma-wood-ventura-ca',
    'Ventura',
    'A mix of reef and sand peaks with a punchy take-off that mellows into long walls when the reef section lights up. The spot catches most swells and can produce long right and left walls around the offshore reef.',
    'Limited parking along the frontage road and campground; pay attention to signage.',
    'Paddle out from the beach and watch for the channel near the reef to avoid pounding sets.',
    'Position yourself just inside of the reef for the longest walls; on big swells the outside reef offers heavy drops.',
    'Locals dominate the take-off zone when it''s on – respect the rotation and share waves.',
    'Low-mid tide, light NE wind, 4-8 ft W-SW swell',
    ARRAY['Shallow reef', 'Strong currents', 'Localism'],
    'Wait your turn and don''t back-paddle; only experienced surfers should challenge the outside reef.',
    'medium',
    ARRAY['🅿️ Limited roadside parking', '🌬️ Early NE winds are best', '🌊 Sit near the reef for longer walls'],
    false
  ),

  -- 3. Solimar Reef
  (
    '411b3825-c047-4628-997d-08712117ad56',
    'Solimar Reef',
    'Ventura',
    'CA',
    'USA',
    34.3087671,
    -119.3648082,
    'reef',
    'intermediate',
    ARRAY['rocks', 'shallow reef', 'localism'],
    ARRAY['Parking nearby', 'Consistent waves', 'Beginner friendly'],
    190,
    300,
    45,
    35,
    12,
    8,
    1.5,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 245, "period_s": 12}, "notes": "Handles a variety of swell directions; bigger souths favour the beach break while west swells light up the reef"}'::jsonb,
    260,
    245,
    55,
    ARRAY[10,11,12,1,2,3],
    'solimar-reef-ventura-ca',
    'Ventura',
    'Solimar offers a trio of options: a quick, ledgy reef peak called Solimar Reef, a mellower point that peels left over cobblestones, and a beachbreak that handles wind swell. The reef is punchy and suited to intermediate surfers comfortable with rocks.',
    'Park along Highway 1 but watch for no-parking signs and respect private property; there are no facilities here.',
    'Scramble down the riprap and paddle out through a channel between boulders; be mindful of the tides.',
    'For the reef peak, line up with the telephone pole; for the point break, wait for medium-sized sets and trim down the cobblestone point.',
    'Usually less crowded than Ventura Point, but the reef peak can get packed when it''s firing.',
    'Mid tide, light NE wind, 3-6 ft W-SW swell',
    ARRAY['Shallow reef', 'Rocks', 'Localism'],
    'Keep a low profile and share waves with locals; respect the rotation.',
    'medium',
    ARRAY['🅿️ Roadside parking only', '🌬️ Mornings bring light offshore winds', '🌊 Choose between the reef, point or beach depending on swell size'],
    false
  ),

  -- 4. Mondos Beach
  (
    '9a64d63a-0c0c-40b7-bc97-d3d931204bba',
    'Mondos Beach',
    'Ventura',
    'CA',
    'USA',
    34.320498,
    -119.377033,
    'beach',
    'beginner',
    ARRAY['rip currents', 'localism'],
    ARRAY['Parking nearby', 'Beginner friendly', 'Consistent waves'],
    190,
    300,
    45,
    35,
    12,
    8,
    1.5,
    4.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 220, "period_s": 10}, "notes": "Ideal for smaller swells and warm summer conditions"}'::jsonb,
    260,
    245,
    55,
    ARRAY[6,7,8,9,10],
    'mondos-beach-ventura-ca',
    'Ventura',
    'A mellow, rolling wave that breaks over a gently sloping sandbar and cobblestones, ideal for longboards and learners. Mondos picks up most swell directions and has a friendly, welcoming vibe.',
    'Limited roadside parking along Pacific Coast Highway; park tight to the road and avoid blocking driveways.',
    'Walk down the beach and paddle out through the sandy channels; avoid standing on submerged cobbles.',
    'Sit further inside to catch the softer reforms; ideal for practising trimming and cross-stepping on a longboard.',
    'Popular with surf schools and beginners – hit it early morning for fewer people.',
    'Mid tide, light NE winds, 2-4 ft S-W swell',
    ARRAY['Rip currents', 'Localism'],
    'Be patient and share with beginners and surf schools.',
    'high',
    ARRAY['🅿️ Tight roadside parking', '🌬️ Early morning glass-off', '🌊 Gentle rollers perfect for longboards'],
    false
  ),

  -- SANTA BARBARA COUNTY (3)

  -- 5. El Capitan
  (
    '4194e543-a87e-46ee-b317-56c5820c5567',
    'El Capitan',
    'Santa Barbara',
    'CA',
    'USA',
    34.463,
    -120.120,
    'point',
    'advanced',
    ARRAY['rocks', 'strong currents', 'localism'],
    ARRAY['Parking nearby', 'Consistent waves', 'Restrooms', 'Camping'],
    250,
    310,
    45,
    35,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid-low", "primary_swell": {"dir_deg": 280, "period_s": 14}, "notes": "Rarely breaks without a long-period west swell; avoid strong south winds"}'::jsonb,
    280,
    280,
    30,
    ARRAY[10,11,12,1,2,3],
    'el-capitan-santa-barbara-ca',
    'Santa Barbara',
    'When a strong west swell wraps into this secluded point, El Capitan can produce 300-yard right-handers with barrel sections, but it''s fickle and often flat. The take-off is steep over boulders and reef, making it best for experienced surfers.',
    'Parking is available in the state park campground for a day-use fee; arrive early on big swell days.',
    'Follow the trail from the campground down to the cobblestone beach and paddle out through the keyhole in the kelp.',
    'Line up with the cliff and commit to the steep take-off; connect the sections for long rides.',
    'Expect heavy crowds when it''s breaking; respect the tight rotation and give way to those deeper on the point.',
    'Low to mid tide, light NE wind, long-period W-WSW swell',
    ARRAY['Rocks', 'Strong currents', 'Localism'],
    'Wait your turn and avoid paddling around others; locals enforce the lineup etiquette strictly.',
    'high',
    ARRAY['🅿️ Day-use parking in campground', '🌬️ Light NE winds ideal', '🌊 Needs a solid W swell to break'],
    false
  ),

  -- 6. Refugio State Beach
  (
    'a17f4c57-324d-4157-a641-fa935464302e',
    'Refugio State Beach',
    'Goleta',
    'CA',
    'USA',
    34.46222,
    -120.0725,
    'point',
    'beginner',
    ARRAY['rocks', 'rip currents'],
    ARRAY['Parking nearby', 'Beginner friendly', 'Restrooms', 'Camping'],
    250,
    310,
    45,
    35,
    12,
    8,
    0.5,
    3.5,
    '{"tide": "mid-high", "primary_swell": {"dir_deg": 280, "period_s": 12}, "notes": "Needs a west swell to wrap into the cove"}'::jsonb,
    280,
    280,
    30,
    ARRAY[10,11,12,1,2,3],
    'refugio-state-beach-goleta-ca',
    'Santa Barbara',
    'A sheltered, palm-lined point that offers a slow, mushy right-hander over sand and cobblestones – perfect for beginners and longboarders. It needs a decent west swell to wrap into the cove and works at most tides.',
    'Day-use parking is available for a small fee inside the state park; there''s a small store for supplies.',
    'Walk down the path to the beach; paddle out from the sandy inside to reach the point.',
    'Sit wide on the shoulder and angle gently into the soft right walls – great for practising trims.',
    'Families and beginners flock here on weekends; check it during weekdays for more room.',
    'All tides, light NE winds, 2-5 ft W swell',
    ARRAY['Rocks', 'Rip currents'],
    'Share the mellow vibe and yield to beginners; no dropping in on long rides.',
    'medium',
    ARRAY['🅿️ Pay to park in the state park', '🌬️ Works best with light NE winds', '🌊 Slow, beginner-friendly right'],
    false
  ),

  -- 7. Mesa Lane
  (
    '0f0a1339-f7d0-4b1a-ae95-61939998b4ef',
    'Mesa Lane',
    'Santa Barbara',
    'CA',
    'USA',
    34.4031,
    -119.7244,
    'reef',
    'upper-intermediate',
    ARRAY['rocks', 'shallow reef', 'localism'],
    ARRAY['Parking nearby', 'Consistent waves'],
    240,
    300,
    45,
    35,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid-high", "primary_swell": {"dir_deg": 270, "period_s": 12}, "notes": "Rocky reef requires care; only surfable when sand fills in"}'::jsonb,
    275,
    270,
    30,
    ARRAY[10,11,12,1,2,3],
    'mesa-lane-santa-barbara-ca',
    'Santa Barbara',
    'A rarely surfed reef break accessed via 240 steep steps, Mesa Lane offers both lefts and rights over a rocky bottom and works best on a rising tide with a west swell. Local surfers favour this spot after work and school.',
    'Street parking in the Mesa neighbourhood; be respectful of residents and pack out trash.',
    'Descend the long staircase to the beach; paddle out carefully over rocks and stay clear of submerged boulders.',
    'Wait for incoming tide and west swell; aim for the channel to avoid the shallow reef and pick off the cleaner peaks.',
    'Not as crowded as other Santa Barbara spots but locals can be unfriendly; go with a buddy and be respectful.',
    'Mid tide rising, light NE winds, 3-6 ft W swell',
    ARRAY['Rocks', 'Shallow reef', 'Localism'],
    'Don''t litter and keep noise down in the residential area; respect the lineup hierarchy.',
    'medium',
    ARRAY['🅿️ Limited street parking', '🌬️ Morning offshore winds', '🌊 Needs rising tide and west swell'],
    false
  ),

  -- CENTRAL COAST (10)

  -- 8. Pismo Pier
  (
    'ee2aad76-966d-4aa3-86a2-499fde59b271',
    'Pismo Pier',
    'Pismo Beach',
    'CA',
    'USA',
    35.142,
    -120.642,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'strong currents', 'sharks', 'localism'],
    ARRAY['Parking nearby', 'Consistent waves', 'Restrooms', 'Lifeguard'],
    230,
    300,
    90,
    35,
    12,
    8,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 265, "period_s": 13}, "notes": "Works best with W-NW swells; avoid when winds exceed 15 kt"}'::jsonb,
    270,
    265,
    35,
    ARRAY[10,11,12,1,2,3],
    'pismo-pier-pismo-beach-ca',
    'Central Coast',
    'A long pier divides this consistent Central Coast beach break. The north side offers peaky lefts and rights with more punch, while the south side is mellower and better for learners. It catches most W and NW swells and can be rippable on a mid tide.',
    'Ample parking in downtown Pismo Beach lots and along the promenade; pay stations operate during peak season.',
    'Walk onto the sand near the pier and choose north or south; watch out for pilings and fishermen.',
    'Look for sandbars north of the pier for longer rides; head south for softer walls and less crowd.',
    'Crowded on weekends but spreads out along the beach; dawn patrol offers emptier peaks.',
    'Mid tide, light E wind, 3-6 ft W-NW swell',
    ARRAY['Rip currents', 'Sharks', 'Localism'],
    'Don''t paddle between the pier pilings; respect fishermen and other beach users.',
    'medium',
    ARRAY['🅿️ Plenty of parking downtown', '🌬️ Light east winds groom the sandbars', '🌊 Choose north side for punchier peaks'],
    false
  ),

  -- 9. Oceano / Grover Beach
  (
    '124c7751-a232-4c92-be53-3a750a315256',
    'Oceano / Grover Beach',
    'Grover Beach',
    'CA',
    'USA',
    35.105,
    -120.62,
    'beach',
    'beginner',
    ARRAY['rip currents', 'shorebreak'],
    ARRAY['Parking nearby', 'Beginner friendly', 'Restrooms'],
    230,
    300,
    90,
    35,
    12,
    8,
    2.0,
    6.0,
    '{"tide": "mid-high", "primary_swell": {"dir_deg": 265, "period_s": 12}, "notes": "Beachbreak that works year-round; avoid strong onshore winds"}'::jsonb,
    270,
    265,
    35,
    ARRAY[10,11,12,1,2,3],
    'oceano-grover-beach-ca',
    'Central Coast',
    'Wide, sandy beach break just south of Pismo Pier, offering gentle peaks ideal for beginners and longboarders. Sandbars shift often, and the southern sections see fewer crowds.',
    'Park in the public lot off Grand Avenue or on side streets; there''s usually room except summer weekends.',
    'Walk across the broad beach to the water; watch for vehicles as parts are open to driving.',
    'Look for small rips to find deeper channels; ride the softer shoulders for long rides.',
    'Less crowded than Pismo Pier; spread out along the long shoreline for space.',
    'Mid-high tide, light E winds, 2-5 ft W-NW swell',
    ARRAY['Rip currents', 'Shorebreak'],
    'Respect families and beach drivers; keep off the dunes.',
    'medium',
    ARRAY['🅿️ Easy parking off Grand Avenue', '🌬️ Offshore east winds clean up the waves', '🌊 Gentle peaks ideal for learners'],
    false
  ),

  -- 10. Jalama Beach
  (
    '1ec3682e-d993-4c60-a650-f630e1ea3b06',
    'Jalama Beach',
    'Jalama',
    'CA',
    'USA',
    34.5119,
    -120.5,
    'beach',
    'upper-intermediate',
    ARRAY['sharks', 'strong currents', 'rip currents', 'cold water'],
    ARRAY['Parking nearby', 'Restrooms', 'Camping', 'Consistent waves'],
    230,
    310,
    90,
    35,
    12,
    8,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 270, "period_s": 14}, "notes": "Best on long-period NW swells with light wind"}'::jsonb,
    280,
    270,
    40,
    ARRAY[10,11,12,1,2,3],
    'jalama-beach-jalama-ca',
    'Central Coast',
    'Remote and exposed beach break known for powerful, hollow peaks and long walls when sandbars align. Jalama picks up any swell and can be world-class on a clean NW swell, but currents are strong and the water is cold.',
    'Day-use parking available at Jalama Beach County Park for a fee; camping spots are also available.',
    'Walk down the beach from the parking lot to whichever sandbar looks best; there''s a long stretch to choose from.',
    'Check multiple peaks; the best banks are often near the rivermouth. Duck-dive often to get out in heavy surf.',
    'Usually uncrowded due to remote location; still respect other surfers and spread out.',
    'Mid tide, light E winds, 4-8 ft NW swell',
    ARRAY['Sharks', 'Strong currents', 'Rip currents', 'Cold water'],
    'Pack out all trash and respect the wildness of this beach; give right of way to surfers already riding.',
    'low',
    ARRAY['🅿️ Pay to park at the county park', '🌬️ Offshore east winds clean up the swell', '🌊 Remote beachbreak picks up all swell'],
    false
  ),

  -- 11. Waddell Creek
  (
    '1913d8a0-38f9-468f-bb4c-18789e92731d',
    'Waddell Creek',
    'Davenport',
    'CA',
    'USA',
    37.0925,
    -122.2767,
    'river-mouth',
    'upper-intermediate',
    ARRAY['rip currents', 'strong currents', 'sharks', 'cold water'],
    ARRAY['Parking nearby', 'Consistent waves', 'Wind sports'],
    200,
    310,
    90,
    35,
    15,
    10,
    2.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 255, "period_s": 13}, "notes": "Works on multiple swell directions; wind is the biggest factor"}'::jsonb,
    260,
    255,
    55,
    ARRAY[10,11,12,1,2,3],
    'waddell-creek-davenport-ca',
    'Central Coast',
    'Exposed rivermouth and beach break at the base of the Santa Cruz Mountains, Waddell Creek picks up SW, W and NW swells and can deliver punchy peaks and river-mouth walls. Windsurfers and kitesurfers frequent the area when the wind is up.',
    'Park along Highway 1 at the trailhead to Waddell Beach; there''s room for vehicles but no facilities.',
    'Cross the creek if necessary and paddle out through rips; be prepared for long paddles in strong winds.',
    'Find peaks near the rivermouth for the best shape; time your paddle-out between sets and be aware of strong currents.',
    'Surfers share the water with wind and kite surfers; early mornings before the wind picks up offer fewer people.',
    'Mid tide, light E winds, 4-8 ft W-SW swell',
    ARRAY['Rip currents', 'Strong currents', 'Sharks', 'Cold water'],
    'Share the line-up with kite and wind surfers; stay clear of their lines and rigs.',
    'medium',
    ARRAY['🅿️ Roadside parking along Highway 1', '🌬️ Mornings before wind picks up', '🌊 Punchy peaks near rivermouth'],
    false
  ),

  -- 12. Pleasure Point
  (
    'cdfb7e59-ce4e-4112-acc5-15fe56a8b6a3',
    'Pleasure Point',
    'Santa Cruz',
    'CA',
    'USA',
    36.9513,
    -121.9611,
    'point',
    'intermediate',
    ARRAY['rocks', 'shallow reef', 'localism'],
    ARRAY['Parking nearby', 'Consistent waves', 'Beginner friendly', 'Restrooms'],
    200,
    300,
    90,
    35,
    12,
    8,
    2.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 250, "period_s": 12}, "notes": "SW-W swells wrap into the point; hold off until mid tide for best shape"}'::jsonb,
    260,
    250,
    50,
    ARRAY[10,11,12,1,2,3],
    'pleasure-point-santa-cruz-ca',
    'Central Coast',
    'The crown jewel of Santa Cruz''s East Side, Pleasure Point is a long right point over reef offering multiple sections, from First Peak to Sewers. It''s surfable year-round and accommodates longboards and shortboards depending on swell size.',
    'Street parking along East Cliff Drive; expect to walk a bit and respect residents.',
    'Take the staircases down from East Cliff Drive and paddle out through the channel between kelp patches.',
    'Sit deeper for the longest rides; on small days, longboards rule the point, while bigger swells favour high-performance turns.',
    'Always crowded with locals and visitors; dawn patrol or weekday sessions offer slightly less crowd.',
    'Mid tide, light E winds, 3-6 ft SW-W swell',
    ARRAY['Rocks', 'Shallow reef', 'Localism'],
    'Respect locals and take turns; avoid cutting through yards to access the beach.',
    'high',
    ARRAY['🅿️ Street parking only', '🌬️ Early offshore winds', '🌊 Long right point with multiple sections'],
    false
  ),

  -- 13. 38th Avenue (Santa Cruz)
  (
    '36a2d39e-64f1-4c7e-9618-ac8cc695af62',
    '38th Avenue (Santa Cruz)',
    'Santa Cruz',
    'CA',
    'USA',
    36.9557,
    -121.9646,
    'reef',
    'lower-intermediate',
    ARRAY['rocks', 'rip currents'],
    ARRAY['Parking nearby', 'Beginner friendly', 'Consistent waves'],
    200,
    300,
    90,
    35,
    12,
    8,
    2.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 240, "period_s": 11}, "notes": "Loves a mix of south and west swells; avoid negative tides"}'::jsonb,
    260,
    250,
    50,
    ARRAY[5,6,7,8,9,10],
    '38th-avenue-santa-cruz-ca',
    'Central Coast',
    'Sometimes called the Hook''s little sister, 38th Avenue is a user-friendly right reef that handles south and west swells. It offers long rides at lower tide and is popular with longboarders and groms.',
    'Parking is limited along 38th Avenue and East Cliff Drive; arrive early or park farther away and walk.',
    'Walk down the stairway at the end of 38th Avenue; watch your footing on slippery rocks.',
    'Sit wide on the shoulder to pick off softer waves; bigger days produce faster walls closer to the point.',
    'Expect groms and longboarders; share waves and keep an eye on beginners.',
    'Mid tide rising, light E winds, 2-5 ft SW-W swell',
    ARRAY['Rocks', 'Rip currents'],
    'Be courteous to kids and locals; give way when dropping in on the inside.',
    'high',
    ARRAY['🅿️ Very limited parking', '🌬️ Early east winds are best', '🌊 Fun, forgiving right point for longboards'],
    false
  ),

  -- 14. Capitola
  (
    'dca521c3-ab32-46c6-8045-8aa7477f59a8',
    'Capitola',
    'Capitola',
    'CA',
    'USA',
    36.9753,
    -121.9469,
    'beach',
    'beginner',
    ARRAY['rocks', 'rip currents'],
    ARRAY['Parking nearby', 'Beginner friendly', 'Restrooms'],
    150,
    220,
    90,
    35,
    12,
    8,
    1.5,
    4.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 180, "period_s": 12}, "notes": "Only works on south swells; avoid midday low tides"}'::jsonb,
    200,
    185,
    35,
    ARRAY[5,6,7,8,9],
    'capitola-capitola-ca',
    'Central Coast',
    'A protected cove in the heart of Capitola village offering gentle waves ideal for first-timers and longboarders. It needs a south swell to wrap into Monterey Bay and is often flat in winter.',
    'Paid parking lots and meters are available in Capitola village; expect summer crowds and limited spaces.',
    'Walk down the stairs from the Esplanade; paddle out through the sandy channel on the south side.',
    'Stay toward the inside for softer waves; the outside sandbar can offer longer rides on bigger south swells.',
    'Busy with families and learners in summer; go early morning for calmer vibes.',
    'Mid tide, light E winds, 2-4 ft S-SW swell',
    ARRAY['Rocks', 'Rip currents'],
    'Be patient and share with surf schools; keep out of swimmers'' area.',
    'high',
    ARRAY['🅿️ Paid parking in village', '🌬️ Early east winds', '🌊 Needs south swell to break'],
    false
  ),

  -- 15. Steamer Lane
  (
    '2609a9ff-d247-4e0b-888f-a793ff7177a5',
    'Steamer Lane',
    'Santa Cruz',
    'CA',
    'USA',
    36.9506,
    -122.025,
    'point',
    'advanced',
    ARRAY['rocks', 'strong currents', 'localism', 'sharks'],
    ARRAY['Parking nearby', 'Consistent waves', 'World-class wave', 'Restrooms'],
    240,
    320,
    90,
    35,
    15,
    10,
    2.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 290, "period_s": 14}, "notes": "Performs best on long-period NW swells; avoid high tide when the wave backs off"}'::jsonb,
    290,
    280,
    40,
    ARRAY[10,11,12,1,2,3],
    'steamer-lane-santa-cruz-ca',
    'Central Coast',
    'One of California''s most iconic waves, Steamer Lane is a series of right-hand reef points (Indicators, Middle Peak, and Slot). It offers long walls and powerful sections and is best tackled by experienced surfers comfortable with crowds and cliffs.',
    'Parking along West Cliff Drive can be tight; there is a pay lot at the Lighthouse Field State Beach.',
    'Jump off the cliff at the Slot or paddle from the beach at Indicators; time your entry to avoid sets.',
    'Sit deep for the longest rides; watch the boil and time your turns as the wave wraps around the point.',
    'Always crowded with locals, groms and visitors; respect the order and don''t cut the line.',
    'Mid tide, light E winds, long-period NW swell',
    ARRAY['Rocks', 'Strong currents', 'Localism', 'Sharks'],
    'Know the pecking order and wait your turn; mistakes on the take-off can be dangerous.',
    'high',
    ARRAY['🅿️ Pay lot near Lighthouse Field', '🌬️ Needs light east winds', '🌊 Legendary right-hand reef points'],
    false
  ),

  -- 16. Rockview (Santa Cruz)
  (
    'f3e1216f-2a17-47be-8c2e-67d8588ab065',
    'Rockview (Santa Cruz)',
    'Santa Cruz',
    'CA',
    'USA',
    36.9564,
    -121.967,
    'reef',
    'intermediate',
    ARRAY['rocks', 'shallow reef', 'localism'],
    ARRAY['Parking nearby', 'Consistent waves'],
    200,
    300,
    90,
    35,
    12,
    8,
    2.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 245, "period_s": 11}, "notes": "Loves south swells with a little west in the mix"}'::jsonb,
    260,
    250,
    50,
    ARRAY[5,6,7,8,9,10],
    'rockview-santa-cruz-ca',
    'Central Coast',
    'Known locally as The Hook, Rockview offers a peaky right-hand reef break with playful sections that work on south and west swells. It''s slightly more exposed than neighbouring Pleasure Point and has a punchier take-off.',
    'Parking along East Cliff Drive is limited; arrive early or park inland and walk.',
    'Use the stairway down the cliff and jump off the rocks or paddle around the point; be mindful of seaweed.',
    'Sit inside to pick off the reforms; bigger sets break further out and are more powerful.',
    'Crowded on south swells; share the line-up and avoid burning locals.',
    'Mid tide rising, light E winds, 3-5 ft SW-W swell',
    ARRAY['Rocks', 'Shallow reef', 'Localism'],
    'Same rules as Pleasure Point – wait your turn and respect the order.',
    'high',
    ARRAY['🅿️ Limited cliff-side parking', '🌬️ Early east winds', '🌊 Punchy right reef with fun sections'],
    false
  ),

  -- 17. Mitchell's Cove
  (
    'abb56ca0-7dad-4026-960f-23412fa5cc8b',
    'Mitchell''s Cove',
    'Santa Cruz',
    'CA',
    'USA',
    36.9496,
    -122.0295,
    'reef',
    'intermediate',
    ARRAY['rocks', 'rip currents'],
    ARRAY['Parking nearby', 'Consistent waves', 'Dog friendly'],
    240,
    300,
    90,
    35,
    15,
    10,
    1.5,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 280, "period_s": 13}, "notes": "Works best on W-NW swells when other Santa Cruz spots are too crowded"}'::jsonb,
    285,
    270,
    30,
    ARRAY[10,11,12,1,2,3],
    'mitchells-cove-santa-cruz-ca',
    'Central Coast',
    'A reefy cove along West Cliff Drive that offers wedgy peaks and occasional barrels on W and NW swells. It''s also a popular dog beach, so expect pups running around the sand.',
    'Small parking area along West Cliff Drive; spaces fill quickly on swell days.',
    'Climb down the bluff via a staircase and paddle out through the small channel on the west side.',
    'Sit deep in the bowl for the wedgiest take-offs; be ready to kick out before the inside closes out.',
    'Locals frequent this spot but crowds thin out compared to Steamer Lane; be respectful and share with dog walkers.',
    'Mid tide, light E winds, 3-6 ft NW swell',
    ARRAY['Rocks', 'Rip currents'],
    'Keep your dog under control and pack out waste; respect locals in the line-up.',
    'medium',
    ARRAY['🅿️ Small bluff-top parking', '🌬️ Morning offshore winds', '🌊 Wedgy peaks at mid tide'],
    false
  ),

  -- SAN FRANCISCO (5)

  -- 18. Ocean Beach SF – North
  (
    'eca7e91a-0e5e-40d5-acb4-59c6ff50d861',
    'Ocean Beach SF – North',
    'San Francisco',
    'CA',
    'USA',
    37.7751,
    -122.5142,
    'beach',
    'advanced',
    ARRAY['rip currents', 'strong currents', 'cold water', 'sharks'],
    ARRAY['Parking nearby', 'Consistent waves', 'Restrooms', 'Lifeguard'],
    240,
    320,
    90,
    35,
    15,
    10,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 290, "period_s": 14}, "notes": "Thrives on long-period NW swells and light offshore winds"}'::jsonb,
    280,
    280,
    40,
    ARRAY[9,10,11,12,1,2],
    'ocean-beach-north-san-francisco-ca',
    'San Francisco',
    'The north end of Ocean Beach near the Cliff House can handle large winter swells, producing heavy A-frame peaks and long walls. Strong rips and cold water make it suitable only for experienced surfers.',
    'Park along Point Lobos Avenue or in the Cliff House lot; carry valuables with you.',
    'Walk down the sand dunes and time your paddle-out through a rip; prepare for long paddles.',
    'Look for rip currents that act as channels out; position yourself to catch the largest sets and be ready to pump down the line.',
    'Crowds thin out on the north end compared to central beach, but locals frequent the area; respect them.',
    'Mid tide, light E winds, 6-10 ft NW swell',
    ARRAY['Rip currents', 'Strong currents', 'Cold water', 'Sharks'],
    'Only experienced surfers should paddle out; don''t paddle out alone in heavy surf.',
    'medium',
    ARRAY['🅿️ Parking at Point Lobos Avenue', '🌬️ Offshore east winds clean up the surf', '🌊 Heavy peaks require strong paddling'],
    false
  ),

  -- 19. Ocean Beach SF – Middle
  (
    'e8a921b7-c2b5-4259-9e5c-bd06765f7ae4',
    'Ocean Beach SF – Middle',
    'San Francisco',
    'CA',
    'USA',
    37.7601,
    -122.5130,
    'beach',
    'advanced',
    ARRAY['rip currents', 'strong currents', 'cold water', 'sharks'],
    ARRAY['Parking nearby', 'Consistent waves', 'Restrooms', 'Lifeguard'],
    240,
    320,
    90,
    35,
    15,
    10,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 295, "period_s": 15}, "notes": "Needs strong, long-period NW swells; currents can be brutal"}'::jsonb,
    280,
    280,
    40,
    ARRAY[9,10,11,12,1,2],
    'ocean-beach-middle-san-francisco-ca',
    'San Francisco',
    'The middle section of Ocean Beach offers shifting sandbars that produce hollow barrels on a strong NW swell. Peaks are less defined but can provide long rides when the banks are good. Expect powerful waves and strong currents.',
    'Large parking lots at the Great Highway and beach chalet; watch for vehicle break-ins.',
    'Walk over the dunes and paddle out through a rip; choose a central channel for easier access.',
    'Keep moving to find the best sandbar; use the rip currents to get outside and choose waves that wall up down the line.',
    'Most crowded section of Ocean Beach; however, the beach is long so you can spread out.',
    'Mid tide, light E winds, 6-12 ft NW swell',
    ARRAY['Rip currents', 'Strong currents', 'Cold water', 'Sharks'],
    'Know your limits and avoid paddling out alone; respect locals and keep the beach clean.',
    'high',
    ARRAY['🅿️ Large parking lots along Great Highway', '🌬️ Offshore east wind cleans up barrels', '🌊 Shifting sandbars require constant repositioning'],
    false
  ),

  -- 20. Ocean Beach SF – Sloat
  (
    'd9524c9d-8315-4686-9d35-24ceb6db2a82',
    'Ocean Beach SF – Sloat',
    'San Francisco',
    'CA',
    'USA',
    37.7367,
    -122.5109,
    'beach',
    'advanced',
    ARRAY['rip currents', 'strong currents', 'cold water', 'sharks'],
    ARRAY['Parking nearby', 'Consistent waves', 'Restrooms', 'Lifeguard'],
    240,
    320,
    90,
    35,
    15,
    10,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 290, "period_s": 14}, "notes": "Firing on winter NW swells; still needs small window for safety"}'::jsonb,
    280,
    280,
    40,
    ARRAY[9,10,11,12,1,2],
    'ocean-beach-sloat-san-francisco-ca',
    'San Francisco',
    'The south end of Ocean Beach around Sloat Boulevard often has the most defined sandbars, producing punchy peaks and occasional tubes. Currents are still strong and the water is frigid, so only confident surfers should paddle out.',
    'Ample parking at Sloat Boulevard and along the Great Highway; still keep valuables hidden.',
    'Use the rip currents as channels to paddle out; time your entry to avoid being caught inside.',
    'Look for sandbars near the lifeguard tower; waves here can be shorter but more hollow.',
    'Popular with the daily crew but you can still find peaks to yourself due to the beach''s length.',
    'Mid tide, light E winds, 6-10 ft NW swell',
    ARRAY['Rip currents', 'Strong currents', 'Cold water', 'Sharks'],
    'Don''t leave trash behind and be aware of other surfers; help others if they get caught in rips.',
    'medium',
    ARRAY['🅿️ Parking near Sloat Boulevard', '🌬️ Offshore east wind is key', '🌊 Hollow peaks with strong rips'],
    false
  ),

  -- 21. Fort Point (San Francisco)
  (
    '208cd792-7e94-419f-802c-09c9634ec6a9',
    'Fort Point (San Francisco)',
    'San Francisco',
    'CA',
    'USA',
    37.81,
    -122.478,
    'reef',
    'upper-intermediate',
    ARRAY['rocks', 'strong currents', 'localism', 'cold water'],
    ARRAY['Parking nearby', 'Consistent waves', 'Unique scenery'],
    250,
    310,
    90,
    35,
    15,
    10,
    1.0,
    4.0,
    '{"tide": "mid-low", "primary_swell": {"dir_deg": 285, "period_s": 15}, "notes": "Only breaks a few times a year on large W swells"}'::jsonb,
    295,
    280,
    30,
    ARRAY[9,10,11,12,1,2],
    'fort-point-san-francisco-ca',
    'San Francisco',
    'A novelty right-hand reef that breaks directly under the Golden Gate Bridge. When a big west swell refracts around Land''s End, Fort Point offers long peeling rights with a spectacular backdrop. It''s fickle and often crowded with locals.',
    'Parking lot at Fort Point National Historic Site; limited when the surf is on.',
    'Scramble down the rocks and jump off the seawall at low tide; be careful of slippery algae.',
    'Line up with the bridge tower for the best take-off; the wave speeds up around the corner, so stay high on the face.',
    'Local bodyboarders and surfers dominate when it breaks; be respectful and expect to wait your turn.',
    'Low to mid tide, light E winds, 6-10 ft W-NW swell',
    ARRAY['Rocks', 'Strong currents', 'Localism', 'Cold water'],
    'Locals have priority – wait for invites and don''t paddle around others.',
    'high',
    ARRAY['🅿️ Limited parking at the fort', '🌬️ Needs east winds', '🌊 Novelty right reef under the bridge'],
    false
  ),

  -- 22. Mavericks
  (
    '033b5518-ee98-4014-9d81-114b936778af',
    'Mavericks',
    'Half Moon Bay',
    'CA',
    'USA',
    37.4945,
    -122.5022,
    'reef',
    'advanced',
    ARRAY['sharks', 'strong currents', 'cold water', 'shallow reef', 'rocks'],
    ARRAY['Parking nearby', 'World-class wave'],
    270,
    330,
    90,
    30,
    10,
    5,
    2.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 300, "period_s": 20}, "notes": "Requires large, long-period NW swells; safety is paramount"}'::jsonb,
    305,
    300,
    30,
    ARRAY[11,12,1,2,3],
    'mavericks-half-moon-bay-ca',
    'San Francisco',
    'One of the most famous big-wave spots on Earth, Mavericks breaks a half-mile offshore over a shallow reef, producing giant right and left walls when long-period NW swells march in. Only expert big-wave surfers with safety teams should attempt it.',
    'Park at Pillar Point Harbor and walk the trail out to the bluff; safety crews often launch from the harbour.',
    'Most surfers reach the lineup by Jet Ski; if paddling, expect a 30-minute paddle around the reef and huge walls of whitewater.',
    'Wait for the largest sets and commit fully; know how to use a vest and safety equipment. Spotters and rescue teams are essential.',
    'Only a handful of surfers are in the lineup when it''s breaking; respect the professionals and don''t paddle out if you''re not qualified.',
    'Mid tide, light E winds, 20-40 ft NW swell',
    ARRAY['Sharks', 'Strong currents', 'Cold water', 'Shallow reef', 'Rocks'],
    'Coordinate with safety teams; follow big-wave protocols and never surf alone.',
    'low',
    ARRAY['🅿️ Park at Pillar Point Harbor', '🌬️ East winds and fogless mornings', '🌊 Huge, dangerous waves for experts only'],
    false
  ),

  -- NORTH COAST (7)

  -- 23. Pacifica / Linda Mar
  (
    'f2cc331f-6569-40d9-a98b-9f50fb3da67f',
    'Pacifica / Linda Mar',
    'Pacifica',
    'CA',
    'USA',
    37.59,
    -122.4958,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'localism', 'sharks', 'cold water'],
    ARRAY['Parking nearby', 'Beginner friendly', 'Restrooms', 'Showers'],
    210,
    300,
    90,
    35,
    12,
    8,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 255, "period_s": 12}, "notes": "Handles multiple swell directions; avoid high wind afternoons"}'::jsonb,
    260,
    255,
    45,
    ARRAY[9,10,11,12,1,2],
    'linda-mar-pacifica-ca',
    'San Francisco',
    'Pacifica''s main break is a long crescent beach offering peaks for all levels. The north end offers punchier waves, the middle is usually softer for beginners, and the south end near the cliff produces occasional lefts on south swells.',
    'Large paid parking lot at the south end; free street parking fills quickly on the north end.',
    'Easy beach access from the parking lots; avoid surfing near fishermen or swimmers.',
    'On smaller days stay in the middle for mellow rollers; on bigger days head north for more power.',
    'Very crowded on weekends and holidays; midweek and early mornings have fewer learners.',
    'Mid tide, light E winds, 3-6 ft W-SW swell',
    ARRAY['Rip currents', 'Localism', 'Sharks', 'Cold water'],
    'Respect surf schools and novices; don''t hassle learners.',
    'high',
    ARRAY['🅿️ Big paid lot by Taco Bell', '🌬️ Light offshore winds improve shape', '🌊 Choose section based on skill level'],
    false
  ),

  -- 24. Rockaway Beach (Pacifica)
  (
    '49739de1-95fb-4e26-b890-56fafd8d2622',
    'Rockaway Beach (Pacifica)',
    'Pacifica',
    'CA',
    'USA',
    37.5932,
    -122.5165,
    'beach',
    'intermediate',
    ARRAY['rocks', 'rip currents', 'localism', 'cold water'],
    ARRAY['Parking nearby', 'Consistent waves', 'Restrooms'],
    230,
    320,
    90,
    35,
    12,
    8,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 290, "period_s": 13}, "notes": "Best on mid-sized NW swells; avoid at maxed-out sizes"}'::jsonb,
    280,
    275,
    45,
    ARRAY[9,10,11,12,1,2],
    'rockaway-beach-pacifica-ca',
    'San Francisco',
    'Smaller cove just south of Linda Mar, Rockaway Beach offers punchy peaks and occasional barrels when sandbars align. The northern corner has a rock reef that produces a wedgy right. Currents can be strong and it closes out on big swells.',
    'Small parking lot near the beach and additional street parking; restaurants line the cove but spaces fill quickly.',
    'Walk across the beach and pick a sandbar; avoid surfing too close to the rocks on big days.',
    'Look for peaks near the northern reef for wedgy rights; on smaller days there are peaks scattered across the beach.',
    'Locals frequent the north reef; the middle section is less crowded but also less consistent.',
    'Mid tide, light E winds, 4-7 ft NW swell',
    ARRAY['Rocks', 'Rip currents', 'Localism', 'Cold water'],
    'Give locals priority at the reef; be cautious when paddling near rocks.',
    'medium',
    ARRAY['🅿️ Limited cove parking', '🌬️ Offshore east winds', '🌊 Punchy peaks with wedgy rights'],
    false
  ),

  -- 25. Bolinas
  (
    '5c0969f9-8496-4291-830e-8caea021d7cc',
    'Bolinas',
    'Bolinas',
    'CA',
    'USA',
    37.9109,
    -122.6891,
    'river-mouth',
    'beginner',
    ARRAY['sharks', 'rip currents', 'rocks'],
    ARRAY['Parking nearby', 'Beginner friendly', 'Restrooms'],
    260,
    330,
    90,
    35,
    12,
    8,
    1.5,
    5.0,
    '{"tide": "high", "primary_swell": {"dir_deg": 295, "period_s": 10}, "notes": "Needs small to medium NW swells; bigger swells go past the headland"}'::jsonb,
    310,
    295,
    35,
    ARRAY[9,10,11,12,1,2],
    'bolinas-bolinas-ca',
    'North Coast',
    'Tucked in behind Duxbury Reef, Bolinas offers soft rolling waves at the mouth of a lagoon – perfect for beginners and longboarders. The sandbars shift but there''s usually a mellow left breaking off the jetty and a right across the channel.',
    'Parking is limited in the small village; park along the road to the beach or at the ferry landing.',
    'Walk down the ramp near the lagoon and paddle across the channel to the sandbar; watch for currents around the rivermouth.',
    'For the left, sit by the groyne and wait for sets; the right works best on small swells and high tide.',
    'Popular with beginners and rental shops; weekdays and mornings are quieter.',
    'High tide, light E winds, 2-4 ft NW swell',
    ARRAY['Sharks', 'Rip currents', 'Rocks'],
    'Be respectful of the tight-knit community; stay off private property and don''t litter.',
    'medium',
    ARRAY['🅿️ Very limited parking in town', '🌬️ Offshore east winds help break wrap around', '🌊 Soft waves ideal for longboards'],
    false
  ),

  -- 26. Stinson Beach
  (
    '5a5dc7b8-4d30-44af-9715-3dbb4dbc9859',
    'Stinson Beach',
    'Stinson Beach',
    'CA',
    'USA',
    37.9007,
    -122.6443,
    'beach',
    'beginner',
    ARRAY['sharks', 'rip currents', 'rocks'],
    ARRAY['Parking nearby', 'Beginner friendly', 'Restrooms', 'Lifeguard'],
    240,
    320,
    90,
    35,
    12,
    8,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 280, "period_s": 11}, "notes": "Needs smaller NW swells for beginner waves; bigger swells become heavy"}'::jsonb,
    280,
    280,
    40,
    ARRAY[9,10,11,12,1,2],
    'stinson-beach-stinson-beach-ca',
    'North Coast',
    'Long sandy beach north of San Francisco that offers gentle beach break waves for beginners when the sandbars are arranged. It gets bigger and more powerful during winter swells but is usually a mellow place to learn.',
    'Large parking lot at Stinson Beach State Park fills early on sunny days; arrive early or visit midweek.',
    'Easy walk across the wide beach; watch for lifeguard flags indicating rip currents.',
    'Look for smaller peaks near the lifeguard towers; bigger days require more paddling and caution.',
    'Popular with beachgoers and families; summer crowds are heavy but the beach is long enough to spread out.',
    'Mid tide, light E winds, 3-5 ft W-NW swell',
    ARRAY['Sharks', 'Rip currents', 'Rocks'],
    'Stay out of flagged swim areas and follow lifeguard instructions.',
    'medium',
    ARRAY['🅿️ Arrive early to find parking', '🌬️ Morning offshore winds clean up the surf', '🌊 Gentle beach break for beginners'],
    false
  ),

  -- 27. Bodega Bay / Doran Beach
  (
    '92e18cf0-97c3-4c68-9cdf-800eb9ac4313',
    'Bodega Bay / Doran Beach',
    'Bodega Bay',
    'CA',
    'USA',
    38.3117,
    -123.0477,
    'beach',
    'beginner',
    ARRAY['sharks', 'rip currents', 'rocks'],
    ARRAY['Parking nearby', 'Beginner friendly', 'Restrooms'],
    260,
    320,
    90,
    35,
    12,
    8,
    1.5,
    5.0,
    '{"tide": "high", "primary_swell": {"dir_deg": 295, "period_s": 10}, "notes": "Protected bay needs NW swells to wrap in; great for first timers"}'::jsonb,
    290,
    290,
    30,
    ARRAY[9,10,11,12,1,2],
    'doran-beach-bodega-bay-ca',
    'North Coast',
    'Doran Beach inside Bodega Bay offers gentle beach break waves ideal for beginners. The outer reefs protect the bay from larger swells, so waves are usually small, but occasional NW swells can produce fun, rippable peaks.',
    'Park inside Doran Regional Park for a fee; spots are close to the beach.',
    'Short walk across the dunes to the water; watch out for bird nesting areas.',
    'Look for small sandbars along the beach; on bigger days, peaks form near the jetty.',
    'Rarely crowded outside of summer; surfers often have peaks to themselves.',
    'High tide, light E winds, 2-4 ft NW swell',
    ARRAY['Sharks', 'Rip currents', 'Rocks'],
    'Respect wildlife and avoid disturbing nesting birds.',
    'low',
    ARRAY['🅿️ Pay to park in the regional park', '🌬️ Offshore east winds help small waves break', '🌊 Protected beach with small beginner peaks'],
    false
  ),

  -- 28. Point Arena / Manchester Beach
  (
    'c778cc0a-2094-4649-84cd-4c38ce864f23',
    'Point Arena / Manchester Beach',
    'Manchester',
    'CA',
    'USA',
    38.957,
    -123.692,
    'beach',
    'upper-intermediate',
    ARRAY['sharks', 'strong currents', 'rip currents', 'cold water', 'rocks'],
    ARRAY['Parking nearby', 'Consistent waves', 'Restrooms', 'Camping'],
    250,
    330,
    90,
    35,
    15,
    10,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 300, "period_s": 13}, "notes": "Best on medium NW swells; too big and it closes out"}'::jsonb,
    300,
    290,
    40,
    ARRAY[9,10,11,12,1,2],
    'point-arena-manchester-beach-ca',
    'North Coast',
    'This remote stretch of beach north of Point Arena Lighthouse sees powerful, cold surf from W and NW swells. Sandbars shift, creating rips and long walls; it''s a great spot for experienced surfers seeking solitude.',
    'Small parking area at Manchester State Park; there''s also beach access from the lighthouse road.',
    'Walk through dunes to the beach and pick a sandbar; be prepared for long paddles in strong currents.',
    'Look for defined rips to help you paddle out; waves can close out on huge days but offer long rides when smaller.',
    'Usually empty due to remote location and cold water; bring a buddy and watch for wildlife.',
    'Mid tide, light E winds, 4-8 ft NW swell',
    ARRAY['Sharks', 'Strong currents', 'Rip currents', 'Cold water', 'Rocks'],
    'Pack out trash and respect the wilderness; be self-sufficient as there are no services nearby.',
    'low',
    ARRAY['🅿️ Small parking at state park', '🌬️ Offshore east winds required', '🌊 Remote, powerful beach break'],
    false
  )

ON CONFLICT (id) DO NOTHING;

COMMIT;














