-- Add 14 Puerto Rico surf spots: Rincón, Isabela, Aguadilla, Luquillo
-- Safe, idempotent insert using ON CONFLICT

BEGIN;

INSERT INTO public.beaches (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private
) VALUES
  -- 1. Domes (Rincón, PR)
  (
    '8a2b0951-38b4-4d7e-b5d5-6e076b58a5f0',
    'Domes',
    'Rincón',
    'PR',
    'USA',
    18.36611,
    -67.27056,
    'reef',
    'upper-intermediate',
    ARRAY['shallow reef', 'sea urchins', 'rocks', 'strong currents', 'crowds'],
    ARRAY['Consistent waves', 'World-class wave', 'Scenic', 'Parking nearby'],
    280,
    350,
    125,
    45,
    12,
    8,
    0.5,
    1.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 315, "period_s": 14}, "notes": "Handles NW swells. Needs SE winds to stay clean."}'::jsonb,
    305,
    315,
    35,
    ARRAY[11,12,1,2,3],
    'domes-rincon-pr',
    'Rincón',
    'Domes is a classic Rincón reef break known for its powerful hollow right-hand waves. It handles N–NW swells and works best with SE offshore winds. Intermediate and advanced surfers enjoy long, fast walls and the occasional barrel, but the shallow reef and busy lineup mean caution is essential.',
    'Park along the road near the old nuclear dome or at the lighthouse. Arrive early on good swells as spaces fill up quickly.',
    'There''s a small beach path to the right of the nuclear dome. Time your paddle-out between sets to avoid the impact zone and stay in the channel.',
    'Sit wide of the peak to pick off the long right-hand walls. Watch the experienced locals to learn the takeoff spot and be prepared for fast sections.',
    'Domes is one of Rincón''s busiest breaks. Respect the locals, wait your turn, and avoid snaking. Early mornings tend to be less crowded.',
    'Low to mid tide, SE offshore winds, and head-high to overhead NW swells.',
    ARRAY['Intermediate and up', 'Crowded when good', 'Watch for shallow sections'],
    'Domes has a core local crew. Be courteous, don''t drop in, and share waves politely.',
    'high',
    ARRAY['🪸 Booties recommended for reef', '🌬️ SE trades keep it offshore', '🐋 Winter whale sightings sometimes'],
    false
  ),

  -- 2. María's (Rincón, PR)
  (
    '5c879b55-26e6-4755-92f3-0291f4634f24',
    'María''s',
    'Rincón',
    'PR',
    'USA',
    18.35645,
    -67.2691,
    'point',
    'intermediate',
    ARRAY['shallow reef', 'rocks', 'strong currents', 'sea urchins'],
    ARRAY['Long rides', 'Surf schools nearby', 'Amenities', 'Scenic'],
    280,
    350,
    120,
    45,
    12,
    8,
    0.7,
    2.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 310, "period_s": 13}, "notes": "Works on NW swells with SE offshore winds."}'::jsonb,
    300,
    315,
    35,
    ARRAY[11,12,1,2,3],
    'marias-rincon-pr',
    'Rincón',
    'María''s is a celebrated right‑hand point break that offers long, manageable rides over a shallow reef. The wave can handle large winter swells, making it a contest venue during the surf season. Intermediate surfers will enjoy its predictability, but during big swells it becomes challenging and attracts pros and strong locals.',
    'Free parking is available where Route 413 meets Route 4413; arrive early on swell days. Bathrooms, showers, and picnic tables are nearby.',
    'The paddle‑out is farther than at Domes. Use the sandy entry left of the wooden ramp, then hug the channel to avoid the reef.',
    'The main peak is a right point that occasionally links with neighboring sections. Sit deeper for longer rides and be aware of wide‑swinging sets.',
    'Maria''s can be packed when good. Spread out along the different peaks and wait your turn. Local surf schools often use the inside section—give learners space.',
    'Mid to high tide, NW swell 3–8 ft, and SE winds.',
    ARRAY['Crowded lineups', 'Rocky shoreline', 'Long paddle out'],
    'Respect the locals and the history of the break (named after María Garcia). Share waves and keep the vibe friendly.',
    'very_high',
    ARRAY['🪸 Booties help on reef', '🏄 Multiple peaks spread the crowd', '🚿 Facilities and food close by'],
    false
  ),

  -- 3. Tres Palmas (Rincón, PR)
  (
    '88424465-0b1d-4f93-aa17-93dd1c4d03f3',
    'Tres Palmas',
    'Rincón',
    'PR',
    'USA',
    18.34868,
    -67.26398,
    'reef',
    'expert',
    ARRAY['shallow reef', 'big wave spot', 'strong currents', 'rocks', 'sea urchins'],
    ARRAY['World-class wave', 'Scenic', 'Big wave spot', 'Marine reserve'],
    280,
    340,
    105,
    45,
    10,
    8,
    1.0,
    2.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 315, "period_s": 16}, "notes": "Needs solid NW groundswells and long period. Trades keep it offshore."}'::jsonb,
    285,
    310,
    30,
    ARRAY[12,1,2,3],
    'tres-palmas-rincon-pr',
    'Rincón',
    'Also called Steps, Tres Palmas is Puerto Rico''s famed big‑wave reef within the Tres Palmas Marine Reserve. When large NW swells march down from the North Atlantic, this spot produces long, powerful rights with faces that can exceed 20 feet. It''s a proving ground for experienced chargers; when small it offers fun waves for advanced surfers.',
    'Street parking lines the road near the reserve. Get there early on a good swell, and be mindful not to block driveways.',
    'Enter via the sandy channel and paddle out wide. On big days you may need to paddle from the neighboring beach to avoid the impact zone.',
    'Sit deep to catch the larger sets, but commit—hesitation will see you caught by heavy walls. Watch the lineup from shore before paddling out.',
    'Crowds are smaller due to the wave''s seriousness. Respect the locals and big‑wave crew and wait your turn.',
    'Mid tide, light E winds, and 8–15 ft NW swell 14 s+.',
    ARRAY['Experts only', 'Can hold 20+ ft faces', 'Long paddle and strong currents'],
    'Tres Palmas has a tight-knit crew. Don''t paddle out unless you have the skills and proper safety gear.',
    'moderate',
    ARRAY['🌊 Puerto Rico''s premier big wave spot', '🪸 Shallow reef—booties advised', '⚠️ Experts only when overhead'],
    false
  ),

  -- 4. Indicators (Rincón, PR)
  (
    'f298d080-177b-4407-9e3a-be51bae58605',
    'Indicators',
    'Rincón',
    'PR',
    'USA',
    18.3605,
    -67.2765,
    'point',
    'advanced',
    ARRAY['shallow reef', 'rocks', 'sea urchins', 'strong currents', 'localism'],
    ARRAY['Long right point', 'Scenic', 'Smaller crowd'],
    280,
    350,
    130,
    40,
    12,
    8,
    0.5,
    1.5,
    '{"tide": "low", "primary_swell": {"dir_deg": 310, "period_s": 13}, "notes": "Wraps a NW swell; needs light SE winds."}'::jsonb,
    310,
    315,
    35,
    ARRAY[12,1,2,3],
    'indicators-rincon-pr',
    'Rincón',
    'Around the corner from Domes, Indicators is named for the exposed rock that marks the takeoff. This long right‑hand point provides a good gauge of swell size for the Rincón area. It''s mostly surfed by experienced locals because the takeoff is close to a shallow, exposed reef, and the wave bowls as it wraps into the bay.',
    'Limited roadside parking near the lighthouse. Walk down the path toward the rocky outcrop.',
    'Carefully climb down the rocks and time your paddle‑out between sets. There''s no easy channel.',
    'Sit close to the rock for the best takeoff. The wave runs down the point; watch for backwash and wide sets.',
    'Crowds are lighter than at Maria''s, but locals dominate. Give way to those with priority and avoid dropping in.',
    'Low to mid tide, light SE winds, and NW swell 4–10 ft.',
    ARRAY['Advanced surfers only', 'Sharp reef near takeoff', 'Strong sets wrap around the point'],
    'Indicators has a core crew; be humble, introduce yourself, and respect the rotation.',
    'moderate',
    ARRAY['🪸 Booties help on rocky entry', '🌊 Sets wrap around the rock', '🙏 Respect the local crew'],
    false
  ),

  -- 5. Sandy Beach Rincón (Rincón, PR)
  (
    'f11ccd59-b778-4ea1-a8ff-88bffb447cd8',
    'Sandy Beach Rincón',
    'Rincón',
    'PR',
    'USA',
    18.370386,
    -67.25763,
    'beach',
    'beginner',
    ARRAY['rip currents', 'localism', 'sea urchins', 'rocks (in some sections)', 'strong winds'],
    ARRAY['Beginner friendly', 'Surf schools nearby', 'Restaurants nearby', 'Vibrant nightlife'],
    280,
    340,
    115,
    45,
    12,
    10,
    0.5,
    1.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 300, "period_s": 12}, "notes": "Best for beginners on small swells. Trades make mornings better."}'::jsonb,
    295,
    310,
    30,
    ARRAY[11,12,1,2,3],
    'sandy-beach-rincon-rincon-pr',
    'Rincón',
    'Sandy Beach Rincón is Rincón''s go‑to beginner and longboard spot. The sandy bottom and forgiving peaks make it ideal for learning to surf, and the surrounding bars and guesthouses create a lively scene. On bigger swells it can provide fun shoulders for intermediates, but the afternoon trade winds often turn it onshore.',
    'Limited parking is available near Tamboo Tavern and Casa Isleña. Arrive early or park along the road.',
    'Easy beach access via sandy paths. Just walk out and paddle—no reef to negotiate in most sections.',
    'Look for the sandbars that form small peaks along the beach. Mornings offer cleaner waves before the trades get strong.',
    'Afternoons and weekends can be busy with tourists and learners. Respect surf school students and share the peaks.',
    'Low to mid tide, calm morning winds, and small N–W swells 2–6 ft.',
    ARRAY['Onshore trades by afternoon', 'No lifeguards', 'Watch for rip currents'],
    'Keep the vibe friendly; many visitors are beginners. Don''t hog waves and be mindful of swimmers.',
    'high',
    ARRAY['🏖️ Sand bottom and mellow waves', '🍹 Bars and restaurants on the beach', '🌬️ Go early before trades pick up'],
    false
  ),

  -- 6. The Point at Sandy (Rincón, PR)
  (
    'bfd3e168-f268-4692-901c-4b80b9b58dcb',
    'The Point at Sandy',
    'Rincón',
    'PR',
    'USA',
    18.368,
    -67.256,
    'point',
    'upper-intermediate',
    ARRAY['shallow reef', 'rocks', 'crowds', 'strong currents'],
    ARRAY['Long right-hander', 'Connects with Maria''s on big swells', 'Scenic'],
    280,
    350,
    120,
    45,
    12,
    8,
    0.5,
    2.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 305, "period_s": 14}, "notes": "Needs NW swell to line up; SE wind keeps it clean."}'::jsonb,
    300,
    315,
    35,
    ARRAY[11,12,1,2,3],
    'the-point-at-sandy-rincon-pr',
    'Rincón',
    'At the southern end of Sandy Beach lies The Point, a rocky outcrop that produces a long right‑hander. On big NW swells the wave can connect with Maria''s, offering rides of several hundred meters. The reefy takeoff zone and speedy wall suit upper‑intermediate surfers and above.',
    'Park at Sandy Beach and walk south along the sand. There are few spots near the point itself.',
    'Enter from the sandy beach and paddle out around the rocks. Watch for submerged reef near the takeoff.',
    'Sit wide on smaller days; when a solid set arrives the wave hugs the point and reels down the line. Patience is key.',
    'Expect a heavy crowd when it''s connecting to Maria''s. Be respectful and yield to those deeper on the point.',
    'Mid tide, SE offshore winds, and solid NW swells.',
    ARRAY['Crowded when working', 'Sharp reef at takeoff', 'Not suitable for novices'],
    'Locals surf here regularly—follow their lead and don''t paddle around them.',
    'high',
    ARRAY['🌊 Long peeling right', '🏄 Connects with Maria''s on solid NW swells', '🌅 Beautiful sunsets from the lineup'],
    false
  ),

  -- 7. Jobos (Isabela, PR)
  (
    '388bb737-5889-46d0-a182-d26567bf23f6',
    'Jobos',
    'Isabela',
    'PR',
    'USA',
    18.515,
    -67.07388,
    'reef',
    'intermediate',
    ARRAY['shallow reef', 'rocks', 'sea urchins', 'crowds', 'rip currents'],
    ARRAY['Two peaks (inside and outside)', 'Restaurants and bars', 'Photogenic setting', 'Consistent'],
    300,
    359,
    140,
    40,
    12,
    10,
    0.5,
    2.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 330, "period_s": 13}, "notes": "Picks up any northern swell; south winds groom it."}'::jsonb,
    320,
    330,
    30,
    ARRAY[11,12,1,2,3],
    'jobos-isabela-pr',
    'Isabela',
    'Jobos is Isabela''s iconic surf beach, offering a powerful right‑hand reef break off the rocks and a softer inside peak over sand. Intermediate surfers can test themselves on the outside while beginners ride the rolling inside section. The wave picks up almost any northern swell and can get hollow, drawing a large crowd and lively scene.',
    'There''s a main parking area behind the beach bars, but it fills up quickly on weekends. Additional parking can be found along the road.',
    'Walk across the sand and paddle out along the channel next to the rocks. Beware of strong side currents during bigger swells.',
    'The outside peak is a fast right that throws a hollow section; take off deep and pull in. The inside peak is slower—great for beginners and longboarders.',
    'Jobos is always busy. Respect the locals and split your time between the inside and outside to share waves.',
    'Any tide, N–NW swells 4–10 ft, and light S to SE winds.',
    ARRAY['Heavy crowd at main peak', 'Sharp reef on the outside', 'Strong currents during big swells'],
    'Locals run the show at the outside peak. Don''t paddle around them and keep the energy positive.',
    'very_high',
    ARRAY['🏝️ Inside peak is mellow for learners', '🏄 Outside offers hollow rights', '🍻 Beachside eateries and nightlife'],
    false
  ),

  -- 8. Middles Isabela (Isabela, PR)
  (
    '77903282-042b-4294-b6b2-2e3815489513',
    'Middles Isabela',
    'Isabela',
    'PR',
    'USA',
    18.503,
    -67.083,
    'beach',
    'lower-intermediate',
    ARRAY['strong rip currents', 'rocks', 'localism', 'sea urchins'],
    ARRAY['Multiple peaks', 'Surf schools', 'Consistent', 'Spacious beach'],
    300,
    359,
    150,
    40,
    12,
    10,
    0.5,
    2.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 335, "period_s": 12}, "notes": "Consistent in winter; watch rip currents."}'::jsonb,
    330,
    330,
    30,
    ARRAY[10,11,12,1,2],
    'middles-isabela-isabela-pr',
    'Isabela',
    'Middles Isabela is a versatile stretch of beach between Jobos and Shacks with several peaks breaking over sand and reef. It''s one of the best competition sites on the island and hosts the annual Corona Pro Surf. While the western end can get powerful and hollow, the east side is more forgiving and popular with surf schools.',
    'Park along the dirt lot behind the dunes. Lock your car and don''t leave valuables visible.',
    'Walk across the sand to your chosen peak. Watch for rip currents when paddling out.',
    'Choose your peak: the western peak throws punchy barrels; the east offers mellow walls. Always be aware of rip currents.',
    'Middles Isabela can be busy during contests but quieter on regular days. Spread out along the beach and respect priority.',
    'Any tide, N or NW swell 3–7 ft, and light SE winds.',
    ARRAY['Rip currents and undertow', 'Crowds during contests', 'Avoid swimming'],
    'Locals and contest surfers frequent Middles Isabela—share waves and be mindful during competitions.',
    'moderate',
    ARRAY['🏄 Multiple peaks for all levels', '🎪 Hosts annual Corona Pro Surf', '🚫 Not recommended for swimming'],
    false
  ),

  -- 9. Shacks (Isabela, PR)
  (
    'a240ccfc-d047-4471-a406-6ae5e92b0816',
    'Shacks',
    'Isabela',
    'PR',
    'USA',
    18.515891,
    -67.100179,
    'reef',
    'advanced',
    ARRAY['sharp coral reef', 'hollow barrels', 'strong currents', 'localism', 'shallow sections'],
    ARRAY['World-class hollow waves', 'Consistent trade winds (great for kitesurfing)', 'Scenic snorkeling when calm'],
    320,
    359,
    160,
    40,
    12,
    10,
    0.5,
    2.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 345, "period_s": 14}, "notes": "Needs NE swell; trades can be strong."}'::jsonb,
    340,
    350,
    30,
    ARRAY[11,12,1,2,3],
    'shacks-isabela-pr',
    'Isabela',
    'Shacks is regarded as one of Puerto Rico''s most challenging reef breaks. When a NE swell arrives, the shallow coral reef produces fast, hollow waves that pitch over sharp coral heads—experts only. On calmer days it''s a snorkeling paradise, but when it''s pumping, only confident tube riders should paddle out.',
    'Limited parking along Route 4466. Respect private property and do not block driveways.',
    'Carefully walk over the reef at high tide or paddle from the sandy section. The entry can be slippery and sharp.',
    'Position yourself at the takeoff to pull straight into the barrel. The wave throws fast; maintain speed and exit before the shallow inside section.',
    'Locals dominate and the wave is heavy—respect their rotation. Crowds are lighter due to the wave''s difficulty.',
    'Any tide, NE swell 4–8 ft, and light SW winds.',
    ARRAY['Experts only on NE swells', 'Dangerous shorebreak', 'Sharp coral everywhere'],
    'Only paddle out if you have the skills. Respect the local riders and kitesurfers.',
    'low',
    ARRAY['🏄 Experts only when firing', '🪸 Shallow coral—wear booties', '🪁 Great kite/windsurfing spot'],
    false
  ),

  -- 10. Wilderness (Aguadilla, PR)
  (
    '2795319c-e680-45d0-a8af-f4c55631986e',
    'Wilderness',
    'Aguadilla',
    'PR',
    'USA',
    18.4837946,
    -67.1667472,
    'point',
    'upper-intermediate',
    ARRAY['rocky shoreline', 'long paddle', 'strong currents', 'sea urchins', 'localism'],
    ARRAY['Secluded setting', 'Long rides', 'Barrel sections', 'Scenic'],
    300,
    359,
    135,
    40,
    12,
    10,
    0.5,
    2.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 325, "period_s": 14}, "notes": "Works best with NW swells and SE winds."}'::jsonb,
    315,
    330,
    30,
    ARRAY[11,12,1,2,3],
    'wilderness-aguadilla-pr',
    'Aguadilla',
    'True to its name, Wilderness is a secluded right‑hand point break reached via a dirt road. It produces long rides with carveable walls and occasional barrel sections when a solid NW swell meets SE winds. The rocky shoreline and strong currents make the paddle‑out tricky, so it''s best suited to experienced surfers.',
    'Drive down the rough dirt road and park near the clearing (4×4 recommended). Lock your vehicle and don''t leave valuables.',
    'Use the small sandy area left of the wooden ramp to enter. Avoid stepping on the rock shelf and watch the current.',
    'The takeoff can be steep. Sit deep for the longest rides and watch for the occasional barrel section down the line.',
    'Crowds are moderate thanks to the remote access. Show respect to the locals who regularly surf here.',
    'Mid tide, SE winds, and NW swells 4–10 ft.',
    ARRAY['Use a 4×4 on the access road', 'Enter via small sandy spot', 'Advanced surfers only on big swells'],
    'Keep the lineup friendly. Pack out trash and respect the pristine environment.',
    'moderate',
    ARRAY['🚙 Dirt road access—be prepared', '🌊 Long right-hand walls with barrels', '🧗 Rocky entry—wear reef booties'],
    false
  ),

  -- 11. Crash Boat (Aguadilla, PR)
  (
    'acfad2b2-7d0c-4c42-9fba-e78fa73e4ae3',
    'Crash Boat',
    'Aguadilla',
    'PR',
    'USA',
    18.458392,
    -67.164863,
    'beach',
    'lower-intermediate',
    ARRAY['crowds', 'rip currents near pier', 'rocks', 'boat traffic'],
    ARRAY['Beginner friendly', 'Pier jump', 'Amenities and food', 'Snorkeling'],
    300,
    359,
    130,
    40,
    12,
    10,
    0.5,
    2.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 320, "period_s": 12}, "notes": "Fun learner wave on small swells; avoid busy weekends."}'::jsonb,
    310,
    330,
    30,
    ARRAY[10,11,12,1,2],
    'crash-boat-aguadilla-pr',
    'Aguadilla',
    'Crash Boat is a popular family beach with a picturesque pier and a user‑friendly beach break. When small N–NW swells roll in, the sandy bottom produces gentle rights and lefts perfect for longboarders and intermediates. The pier area also offers diving and snorkeling, drawing crowds year‑round.',
    'Large parking lot near the beach. On busy days it fills up quickly—arrive early or during weekdays.',
    'Easy walk down the sand or jump off the pier when conditions allow. Stay clear of boat lanes.',
    'Small peaks form around the pier; look for sandbars that produce the best shape. During bigger swells sit farther outside.',
    'Expect heavy crowds on weekends and holidays. Surf early morning or off‑season for fewer people.',
    'Any tide, small N–NW swells 2–6 ft, and light SE winds.',
    ARRAY['Heavy crowds on weekends', 'Watch for boats and swimmers', 'Rip currents around the pier'],
    'This is a shared recreational beach. Watch for swimmers and be polite to non-surfers.',
    'very_high',
    ARRAY['🤿 Fun beach with snorkel spots', '🏄 Gentle waves for learners', '🍹 Food and drinks steps away'],
    false
  ),

  -- 12. Surfer's Beach (Aguadilla, PR)
  (
    '4a0aac5b-86e5-433d-8a54-64c8e15197f9',
    'Surfer''s Beach',
    'Aguadilla',
    'PR',
    'USA',
    18.5050767,
    -67.1414638,
    'beach',
    'intermediate',
    ARRAY['rocky shoreline', 'strong currents', 'jagged rocks on shore', 'localism'],
    ARRAY['Reliable waves', 'Friendly vibe', 'Close to airport', 'Reef/sand bottom'],
    300,
    359,
    120,
    40,
    12,
    10,
    0.5,
    2.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 310, "period_s": 12}, "notes": "Works on various N–NE swells; NE wind is fine."}'::jsonb,
    300,
    340,
    40,
    ARRAY[10,11,12,1,2],
    'surfers-beach-aguadilla-pr',
    'Aguadilla',
    'Surfer''s Beach sits near Aguadilla''s airport and is a reliable surf spot that handles a variety of swell directions. It offers long, rippable rights and occasional lefts over a mix of sand and reef. While more forgiving than nearby Shacks, the jagged shoreline makes entry and exit tricky, and bigger swells demand respect.',
    'Park in the dirt lot near the old Ramey Air Force Base structures. Walk down the path to the beach.',
    'Carefully traverse the rocks to enter; look for a small sandy channel. Exit in the same area to avoid the jagged shoreline.',
    'Sit near the main peak for the longest rights. Lefts can break on the inside at low tide.',
    'The vibe is friendly, but respect locals and visiting windsurfers. Mornings are quieter.',
    'Any tide, N–NE swells 3–8 ft, and light NE winds.',
    ARRAY['Watch for the jagged rock on shore', 'Can be heavy on bigger swells', 'Respect kite and windsurfers'],
    'Share waves with kite and windsurfers and be courteous. Don''t litter.',
    'moderate',
    ARRAY['🏄 Consistent right-hand walls', '🪁 Works in NE wind', '🪨 Jagged shoreline—exit carefully'],
    false
  ),

  -- 13. La Pared (Luquillo, PR)
  (
    '6c111c72-1773-490b-ae9e-fe6d81827989',
    'La Pared',
    'Luquillo',
    'PR',
    'USA',
    18.3769,
    -65.714361,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'crowds', 'localism', 'rocks at ends'],
    ARRAY['Multiple peaks', 'Beginner/intermediate friendly', 'Surf shops and restaurants nearby', 'Scenic town setting'],
    0,
    60,
    200,
    40,
    12,
    10,
    0.5,
    1.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 30, "period_s": 12}, "notes": "Consistent NE–E swells; W winds groom the surface."}'::jsonb,
    20,
    30,
    30,
    ARRAY[10,11,12,1,2,3],
    'la-pared-luquillo-pr',
    'North Coast',
    'La Pared is the most accessible surf beach near San Juan. It''s a consistent beach break that turns on with NE to E swells and W winds, producing multiple peaks for beginners and intermediates. The town of Luquillo backs the beach, offering amenities and a lively atmosphere, but rip currents mean it''s rarely a safe swimming beach.',
    'Park along the road behind the seawall or in designated lots in Luquillo. Keep valuables out of sight.',
    'Easy walk over the seawall. Paddle out between rip currents for the quickest route.',
    'Find a sandbar that''s lining up; peaks shift frequently. High tides soften the waves, while lower tides make them punchier.',
    'Weekends bring crowds from San Juan. Surf early or during weekdays to avoid the rush.',
    'Mid tide, W winds, and NE–E swells 3–8 ft.',
    ARRAY['Strong rip currents—swimming not recommended', 'Can be choppy in trade winds', 'Watch for red flags'],
    'Respect the local surf community and the beach''s rules. Watch for flags indicating hazardous conditions.',
    'high',
    ARRAY['🏄 Consistent beach break on N/NE swells', '🍴 Plenty of food options in Luquillo', '⚠️ Strong rip currents—respect the ocean'],
    false
  ),

  -- 14. La Selva (Luquillo, PR)
  (
    '7db87d82-4e66-4a48-9c8b-d5f95a282a4c',
    'La Selva',
    'Luquillo',
    'PR',
    'USA',
    18.368333,
    -65.684338,
    'point',
    'upper-intermediate',
    ARRAY['remote access', 'strong surf', 'sharp reef', 'sea urchins', 'localism', 'wildlife (turtles)'],
    ARRAY['Secluded surf point', 'Multiple peaks', 'Scenic rainforest backdrop', 'Local surf culture'],
    20,
    80,
    225,
    40,
    12,
    10,
    0.5,
    1.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 50, "period_s": 13}, "notes": "Needs NE swell; remote and pristine."}'::jsonb,
    45,
    50,
    30,
    ARRAY[9,10,11,12,1,2],
    'la-selva-luquillo-pr',
    'North Coast',
    'La Selva is a secluded surf zone within the Northeast Ecological Corridor near Luquillo. A NE swell wraps into the headland, producing a right‑hand point wave with adjacent beach‑break peaks. Intermediate and advanced surfers enjoy 4–8 ft waves in an unspoiled setting backed by palms and El Yunque rainforest. Access requires a hike or 4×4 and the area is protected as a sea‑turtle reserve.',
    'Park at the end of the road near La Pared and hike east along the coast or drive a 4×4 down the rough dirt path if open. There are no facilities.',
    'Follow the trail through the nature reserve to the beach. Bring all supplies as there are no services. Enter via the sandy section and avoid reef outcrops.',
    'The main point wave hugs the headland, offering long rights on NE swells. There are also shorter peaks down the beach. Best surf is in winter and during hurricane swells.',
    'Crowds are low due to the hike. Respect the locals and give right of way to those already in the lineup.',
    'Mid tide, W winds, and NE swells 4–8 ft.',
    ARRAY['4×4 or hike required', 'Respect sea turtle nesting areas', 'Advanced surfers only on bigger swells'],
    'This area is sacred to the local surf community and wildlife. Pack out everything and respect nesting turtles. Don''t disturb the quiet vibe.',
    'low',
    ARRAY['🚶 Remote hike to reach the break', '🐢 Respect nesting turtles and nature', '🌊 Powerful waves with few people'],
    false
  )

ON CONFLICT (id) DO NOTHING;

COMMIT;
