-- Add 17 Hawaii beaches: Oahu (8), Maui (3), Kauai (3), Big Island (3)
-- Safe, idempotent insert using ON CONFLICT

BEGIN;

INSERT INTO public.beaches (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private
) VALUES
  -- OAHU (8)

  -- 1. Waikiki – Canoes
  (
    '2ac8b200-fdf2-4822-bcb1-3ec336b83d05',
    'Waikiki – Canoes',
    'Honolulu',
    'HI',
    'USA',
    21.27625,
    -157.82925,
    'reef',
    'beginner',
    ARRAY['shallow reef', 'rocks', 'sea urchins', 'localism'],
    ARRAY['Parking nearby', 'Beginner friendly', 'Restrooms', 'Showers', 'Lifeguard', 'Consistent waves', 'Scenic'],
    170,
    220,
    0,
    35,
    12,
    8,
    0.5,
    3.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 190, "period_s": 12}, "notes": "Prefers a clean south swell; avoid when trades blow onshore."}'::jsonb,
    180,
    195,
    25,
    ARRAY[4,5,6,7,8,9],
    'waikiki-canoes-honolulu-hi',
    'Oahu',
    'Canoes, located off Waikiki in Honolulu, is a gentle reef break over a sandy bottom that produces long, mellow rides ideal for beginners and longboarders. The wave has a welcoming vibe with beach-boy surf lessons and outrigger canoes sharing the lineup, though it can be crowded in summer. The break works best on a south swell and a light northerly wind, delivering fun walls for surfers of all ages.',
    'Use the Kuhio Beach Park or Kapiolani Park parking lots along Kalakaua Avenue; arrive early to secure a spot as the area fills up quickly.',
    'Walk along the beach past the Moana Surfrider hotel and paddle out from the sandy shoreline toward the lineup inside the buoy line.',
    'Sit wide to avoid the canoe traffic and pick the bigger outside sets; the wave is slow, so angle your takeoff and trim down the line.',
    'Expect high crowds during summer afternoons; to find space, surf early in the morning or on days with a smaller south swell.',
    'Mid tide, light north wind, 2–3 ft south swell',
    ARRAY['Shallow reef', 'Sea urchins', 'Localism'],
    'Respect surf instructors and tourists learning to surf; share waves generously and yield to outrigger canoes passing through.',
    'high',
    ARRAY['🅿️ Arrive early for limited parking', '🌬️ North winds keep the face clean', '🌊 Takeoff early to enjoy long rides'],
    false
  ),

  -- 2. Waikiki – Queens
  (
    'ae2e2eee-897c-4198-80fa-04b2d47128d7',
    'Waikiki – Queens',
    'Honolulu',
    'HI',
    'USA',
    21.27481,
    -157.82281,
    'reef',
    'lower-intermediate',
    ARRAY['shallow reef', 'rocks', 'sea urchins', 'localism'],
    ARRAY['Parking nearby', 'Beginner friendly', 'Restrooms', 'Showers', 'Lifeguard', 'Consistent waves', 'World-class wave', 'Scenic'],
    170,
    220,
    0,
    35,
    12,
    8,
    0.5,
    3.0,
    '{"tide": "mid-high", "primary_swell": {"dir_deg": 195, "period_s": 12}, "notes": "Higher tide helps the reef hold the shape; avoid strong trades."}'::jsonb,
    180,
    195,
    25,
    ARRAY[4,5,6,7,8,9],
    'waikiki-queens-honolulu-hi',
    'Oahu',
    'Queens is the jewel of Waikiki, delivering a long right-hand reef wave with occasional lefts that are faster and more powerful than neighboring Canoes. The break sits in front of the Royal Hawaiian and sets up clean walls during summer south swells, making it a favorite for longboarders and surf contests. Proper etiquette is essential because the lineup can be territorial and extremely crowded.',
    'Park at Kuhio Beach Park or in nearby paid garages in Waikiki; metered street parking is also available along Kalakaua Avenue.',
    'Walk down the beach toward the pink Royal Hawaiian hotel and paddle through the channel between buoys to reach the deeper reef.',
    'Position yourself slightly inside to catch the long rights; be patient for sets and watch for quick takeoffs on the faster lefts.',
    'Arrive at dawn or midweek to avoid the surf-school crowds; always yield to locals and communicate clearly when sharing waves.',
    'Mid tide, light north winds, 3–4 ft south swell',
    ARRAY['Localism', 'Shallow reef', 'Sea urchins'],
    'Queue up at the takeoff spot and wait your turn; avoid dropping in on local longboarders.',
    'high',
    ARRAY['🅿️ Paid garages offer reliable parking', '🌬️ Light north winds groom the face', '🌊 Patience is key to score the long right'],
    false
  ),

  -- 3. Ala Moana Bowls
  (
    '80fc2c1b-2d3f-4a94-bcc2-c8ea0e9b8fc5',
    'Ala Moana Bowls',
    'Honolulu',
    'HI',
    'USA',
    21.280883,
    -157.843883,
    'reef',
    'advanced',
    ARRAY['shallow reef', 'coral', 'sea urchins', 'rocks', 'strong currents', 'localism'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Consistent waves', 'World-class wave', 'Scenic'],
    180,
    230,
    0,
    35,
    12,
    8,
    0.5,
    3.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 205, "period_s": 14}, "notes": "Needs a powerful south or southwest swell; avoid onshore winds."}'::jsonb,
    180,
    205,
    25,
    ARRAY[4,5,6,7,8,9],
    'ala-moana-bowls-honolulu-hi',
    'Oahu',
    'Ala Moana Bowls is a legendary reef break off Magic Island known for its heaving left-hand tube and occasional right. Breaking over a shallow coral reef, Bowls offers long, hollow waves that attract expert shortboarders when a solid south or southwest swell lines up with light northerly winds. On bigger swells the barrels are thick and dangerous, and the lineup is extremely competitive.',
    'Park in the Ala Moana Beach Park lots near Magic Island; watch out for car break-ins and don''t leave valuables visible.',
    'Walk around the Magic Island seawall and paddle across the boat channel toward the reef; time your paddle between sets to avoid the current.',
    'Sit deep on the boil to catch the steepest peaks; commit to the late drop and stay in the barrel—there''s no shoulder.',
    'Expect highly skilled locals and a pecking order; wait your turn and avoid burning anyone or you''ll be called out.',
    'Mid tide, light northeast trades, 4–6 ft south-southwest swell',
    ARRAY['Shallow reef', 'Strong currents', 'Localism'],
    'Only paddle out if you are confident in your abilities; respect the established hierarchy and call out if dropping in.',
    'high',
    ARRAY['🅿️ Leave no valuables in your car', '🌬️ Trades blowing lightly groom the barrels', '🌊 Sit deep for the heaviest sections'],
    false
  ),

  -- 4. Diamond Head (Cliffs)
  (
    '8ee452f0-4043-4fe0-a049-207afbd95523',
    'Diamond Head (Cliffs)',
    'Honolulu',
    'HI',
    'USA',
    21.252533,
    -157.804117,
    'reef',
    'intermediate',
    ARRAY['shallow reef', 'rocks', 'sea urchins', 'strong currents', 'localism'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Consistent waves', 'Scenic'],
    140,
    210,
    0,
    35,
    12,
    8,
    0.5,
    3.0,
    '{"tide": "mid-low", "primary_swell": {"dir_deg": 170, "period_s": 12}, "notes": "Performs on multiple swell directions but prefers clean south swell and light winds."}'::jsonb,
    150,
    175,
    35,
    ARRAY[4,5,6,7,8,9],
    'diamond-head-cliffs-honolulu-hi',
    'Oahu',
    'Diamond Head Cliffs is a long stretch of reef along the slopes of Leʻahi where multiple peaks offer rippable lefts and occasional rights. The waves are consistent year-round and handle a variety of swell directions, but they break over sharp lava and coral that require confident paddling and knowledge of the currents. Getting there involves a hike down the bluff and a long paddle, and the lineup can be crowded when the south swell pulses.',
    'Park at the Diamond Head lookout parking area along Diamond Head Road; lock your vehicle and do not leave valuables.',
    'Walk down the trail by the guardrail and scramble over rocks to the water; allow extra energy for the paddle through deep water to the lineup.',
    'Position yourself near the cliffs to catch the best lefts; be mindful of shifting peaks and watch for sets swinging wide.',
    'Spread out along the various peaks to find space; avoid the main pack if you''re still learning.',
    'Mid tide, light north winds, 3–5 ft south or southeast swell',
    ARRAY['Shallow reef', 'Sharp rocks', 'Strong currents'],
    'Respect local surfers and hikers; pack out all trash and be mindful of the fragile coastal environment.',
    'medium',
    ARRAY['🅿️ Park at the lookout and hike down carefully', '🌬️ Northerly winds keep it offshore', '🌊 Lineup shifts—watch the sets'],
    false
  ),

  -- 5. Sunset Beach
  (
    'f52f2c49-342a-4694-b04a-d66503446736',
    'Sunset Beach',
    'Pupukea',
    'HI',
    'USA',
    21.673056,
    -158.048056,
    'reef',
    'advanced',
    ARRAY['rip currents', 'rocks', 'shallow reef', 'localism', 'strong currents'],
    ARRAY['Parking nearby', 'World-class wave', 'Consistent waves', 'Scenic'],
    295,
    340,
    180,
    35,
    12,
    8,
    1.0,
    3.0,
    '{"tide": "high", "primary_swell": {"dir_deg": 315, "period_s": 16}, "notes": "Needs solid northwest swells; avoid strong trades and west winds."}'::jsonb,
    320,
    317,
    22,
    ARRAY[10,11,12,1,2,3],
    'sunset-beach-pupukea-hi',
    'Oahu',
    'Sunset Beach on Oahu''s famed North Shore is a legendary big-wave arena featuring multiple peaks that handle long-period northwest swells. Waves range from head high to thirty feet, with heavy lips, moving water, and a powerful rip current that sweeps surfers down the beach. Only experienced surfers should attempt it in the winter, while summer offers small longboard sessions on the inside.',
    'There is a public lot on the mauka (mountain) side of Kamehameha Highway; arrive early during contests as spaces fill quickly.',
    'Cross the highway carefully and walk through the sand to paddle out; use the keyholes between the reef to avoid the rip.',
    'Sit deeper on the bowl to catch the bigger peaks, and paddle hard to avoid getting caught inside; know when to straighten out and head for the channel.',
    'During winter swells the lineup is thick with pros and photographers; watch a few sets before paddling out and be respectful of locals and competitors.',
    'High tide, light southerly wind, 8–15 ft northwest swell',
    ARRAY['Rip currents', 'Strong currents', 'Localism'],
    'If you''re not confident, watch from the beach; respect the heavy vibe and stay out of the way of competitors during events.',
    'high',
    ARRAY['🅿️ Arrive early during contests', '🌬️ Southerly winds create glassy faces', '🌊 Navigate the rip to stay in position'],
    false
  ),

  -- 6. Waimea Bay
  (
    '12431285-b73c-48e4-99b3-731594f6f98c',
    'Waimea Bay',
    'Pupukea',
    'HI',
    'USA',
    21.640297,
    -158.063778,
    'reef',
    'advanced',
    ARRAY['rip currents', 'rocks', 'strong currents', 'localism', 'sharks'],
    ARRAY['Parking nearby', 'World-class wave', 'Scenic', 'Restrooms', 'Showers', 'Lifeguard'],
    290,
    330,
    180,
    35,
    12,
    8,
    1.0,
    3.0,
    '{"tide": "high", "primary_swell": {"dir_deg": 310, "period_s": 16}, "notes": "Requires long-period NW swells; Kona winds produce offshore conditions."}'::jsonb,
    320,
    310,
    20,
    ARRAY[10,11,12,1,2,3],
    'waimea-bay-pupukea-hi',
    'Oahu',
    'Waimea Bay is the birthplace of big-wave surfing, where deep-water northwest swells explode over a lava shelf to produce massive, powerful walls. When the Eddie Aikau Invitational runs, waves can exceed 20 feet and only elite surfers paddle out; at smaller sizes the shorebreak is steep and unforgiving. The bay''s dramatic cliffs and emerald water make it a breathtaking place to watch nature''s power.',
    'Park in the state beach lot at Waimea Bay; overflow parking can be found along the highway but be prepared for a walk.',
    'Enter from the sandy beach near the river mouth and time your paddle between sets; the inside shorebreak can be treacherous at high surf.',
    'Use the rip current near the rocks to paddle out; catch the peak near the bay''s center and angle into the channel for a safe exit.',
    'Spectators line the cliffs during big swells; surfers should be comfortable in heavy water and respect the priority of local chargers.',
    'Mid-high tide, light southerly wind, 10–20 ft northwest swell',
    ARRAY['Strong currents', 'Rip currents', 'Sharks'],
    'Honor the legacy of Eddie Aikau and the bay''s rich cultural history; never surf beyond your skill level.',
    'high',
    ARRAY['🅿️ Limited parking fills quickly', '🌬️ Kona winds clean up the face', '🌊 Use the rip by the rocks to paddle out'],
    false
  ),

  -- 7. Haleiwa
  (
    '43cfaf0d-0376-45cb-a8bd-78087ba4ee15',
    'Haleiwa',
    'Haleiwa',
    'HI',
    'USA',
    21.59,
    -158.113889,
    'river-mouth',
    'advanced',
    ARRAY['rip currents', 'rocks', 'shallow reef', 'strong currents', 'localism'],
    ARRAY['Parking nearby', 'World-class wave', 'Restrooms', 'Showers', 'Consistent waves', 'Scenic'],
    300,
    340,
    180,
    35,
    12,
    8,
    1.0,
    3.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 315, "period_s": 14}, "notes": "Mid-period NW swells produce the best shape; avoid strong trades."}'::jsonb,
    320,
    320,
    20,
    ARRAY[10,11,12,1,2,3],
    'haleiwa-haleiwa-hi',
    'Oahu',
    'Haleiwa is the gateway to the North Shore''s Seven-Mile Miracle, offering a powerful right-hand reef wave that wraps around a river mouth. When mid-period northwest swells arrive, the outside peak produces long rippable rights with sections that get hollow and heavy; on bigger days the inside Toilet Bowl section becomes treacherous and shallow. Strong currents and crowds are common, so this spot is best left to advanced surfers.',
    'Park at Haleʻiwa Aliʻi Beach Park where there is a large lot with restrooms and showers.',
    'Paddle out through the channel next to the harbor wall; watch for outbound rip currents that can pull you toward the rocks.',
    'Line up off the reef finger to catch the main peak; connect sections through the mid-face and kick out before the shallow bowl.',
    'Haleiwa can be packed when the first winter swells arrive; patience and respect go a long way—allow locals and pros priority.',
    'Mid tide, light south winds, 4–8 ft northwest swell',
    ARRAY['Rip currents', 'Shallow reef', 'Strong currents'],
    'Give right of way to surfers coming from the outside peak and never paddle straight through the lineup.',
    'high',
    ARRAY['🅿️ Ample parking at Aliʻi Beach Park', '🌬️ South winds groom the waves', '🌊 Stay alert for the Toilet Bowl section'],
    false
  ),

  -- 8. Sandy Beach
  (
    'd663a525-f59d-4873-b67a-50898ca1c72c',
    'Sandy Beach',
    'Honolulu',
    'HI',
    'USA',
    21.28725,
    -157.66925,
    'beach',
    'upper-intermediate',
    ARRAY['shorebreak', 'rocks', 'rip currents', 'shallow reef', 'strong currents', 'localism'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Lifeguard', 'Scenic', 'Consistent waves'],
    60,
    120,
    270,
    35,
    12,
    8,
    0.5,
    2.5,
    '{"tide": "low", "primary_swell": {"dir_deg": 90, "period_s": 8}, "notes": "Works best on easterly trade swells; avoid high tide when waves fatten."}'::jsonb,
    90,
    90,
    30,
    ARRAY[1,2,3,4,5,6,7,8,9,10,11,12],
    'sandy-beach-honolulu-hi',
    'Oahu',
    'Sandy Beach is famous for its powerful shorebreak that explodes directly onto the sand, making it more popular with bodysurfers and bodyboarders than surfers. Multiple peaks like Full Point and Middle Peak deliver short, hollow waves that can snap boards and bones when the tradewind-driven swell peaks. Experienced wave riders love the challenge, but this spot is unforgiving for novices.',
    'A large parking lot sits right next to the beach along Kalanianaʻole Highway; watch valuables because car break-ins are common.',
    'Walk straight to the shoreline from the parking lot and pick a channel between peaks; always check the waves before entering.',
    'Time your entry carefully between sets and stay low when dropping into the pitching shorebreak; kick out before the inside closeout.',
    'Crowds thin when the surf is heavy; if you are not comfortable with steep shorebreaks, watch from the sand.',
    'Low to mid tide, light west winds, 2–6 ft east swell',
    ARRAY['Shorebreak', 'Strong currents', 'Localism'],
    'Respect the bodyboarding community; don''t drop in on locals and leave room for everyone to exit safely.',
    'medium',
    ARRAY['🅿️ Spacious lot but watch your valuables', '🌬️ West winds provide offshore conditions', '🌊 Only experienced riders should attempt the shorebreak'],
    false
  ),

  -- MAUI (3)

  -- 9. Honolua Bay
  (
    '4dd216b1-edc3-46b6-aabb-66beb467bcaf',
    'Honolua Bay',
    'Kapalua',
    'HI',
    'USA',
    21.0147,
    -156.6395,
    'point',
    'advanced',
    ARRAY['shallow reef', 'rocks', 'sea urchins', 'localism', 'strong currents'],
    ARRAY['Parking nearby', 'World-class wave', 'Consistent waves', 'Scenic', 'Restrooms'],
    290,
    340,
    45,
    35,
    12,
    8,
    1.0,
    3.0,
    '{"tide": "mid-high", "primary_swell": {"dir_deg": 315, "period_s": 15}, "notes": "Needs a solid north swell with light winds; avoid Kona winds which texture the surface."}'::jsonb,
    310,
    315,
    25,
    ARRAY[10,11,12,1,2,3],
    'honolua-bay-kapalua-hi',
    'Maui',
    'Honolua Bay on West Maui is regarded as one of the best right-hand point breaks on Earth. The wave peels along a rocky headland in several sections, offering long barreling walls when north or northwest swells wrap into the bay. Crowds of experts flock here during the winter season, and the coral reef demands precision and respect.',
    'Parking is limited along the cliff road to Honolua; arrive early and be prepared for a short hike down through the vegetation.',
    'Follow the trail to the shoreline and paddle out from the keyhole in the reef; beware of slippery rocks at the entry.',
    'Sit deep near the Cave section to connect through Racetracks and Keiki Bowl; avoid straightening out over shallow sections.',
    'Be courteous in the lineup—take turns and watch for sets wrapping wide; locals know the wave intimately.',
    'Mid tide, light east winds, 4–10 ft northwest swell',
    ARRAY['Shallow reef', 'Localism', 'Strong currents'],
    'Do not attempt if you aren''t comfortable in barrels; respect the environment and remain quiet to preserve the bay''s serene atmosphere.',
    'high',
    ARRAY['🅿️ Limited parking fills before sunrise', '🌬️ Light trades create perfect tubes', '🌊 Connect sections for rides over 200 m'],
    false
  ),

  -- 10. Ho'okipa
  (
    'e6cec9c8-ab43-4ff8-9d79-cb297422b529',
    'Ho''okipa',
    'Paia',
    'HI',
    'USA',
    20.935328,
    -156.355577,
    'reef',
    'advanced',
    ARRAY['strong currents', 'shallow reef', 'rocks', 'sea urchins', 'localism', 'sharks'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Lifeguard', 'Scenic', 'Consistent waves', 'World-class wave'],
    10,
    120,
    270,
    35,
    12,
    8,
    0.5,
    3.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 60, "period_s": 11}, "notes": "Works year-round but excels on NE trade swells; avoid strong trades if you''re only surfing."}'::jsonb,
    50,
    65,
    55,
    ARRAY[1,2,3,4,5,6,7,8,9,10,11,12],
    'hookipa-paia-hi',
    'Maui',
    'Hoʻokipa Beach Park on Maui''s north shore is world famous for windsurfing and kitesurfing but also has excellent surf for experts. Multiple breaks—from the right-hand Pavilions to the fast left at Lanes—offer powerful waves over a shallow reef, and the trades can quickly turn the lineup into a challenging windswept arena. Beginners should stay on the sand and watch, as currents and urchins pose real dangers.',
    'A paved lot off Hana Highway overlooks the break; arrive early to get a spot and lock up valuables.',
    'Use the stairway down the bluff and enter through the channel near Pavilions; time your paddle between sets.',
    'Each peak has its own crowd; know which section you''re surfing and watch the wind to adjust positioning. Wear booties to protect against the reef.',
    'Windsurfers and kiters often share the water; give them space and communicate; the lineup spreads out along the reef.',
    'Mid tide, light west winds, 4–8 ft north or northeast swell',
    ARRAY['Shallow reef', 'Strong currents', 'Sharks'],
    'Respect lifeguards'' instructions; do not kite or windsurf in the surf zone when signposted.',
    'medium',
    ARRAY['🅿️ The bluff lot has great views but fills quickly', '🌬️ Light west winds give rare glassy conditions', '🌊 Multiple peaks—pick one and commit'],
    false
  ),

  -- 11. Lahaina Harbor (Breakwall)
  (
    '2c622571-c1fa-4c46-afd1-c0769c184570',
    'Lahaina Harbor (Breakwall)',
    'Lahaina',
    'HI',
    'USA',
    20.867574,
    -156.676111,
    'jetty',
    'intermediate',
    ARRAY['shallow reef', 'rocks', 'sea urchins', 'localism'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Scenic', 'Consistent waves', 'Beginner friendly'],
    180,
    225,
    0,
    35,
    12,
    8,
    1.0,
    3.0,
    '{"tide": "mid-high", "primary_swell": {"dir_deg": 200, "period_s": 13}, "notes": "Needs a south to southwest swell; avoid strong afternoon trades."}'::jsonb,
    180,
    202,
    22,
    ARRAY[5,6,7,8,9],
    'lahaina-harbor-breakwall-lahaina-hi',
    'Maui',
    'Lahaina Harbor''s Breakwall is a popular surf break in the heart of Lahaina, with an inside section used by surf schools and an outside section that produces steep lefts on a good south swell. The wave breaks beside the harbor''s jetty over a shallow reef, so it gets shallow at low tide, but a mid-to-high tide provides fun walls up to head high. Crowds are heavy and the name "Snakewall" reflects the constant jockeying for position.',
    'Park in the Lahaina Harbor public lot or at the adjacent 505 Front Street shopping center (paid); avoid parking in private stalls.',
    'Walk down to the harbor wall and paddle out beside the breakwall; beware of the rocks and barnacles on the jetty.',
    'For the inside, position yourself near the surf-school pack and go on the softer peaks; for the outside, wait for the larger set waves and crank a hard bottom turn into the pocket.',
    'Expect heavy crowds and snake-ins; be assertive but polite and share waves with the numerous surf schools.',
    'Mid-high tide, light north winds, 2–4 ft south swell',
    ARRAY['Shallow reef', 'Localism', 'Rocks'],
    'Don''t paddle back out through the lineup; stay to the channel near the jetty and give lessons plenty of room.',
    'high',
    ARRAY['🅿️ Paid parking at 505 Front Street', '🌬️ North winds groom the lefts', '🌊 Choose inside or outside based on skill'],
    false
  ),

  -- KAUAI (3)

  -- 12. Kalapaki Beach
  (
    'b2b469ea-3d00-44df-88e8-621934c6926f',
    'Kalapaki Beach',
    'Lihue',
    'HI',
    'USA',
    21.956667,
    -159.349444,
    'beach',
    'beginner',
    ARRAY['rip currents', 'rocks', 'shallow reef', 'localism'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Beginner friendly', 'Lifeguard', 'Scenic'],
    45,
    120,
    315,
    35,
    12,
    8,
    0.5,
    2.5,
    '{"tide": "mid-low", "primary_swell": {"dir_deg": 80, "period_s": 8}, "notes": "Works on small east swells; avoid large swells that close out the bay."}'::jsonb,
    60,
    82,
    37,
    ARRAY[1,2,3,4,5,6,7,8,9,10,11,12],
    'kalapaki-beach-lihue-hi',
    'Kauai',
    'Kalapaki Beach in Līhue is a crescent of golden sand sheltered by a breakwall that tames the waves and creates calm waters perfect for swimming and learning to surf. Surfers enjoy small, fun peaks near the river mouth and harbor entrance on modest east or northeast swells. The beach fronts a resort with amenities, making it a family-friendly spot but still requiring awareness of currents near the harbor.',
    'Park in the public parking lot at the Kauaʻi Marriott or along Rice Street; follow shoreline access signs to the beach.',
    'Walk down the paved path through the resort grounds and enter the water from the sandy shoreline; avoid the rocky jetty.',
    'Stay near the harbor entrance to catch the bigger sets; the waves are soft, so use a longboard or foam board for better glide.',
    'The beach can get busy with families and cruise passengers; surf early in the morning for fewer crowds.',
    'Low to mid tide, light northwest winds, 1–3 ft east-northeast swell',
    ARRAY['Rip currents', 'Rocks', 'Shallow reef'],
    'Share the lineup with beginners and be courteous to resort guests; respect private property signs along the access path.',
    'medium',
    ARRAY['🅿️ Park at the Marriott but respect access rules', '🌬️ Northwest winds keep conditions clean', '🌊 Perfect for longboard cruising'],
    false
  ),

  -- 13. Kekaha / Pakala (Infinities)
  (
    '34e6e6d4-b640-4412-934f-4343b7dd8dfc',
    'Kekaha / Pakala (Infinities)',
    'Waimea',
    'HI',
    'USA',
    21.93385,
    -159.651,
    'point',
    'intermediate',
    ARRAY['shallow reef', 'rocks', 'sea urchins', 'localism', 'strong currents'],
    ARRAY['Parking nearby', 'World-class wave', 'Scenic', 'Consistent waves'],
    180,
    225,
    90,
    35,
    12,
    8,
    1.0,
    3.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 200, "period_s": 14}, "notes": "Needs a strong south or southwest swell; avoid high tide which burgers the wave."}'::jsonb,
    240,
    202,
    22,
    ARRAY[4,5,6,7,8,9],
    'pakala-infinities-waimea-hi',
    'Kauai',
    'Pakala, also known as Infinities, is a long left-hand point break on Kauaʻi''s west side near Kekaha. On summer south swells the wave peels for hundreds of meters over a shallow coral reef, making it a dream for goofy-footers who can handle the long paddle and occasional strong currents. The vibe is mellow but respect the local surfers and watch for sea urchins in the channel.',
    'Park off the highway on the dirt shoulder near the coconut grove; keep valuables hidden and be aware of soft sand.',
    'Follow the footpath through the trees to the shoreline and paddle out from the small beach; the paddle to the lineup is long, so conserve energy.',
    'Sit deep at the top of the point to catch the sets and stay high on the wave face to connect the reforms all the way down the line.',
    'Crowds are moderate but locals know the lineup; share waves and don''t cut people off on the inside sections.',
    'Mid tide, light east winds, 3–6 ft south swell',
    ARRAY['Shallow reef', 'Sea urchins', 'Localism'],
    'Smile and say aloha when you arrive; do not litter or trespass on private property near the access trail.',
    'medium',
    ARRAY['🅿️ Dirt roadside parking can be soft', '🌬️ Easterly winds groom the long lefts', '🌊 Paddle fitness is essential for long rides'],
    false
  ),

  -- 14. Anahola
  (
    'c9659503-c562-4379-9177-fff60acdfb7f',
    'Anahola',
    'Anahola',
    'HI',
    'USA',
    22.150278,
    -159.306944,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'rocks', 'shallow reef', 'localism', 'strong currents'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Scenic', 'Beginner friendly', 'Lifeguard'],
    50,
    100,
    270,
    35,
    12,
    8,
    0.5,
    2.5,
    '{"tide": "mid-low", "primary_swell": {"dir_deg": 70, "period_s": 9}, "notes": "Works on small trade swells; avoid high surf which can close out the bay."}'::jsonb,
    80,
    75,
    25,
    ARRAY[1,2,3,4,5,6,7,8,9,10,11,12],
    'anahola-anahola-hi',
    'Kauai',
    'Anahola Beach on Kauaʻi''s windward side is a tranquil bay protected by a fringing reef that creates a calm inner lagoon and a fun outer break when north- or east-facing swells arrive. Locals enjoy fishing, snorkeling and surfing here, and the white sand and lush backdrop make it picturesque. Watch for currents near the old pier and rocks at either end of the bay.',
    'There is ample parking at Anahola Beach Park off Anahola Road; park near the picnic area for easy access.',
    'Walk across the sandy park to the shoreline; paddle out through the deeper channels avoiding the rocky points.',
    'The outer reef offers mellow peaks best for longboards and funboards; stay clear of the rocky ends and keep an eye on shifting peaks.',
    'The beach is rarely crowded; be respectful of the local families and avoid surfing near swimmers.',
    'Mid tide, light west winds, 2–4 ft east-northeast swell',
    ARRAY['Rip currents', 'Shallow reef', 'Rocks'],
    'Respect the quiet residential nature of Anahola; keep noise down and pack out all trash.',
    'low',
    ARRAY['🅿️ Plenty of parking near the beach park', '🌬️ West winds clean up the waves', '🌊 Enjoy mellow peaks in a serene setting'],
    false
  ),

  -- BIG ISLAND (3)

  -- 15. Banyans
  (
    'eadd2bf6-759a-46e4-a8af-8df1feb635cb',
    'Banyans',
    'Kailua-Kona',
    'HI',
    'USA',
    19.606817,
    -155.977117,
    'reef',
    'advanced',
    ARRAY['shallow reef', 'rocks', 'sea urchins', 'localism', 'strong currents'],
    ARRAY['Parking nearby', 'World-class wave', 'Consistent waves', 'Scenic'],
    200,
    300,
    90,
    35,
    12,
    8,
    1.0,
    3.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 250, "period_s": 14}, "notes": "Needs a solid NW or SW swell; avoid high tide that softens the wave."}'::jsonb,
    275,
    250,
    50,
    ARRAY[10,11,12,1,2,3],
    'banyans-kailua-kona-hi',
    'Big Island',
    'Banyans, along Aliʻi Drive in Kailua-Kona, is a fast, hollow reef break named after a large banyan tree that once shaded the shoreline. The wave serves up a long, powerful right and shorter left when northwest or southwest swells wrap around the island, drawing a dedicated crowd of expert surfers. Shallow reefs, sea urchins and a competitive lineup make this spot suitable only for advanced surfers.',
    'Limited street parking is available along Aliʻi Drive; arrive early and park legally to avoid towing.',
    'Enter from the small beach next to Kona Bali Kai condos; walk over lava rocks and paddle straight out through the keyhole in the reef.',
    'Sit deep to catch the wedgey takeoff and pull into the barrel; on smaller days longboarders can enjoy the softer reforms.',
    'Local rippers dominate the peak; be patient, show respect and wait for your turn.',
    'Mid tide, light east winds, 3–6 ft west-northwest swell',
    ARRAY['Shallow reef', 'Sea urchins', 'Localism'],
    'Know your limits; this is a locals'' spot—smile, say hello and don''t paddle around people.',
    'high',
    ARRAY['🅿️ Limited parking along Aliʻi Drive', '🌬️ Easterlies clean up the lineup', '🌊 Expert only—watch first before paddling out'],
    false
  ),

  -- 16. Kahalu'u
  (
    '67996143-6e0e-4391-a810-9dec48e19963',
    'Kahalu''u',
    'Kahaluu-Keauhou',
    'HI',
    'USA',
    19.580278,
    -155.967417,
    'reef',
    'beginner',
    ARRAY['shallow reef', 'rocks', 'sea urchins', 'strong currents', 'localism'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Beginner friendly', 'Lifeguard', 'Scenic', 'Consistent waves'],
    190,
    290,
    90,
    35,
    12,
    8,
    0.5,
    2.5,
    '{"tide": "mid-low", "primary_swell": {"dir_deg": 220, "period_s": 9}, "notes": "Small SW swells provide ideal beginner waves; avoid larger swells that close out the bay."}'::jsonb,
    250,
    240,
    50,
    ARRAY[3,4,5,6,7,8],
    'kahaluu-kahaluu-keauhou-hi',
    'Big Island',
    'Kahaluʻu Beach Park south of Kailua-Kona is a small bay protected by a man-made breakwater that creates calm water for snorkeling and swimming. The northern corner of the bay features a gentle reef break that produces soft rollers perfect for beginners learning to surf or SUP. Watch for slippery lava rocks and keep an eye on turtles and other marine life that frequent the bay.',
    'Park in the paved lot at Kahaluʻu Beach Park; overflow parking and surf shops are across Aliʻi Drive.',
    'Walk across the reef shelf using the sandy channels and paddle out inside the breakwater; pick a clear path to avoid stepping on coral.',
    'Stay on the inside peak if you''re a beginner and let the larger sets roll through; keep your knees bent and watch for other learners.',
    'Expect lots of surf lessons and snorkelers; be courteous and give way to others.',
    'Low to mid tide, light east winds, 1–3 ft southwest swell',
    ARRAY['Shallow reef', 'Sea urchins', 'Strong currents'],
    'Do not touch the reef or marine life; respect the cultural significance of the bay and keep noise down.',
    'medium',
    ARRAY['🅿️ Paved parking with nearby rentals', '🌬️ Easterly winds keep it glassy', '🌊 Ideal for first-time surfers on soft-top boards'],
    false
  ),

  -- 17. Pine Trees (Kohanaiki)
  (
    'fbe805b3-b9f5-40e0-afbb-3c5a8d45f67b',
    'Pine Trees (Kohanaiki)',
    'Kailua-Kona',
    'HI',
    'USA',
    19.698012,
    -156.045533,
    'reef',
    'intermediate',
    ARRAY['shallow reef', 'rocks', 'strong currents', 'sea urchins', 'localism'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Consistent waves', 'Scenic'],
    200,
    300,
    90,
    35,
    12,
    8,
    0.5,
    2.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 250, "period_s": 13}, "notes": "Best with a west-northwest swell; avoid extreme low tide when waves hit dry reef."}'::jsonb,
    255,
    250,
    50,
    ARRAY[10,11,12,1,2,3],
    'pine-trees-kohanaiki-kailua-kona-hi',
    'Big Island',
    'Pine Trees, officially Kohanaiki Beach Park, is a popular surf zone north of Kailua-Kona where a series of peaks break over reef and lava rock. The spot is named after heliotrope and hau trees that resemble pines and offer shade along the shoreline. Multiple peaks provide lefts and rights that work on all tides, making it one of the Big Island''s most consistent breaks for surfers of various abilities.',
    'Drive down the coastal access road and park on the packed sand near the surf huts; a permit is needed for overnight camping.',
    'Walk across the beach or lava shelf to the nearest channel and paddle out; choose your peak based on ability and crowd.',
    'Position yourself at the peak that matches your skill level; the main peak offers long rights while other sections produce peaky lefts and rights.',
    'Local families frequent this beach; be courteous and give space to keiki (kids) learning to surf.',
    'Mid tide, light east winds, 3–6 ft west-northwest swell',
    ARRAY['Shallow reef', 'Strong currents', 'Sea urchins'],
    'Pack out what you pack in; respect the camping and fishing families sharing the beach.',
    'medium',
    ARRAY['🅿️ Park right on the beach but watch soft sand', '🌬️ East winds shape the peaks', '🌊 Choose the peak that suits your ability'],
    false
  )

ON CONFLICT (id) DO NOTHING;

COMMIT;







