-- Add 12 Pacific Northwest beaches: Oregon (6) and Washington (6)
-- Safe, idempotent insert using ON CONFLICT

BEGIN;

INSERT INTO public.beaches (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private
) VALUES
  -- OREGON (6)

  -- 1. Short Sands (Oswald West)
  (
    '6d3a734b-b051-490d-87e4-df83c3f49c42',
    'Short Sands',
    'Manzanita',
    'OR',
    'USA',
    45.759917,
    -123.966633,
    'beach',
    'beginner',
    ARRAY['rip currents', 'rocks', 'cold water', 'sneaker waves', 'logs'],
    ARRAY['Parking nearby', 'Beginner friendly', 'Restrooms', 'Scenic'],
    180,
    310,
    90,
    45,
    12,
    8,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 270, "period_s": 12}, "notes": "Look for mid-size west or northwest swells and light easterly wind for glassy conditions."}'::jsonb,
    270,
    245,
    65,
    ARRAY[10,11,12,1,2,3],
    'short-sands-manzanita-or',
    'Oregon Coast',
    'This sandy cove in Oswald West State Park offers fun peaks and a mellow vibe. It''s a popular spot for beginners and longboarders, although October and November groom the sandbars for occasional barrels and long rides. The beach is reached via a forest trail and is sheltered from north winds, but heavy winter swells can be powerful.',
    'Park at the Oswald West lot off Highway 101 and take the half-mile trail through old-growth forest to the beach. Arrive early on summer weekends as spaces fill up quickly.',
    'Follow the well-marked trail from the parking area, cross the bridge over Short Sands Creek, and walk across the creek mouth. Check tides to avoid wading at high tide.',
    'Best waves form on west swells. Sit inside for smaller peaks or further out at the main sandbar for longer rides. Watch for shifting currents and avoid surfing near the cliffs.',
    'Summer weekends can be packed with beginners, but dawn patrol or mid-week sessions offer more space. Be patient and share waves.',
    'Mid tide, E wind, 3-6 ft W-NW swell',
    ARRAY['Strong currents', 'Sneaker waves'],
    'Respect the beach''s marine reserve status. Pack out trash and be courteous to fellow surfers and hikers.',
    'high',
    ARRAY['🅿️ Limited parking; arrive early', '🌬️ East winds groom the surface', '🌊 West swell shapes fun peaks'],
    false
  ),

  -- 2. Seaside Cove (Oregon)
  (
    '6f683baf-fd73-4a77-95b2-46f04050b136',
    'Seaside Cove (Oregon)',
    'Seaside',
    'OR',
    'USA',
    45.977967,
    -123.94115,
    'beach',
    'intermediate',
    ARRAY['rip currents', 'rocks', 'cold water', 'sneaker waves', 'localism', 'sharks'],
    ARRAY['Parking nearby', 'Restrooms', 'Consistent waves'],
    200,
    310,
    90,
    35,
    12,
    8,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 290, "period_s": 13}, "notes": "Strong W-NW swells and light easterlies produce the best peaks; avoid south winds."}'::jsonb,
    270,
    255,
    55,
    ARRAY[10,11,12,1,2,3],
    'seaside-cove-oregon-seaside-or',
    'Oregon Coast',
    'Seaside Cove (Oregon) is a powerful sand-and-rock break with lefts and rights. Waves can reach 10-15 ft in winter and 5-7 ft in summer, attracting experienced locals. Beginners should stay out of the main lineup and respect the locals and reef.',
    'Park at Avenue U or along the promenade. Avoid blocking driveways, and be prepared to walk with your board.',
    'Follow paved trails to the beach and paddle out through the channel near the rocks. Watch for slippery boulders.',
    'Sit inside for reform sections or further out for the main peak. Current runs along the head at high tide.',
    'Crowds can be intense; try mid-week mornings to avoid the rush. Keep your distance from locals and be courteous.',
    'Mid tide, E wind, 4-8 ft W-NW swell',
    ARRAY['Rip currents', 'Rocks', 'Localism'],
    'Respect experienced locals and surf etiquette. Give right of way and don''t snake.',
    'high',
    ARRAY['🅿️ Limited parking near Cove', '🌬️ East winds clean up the surf', '🌊 Powerful reef and sandbar'],
    false
  ),

  -- 3. Otter Rock
  (
    '1fbbe6cc-783f-4b74-9664-a1996ca2649a',
    'Otter Rock',
    'Otter Rock',
    'OR',
    'USA',
    44.775933,
    -124.073533,
    'beach',
    'beginner',
    ARRAY['rip currents', 'rocks', 'cold water', 'sneaker waves', 'sharks'],
    ARRAY['Parking nearby', 'Beginner friendly', 'Restrooms', 'Scenic'],
    180,
    300,
    90,
    40,
    12,
    8,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 250, "period_s": 12}, "notes": "Look for small to medium west swells and avoid strong south winds."}'::jsonb,
    260,
    240,
    60,
    ARRAY[10,11,12,1,2,3],
    'otter-rock-otter-rock-or',
    'Oregon Coast',
    'Often called the ''Waikiki of Oregon,'' Otter Rock offers gentle waves perfect for learning to surf. The sand-and-rock bottom provides playful peaks at all tides, though winter swells can bring larger sets.',
    'Park at the Devil''s Punchbowl State Natural Area lot and walk down the path to the beach. Get there early on summer weekends.',
    'Follow the trail down the bluff and paddle out through the channel. Be mindful of the marine reserve boundaries and avoid the rocks at the north end.',
    'Stay near the inside for fun reforms when it''s crowded. When bigger swells arrive, line up further out for long rides.',
    'Otter Rock is popular with surf schools; mornings and weekdays are less busy. Share waves and smile.',
    'Mid tide, E wind, 2-5 ft W-SW swell',
    ARRAY['Rip currents', 'Rocks', 'Marine reserve restrictions'],
    'Respect the marine reserve rules and wildlife. Avoid litter and keep noise down.',
    'high',
    ARRAY['🅿️ Parking at Devil''s Punchbowl', '🌬️ Light easterly wind preferred', '🌊 Gentle peaks for learners'],
    false
  ),

  -- 4. Nelscott Reef
  (
    '998e264e-3ad7-4875-bb19-04c25d1b173e',
    'Nelscott Reef',
    'Lincoln City',
    'OR',
    'USA',
    44.949667,
    -124.026333,
    'reef',
    'advanced',
    ARRAY['strong currents', 'shallow reef', 'cold water', 'sharks', 'sneaker waves'],
    ARRAY['Parking nearby', 'Scenic'],
    230,
    310,
    90,
    35,
    12,
    8,
    2.0,
    5.0,
    '{"tide": "mid-low", "primary_swell": {"dir_deg": 275, "period_s": 16}, "notes": "Only attempt when conditions align with east wind and large west swells; jetski support mandatory."}'::jsonb,
    270,
    270,
    40,
    ARRAY[11,12,1,2],
    'nelscott-reef-lincoln-city-or',
    'Oregon Coast',
    'Half a mile off Lincoln City, Nelscott Reef is Oregon''s big-wave arena where west swells and east winds produce 25-50 ft monsters. Only expert surfers with jetski support attempt this outer reef.',
    'Park at Canyon Drive Park or on SW 3rd Avenue. Spotters can watch from the beach or cliffs.',
    'Paddling is not recommended; surfers launch via jetski from the harbor. Coordinate with a local team and safety crew.',
    'Wait for deep-water swells from the west and line up on the outer reef. Tow teams work in rotation; communication and safety are critical.',
    'Only a handful of big-wave surfers tackle the reef, so crowding isn''t an issue. Spectators watch from shore.',
    'Low to mid tide, E wind, 15-25 ft W swell',
    ARRAY['Extreme waves', 'Strong currents', 'Sharks'],
    'Coordinate with local big-wave crews and respect the risk. Spectators should observe from safe distances.',
    'low',
    ARRAY['🅿️ Park at Canyon Drive', '🌬️ East wind essential', '🌊 Only for experts'],
    false
  ),

  -- 5. Bastendorff Beach
  (
    '615ff20a-922f-4487-88d8-fa7d830ebacf',
    'Bastendorff Beach',
    'Coos Bay',
    'OR',
    'USA',
    43.346933,
    -124.345536,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'sharks', 'pollution', 'cold water', 'sneaker waves'],
    ARRAY['Parking nearby', 'Restrooms', 'Scenic'],
    210,
    300,
    90,
    40,
    12,
    8,
    2.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 260, "period_s": 13}, "notes": "Look for mid-period west swells and avoid onshore winds."}'::jsonb,
    260,
    255,
    45,
    ARRAY[10,11,12,1,2,3],
    'bastendorff-beach-coos-bay-or',
    'Oregon Coast',
    'This exposed beach break near Coos Bay offers reliable surf with left and right peaks. It starts at less than 3 ft and holds up to 6 ft; optimum swell is from the west with offshore southeast winds.',
    'Parking is free at the Bastendorff County Park day-use area. Avoid camping areas unless you have a permit.',
    'Take Cape Arago Highway west of Charleston and turn onto Bastendorff Beach Road to the parking lot. Walk over the dunes to the shore.',
    'Surf near the center of the beach for consistent peaks. Beware of strong rips and pollution near the jetty. Mid tide is ideal.',
    'The beach rarely gets crowded; you''ll often have it to yourself.',
    'Mid tide, SE wind, 3-6 ft W swell',
    ARRAY['Strong rip currents', 'Sharks', 'Pollution'],
    'Leave no trace and respect fishermen and locals. The area can be littered; pack out trash.',
    'low',
    ARRAY['🅿️ Free parking at county park', '🌬️ SE wind works best', '🌊 Consistent peaks with rips'],
    false
  ),

  -- 6. Sunset Bay State Park
  (
    'bd7a7984-d69a-4969-85b1-b97ea78d8fb7',
    'Sunset Bay State Park',
    'Charleston',
    'OR',
    'USA',
    43.3339,
    -124.3686,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'shallow reef', 'cold water', 'sneaker waves', 'logs'],
    ARRAY['Parking nearby', 'Restrooms', 'Camping', 'Scenic'],
    200,
    300,
    90,
    40,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 255, "period_s": 13}, "notes": "The cove favours west swells and easterly winds; best during mid tide and bigger swell events."}'::jsonb,
    250,
    250,
    50,
    ARRAY[10,11,12,1,2,3],
    'sunset-bay-charleston-or',
    'Oregon Coast',
    'Sunset Bay is a crescent-shaped cove near Cape Arago with tide pools and a campground. It''s popular with surfers when large winter swells create rolling pipes of ocean. On smaller days it''s sheltered and calm, suitable for intermediates.',
    'Park at the state park day-use area off Cape Arago Highway; spaces can fill during summer. The park has restrooms and picnic tables.',
    'A short walk leads from the parking lot to the sandy beach. Paddle out through the channel near the east headland to avoid shallow rocks.',
    'Look for big west swells for long, rolling waves. During smaller swells, head to the outer sandbar for better shape. Watch for submerged rocks at low tide.',
    'Even when the surf is good, crowds are manageable. Share waves with bodyboarders and respect the campground''s quiet hours.',
    'Mid tide, E wind, 4-8 ft W swell',
    ARRAY['Shallow reef', 'Sneaker waves', 'Logs'],
    'Stay off the cliffs and respect the marine life. Pack out trash and keep noise down at the campground.',
    'medium',
    ARRAY['🅿️ Day-use parking at state park', '🌬️ East winds clean up the bay', '🌊 Works on large west swells'],
    false
  ),

  -- WASHINGTON (6)

  -- 7. Westport – The Jetty
  (
    'cb75834d-79cb-4b65-859b-d0a370bfc75e',
    'Westport – The Jetty',
    'Westport',
    'WA',
    'USA',
    46.90055,
    -124.1328833,
    'beach',
    'intermediate',
    ARRAY['rip currents', 'cold water', 'shallow sandbar', 'sneaker waves'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Consistent waves'],
    200,
    310,
    90,
    45,
    12,
    8,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 270, "period_s": 12}, "notes": "West swells and light easterly winds produce classic A-frames. Avoid onshore south winds."}'::jsonb,
    260,
    255,
    55,
    ARRAY[9,10,11,12,1,2],
    'westport-jetty-westport-wa',
    'Washington Coast',
    'Washington''s most consistent surf spot features A-frame peaks on a sand bottom. Beginners and pros share the lineup, but a strong rip current runs along the jetty; surfers should stay 50 yards south.',
    'Parking at Westhaven State Park requires a Discover Pass. Restrooms and showers are available near the lot.',
    'Walk down the beach from the parking lot and paddle out south of the jetty. Avoid the rip current hugging the rocks.',
    'Look for A-frame peaks and position yourself to catch both lefts and rights. Rips can help you paddle out but watch for surfers returning on them.',
    'Expect crowds on weekends, especially during fall and winter. Dawn patrol or mid-week sessions offer more room.',
    'Mid tide, E wind, 4-8 ft W-NW swell',
    ARRAY['Rip currents', 'Sneaker waves'],
    'Stay 50 yards south of the jetty to avoid the rip current and respect anglers. Keep the beach clean.',
    'high',
    ARRAY['🅿️ Discover Pass required', '🌬️ East winds clean up surf', '🌊 A-frame peaks with rip along jetty'],
    false
  ),

  -- 8. Westport – The Groins
  (
    '4ec455fa-dab5-4cfa-884f-1f1d29154c74',
    'Westport – The Groins',
    'Westport',
    'WA',
    'USA',
    46.91135,
    -124.1151167,
    'jetty',
    'upper-intermediate',
    ARRAY['strong currents', 'rocks', 'cold water', 'sneaker waves'],
    ARRAY['Parking nearby', 'Scenic'],
    200,
    310,
    90,
    45,
    12,
    8,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 270, "period_s": 13}, "notes": "Needs a wraparound west swell and moderate tide; avoid strong ebb or flood currents."}'::jsonb,
    260,
    255,
    55,
    ARRAY[9,10,11,12,1,2],
    'westport-groins-westport-wa',
    'Washington Coast',
    'Located on the north side of the marina, The Groins provides a lefthand point break when swells wrap into Grays Harbor. It''s not a beginner spot due to powerful tidal currents flowing in and out of the harbor.',
    'Park along Neddie Rose Drive near the marina and walk toward the finger jetties. There are no restrooms here.',
    'Climb over the rock wall to reach the point and paddle out next to the groins. Know the tide schedule to avoid getting trapped.',
    'Wait for a mid tide with a wraparound west swell; then drop in on the left peeling along the rocks. Strong paddling skills are required to handle the currents.',
    'Crowds are moderate; more experienced surfers line up here. Respect the locals and rotate waves.',
    'Mid tide, E wind, 4-8 ft W-NW swell',
    ARRAY['Strong currents', 'Rocks'],
    'This is a more advanced lineup; mind your position and yield to surfers taking off deeper.',
    'medium',
    ARRAY['🅿️ Park on Neddie Rose Drive', '🌬️ East wind is ideal', '🌊 Powerful currents and wrap lefts'],
    false
  ),

  -- 9. Westport – Half Moon Bay (The Cove)
  (
    '51180cd3-b83b-4cf8-99b2-8705c68b87ef',
    'Westport – Half Moon Bay (The Cove)',
    'Westport',
    'WA',
    'USA',
    46.90551667,
    -124.1233667,
    'beach',
    'advanced',
    ARRAY['shallow sandbar', 'strong currents', 'cold water', 'sneaker waves'],
    ARRAY['Parking nearby', 'Scenic'],
    200,
    310,
    90,
    45,
    12,
    8,
    2.0,
    6.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 270, "period_s": 13}, "notes": "Best used for watching large swells; surfing only when conditions align and you''re prepared for heavy shorebreak."}'::jsonb,
    260,
    255,
    55,
    ARRAY[9,10,11,12,1,2],
    'westport-half-moon-bay-westport-wa',
    'Washington Coast',
    'Once a favourite for advanced surfers, Half Moon Bay has become a dangerous shorebreak after sand redistribution. Powerful waves and currents mean it''s now rarely surfed, best watched from shore.',
    'Park along Jetty Haul Road; no pass is required.',
    'Walk down the beach to the shorebreak. Be cautious of rogue waves and deep troughs near the sandbar.',
    'Only experienced surfers should consider paddling out on moderate days. Otherwise, enjoy the view and photograph the heavy shorebreak from a safe distance.',
    'Surfers are rare here now; the beach is mostly empty. Photographers and spectators gather during large swells.',
    'Mid tide, E wind, 4-8 ft W-NW swell',
    ARRAY['Dangerous shorebreak', 'Strong currents'],
    'Observe from a safe distance. If you surf, respect local knowledge and watch out for unexpected waves.',
    'low',
    ARRAY['🅿️ Park along Jetty Haul Rd', '🌬️ East wind cleans up the wave', '🌊 Heavy shorebreak; mostly for watching'],
    false
  ),

  -- 10. La Push – Second Beach
  (
    '281b7eef-bcc3-4ecd-998f-1faa190ed956',
    'La Push – Second Beach',
    'La Push',
    'WA',
    'USA',
    47.8982,
    -124.6238,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'logs', 'cold water', 'sneaker waves'],
    ARRAY['Parking nearby', 'Scenic', 'Camping'],
    200,
    300,
    90,
    40,
    12,
    8,
    1.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 250, "period_s": 12}, "notes": "Wide swell window but best with west-southwest swells and light east winds."}'::jsonb,
    250,
    250,
    50,
    ARRAY[9,10,11,12,1,2],
    'la-push-second-beach-la-push-wa',
    'Washington Coast',
    'This wide sandy beach on the Olympic Coast offers playful waist- to head-high waves ideal for longboarding and cruising. Logs and driftwood line the shore, and cold, clear water keeps crowds thin. Access requires a forest trail hike with scenic sea stacks and sea caves.',
    'Limited parking at the trailhead; overflow parking is located east of the main lot. Secure valuables and display a recreation pass if required.',
    'Follow the 0.7-mile trail through lush forest, down stairs, and across driftwood to reach the beach. Arrive early, as the lot fills on summer days.',
    'Surf near the river mouth for sandbar peaks or move further south for longer rides. Beware of rips and floating logs in the lineup.',
    'Crowds are moderate; most visitors hike to sightsee. Surf early or in the off-season for more space.',
    'Mid tide, E wind, 3-6 ft W-SW swell',
    ARRAY['Floating logs', 'Strong currents', 'Sneaker waves'],
    'Respect the Quileute Reservation rules. Pack out trash and do not disturb wildlife or logs.',
    'medium',
    ARRAY['🅿️ Limited trailhead parking', '🌬️ Light easterly wind preferred', '🌊 Logs and sandbars create fun peaks'],
    false
  ),

  -- 11. La Push – Third Beach
  (
    'c03fc6d7-913e-4c99-b1f4-610d036b3cbf',
    'La Push – Third Beach',
    'La Push',
    'WA',
    'USA',
    47.8906,
    -124.599,
    'beach',
    'intermediate',
    ARRAY['rip currents', 'logs', 'cold water', 'sneaker waves'],
    ARRAY['Parking nearby', 'Scenic', 'Camping'],
    200,
    300,
    90,
    40,
    12,
    8,
    1.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 250, "period_s": 13}, "notes": "Prefers west-southwest swells and mid tides; best when wind is light and from the east."}'::jsonb,
    250,
    250,
    50,
    ARRAY[9,10,11,12,1,2],
    'la-push-third-beach-la-push-wa',
    'Washington Coast',
    'A bit more exposed than Second Beach, Third Beach offers longer rides and more powerful peaks. Access involves a 1.3-mile hike with a steep descent and driftwood crossing. Logs and rips demand caution, but the remote setting keeps crowds low.',
    'Parking for about 20 cars at the trailhead; arrive early to secure a spot. Overflow parking is limited.',
    'Hike 1.3 miles through Sitka spruce forest and descend a steep slope to the beach. Cross large driftwood piles at the creek mouth to reach the surf.',
    'Surf near the middle of the beach for consistent peaks. Rips form near the headlands; use them to paddle out but watch for strong currents.',
    'Crowds are low due to the hike in. Camp overnight with a permit for solitude and early sessions.',
    'Mid tide, E wind, 3-7 ft W-SW swell',
    ARRAY['Floating logs', 'Strong currents', 'Sneaker waves'],
    'Follow Quileute Tribe regulations. Pack out trash and respect the wilderness.',
    'low',
    ARRAY['🅿️ Limited trailhead parking', '🌬️ East winds clean up surf', '🌊 Long rides but watch logs and rips'],
    false
  ),

  -- 12. Hobuck Beach (Neah Bay)
  (
    '44c9add8-cbd4-4e2f-8554-58a32b9b3c08',
    'Hobuck Beach (Neah Bay)',
    'Neah Bay',
    'WA',
    'USA',
    48.3336014,
    -124.6653414,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'logs', 'cold water', 'sneaker waves', 'wildlife'],
    ARRAY['Parking nearby', 'Camping', 'Scenic', 'Consistent waves'],
    200,
    300,
    90,
    40,
    12,
    8,
    1.0,
    5.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 250, "period_s": 12}, "notes": "Works best with medium west swells and light east winds; avoid strong south winds."}'::jsonb,
    250,
    250,
    50,
    ARRAY[9,10,11,12,1,2],
    'hobuck-beach-neah-bay-wa',
    'Washington Coast',
    'Hobuck Beach is a remote, crescent-shaped beach on the Makah Reservation. It offers fun peaks for beginners to intermediates and stunning views of Cape Flattery. Camping and cabins are available, and surfers often spot sea lions and jellyfish. A Makah Recreation Permit is required for access and camping.',
    'Park at the Hobuck Beach Resort and purchase a $10 Makah Recreation Permit at check-in. Campsites and cabins must be reserved ahead during peak season.',
    'The beach is right in front of the campground. Walk across the dunes to paddle out. Watch for drifting logs during big swells.',
    'Find peaks along the middle of the beach; waves are mostly soft and suitable for longboards. During larger swells, look for rips to help paddle out.',
    'Because of the long drive from Seattle, crowds are low except during sunny summer weekends. Early sessions offer solitude.',
    'Mid tide, E wind, 3-6 ft W-SW swell',
    ARRAY['Floating logs', 'Strong currents', 'Wildlife'],
    'Respect the Makah Tribe''s land and regulations. Purchase a permit and leave no trace.',
    'medium',
    ARRAY['🅿️ Makah permit required', '🌬️ East winds clean up the surf', '🌊 Remote peaks with wildlife'],
    false
  )

ON CONFLICT (id) DO NOTHING;

COMMIT;

