-- Populate beach characteristics from parsed surf database
-- Generated by parse-surf-database.ts (regex parsing - no API calls)
-- Date: 2025-10-29T03:49:42.814Z
-- Spots parsed: 56


-- Bottom line:
UPDATE beaches SET
  swell_window_center_deg = 180,
  swell_window_halfwidth_deg = 45,
  wind_offshore_deg = null,
  break_type = 'reef break'
WHERE name ILIKE 'Bottom line:';


-- Lower Trestles
UPDATE beaches SET
  swell_window_center_deg = 215,
  swell_window_halfwidth_deg = 35,
  wind_offshore_deg = 67,
  break_type = 'reef break'
WHERE name ILIKE 'Lower Trestles';


-- Upper Trestles
UPDATE beaches SET
  swell_window_center_deg = 280,
  swell_window_halfwidth_deg = 38,
  wind_offshore_deg = null,
  preferred_tide_ft_min = 2.5,
  preferred_tide_ft_max = 5.5,
  break_type = 'point break'
WHERE name ILIKE 'Upper Trestles';


-- T-Street
UPDATE beaches SET
  swell_window_center_deg = 215,
  swell_window_halfwidth_deg = 45,
  wind_offshore_deg = null,
  break_type = 'beach break',
  hazards = ARRAY['rocks'],
  warnings = ARRAY['Blackballed - check hours']
WHERE name ILIKE 'T-Street';


-- San Onofre State Beach
UPDATE beaches SET
  swell_window_center_deg = 225,
  swell_window_halfwidth_deg = 55,
  wind_offshore_deg = null
WHERE name ILIKE 'San Onofre State Beach';


-- Doheny State Beach
UPDATE beaches SET
  swell_window_center_deg = 200,
  swell_window_halfwidth_deg = 28,
  wind_offshore_deg = null,
  preferred_tide_ft_min = 0.5,
  preferred_tide_ft_max = 4,
  break_type = 'beach break',
  skill_level = 'beginner',
  hazards = ARRAY['water quality']
WHERE name ILIKE 'Doheny State Beach';


-- Salt Creek
UPDATE beaches SET
  swell_window_center_deg = 210,
  swell_window_halfwidth_deg = 30,
  wind_offshore_deg = 60,
  preferred_tide_ft_min = 2,
  preferred_tide_ft_max = 4,
  break_type = 'reef break',
  warnings = ARRAY['Blackballed - check hours']
WHERE name ILIKE 'Salt Creek';


-- The Wedge
UPDATE beaches SET
  swell_window_center_deg = 200,
  swell_window_halfwidth_deg = 20,
  wind_offshore_deg = 0,
  preferred_tide_ft_min = 2.5,
  preferred_tide_ft_max = 4,
  break_type = 'jetty',
  skill_level = 'expert',
  warnings = ARRAY['Blackballed - check hours']
WHERE name ILIKE 'The Wedge';


-- Newport Point
UPDATE beaches SET
  swell_window_center_deg = 175,
  swell_window_halfwidth_deg = 15,
  wind_offshore_deg = null,
  preferred_tide_ft_min = 2,
  preferred_tide_ft_max = 5
WHERE name ILIKE 'Newport Point';


-- Brooks Street
UPDATE beaches SET
  swell_window_center_deg = 200,
  swell_window_halfwidth_deg = 30,
  wind_offshore_deg = 45,
  preferred_tide_ft_min = 1.5,
  preferred_tide_ft_max = 5
WHERE name ILIKE 'Brooks Street';


-- Crystal Cove
UPDATE beaches SET
  swell_window_center_deg = 200,
  swell_window_halfwidth_deg = 30,
  wind_offshore_deg = null,
  preferred_tide_ft_min = 2.5,
  preferred_tide_ft_max = 4.5
WHERE name ILIKE 'Crystal Cove';


-- El Porto
UPDATE beaches SET
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 2,
  preferred_tide_ft_max = 4.5,
  break_type = 'beach break'
WHERE name ILIKE 'El Porto';


-- Bolsa Chica State Beach
UPDATE beaches SET
  swell_window_center_deg = 225,
  swell_window_halfwidth_deg = 55,
  wind_offshore_deg = 45,
  preferred_tide_ft_min = 1.5,
  preferred_tide_ft_max = 4,
  break_type = 'jetty',
  skill_level = 'beginner',
  warnings = ARRAY['Parking: $15']
WHERE name ILIKE 'Bolsa Chica State Beach';


-- Oceanside Pier
UPDATE beaches SET
  swell_window_center_deg = 240,
  swell_window_halfwidth_deg = 80,
  wind_offshore_deg = 45,
  preferred_tide_ft_min = 0.5,
  preferred_tide_ft_max = 4,
  break_type = 'beach break'
WHERE name ILIKE 'Oceanside Pier';


-- Oceanside Harbor
UPDATE beaches SET
  wind_offshore_deg = 45,
  preferred_tide_ft_min = 3,
  preferred_tide_ft_max = 5.7,
  break_type = 'jetty',
  skill_level = 'advanced',
  hazards = ARRAY['rip currents', 'aggressive locals']
WHERE name ILIKE 'Oceanside Harbor';


-- Ponto
UPDATE beaches SET
  wind_offshore_deg = 45,
  preferred_tide_ft_min = 2.5,
  preferred_tide_ft_max = 4.5,
  break_type = 'jetty',
  hazards = ARRAY['rip currents']
WHERE name ILIKE 'Ponto';


-- Tamarack State Beach
UPDATE beaches SET
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 2,
  preferred_tide_ft_max = 4,
  break_type = 'jetty'
WHERE name ILIKE 'Tamarack State Beach';


-- Terramar Point
UPDATE beaches SET
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 2,
  preferred_tide_ft_max = 4,
  break_type = 'point break'
WHERE name ILIKE 'Terramar Point';


-- Swami's
UPDATE beaches SET
  swell_window_center_deg = 270,
  swell_window_halfwidth_deg = 35,
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 0.5,
  preferred_tide_ft_max = 3.5,
  break_type = 'point break'
WHERE name ILIKE 'Swami''s';


-- Cardiff Reef
UPDATE beaches SET
  swell_window_center_deg = 285,
  swell_window_halfwidth_deg = 35,
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 0,
  preferred_tide_ft_max = 4
WHERE name ILIKE 'Cardiff Reef';


-- Seaside Reef
UPDATE beaches SET
  swell_window_center_deg = 280,
  swell_window_halfwidth_deg = 30,
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 1.5,
  preferred_tide_ft_max = 4.5
WHERE name ILIKE 'Seaside Reef';


-- Grandview
UPDATE beaches SET
  wind_offshore_deg = 85,
  preferred_tide_ft_min = 1,
  preferred_tide_ft_max = 4,
  break_type = 'reef break',
  skill_level = 'beginner'
WHERE name ILIKE 'Grandview';


-- Leucadia
UPDATE beaches SET
  swell_window_center_deg = 270,
  swell_window_halfwidth_deg = 30,
  wind_offshore_deg = 67,
  preferred_tide_ft_min = 0,
  preferred_tide_ft_max = 6,
  break_type = 'beach break'
WHERE name ILIKE 'Leucadia';


-- Moonlight Beach
UPDATE beaches SET
  swell_window_center_deg = 225,
  swell_window_halfwidth_deg = 50,
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 1.5,
  preferred_tide_ft_max = 4.5,
  skill_level = 'beginner'
WHERE name ILIKE 'Moonlight Beach';


-- Del Mar
UPDATE beaches SET
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 0,
  preferred_tide_ft_max = 4,
  break_type = 'reef break'
WHERE name ILIKE 'Del Mar';


-- Windansea
UPDATE beaches SET
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 0,
  preferred_tide_ft_max = 6,
  skill_level = 'advanced'
WHERE name ILIKE 'Windansea';


-- Tourmaline
UPDATE beaches SET
  wind_offshore_deg = 45,
  preferred_tide_ft_min = 2,
  preferred_tide_ft_max = 5.5,
  break_type = 'beach break',
  skill_level = 'beginner',
  hazards = ARRAY['aggressive locals']
WHERE name ILIKE 'Tourmaline';


-- Pacific Beach
UPDATE beaches SET
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 1.5,
  preferred_tide_ft_max = 4.5,
  break_type = 'beach break'
WHERE name ILIKE 'Pacific Beach';


-- Mission Beach
UPDATE beaches SET
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 2,
  preferred_tide_ft_max = 6,
  break_type = 'jetty'
WHERE name ILIKE 'Mission Beach';


-- La Jolla Shores
UPDATE beaches SET
  wind_offshore_deg = 135,
  preferred_tide_ft_min = 1,
  preferred_tide_ft_max = 5,
  break_type = 'beach break',
  skill_level = 'advanced'
WHERE name ILIKE 'La Jolla Shores';


-- Blacks Beach
UPDATE beaches SET
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 0.5,
  preferred_tide_ft_max = 4,
  break_type = 'beach break',
  skill_level = 'expert'
WHERE name ILIKE 'Blacks Beach';


-- Scripps Pier
UPDATE beaches SET
  swell_window_center_deg = 285,
  swell_window_halfwidth_deg = 50,
  wind_offshore_deg = 135,
  preferred_tide_ft_min = 2,
  preferred_tide_ft_max = 5,
  break_type = 'beach break',
  skill_level = 'intermediate'
WHERE name ILIKE 'Scripps Pier';


-- Ocean Beach
UPDATE beaches SET
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 1,
  preferred_tide_ft_max = 4,
  break_type = 'jetty',
  skill_level = 'advanced',
  hazards = ARRAY['rip currents', 'aggressive locals']
WHERE name ILIKE 'Ocean Beach';


-- Sunset Cliffs
UPDATE beaches SET
  swell_window_center_deg = 270,
  swell_window_halfwidth_deg = 40,
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 0.5,
  preferred_tide_ft_max = 3,
  break_type = 'reef break',
  hazards = ARRAY['rocks', 'aggressive locals']
WHERE name ILIKE 'Sunset Cliffs';


-- Silver Strand State Beach
UPDATE beaches SET
  swell_window_center_deg = 200,
  swell_window_halfwidth_deg = 40,
  wind_offshore_deg = 45,
  preferred_tide_ft_min = 2,
  preferred_tide_ft_max = 4,
  break_type = 'beach break',
  skill_level = 'beginner'
WHERE name ILIKE 'Silver Strand State Beach';


-- Tijuana Sloughs
UPDATE beaches SET
  swell_window_center_deg = 280,
  swell_window_halfwidth_deg = 50,
  wind_offshore_deg = 75,
  preferred_tide_ft_min = 1,
  preferred_tide_ft_max = 6,
  break_type = 'reef break',
  skill_level = 'expert',
  hazards = ARRAY['water quality']
WHERE name ILIKE 'Tijuana Sloughs';


-- Seaside Cove
UPDATE beaches SET
  swell_window_center_deg = 315,
  swell_window_halfwidth_deg = 45,
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 4,
  preferred_tide_ft_max = 8,
  break_type = 'point break',
  skill_level = 'expert'
WHERE name ILIKE 'Seaside Cove';


-- Short Sands
UPDATE beaches SET
  swell_window_center_deg = 225,
  swell_window_halfwidth_deg = 68,
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 2,
  preferred_tide_ft_max = 8,
  break_type = 'beach break',
  skill_level = 'advanced'
WHERE name ILIKE 'Short Sands';


-- Otter Rock
UPDATE beaches SET
  swell_window_center_deg = 270,
  swell_window_halfwidth_deg = 68,
  wind_offshore_deg = 90,
  break_type = 'beach break',
  skill_level = 'advanced',
  hazards = ARRAY['rocks']
WHERE name ILIKE 'Otter Rock';


-- Pacific City
UPDATE beaches SET
  swell_window_center_deg = 270,
  swell_window_halfwidth_deg = 30,
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 0,
  preferred_tide_ft_max = 8,
  break_type = 'reef break',
  warnings = ARRAY['Parking: $10']
WHERE name ILIKE 'Pacific City';


-- Florence South Jetty
UPDATE beaches SET
  swell_window_center_deg = 225,
  swell_window_halfwidth_deg = 45,
  wind_offshore_deg = 45,
  break_type = 'jetty',
  skill_level = 'advanced',
  hazards = ARRAY['rip currents', 'rocks']
WHERE name ILIKE 'Florence South Jetty';


-- Gold Beach
UPDATE beaches SET
  swell_window_center_deg = 270,
  swell_window_halfwidth_deg = 30,
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 2,
  preferred_tide_ft_max = 6,
  break_type = 'jetty'
WHERE name ILIKE 'Gold Beach';


-- Seabrook Beach
UPDATE beaches SET
  swell_window_center_deg = 270,
  swell_window_halfwidth_deg = 45,
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 2,
  preferred_tide_ft_max = 8,
  break_type = 'beach break',
  skill_level = 'beginner'
WHERE name ILIKE 'Seabrook Beach';


-- La Push
UPDATE beaches SET
  wind_offshore_deg = 90,
  preferred_tide_ft_min = 3,
  preferred_tide_ft_max = 7,
  break_type = 'beach break',
  skill_level = 'advanced'
WHERE name ILIKE 'La Push';


-- Westport
UPDATE beaches SET
  wind_offshore_deg = null,
  preferred_tide_ft_min = 1,
  preferred_tide_ft_max = 9,
  break_type = 'reef break',
  skill_level = 'advanced'
WHERE name ILIKE 'Westport';


-- Pipeline
UPDATE beaches SET
  swell_window_center_deg = 310,
  swell_window_halfwidth_deg = 30,
  wind_offshore_deg = 110,
  preferred_tide_ft_min = 0,
  preferred_tide_ft_max = 3,
  skill_level = 'expert',
  hazards = ARRAY['rocks', 'shallow reef', 'localism']
WHERE name ILIKE 'Pipeline';


-- Sunset Beach
UPDATE beaches SET
  swell_window_center_deg = 350,
  swell_window_halfwidth_deg = -125,
  wind_offshore_deg = 160,
  preferred_tide_ft_min = 0,
  preferred_tide_ft_max = 4,
  break_type = 'reef break'
WHERE name ILIKE 'Sunset Beach';


-- Waimea Bay
UPDATE beaches SET
  swell_window_center_deg = 330,
  swell_window_halfwidth_deg = -140,
  wind_offshore_deg = 110,
  preferred_tide_ft_min = 0.5,
  preferred_tide_ft_max = 3.5,
  skill_level = 'expert'
WHERE name ILIKE 'Waimea Bay';


-- Honolua Bay
UPDATE beaches SET
  swell_window_center_deg = 345,
  swell_window_halfwidth_deg = -145,
  wind_offshore_deg = 135,
  preferred_tide_ft_min = 0.8,
  preferred_tide_ft_max = 1.8,
  skill_level = 'expert'
WHERE name ILIKE 'Honolua Bay';


-- Hanalei Bay
UPDATE beaches SET
  swell_window_center_deg = 0,
  swell_window_halfwidth_deg = -142,
  wind_offshore_deg = 155,
  preferred_tide_ft_min = 0.2,
  preferred_tide_ft_max = 1.8,
  break_type = 'point break'
WHERE name ILIKE 'Hanalei Bay';


-- Poipu Beach Park
UPDATE beaches SET
  swell_window_center_deg = 157,
  swell_window_halfwidth_deg = 33,
  wind_offshore_deg = 315,
  preferred_tide_ft_min = 0.1,
  preferred_tide_ft_max = 1.7,
  skill_level = 'intermediate'
WHERE name ILIKE 'Poipu Beach Park';


-- Rockaway Beach
UPDATE beaches SET
  swell_window_center_deg = 135,
  swell_window_halfwidth_deg = 65,
  wind_offshore_deg = 315,
  preferred_tide_ft_min = 0.3,
  preferred_tide_ft_max = 3.5,
  break_type = 'beach break',
  hazards = ARRAY['rip currents', 'rocks', 'water quality', 'localism', 'aggressive locals']
WHERE name ILIKE 'Rockaway Beach';


-- Long Beach
UPDATE beaches SET
  swell_window_center_deg = 145,
  swell_window_halfwidth_deg = 45,
  wind_offshore_deg = 25,
  preferred_tide_ft_min = 0.1,
  preferred_tide_ft_max = 1.5,
  break_type = 'beach break',
  skill_level = 'intermediate'
WHERE name ILIKE 'Long Beach';


-- Montauk
UPDATE beaches SET
  swell_window_center_deg = 155,
  swell_window_halfwidth_deg = 35,
  wind_offshore_deg = 315,
  preferred_tide_ft_min = 0.2,
  preferred_tide_ft_max = 3,
  break_type = 'reef break',
  skill_level = 'expert'
WHERE name ILIKE 'Montauk';


-- Newport
UPDATE beaches SET
  swell_window_center_deg = 135,
  swell_window_halfwidth_deg = 45,
  wind_offshore_deg = 0,
  preferred_tide_ft_min = 0.5,
  preferred_tide_ft_max = 3.8,
  break_type = 'beach break',
  skill_level = 'beginner'
WHERE name ILIKE 'Newport';


-- Wrightsville Beach
UPDATE beaches SET
  swell_window_center_deg = 135,
  swell_window_halfwidth_deg = 68,
  wind_offshore_deg = 315,
  preferred_tide_ft_min = 0.2,
  preferred_tide_ft_max = 5.5,
  break_type = 'beach break'
WHERE name ILIKE 'Wrightsville Beach';


-- Verification
SELECT name, swell_window_center_deg, wind_offshore_deg, preferred_tide_ft_min, preferred_tide_ft_max, break_type, skill_level
FROM beaches
WHERE swell_window_center_deg IS NOT NULL
ORDER BY name;
