-- Add 9 Central Coast & Santa Barbara beaches
-- Includes: Morro Bay, Cayucos, Avila Beach, Big Sur, Monterey Bay, and Santa Barbara spots
-- Safe, idempotent insert using ON CONFLICT

BEGIN;

-- Insert beaches with comprehensive surf data
-- ON CONFLICT on id ensures idempotency
INSERT INTO public.beaches (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private
) VALUES
  -- 1. Morro Rock / Sandspit (inside bend)
  (
    '5c7c2a2e-3c7f-4a8c-8e8a-5cf2e9a0b101',
    'Morro Rock / Sandspit (inside bend)',
    'Morro Bay',
    'CA',
    'USA',
    35.36944,
    -120.86757,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'strong longshore current', 'shorebreak'],
    ARRAY['Parking nearby', 'Beginner friendly on small days', 'Restrooms'],
    235,
    305,
    90,
    35,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 270, "period_s": 12}, "notes": "Pick the inside bend near the rock for softer peaks on W–WNW."}'::jsonb,
    275,
    270,
    35,
    ARRAY[10,11,12,1,2,3],
    'morro-rock-sandspit-inside-bend-morro-bay-ca',
    'Central Coast',
    'Inside Sandspit bend with wrapping peaks and easier channels than the outer bars.',
    'Park by Coleman Park lot near the rock; short walk to inside bend.',
    'Use signed paths; avoid climbing rip-rap.',
    'Sit wide of the main peak and trim to the shoulder.',
    'Spread along the inside bars; avoid the main takeoff pack.',
    'Mid tide, E wind, 3–6 ft W–WNW swell.',
    ARRAY['Harbor currents can be strong', 'Occasional heavy outside sets'],
    'Stay clear of the main outside pack if under-gunned.',
    'medium',
    ARRAY['🅿️ Park by the rock', '🌬️ Early east wind', '🌊 Inside bars are friendlier'],
    false
  ),

  -- 2. Cayucos Pier (south side)
  (
    '1bd1a1f5-5c8a-4607-8d7b-0b8f0d2c9b02',
    'Cayucos Pier (south side)',
    'Cayucos',
    'CA',
    'USA',
    35.447751,
    -120.907126,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'shorebreak'],
    ARRAY['Pier reference', 'Parking', 'Food nearby'],
    240,
    310,
    90,
    35,
    12,
    8,
    1.5,
    4.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 280, "period_s": 11}, "notes": "Defined bars by the pier with easier channels than open Morro Strand."}'::jsonb,
    285,
    275,
    35,
    ARRAY[10,11,12,1,2,3],
    'cayucos-pier-south-cayucos-ca',
    'Central Coast',
    'User-friendly Central Coast beachbreak with consistent bars by the pier.',
    'Street parking near the pier; check signs.',
    'Use stair access south side.',
    'Line up off a pier piling for positioning; watch for sweep.',
    'Walk a block south to find space.',
    'Early E wind, mid tide, peaky WNW.',
    ARRAY['Pilings during strong drift'],
    'Mind anglers and stay clear of the pier zone.',
    'medium',
    ARRAY['📍 Aim off a piling', '🏃 Drift management', '🕘 Morning glass'],
    false
  ),

  -- 3. Avila Beach
  (
    '0e7a0a9f-3a0b-44a2-b81c-43a6f7b2a203',
    'Avila Beach',
    'Avila Beach',
    'CA',
    'USA',
    35.180583,
    -120.731972,
    'beach',
    'beginner',
    ARRAY['shorebreak', 'localized rip currents'],
    ARRAY['Beginner friendly', 'Amenities', 'Parking'],
    160,
    240,
    20,
    40,
    14,
    10,
    2.0,
    5.0,
    '{"tide": "mid-high", "primary_swell": {"dir_deg": 200, "period_s": 12}, "notes": "Smallest option in SLO county when outer beaches are large."}'::jsonb,
    205,
    200,
    40,
    ARRAY[5,6,7,8,9],
    'avila-beach-avila-beach-ca',
    'Central Coast',
    'Sheltered south-facing beach in San Luis Bay with gentle waves.',
    'Downtown lots near the beach; pay kiosks.',
    'Multiple stairways along the promenade.',
    'Look for bars near the piers for shape.',
    'Spread along the promenade blocks.',
    'Light N–E wind, mid to high tide, S–SW swell.',
    ARRAY['Boat traffic near piers'],
    'Give learners space.',
    'medium',
    ARRAY['🧘 Easiest fallback', '🔄 Works when outside is big', '🚗 Easy access'],
    false
  ),

  -- 4. Andrew Molera State Beach (river mouth)
  (
    '3b2d3a98-7c91-4d8a-81a4-6e0d5d2b9a04',
    'Andrew Molera State Beach (river mouth)',
    'Big Sur',
    'CA',
    'USA',
    36.283,
    -121.833,
    'river-mouth',
    'intermediate',
    ARRAY['powerful shorebreak', 'strong currents', 'rocky sections'],
    ARRAY['Scenic', 'Hike-in', 'Multiple peaks'],
    235,
    305,
    70,
    35,
    12,
    8,
    1.5,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 270, "period_s": 13}, "notes": "Longer walls near the rivermouth sandbars when bars are set."}'::jsonb,
    255,
    270,
    35,
    ARRAY[10,11,12,1,2,3],
    'andrew-molera-river-mouth-big-sur-ca',
    'Big Sur',
    'Open-coast Big Sur beach with shifting rivermouth bars and big scenery.',
    'State park lot; walk across the fields and river trail.',
    'Be prepared for river crossing depending on flow.',
    'Hunt for outside bars that taper; avoid closeouts.',
    'Plenty of room to spread; respect locals.',
    'Light E wind, mid tide, mid-period W–WNW swell.',
    ARRAY['Remote setting', 'Cold water', 'Wildlife'],
    'Keep groups small; pack out everything.',
    'low',
    ARRAY['🥾 Walk-in spot', '🌬️ Morning best', '📉 Tide sensitive'],
    false
  ),

  -- 5. Garrapata State Beach (southern coves)
  (
    'f0d0c0d9-6c1a-4d2b-9f4e-9f7bb7b8c205',
    'Garrapata State Beach (southern coves)',
    'Carmel-by-the-Sea',
    'CA',
    'USA',
    36.46833,
    -121.90599,
    'beach',
    'intermediate',
    ARRAY['steep shorebreak', 'hidden rocks', 'strong currents'],
    ARRAY['Multiple coves', 'Parking turnouts'],
    235,
    305,
    80,
    30,
    10,
    8,
    1.0,
    3.5,
    '{"tide": "mid-falling", "primary_swell": {"dir_deg": 270, "period_s": 13}, "notes": "Use coves to trim size and find shape."}'::jsonb,
    260,
    270,
    35,
    ARRAY[10,11,12,1,2,3],
    'garrapata-southern-coves-carmel-ca',
    'Big Sur',
    'Series of coves offering angle variety on open-coast Big Sur.',
    'Highway 1 turnouts; obey signage.',
    'Use signed trails; some steep stairs.',
    'Check several coves; look for tapering shoulders.',
    'Spread across pullouts; keep valuables out of sight.',
    'Early NE wind, mid tide, W–WNW swell.',
    ARRAY['Powerful shorebreak', 'Sneaker sets'],
    'Small groups; be discreet.',
    'low',
    ARRAY['🧭 Coves = size control', '🚶 Short but steep access', '👀 Check a few first'],
    false
  ),

  -- 6. Carmel River State Beach
  (
    'a1a7c2e8-2b3f-4b0d-9a6a-3b9d3b6b6c06',
    'Carmel River State Beach',
    'Carmel-by-the-Sea',
    'CA',
    'USA',
    36.532184,
    -121.926899,
    'river-mouth',
    'lower-intermediate',
    ARRAY['shorebreak', 'strong currents', 'changing bar'],
    ARRAY['Parking', 'Scenic', 'Tide-dependent'],
    170,
    235,
    30,
    40,
    12,
    9,
    2.0,
    5.0,
    '{"tide": "mid-high", "primary_swell": {"dir_deg": 205, "period_s": 12}, "notes": "Sheltered alternative when Big Sur is too big."}'::jsonb,
    205,
    202,
    32,
    ARRAY[5,6,7,8,9],
    'carmel-river-state-beach-carmel-ca',
    'Monterey Bay',
    'South-facing cove with shifting bars at the Carmel River mouth.',
    'Lot at end of Carmelo St.',
    'Short walk from lot; respect protected areas.',
    'Target the rivermouth bars for best shape.',
    'Walk south to thin the crowd.',
    'Light NE wind, mid-high tide, S–SW swell or W wrap.',
    ARRAY['Sudden closeouts', 'River outflow after rains'],
    'Share peaks; many learners.',
    'medium',
    ARRAY['🧭 South-facing shelter', '🚸 Gentler option', '🎯 Rivermouth focus'],
    false
  ),

  -- 7. Campus Point (UCSB)
  (
    '8de2c2cf-2b8d-4a4e-8d5e-3e7b5d5c7d07',
    'Campus Point (UCSB)',
    'Goleta',
    'CA',
    'USA',
    34.405869,
    -119.845558,
    'point',
    'beginner',
    ARRAY['reef/rock inside', 'longboard traffic'],
    ARRAY['Long rides', 'Parking structures nearby', 'Campus scenery'],
    170,
    220,
    10,
    45,
    14,
    10,
    2.0,
    4.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 195, "period_s": 14}, "notes": "Wraps south swells best; also gets selective WNW wrap."}'::jsonb,
    205,
    195,
    25,
    ARRAY[5,6,7,8,9],
    'campus-point-ucsb-goleta-ca',
    'Santa Barbara',
    'Right point with long, soft walls. Best on souths; fun on clean winter wrap.',
    'Use campus structures; walk paths to the point.',
    'Cliff paths; mind tides at the base.',
    'Sit wide, fade takeoff, trim high.',
    'Share waves; many learners and logs.',
    'Light N–E wind, mid tide, S–SSW swell or clean W wrap.',
    ARRAY['Reef at inside', 'Crowded on weekends'],
    'Yield to people already riding; smile and rotate.',
    'high',
    ARRAY['🛹 Longboard heaven', '🕘 Best mornings', '📐 Fade takeoffs'],
    false
  ),

  -- 8. Devereux / Sands (Coal Oil Point)
  (
    'f7fbc2c4-7c4e-4c2c-8f8a-5e3bd1ee8e08',
    'Devereux / Sands (Coal Oil Point)',
    'Isla Vista',
    'CA',
    'USA',
    34.411227,
    -119.87688,
    'beach',
    'lower-intermediate',
    ARRAY['reef patches', 'shorebreak', 'wildlife closures at times'],
    ARRAY['Multiple peaks', 'Trails access'],
    230,
    300,
    30,
    40,
    14,
    10,
    1.5,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 270, "period_s": 12}, "notes": "More exposed than Campus; picks up wrap and NW wind swell."}'::jsonb,
    260,
    265,
    35,
    ARRAY[10,11,12,1,2,3,5,6,7,8,9],
    'devereux-sands-isla-vista-ca',
    'Santa Barbara',
    'Open pocket west of Campus with peaky beach/reef setups.',
    'Street parking near Camino Majorca; respect neighborhoods.',
    'Trail network to beach; avoid signed closures.',
    'Look for sand-reef corners that taper.',
    'Walk north toward Sands to thin the pack.',
    'Light NE wind, mid tide, W wrap or local NW.',
    ARRAY['Kelp', 'Occasional closures for nesting plovers'],
    'Respect protected areas; pack out trash.',
    'medium',
    ARRAY['🚶 Walk to find bars', '🌿 Mind closures', '🌊 Catches more swell'],
    false
  ),

  -- 9. Leadbetter
  (
    'e0dd3e3a-1a9e-4b7d-8c55-2d3b6f9b7f09',
    'Leadbetter',
    'Santa Barbara',
    'CA',
    'USA',
    34.40091,
    -119.69731,
    'point',
    'beginner',
    ARRAY['reef patches', 'longboard traffic'],
    ARRAY['Longboard friendly', 'Harbor-adjacent', 'Amenities'],
    150,
    210,
    20,
    45,
    12,
    9,
    2.0,
    5.0,
    '{"tide": "mid-high", "primary_swell": {"dir_deg": 185, "period_s": 14}, "notes": "Small, soft rights; best on souths, tiny on winter WNW."}'::jsonb,
    160,
    180,
    30,
    ARRAY[5,6,7,8,9],
    'leadbetter-santa-barbara-ca',
    'Santa Barbara',
    'Soft point/inside reef near the harbor with longboard-friendly lines.',
    'Lots along Shoreline Dr by the beach.',
    'Short walk from lot; easy launch.',
    'Wide takeoffs; trim and connect sections.',
    'Share and rotate; heavy with logs when it''s on.',
    'Light N–E wind, mid-high tide, S swell.',
    ARRAY['Boat traffic near harbor', 'Kelp'],
    'Respect learners; no snaking.',
    'high',
    ARRAY['🪵 Bring a log or fish', '🧑‍🎓 Many learners', '🕘 Best mornings'],
    false
  )

ON CONFLICT (id) DO NOTHING;

-- Note: geog is a generated column and will be automatically populated
-- from lat/lon coordinates during INSERT. No manual UPDATE needed.

COMMIT;
