-- Add 13 SoCal beaches: San Diego, Orange County, Los Angeles
-- Safe, idempotent insert using ON CONFLICT

BEGIN;

INSERT INTO public.beaches (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private
) VALUES
  -- 1. Big Rock (La Jolla)
  (
    'dbbafa09-3143-4f73-82e8-90a69a4121f5',
    'Big Rock',
    'La Jolla',
    'CA',
    'USA',
    32.8066,
    -117.2787,
    'reef',
    'advanced',
    ARRAY['rip currents', 'rocks', 'shallow reef', 'localism', 'strong currents'],
    ARRAY['Street parking', 'Consistent waves', 'Beautiful scenery'],
    200,
    310,
    90,
    35,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 270, "period_s": 12}, "notes": "Needs a solid west swell and light east winds to break perfectly."}'::jsonb,
    270,
    255,
    55,
    ARRAY[10,11,12,1,2,3],
    'big-rock-la-jolla-ca',
    'San Diego',
    'Big Rock is a heavy, hollow left-hand reef break at the foot of Palomar Avenue. It produces fast stand-up barrels on west swells and is best suited to advanced surfers due to the very shallow reef and powerful waves.',
    'Limited street parking along Palomar Avenue; arrive early or park in nearby neighborhoods and walk down.',
    'Walk down Palomar Ave to the bluff and scramble over the rocks. Enter the water to the left of the big rock and time your jump between sets.',
    'Sit deep near the reef and look for the west sets that throw hollow lefts. Watch for boils indicating shallow spots.',
    'Can be crowded when it''s working; respect locals and wait your turn. Off-season days are quieter.',
    'Mid tide with an east wind and 4–8 ft W–WNW swell.',
    ARRAY['Shallow reef', 'Strong rip currents', 'Localism'],
    'Respect the locals and take turns. Don''t paddle straight out into the lineup on big days.',
    'high',
    ARRAY['🅿️ Limited parking on Palomar Ave', '🌬️ Needs light E wind', '🌊 Hollow left barrels over shallow reef'],
    false
  ),

  -- 2. Sunset Cliffs – Garbage
  (
    'b939f928-2653-494a-831d-6394cb548190',
    'Sunset Cliffs – Garbage',
    'San Diego',
    'CA',
    'USA',
    32.7169,
    -117.2549,
    'reef',
    'upper-intermediate',
    ARRAY['rocks', 'urchins', 'rip currents', 'localism', 'pollution', 'shorebreak'],
    ARRAY['Free parking', 'Tide pools', 'Scenic cliffs'],
    200,
    300,
    90,
    35,
    12,
    8,
    0.5,
    3.0,
    '{"tide": "low", "primary_swell": {"dir_deg": 275, "period_s": 13}, "notes": "Needs a west–northwest swell and light easterly wind; avoid high tide when it shuts down."}'::jsonb,
    260,
    250,
    50,
    ARRAY[10,11,12,1,2,3],
    'sunset-cliffs-garbage-san-diego-ca',
    'San Diego',
    'Garbage at Sunset Cliffs is an exposed reef with left and right peaks. It lights up during winter west and northwest swells and is best surfed at low to mid tide. Access involves scrambling down a cliff to a rocky beach; the wave is powerful with strong currents and is better for experienced surfers.',
    'Two small parking lots and street parking near Sunset Cliffs Boulevard and Ladera Street; expect crowds on big winter swells.',
    'Take the metal staircase for North Garbage or use the rope-assisted path from the dirt lot for South Garbage. Carefully climb down the sandstone cliff and time your entry between sets.',
    'Position yourself near the reef for the steepest take-offs; aim for the outside peaks that wrap into the cove. At low tide the wave gets hollow and fast.',
    'Moderately crowded due to difficult access; respect locals and spread out between North and South peaks to find space.',
    'Low tide, light easterly wind, 4–8 ft W–NW swell.',
    ARRAY['Rocks', 'Shallow reef', 'Rip currents', 'Localism'],
    'Mind the jump-offs and exits and allow locals priority. Leave no trash in the natural park.',
    'medium',
    ARRAY['🅿️ Park at Ladera St or dirt lot', '🌬️ Light E winds work best', '🌊 Hollow peaks at low tide'],
    false
  ),

  -- 3. Sunset Cliffs – Luscombs
  (
    '34af0af5-b61c-4b86-9d9d-bf328f538a12',
    'Sunset Cliffs – Luscombs',
    'San Diego',
    'CA',
    'USA',
    32.7176,
    -117.2562,
    'reef',
    'advanced',
    ARRAY['rocks', 'urchins', 'rip currents', 'localism', 'shorebreak'],
    ARRAY['Parking nearby', 'Scenic views', 'Raw surf'],
    200,
    300,
    90,
    35,
    12,
    8,
    0.5,
    3.0,
    '{"tide": "low", "primary_swell": {"dir_deg": 275, "period_s": 13}, "notes": "Best on solid west swells and light easterly winds; high tide swamps it out."}'::jsonb,
    250,
    250,
    50,
    ARRAY[10,11,12,1,2,3],
    'sunset-cliffs-luscombs-san-diego-ca',
    'San Diego',
    'Luscombs Point is a left-handing reef at Sunset Cliffs that produces long, powerful walls during west swells. Access is via a fenced point where surfers climb down the rocks and jump off a ledge; timing your entry with the incoming waves is critical. The wave is fast and shallow, so it''s suited to advanced surfers.',
    'Limited street parking along Sunset Cliffs Boulevard near the metal cage; arrive early on swell days.',
    'Walk to the point, climb down onto the ledge near the metal cage and jump into the surf between sets. Be prepared to scramble up slick rocks on exit.',
    'Sit deep on the point and watch for the set waves that wrap into the reef. Paddle hard to catch the fast take-off and stay high on the wall to make sections.',
    'Crowded on big winter swells; locals have priority. Watch the line-up and be patient.',
    'Low to mid tide, light east wind, 5–8 ft W–NW swell.',
    ARRAY['Sharp rocks', 'Shallow reef', 'Strong currents', 'Localism'],
    'Wait your turn on the ledge and don''t drop in on the locals; keep noise down for neighborhood residents.',
    'high',
    ARRAY['🅿️ Limited street parking', '🌬️ Needs easterly winds', '🌊 Long left walls require commitment'],
    false
  ),

  -- 4. Shipwrecks (Coronado)
  (
    '5e8d07ff-786c-4b7e-ab19-53d2b3774e23',
    'Shipwrecks',
    'Coronado',
    'CA',
    'USA',
    32.6763,
    -117.1896,
    'beach',
    'intermediate',
    ARRAY['rip currents', 'shallow sandbars', 'strong currents', 'man-made hazards'],
    ARRAY['Parking nearby', 'Wide beach', 'Lifeguards (seasonal)'],
    180,
    240,
    0,
    30,
    12,
    8,
    2.0,
    5.0,
    '{"tide": "mid-high", "primary_swell": {"dir_deg": 220, "period_s": 12}, "notes": "Best on SW swells with light offshore winds; avoid low tide when the wreck is exposed."}'::jsonb,
    220,
    210,
    30,
    ARRAY[5,6,7,8,9],
    'shipwrecks-coronado-ca',
    'San Diego',
    'Shipwrecks is the stretch of Coronado Beach near the visible remains of the SS Monte Carlo. This exposed beach break can deliver peaky lefts and rights during south-west swells and is generally more mellow than neighboring peaks. Be aware of deep holes and strong currents around the wreck, and avoid climbing on the slippery, rusting metal.',
    'Park along Ocean Boulevard or in the nearby residential area; walk down beach access points toward the visible shipwreck.',
    'Walk along the beach to the shipwreck area. At low tide, parts of the wreck are exposed; at high tide, currents swirl around it.',
    'Look for sandbars that form near the wreck which produce punchy peaks. Surf on a rising tide for more power.',
    'Usually uncrowded, though curious visitors can wander near the wreck. Respect lifeguards and avoid climbing on the wreck.',
    'High-tide rising with light north wind and 3–5 ft SW swell.',
    ARRAY['Deep holes around the wreck', 'Strong currents', 'Rusting metal hazards'],
    'Stay off the wreck; heed lifeguard warnings and keep a safe distance from swimmers.',
    'low',
    ARRAY['🅿️ Easy street parking', '🌬️ Light N winds preferred', '🌊 Avoid currents swirling around the shipwreck'],
    false
  ),

  -- 5. 54th Street (Newport Beach)
  (
    'da8ad733-8e6b-4781-8b3f-0fe4ee492c3f',
    '54th Street',
    'Newport Beach',
    'CA',
    'USA',
    33.6135,
    -117.932,
    'beach',
    'lower-intermediate',
    ARRAY['crowded', 'shorebreak', 'rip currents'],
    ARRAY['Street parking', 'Restrooms', 'Showers'],
    200,
    310,
    90,
    40,
    15,
    10,
    1.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 250, "period_s": 12}, "notes": "Performs best on combo W–SW swells and light offshore winds; mid tide gives the best shape."}'::jsonb,
    260,
    255,
    55,
    ARRAY[9,10,11,12,1,2],
    '54th-street-newport-beach-ca',
    'Orange County',
    'Newport''s 54th Street is a high-performance beach break created by man-made jetties. It offers peaky lefts and rights over a sandy bottom and attracts some of the best local surfers. The wave works on most tides but is best at mid tide and can get very crowded.',
    'Parking along Seashore Drive and side streets; arrive early, especially during summer and weekends.',
    'Easy beach access down the jetties or through public walkways. Watch for slippery rocks when crossing the jetty.',
    'Position near the jetties for the most consistent peaks. Look for wedging right/left peaks that reform and allow for turns and airs.',
    'Often packed with talented locals. Show respect and wait your turn. Surf early mornings for smaller crowds.',
    'Mid tide, light E wind, 3–6 ft W–SW swell.',
    ARRAY['Shorebreak', 'Rip currents', 'Crowds'],
    'Follow local rules, don''t snake or drop in. Share waves and be patient.',
    'high',
    ARRAY['🅿️ Street parking on Seashore Dr', '🌬️ Light E winds ideal', '🌊 Peaky jetties produce high-performance waves'],
    false
  ),

  -- 6. 52nd Street (Newport Beach)
  (
    '1207215c-f61d-4fe1-bbaa-a3db7d4e7d53',
    '52nd Street',
    'Newport Beach',
    'CA',
    'USA',
    33.615,
    -117.934,
    'beach',
    'intermediate',
    ARRAY['shorebreak', 'rip currents', 'crowded'],
    ARRAY['Street parking', 'Restrooms', 'Lifeguards'],
    200,
    310,
    90,
    40,
    15,
    10,
    1.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 250, "period_s": 13}, "notes": "Needs a solid W–SW swell and mid tide; avoid low tide when it closes out."}'::jsonb,
    260,
    255,
    55,
    ARRAY[9,10,11,12,1,2],
    '52nd-street-newport-beach-ca',
    'Orange County',
    'Just north of 54th, 52nd Street serves up slightly bigger, more walled waves that require quick take-offs. The sandy bottom and jetty setup create long walls that are great for experienced surfers who like to race down the line. It works at mid tide and tends to close out on lower tides.',
    'Park along Seashore Drive or Balboa Boulevard; the closer you get to 52nd the busier it gets.',
    'Access via public beach paths; cross the jetty carefully and watch for incoming sets.',
    'Sit a bit further out to catch the bigger sets. Aim for the corners of the peaks to get open face before the wave walls up.',
    'Often busy, though slightly less than 54th. Early mornings or weekdays offer more room.',
    'Mid tide, light E wind, 3–7 ft W–SW swell.',
    ARRAY['Heavy shorebreak', 'Rip currents', 'Crowds'],
    'Respect locals and spread out along the beach; take turns and don''t block the inside.',
    'high',
    ARRAY['🅿️ Park on Seashore Dr', '🌬️ Best with light E winds', '🌊 Longer, more walled waves than 54th'],
    false
  ),

  -- 7. Venice Breakwater
  (
    '96fd7011-b894-4776-a68d-ff16fb1985d8',
    'Venice Breakwater',
    'Los Angeles',
    'CA',
    'USA',
    33.985,
    -118.4749,
    'breakwater',
    'intermediate',
    ARRAY['rocks', 'rip currents', 'localism'],
    ARRAY['Parking nearby', 'Restrooms', 'Lifeguards', 'Boardwalk amenities'],
    220,
    300,
    45,
    35,
    12,
    8,
    0.5,
    3.0,
    '{"tide": "low", "primary_swell": {"dir_deg": 280, "period_s": 12}, "notes": "Works best on west-northwest swells and light NE winds; avoid high tide when it shuts down."}'::jsonb,
    270,
    260,
    40,
    ARRAY[10,11,12,1,2,3],
    'venice-breakwater-los-angeles-ca',
    'Los Angeles',
    'The Venice Breakwater is a hollow and powerful sandbar/jetty break that produces lefts and rights over a sandy bottom. It needs a solid west or northwest swell and offshore northeast wind to break cleanly. Strong currents around the jetty and a competitive local scene make it better for intermediate surfers.',
    'Park at the public lots off Venice Boulevard or use metered street parking; expect fees and crowds.',
    'Walk along the boardwalk and enter the water near the jetty; watch for slippery rocks around the breakwater.',
    'Sit near the wedge where the jetty reflects incoming swells to form hollow peaks. Paddle hard to make the drop and stay ahead of the section.',
    'Very crowded, especially weekends. Respect the locals and spread down the beach if the main peak is packed.',
    'Low tide with NE offshore wind and 4–8 ft W–NW swell.',
    ARRAY['Rocks around jetty', 'Rip currents', 'Localism'],
    'Be courteous and wait your turn at the main peak. Avoid climbing on the breakwater and respect the busy boardwalk area.',
    'high',
    ARRAY['🅿️ Paid lots off Venice Blvd', '🌬️ Needs NE offshore wind', '🌊 Hollow peaks form off the jetty'],
    false
  ),

  -- 8. El Segundo Beach Jetty
  (
    'be03bc6f-878a-4806-bff2-9cf870a9f241',
    'El Segundo Beach Jetty',
    'El Segundo',
    'CA',
    'USA',
    33.9195,
    -118.4165,
    'breakwater',
    'intermediate',
    ARRAY['man-made hazards', 'pollution', 'rip currents'],
    ARRAY['Parking nearby', 'Restrooms', 'Lifeguards'],
    200,
    300,
    45,
    35,
    12,
    8,
    1.0,
    3.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 220, "period_s": 12}, "notes": "Needs southwest swells and NE winds; avoid onshore winds that blow it out."}'::jsonb,
    260,
    250,
    50,
    ARRAY[6,7,8,9,10],
    'el-segundo-beach-jetty-el-segundo-ca',
    'Los Angeles',
    'The El Segundo Jetty is a reliable breakwater break just south of LAX. It picks up southwest swells and offers lefts and rights. Summer brings the most consistent surf, and the best conditions occur when a southwest swell meets a northeast offshore wind. The surf is rarely crowded but pollution and man-made obstacles can be issues.',
    'Parking along Grand Avenue or in nearby beach lots. Be mindful of parking restrictions near the Chevron facility.',
    'Walk down the beach path to the jetty; avoid the restricted areas near the industrial facilities.',
    'Sit near the jetty where the swell refracts to form peaks. Look for lefts wrapping into the beach and rights running alongside the jetty.',
    'Usually uncrowded; share waves with the small local crew and watch out for fishermen on the jetty.',
    'Mid tide, light NE wind, 3–6 ft SW swell.',
    ARRAY['Pollution', 'Man-made hazards', 'Rip currents'],
    'Respect the industrial area and don''t trespass on restricted property. Pack out all trash.',
    'low',
    ARRAY['🅿️ Parking on Grand Ave', '🌬️ Light NE winds ideal', '🌊 Lefts and rights wrap off the jetty'],
    false
  ),

  -- 9. Manhattan Beach Pier
  (
    '7a093b7e-2230-4bf1-abeb-9b31faa794d5',
    'Manhattan Beach Pier',
    'Manhattan Beach',
    'CA',
    'USA',
    33.8841,
    -118.4109,
    'beach',
    'intermediate',
    ARRAY['rip currents', 'crowds', 'shorebreak'],
    ARRAY['Parking nearby', 'Pier amenities', 'Lifeguards'],
    200,
    300,
    90,
    35,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 220, "period_s": 12}, "notes": "Performs best on SW swells with light E winds; avoid high tide when waves get mushy."}'::jsonb,
    270,
    250,
    50,
    ARRAY[6,7,8,9],
    'manhattan-beach-pier-manhattan-beach-ca',
    'Los Angeles',
    'The sandbars north and south of Manhattan Beach Pier provide consistent beach-break peaks with both lefts and rights. Summer southwest swells and offshore east winds create the best conditions. The waves can be fun for intermediates but rips are common and the lineup is often crowded.',
    'Use the pier parking lots or street parking along Manhattan Beach Boulevard; pay attention to time limits.',
    'Walk down the pier or beach paths to the sand; choose a sandbar north or south of the pier depending on the crowd.',
    'Watch the sets to see where the sandbars are breaking; position for peaks that offer open faces. Paddle wide to avoid rip currents.',
    'High crowds, especially in summer. Surf early mornings or weekdays for lighter crowds.',
    'Mid tide, light east wind, 3–6 ft SW swell.',
    ARRAY['Rip currents', 'Crowds', 'Shorebreak'],
    'Follow standard surf etiquette and be courteous to swimmers and anglers on the pier.',
    'high',
    ARRAY['🅿️ Paid parking at the pier', '🌬️ Light E winds are best', '🌊 Consistent peaks north and south of the pier'],
    false
  ),

  -- 10. Redondo Breakwall
  (
    '13a91b0d-3e80-4140-b11e-2c1b12e00687',
    'Redondo Breakwall',
    'Redondo Beach',
    'CA',
    'USA',
    33.8495,
    -118.4041,
    'breakwater',
    'advanced',
    ARRAY['strong currents', 'localism', 'heavy waves'],
    ARRAY['Parking nearby', 'Harbor facilities'],
    260,
    320,
    45,
    35,
    15,
    10,
    0.5,
    3.0,
    '{"tide": "low", "primary_swell": {"dir_deg": 300, "period_s": 14}, "notes": "Best on big NW swells and low tide; avoid when small or onshore winds prevail."}'::jsonb,
    290,
    290,
    30,
    ARRAY[11,12,1,2,3],
    'redondo-breakwall-redondo-beach-ca',
    'Los Angeles',
    'The Redondo Breakwall is a regional classic that breaks along the King Harbor breakwater. When it''s big and working, it produces a fast, walled left over a sandy bottom. This spot is reserved for advanced surfers, as strong currents and powerful waves make it hazardous. It comes alive on large north and west swells and is usually surfed during winter.',
    'Park in the King Harbor lots or along Harbor Drive; be prepared to walk along the breakwall to check the surf.',
    'Enter the water from the beach near the breakwall and paddle around the end; watch for strong currents pulling toward the harbor entrance.',
    'Sit deep near the breakwall to catch the long lefts that run down the wall. Use a step-up board to handle the power.',
    'Busy when large swells hit; heavy localism and experienced chargers dominate. Spectate before paddling out.',
    'Low tide, light NE wind, 8–12 ft NW swell.',
    ARRAY['Powerful waves', 'Strong currents', 'Localism'],
    'Only experienced surfers should paddle out; respect the locals and the harbor rules.',
    'medium',
    ARRAY['🅿️ Harbor parking', '🌬️ Needs NE winds', '🌊 Fast, walled lefts off the breakwall'],
    false
  ),

  -- 11. Topanga
  (
    '101bd2f7-e1dc-4940-b4e3-3a820d5940dd',
    'Topanga',
    'Malibu',
    'CA',
    'USA',
    34.0395,
    -118.597,
    'point',
    'intermediate',
    ARRAY['rocks', 'shallow reef', 'crowds', 'localism'],
    ARRAY['Parking lot', 'Restrooms', 'Showers', 'Scenic canyon'],
    200,
    300,
    0,
    45,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 255, "period_s": 13}, "notes": "Works on both SW and NW swells; mid tide and light north winds produce the best shape."}'::jsonb,
    260,
    250,
    50,
    ARRAY[6,7,8,9,10],
    'topanga-malibu-ca',
    'Los Angeles',
    'Topanga Point is a right-hand point break over a cobble and sand bottom interspersed with rocks. The wave can be hollow and fast, offering fun rides for all levels, though beginners should be cautious at low tide. It works on most tides and picks up both south and northwest swells. Crowds and passionate locals are the norm.',
    'There is a pay parking lot on the ocean side of PCH and limited roadside parking on Topanga Canyon Boulevard; bring cash for parking.',
    'Walk from the parking area down to the beach and paddle around the point. Wear booties if the cobbles hurt your feet.',
    'Sit near the top of the point for the longest rides. Set waves swing wide and offer hollow sections; stay high on the face to make sections.',
    'Expect crowds and vocal locals. Surf early mornings or weekdays to find space, and be polite in the lineup.',
    'Mid tide, light N wind, 3–6 ft W–SW swell.',
    ARRAY['Rocks', 'Shallow reef', 'Crowds', 'Localism'],
    'Follow point-break etiquette, wait your turn, and don''t snake. Avoid dropping in on long rides.',
    'high',
    ARRAY['🅿️ Paid lot or roadside parking', '🌬️ Favors light N winds', '🌊 Right-hand point break with long rides'],
    false
  ),

  -- 12. County Line
  (
    '71bdbe5a-67f6-429c-b1e4-80ec390ec4a3',
    'County Line',
    'Malibu',
    'CA',
    'USA',
    34.0461,
    -118.9639,
    'point',
    'intermediate',
    ARRAY['strong currents', 'rip currents', 'rocks'],
    ARRAY['Free parking', 'Restrooms', 'Nearby restaurant'],
    200,
    300,
    0,
    40,
    12,
    8,
    1.0,
    4.0,
    '{"tide": "mid", "primary_swell": {"dir_deg": 260, "period_s": 12}, "notes": "Works on SW and W swells; mid tide and light north winds give the best shape."}'::jsonb,
    260,
    250,
    50,
    ARRAY[6,7,8,9,10,11],
    'county-line-malibu-ca',
    'Los Angeles',
    'County Line, on the border of LA and Ventura counties, features a right-hand cobblestone reef break at the northern end and 500 yards of beach break to the south. Conditions range from peaky lefts and rights to heavy closeouts. On larger swells, currents and rips become strong and the point turns into an advanced wave.',
    'Free parking is available on both sides of the Pacific Coast Highway near Neptune''s Net; arrive early on weekends.',
    'Paddle out from the beach near the point or along the shore for the beach break. Watch for submerged rocks at low tide.',
    'Choose between the long right off the point or the peaky beach breaks to the south. On bigger swells, sit wider to avoid getting caught inside.',
    'Medium crowds; a mix of longboarders and shortboarders. Spread along the beach to find space.',
    'Mid tide, light N wind, 4–8 ft W–SW swell.',
    ARRAY['Strong rip currents', 'Rocks', 'Powerful waves on big swells'],
    'Respect the lineup and take turns. Beginners should avoid the point on big days and surf the beach break instead.',
    'medium',
    ARRAY['🅿️ Free parking near Neptune''s Net', '🌬️ Best with light N winds', '🌊 Right-hand point and peaky beach break'],
    false
  ),

  -- 13. Zuma Beach
  (
    '836f218a-9471-46c9-b201-24da1dfe0f3a',
    'Zuma Beach',
    'Malibu',
    'CA',
    'USA',
    34.0225,
    -118.8234,
    'beach',
    'beginner',
    ARRAY['rip currents', 'shorebreak', 'closeouts'],
    ARRAY['Large parking lot', 'Restrooms', 'Showers', 'Lifeguards'],
    200,
    300,
    45,
    40,
    12,
    8,
    1.0,
    3.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 250, "period_s": 11}, "notes": "Performs best with SW to W swells and light offshore winds; mid tide provides clean shape."}'::jsonb,
    260,
    250,
    50,
    ARRAY[5,6,7,8,9],
    'zuma-beach-malibu-ca',
    'Los Angeles',
    'Zuma Beach is a long, wide stretch of sand with multiple peaks that break over a sandy bottom. The beach offers consistent, forgiving waves that suit beginners on smaller days and transforms into a powerful shorepound during big winter swells. On any given day you''ll find peaks breaking left and right, with plenty of room to spread out.',
    'Ample paid parking in large county lots along Zuma Beach. Arrive early on summer weekends as the lot fills quickly.',
    'Easy access directly from the parking lot to the sand. Pick a peak and paddle out between sets.',
    'Look for sandbars that create clean peaks. For beginners, surf inside reforms; for experienced surfers, chase the outside sets during a combo swell.',
    'Zuma''s long beach disperses crowds, but the central peaks near lifeguard towers are busier. Walk north or south for more space.',
    'Mid tide, light NE wind, 2–5 ft SW–W swell.',
    ARRAY['Rip currents', 'Heavy shorebreak on big days', 'Closeouts'],
    'Share waves and be mindful of swimmers. Respect lifeguard directions.',
    'medium',
    ARRAY['🅿️ Huge parking lots', '🌬️ Light NE winds ideal', '🌊 Multiple peaks good for all levels'],
    false
  )

ON CONFLICT (id) DO NOTHING;

COMMIT;

