-- Add La Pozita as a local-name El Cocal sub-break.

BEGIN;

WITH new_spots (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  alt_names,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preferred_tide_direction,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  timezone,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private,
  cdip_eligible
) AS (
  VALUES
    (
      'd43d6f41-1458-4141-b11e-837760e8b14c'::uuid,
      'La Pozita',
      'Yabucoa',
      'PR',
      'USA',
      18.0158,
      -65.8444,
      ARRAY['La Posita', 'La Pocita', 'La Posita El Cocal', 'La Pocita El Cocal']::text[],
      'reef',
      'intermediate',
      ARRAY['rocks', 'sea urchins', 'rip currents', 'no lifeguard', 'local knowledge needed']::text[],
      ARRAY['local El Cocal sub-break', 'more organized sets', 'less shorebreak than main El Cocal', 'natural pool nearby', 'rocky shoreline']::text[],
      125,
      170,
      300,
      45,
      12,
      10,
      0.5,
      2.0,
      'either',
      '{"tide": "mid", "data_confidence": "local-research-only", "primary_swell": {"dir_deg": 145, "period_s": 9}, "notes": "Local feedback describes La Pozita as the north-side El Cocal option with more organized sets and less shorebreak. Public beach listings usually map La Posita / La Pocita as part of Playa El Cocal."}'::jsonb,
      135,
      145,
      25,
      ARRAY[12, 1, 2, 3, 4],
      'la-pozita-yabucoa-pr',
      'Southeast Puerto Rico',
      'America/Puerto_Rico',
      'La Pozita is the local-name north-side El Cocal sub-break in Camino Nuevo, Yabucoa. Public beach sources generally describe La Posita or La Pocita as the semi-protected rocky pocket at Playa El Cocal rather than a standalone surf guide spot. Quiver lists it separately because local feedback says the sets can be more organized and less shorebreak-heavy than main El Cocal, while keeping it in the intermediate, local-knowledge-dependent bucket.',
      'Use the same El Cocal / Playa El Guano access and park fully clear of the narrow local roads. Arrive early on weekends and avoid blocking neighborhood or beach-club access.',
      'Start from the El Cocal beach access, then confirm the north-side lineup from shore before entering. Keep the entry conservative and avoid paddling out when the reef or current is unclear.',
      'Look for clean south to southeast swell with light west-northwest to northwest wind. Choose the organized sets away from swimmers near the natural pool, and skip the spot when rocks, current, or shorebreak make the entry unclear.',
      'Usually quieter than headline Puerto Rico surf breaks, but the usable takeoff can be small. Give local surfers priority and keep plenty of room around families using the protected pool.',
      'South to southeast swell, light west-northwest wind, and mid tide are the starting read. Stay conservative when rocks, current, or shorebreak make the entry unclear.',
      ARRAY['No lifeguard coverage', 'Rocky shoreline and sea urchin risk', 'Rip currents can develop around reef and rock structure', 'Swimmers may be near the natural pool']::text[],
      'Treat La Pozita as a local sub-break, not a new discovery. Ask before paddling into the deepest peak, avoid crowding the small lineup, and keep clear of swimmers in the protected pocket.',
      'low',
      ARRAY['Local-name spot near the north side of El Cocal', 'Seeded from public research plus local feedback', 'Intermediate rocky sub-break, not a beginner swim-beach call']::text[],
      false,
      false
    )
)
INSERT INTO public.beaches (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  alt_names,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preferred_tide_direction,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  timezone,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private,
  cdip_eligible
)
SELECT
  spot.id,
  spot.name,
  spot.city,
  spot.state,
  spot.country,
  spot.lat,
  spot.lon,
  spot.alt_names,
  spot.break_type,
  spot.skill_level,
  spot.hazards,
  spot.features,
  spot.swell_window_min_deg,
  spot.swell_window_max_deg,
  spot.wind_offshore_deg,
  spot.wind_offshore_tol_deg,
  spot.wind_cross_shore_ok_kt,
  spot.wind_onshore_bad_kt,
  spot.preferred_tide_ft_min,
  spot.preferred_tide_ft_max,
  spot.preferred_tide_direction,
  spot.preference_model,
  spot.aspect_deg,
  spot.swell_window_center_deg,
  spot.swell_window_halfwidth_deg,
  spot.best_months,
  spot.slug,
  spot.region,
  spot.timezone,
  spot.description,
  spot.parking_tips,
  spot.access_tips,
  spot.wave_tips,
  spot.crowd_tips,
  spot.best_conditions_prose,
  spot.warnings,
  spot.local_etiquette,
  spot.crowd_level,
  spot.real_takeaways,
  spot.is_private,
  spot.cdip_eligible
FROM new_spots AS spot
WHERE NOT EXISTS (
  SELECT 1
  FROM public.beaches AS existing
  WHERE existing.state = spot.state
    AND existing.city = spot.city
    AND existing.slug = spot.slug
    AND existing.deleted_at IS NULL
);

WITH photo_candidates (
  slug,
  city,
  state,
  source_id,
  image_url,
  thumb_url,
  title,
  creator_name,
  creator_url,
  license_code,
  license_url,
  attribution_html
) AS (
  VALUES
    (
      'la-pozita-yabucoa-pr',
      'Yabucoa',
      'PR',
      'File:El Guano Beach in Camino Nuevo, Yabucoa, Puerto Rico.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/d/db/El_Guano_Beach_in_Camino_Nuevo%2C_Yabucoa%2C_Puerto_Rico.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/El_Guano_Beach_in_Camino_Nuevo%2C_Yabucoa%2C_Puerto_Rico.jpg/1280px-El_Guano_Beach_in_Camino_Nuevo%2C_Yabucoa%2C_Puerto_Rico.jpg',
      'El Guano Beach in Camino Nuevo, Yabucoa, Puerto Rico',
      'Winifredo Torres',
      'https://www.flickr.com/photos/182176701@N03/',
      'CC BY-SA 2.0',
      'https://creativecommons.org/licenses/by-sa/2.0/',
      'Representative El Cocal-area photo by Winifredo Torres, licensed CC BY-SA 2.0 via Wikimedia Commons.'
    )
)
INSERT INTO public.beach_photos (
  beach_id,
  source,
  source_id,
  image_url,
  thumb_url,
  title,
  creator_name,
  creator_url,
  license_code,
  license_url,
  attribution_html,
  approved,
  deleted_at
)
SELECT
  b.id,
  'wikimedia',
  photo.source_id,
  photo.image_url,
  photo.thumb_url,
  photo.title,
  photo.creator_name,
  photo.creator_url,
  photo.license_code,
  photo.license_url,
  photo.attribution_html,
  true,
  NULL::timestamptz
FROM photo_candidates AS photo
JOIN public.beaches AS b
  ON b.slug = photo.slug
  AND b.city = photo.city
  AND b.state = photo.state
  AND b.deleted_at IS NULL
ON CONFLICT (beach_id, source, source_id)
DO UPDATE SET
  image_url = EXCLUDED.image_url,
  thumb_url = EXCLUDED.thumb_url,
  title = EXCLUDED.title,
  creator_name = EXCLUDED.creator_name,
  creator_url = EXCLUDED.creator_url,
  license_code = EXCLUDED.license_code,
  license_url = EXCLUDED.license_url,
  attribution_html = EXCLUDED.attribution_html,
  approved = true,
  deleted_at = NULL,
  fetched_at = now();

COMMIT;
