BEGIN;

INSERT INTO public.beaches (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private
) VALUES
  (
    '22696f11-3897-4fa6-b266-2f52dae4d5ac',
    'Robert Moses State Park',
    'Babylon',
    'NY',
    'USA',
    40.6231559,
    -73.2598405,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'shorebreak', 'sweep', 'crowds'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Boardwalk access', 'Long paddling lanes', 'Beginner friendly on small days'],
    90,
    190,
    300,
    45,
    12,
    8,
    0.5,
    4.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 140, "period_s": 9}, "notes": "Robert Moses is a cleaner self-practice Long Island option when south swell stays modest and north-to-northwest wind keeps the beach organized."}'::jsonb,
    120,
    140,
    50,
    ARRAY[8,9,10,11,2,3],
    'robert-moses-state-park-babylon-ny',
    'Long Island',
    'Robert Moses State Park is a long exposed South Shore beach with multiple field entrances and enough open sand to spread out on smaller days. It is still an Atlantic beachbreak with sweep and shorebreak, but on cleaner modest swell it offers a more straightforward practice zone than the more crowded city-beach alternatives.',
    'Field lots and park fees apply in season; arrive early because summer traffic stacks up before the lot and the easiest spaces go first.',
    'Use the marked boardwalk and beach access paths; the beach is straightforward to enter, but the walk can be longer than expected depending on which field you choose.',
    'Pick smaller peaky sandbars and avoid forcing the steepest shorebreak sections. On flatter days it still works for paddling reps and pop-up practice.',
    'It is popular with families, anglers, and surfers in season; go early or choose a quieter stretch instead of dropping into the most obvious cluster.',
    'Low–mid tide, N–NW wind, 2–4 ft S–SE swell',
    ARRAY['Strong sweep on bigger days', 'Shorebreak can get punchy fast'],
    'Respect flagged swim and surf zones during guarded hours and do not assume open sand means there is no lineup order.',
    'high',
    ARRAY['🅿️ Field lots fill quickly on summer mornings', '🌊 Small clean days make this the easiest self-practice call', '🌬️ N–NW wind helps keep the beach organized'],
    false
  ),
  (
    '144b902f-4766-4bfa-a0ed-db41ade6a704',
    'Smith Point County Park',
    'Shirley',
    'NY',
    'USA',
    40.7384,
    -72.8444,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'shorebreak', 'sweep', 'crowds'],
    ARRAY['Parking nearby', 'Restrooms', 'Showers', 'Camping nearby', 'Surfing area', 'Beginner friendly on small days'],
    95,
    190,
    300,
    45,
    12,
    8,
    0.5,
    4.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 145, "period_s": 9}, "notes": "Smith Point is a valid beginner-adjacent option when it is the closest ocean beach and the surf zone stays small, clean, and not too swept by wind or current."}'::jsonb,
    115,
    145,
    45,
    ARRAY[8,9,10,11,2,3],
    'smith-point-county-park-shirley-ny',
    'Long Island',
    'Smith Point County Park is an exposed Fire Island barrier-beach setup with rolling Atlantic surf, a large summer crowd, and plenty of room when the conditions are calm. It can be the closest real ocean option for central and eastern Long Island surfers, but it stops being beginner-friendly quickly once the shorebreak hardens or the sweep starts pulling sideways.',
    'County parking and seasonal beach traffic make timing matter; arrive early on summer weekends and expect the lot to feel busy well before midday.',
    'The beach access is direct from the lot and boardwalk areas, but guarded hours can compress surfing into designated sections.',
    'Use it for mellow small-day reps, paddling, and timing the shorebreak. If it is dumpy, swept, or crowded into a tight surf zone, it is better as a body-surf or boogie day.',
    'The park is busy in summer with swimmers, campers, and surfers sharing space; choose off-peak windows when possible.',
    'Low–mid tide, W–NW wind, 2–4 ft S–SE swell',
    ARRAY['Guarded-hour surf zones can feel tight', 'Sweep and shorebreak rise quickly with size'],
    'Stay inside the designated surf area, respect learners and swimmers around the zone boundaries, and do not paddle out wide just because the beach looks open.',
    'high',
    ARRAY['🅿️ Easy ocean access for central and eastern Long Island surfers', '🌊 Small clean days are the only real beginner filter', '🏄 Body-surf and boogie days still count as useful prep here'],
    false
  )
ON CONFLICT (id) DO NOTHING;

COMMIT;
