-- Add researched southeast Puerto Rico surf spots and licensed Wikimedia photos.

BEGIN;

WITH new_spots (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preferred_tide_direction,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  timezone,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private,
  cdip_eligible
) AS (
  VALUES
    (
      'bf11355b-3072-49ce-9682-783349d5a17d'::uuid,
      'El Cocal',
      'Yabucoa',
      'PR',
      'USA',
      18.01405,
      -65.846954,
      'beach',
      'lower-intermediate',
      ARRAY['shorebreak', 'rip currents', 'rocks', 'no lifeguard']::text[],
      ARRAY['southeast Puerto Rico beachbreak', 'left and right peaks', 'natural pool nearby', 'parking nearby', 'scenic rocky coastline']::text[],
      130,
      180,
      315,
      45,
      12,
      10,
      0.5,
      2.0,
      'either',
      '{"tide": "mid", "primary_swell": {"dir_deg": 155, "period_s": 9}, "notes": "Surf-Forecast reports S-SE swell and NW wind as the cleanest setup; the map point uses the named Playa El Cocal / El Guano beach access in Camino Nuevo, Yabucoa."}'::jsonb,
      135,
      155,
      25,
      ARRAY[12, 1, 2, 3, 4],
      'el-cocal-yabucoa-pr',
      'Southeast Puerto Rico',
      'America/Puerto_Rico',
      'El Cocal, also mapped as Playa El Guano, is a southeast Puerto Rico beachbreak in Camino Nuevo, Yabucoa. It has scenic rock formations and a nearby natural pool, while the surf zone can produce inconsistent left and right peaks when south to southeast swell reaches the coast. Treat it as a lower-intermediate call because shorebreak, rocks, rips, and missing lifeguard coverage matter even when the wave looks playful.',
      'Use the public parking near Playa El Guano / El Cocal and arrive early on weekends. Keep valuables out of sight and avoid blocking local access roads.',
      'Access is from Camino Nuevo on the Yabucoa coast. Check the surf from shore first, then use the safest sandy entry away from rocks and shorebreak.',
      'Look for small to moderate south or southeast swell with northwest wind. The wave can be inconsistent, so choose the cleanest peak with room and skip it when the shorebreak is heavy.',
      'Usually lighter than the better-known west and north coast Puerto Rico spots, but local beach traffic and weekend visitors can cluster around the natural pool and parking area.',
      'South to southeast swell, light northwest wind, and mid tide are the starting read. Winter and early spring are the most useful months when the south-east coast sees enough energy without messy wind.',
      ARRAY['No lifeguard coverage', 'Rocky sections around the natural pool', 'Shorebreak can get punchy', 'Rip currents are possible on stronger swell']::text[],
      'Give the local beach users space, do not crowd the small peaks, and keep clear of swimmers near the natural pool area.',
      'low',
      ARRAY['Adds missing Yabucoa coverage on the southeast coast', 'Use as a lower-intermediate beachbreak, not a first-timer default', 'Best evidence supports no public live camera at this time']::text[],
      false,
      false
    ),
    (
      '4b9682e4-87f9-4058-81aa-ea0630e7be47'::uuid,
      'Inches',
      'Patillas',
      'PR',
      'USA',
      17.9726,
      -65.96151,
      'reef',
      'intermediate',
      ARRAY['shallow reef', 'fire coral', 'sea urchins', 'rocks', 'rip currents', 'no lifeguard']::text[],
      ARRAY['left point', 'summer spot', 'hurricane swell spot', 'roadside access', 'pebble beach', 'nearby restaurants']::text[],
      90,
      140,
      115,
      45,
      12,
      10,
      0.5,
      2.0,
      'either',
      '{"tide": "mid", "primary_swell": {"dir_deg": 115, "period_s": 10}, "notes": "Surf-Forecast lists ESE swell and ESE wind as the cleanest setup; local listings place the surf spot on PR-3 in Patillas around 17.9726, -65.9615."}'::jsonb,
      295,
      115,
      25,
      ARRAY[6, 7, 8, 9, 10],
      'inches-patillas-pr',
      'Southeast Puerto Rico',
      'America/Puerto_Rico',
      'Inches is the Patillas surf spot just off PR-3 on Puerto Rico''s southeast coast. Local surf guides and Surfline describe it as one of the better summer and hurricane-swell spots in the area, with a left-point feel and rides that can run when the ESE swell is right. The bottom is reef, rock, coral, and river-stone style cobble rather than soft sand, so this belongs in the intermediate bucket.',
      'Roadside parking is limited along PR-3 near the surf spot. Pull fully off the road, avoid blocking homes or businesses, and expect fewer formal amenities than the San Juan or Rincon breaks.',
      'Use the roadside access by PR-3 and watch the lineup before entering. The reef, rocks, and cobble bottom make timing and footwear more important than at a sandy beachbreak.',
      'Best on ESE swell with clean wind and enough tide to keep the reef manageable. Look for the main left, avoid surfing over exposed reef, and skip it if the current or fire coral risk is not obvious from shore.',
      'Crowds are usually lighter than Rincon or San Juan, but the takeoff can be concentrated when summer or hurricane swell lines up. Wait your turn and do not paddle straight to the deepest local peak.',
      'ESE swell, ESE to light offshore wind flow, and mid tide are the starting read. Summer, July in particular, is the highlighted season, with tropical systems adding the bigger windows.',
      ARRAY['Shallow reef and fire coral', 'Sea urchins and rocks', 'Rip currents on stronger swell', 'No lifeguard coverage', 'Roadside access requires care']::text[],
      'Keep the lineup orderly, respect the concentrated takeoff, and give local surfers the first waves when the point is working.',
      'moderate',
      ARRAY['Adds missing Patillas coverage on the southeast coast', 'Intermediate reef/point-style listing, not a beginner sand beach', 'No validated public live camera found']::text[],
      false,
      false
    )
)
INSERT INTO public.beaches (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preferred_tide_direction,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  timezone,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private,
  cdip_eligible
)
SELECT
  spot.id,
  spot.name,
  spot.city,
  spot.state,
  spot.country,
  spot.lat,
  spot.lon,
  spot.break_type,
  spot.skill_level,
  spot.hazards,
  spot.features,
  spot.swell_window_min_deg,
  spot.swell_window_max_deg,
  spot.wind_offshore_deg,
  spot.wind_offshore_tol_deg,
  spot.wind_cross_shore_ok_kt,
  spot.wind_onshore_bad_kt,
  spot.preferred_tide_ft_min,
  spot.preferred_tide_ft_max,
  spot.preferred_tide_direction,
  spot.preference_model,
  spot.aspect_deg,
  spot.swell_window_center_deg,
  spot.swell_window_halfwidth_deg,
  spot.best_months,
  spot.slug,
  spot.region,
  spot.timezone,
  spot.description,
  spot.parking_tips,
  spot.access_tips,
  spot.wave_tips,
  spot.crowd_tips,
  spot.best_conditions_prose,
  spot.warnings,
  spot.local_etiquette,
  spot.crowd_level,
  spot.real_takeaways,
  spot.is_private,
  spot.cdip_eligible
FROM new_spots AS spot
WHERE NOT EXISTS (
  SELECT 1
  FROM public.beaches AS existing
  WHERE existing.state = spot.state
    AND existing.city = spot.city
    AND existing.slug = spot.slug
    AND existing.deleted_at IS NULL
);

WITH photo_candidates (
  slug,
  city,
  state,
  source_id,
  image_url,
  thumb_url,
  title,
  creator_name,
  creator_url,
  license_code,
  license_url,
  attribution_html
) AS (
  VALUES
    (
      'el-cocal-yabucoa-pr',
      'Yabucoa',
      'PR',
      'File:El Guano Beach in Camino Nuevo, Yabucoa, Puerto Rico.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/d/db/El_Guano_Beach_in_Camino_Nuevo%2C_Yabucoa%2C_Puerto_Rico.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/El_Guano_Beach_in_Camino_Nuevo%2C_Yabucoa%2C_Puerto_Rico.jpg/1280px-El_Guano_Beach_in_Camino_Nuevo%2C_Yabucoa%2C_Puerto_Rico.jpg',
      'El Guano Beach in Camino Nuevo, Yabucoa, Puerto Rico',
      'Winifredo Torres',
      'https://www.flickr.com/photos/182176701@N03/',
      'CC BY-SA 2.0',
      'https://creativecommons.org/licenses/by-sa/2.0/',
      'Photo by Winifredo Torres, licensed CC BY-SA 2.0 via Wikimedia Commons.'
    ),
    (
      'inches-patillas-pr',
      'Patillas',
      'PR',
      'File:Inches Beach (2025)-1.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/d/db/Inches_Beach_%282025%29-1.jpg',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Inches_Beach_%282025%29-1.jpg/1280px-Inches_Beach_%282025%29-1.jpg',
      'Inches Beach in Patillas, Puerto Rico',
      'Ligocsicnarf89',
      'https://commons.wikimedia.org/wiki/User:Ligocsicnarf89',
      'CC BY 4.0',
      'https://creativecommons.org/licenses/by/4.0/',
      'Photo by Ligocsicnarf89, licensed CC BY 4.0 via Wikimedia Commons.'
    )
)
INSERT INTO public.beach_photos (
  beach_id,
  source,
  source_id,
  image_url,
  thumb_url,
  title,
  creator_name,
  creator_url,
  license_code,
  license_url,
  attribution_html,
  approved,
  deleted_at
)
SELECT
  b.id,
  'wikimedia',
  photo.source_id,
  photo.image_url,
  photo.thumb_url,
  photo.title,
  photo.creator_name,
  photo.creator_url,
  photo.license_code,
  photo.license_url,
  photo.attribution_html,
  true,
  NULL::timestamptz
FROM photo_candidates AS photo
JOIN public.beaches AS b
  ON b.slug = photo.slug
  AND b.city = photo.city
  AND b.state = photo.state
  AND b.deleted_at IS NULL
ON CONFLICT (beach_id, source, source_id)
DO UPDATE SET
  image_url = EXCLUDED.image_url,
  thumb_url = EXCLUDED.thumb_url,
  title = EXCLUDED.title,
  creator_name = EXCLUDED.creator_name,
  creator_url = EXCLUDED.creator_url,
  license_code = EXCLUDED.license_code,
  license_url = EXCLUDED.license_url,
  attribution_html = EXCLUDED.attribution_html,
  approved = true,
  deleted_at = NULL,
  fetched_at = now();

COMMIT;
