BEGIN;

WITH beginner_profiles (
  slug,
  skill_level,
  description,
  features,
  wave_tips,
  best_conditions_prose,
  warnings,
  real_takeaways
) AS (
  VALUES
    (
      'crash-boat',
      'beginner',
      'Crash Boat is a popular Aguadilla family beach with a picturesque pier and a user-friendly beach break. On small north to northwest swells, the sandy peaks are one of the better beginner and longboard options on Puerto Rico''s west side. The beach gets busy with swimmers, snorkelers, and boats, so the safe beginner read is small surf, clear flags, and plenty of room away from the pier traffic.',
      ARRAY['beginner-friendly', 'longboard-friendly', 'sand bottom sections', 'pier landmark', 'amenities and food', 'snorkeling']::text[],
      'Use Crash Boat as a small-day learner and longboard call. Stay away from boat lanes and the pier rip, look for the soft sandbar peaks, and skip it when larger winter swell makes the current stronger.',
      'Best on small north to northwest swell with light south to southeast wind; target mellow knee- to waist-high days for first-timers and longboards.',
      ARRAY['Heavy crowds on weekends', 'Watch for boats and swimmers', 'Rip currents around the pier', 'Not a beginner call when winter swell is strong']::text[],
      ARRAY['Best PR west-side learner update for small days', 'Longboards and foam boards make the most sense here', 'Shared family beach, so swimmer awareness matters']::text[]
    ),
    (
      'jobos',
      'beginner',
      'Jobos is Isabela''s iconic surf beach, with a powerful outside reef and a softer inside/sand section. The outside peak remains an intermediate-plus wave, but the inside zone supports surf schools, longboards, foam boards, and careful beginners on smaller days. Treat the spot as beginner-usable only when the swell is small and the lesson/inside area is clearly separated from the main reef takeoff.',
      ARRAY['inside learner section', 'longboard-friendly on small days', 'surf schools', 'two peaks', 'restaurants and bars', 'consistent']::text[],
      'Beginners should stay on the inside/sand section with a coach or experienced guide. The outside right is a different wave: faster, reefier, crowded, and not appropriate for new surfers.',
      'Small north to northwest swell, light south to southeast wind, and a mellow inside reform are the beginner setup; bigger winter days belong to intermediates and experienced locals.',
      ARRAY['Outside reef is not beginner-friendly', 'Heavy crowd at main peak', 'Sharp reef on the outside', 'Strong currents during big swells']::text[],
      ARRAY['High-search Isabela spot with legitimate beginner lesson demand', 'Beginner rating applies to inside/small-day section only', 'Outside reef warnings need to stay visible']::text[]
    ),
    (
      'middles-isabela',
      'beginner',
      'Middles Isabela is a broad, multi-peak beach between Jobos and Shacks. The western end can get powerful and hollow, but the more open sand-bottom sections and surf-school use make the spot useful for progressing beginners and longboarders when the swell is small. It is a better recommendation for learners who already understand rip currents than for a first solo paddle-out.',
      ARRAY['beginner-friendly on small days', 'longboard-friendly', 'multiple peaks', 'surf schools', 'spacious beach', 'sand and reef mix']::text[],
      'Choose the softer eastern or inside peaks for longboards and progression. Avoid the heavier western peak and any day with obvious rips or contest-level surf.',
      'Small to moderate north or northwest swell with light southeast wind; the learner read is mellow sandbar shoulders, not the hollow competition peak.',
      ARRAY['Rip currents and undertow', 'Western peak can be powerful', 'Crowds during contests', 'Avoid swimming on rough days']::text[],
      ARRAY['Good Isabela expansion for beginner and longboard intent pages', 'Progression spot, not the softest first-timer beach', 'Peak choice matters more than the beach name']::text[]
    ),
    (
      'la-pared',
      'beginner',
      'La Pared is Luquillo''s accessible town beachbreak and the best current Quiver fit for northeast Puerto Rico learner intent. Surf schools and rentals operate nearby, and small northeast to east swells create approachable peaks for beginners and longboards. The same beach can also develop strong rip currents and punchier surf, so beginner suitability depends on size, flags, and local instruction.',
      ARRAY['beginner-friendly on small days', 'longboard-friendly', 'surf schools nearby', 'multiple sandbar peaks', 'restaurants nearby', 'San Juan day-trip access']::text[],
      'Use the mellow sandbar peaks for learners and longboards. If the trade winds are strong, flags are up, or channels are pulling hard, this becomes an intermediate current-management session.',
      'Small northeast to east swell, light west to southwest wind, and manageable rip-current conditions; mornings before trade wind texture are usually the cleanest.',
      ARRAY['Strong rip currents - swimming not recommended when flags are up', 'Can be choppy in trade winds', 'Watch for red flags', 'Beginner suitability changes quickly with swell size']::text[],
      ARRAY['Best Luquillo beginner/longboard intent candidate already in Quiver', 'Small-day surf-school demand is real', 'Rips remain the main caveat']::text[]
    )
)
UPDATE public.beaches AS b
SET
  skill_level = profile.skill_level,
  description = profile.description,
  features = profile.features,
  wave_tips = profile.wave_tips,
  best_conditions_prose = profile.best_conditions_prose,
  warnings = profile.warnings,
  real_takeaways = profile.real_takeaways
FROM beginner_profiles AS profile
WHERE b.state = 'PR'
  AND b.slug = profile.slug
  AND b.deleted_at IS NULL;

WITH new_spots (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preferred_tide_direction,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  timezone,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private,
  cdip_eligible
) AS (
  VALUES
    (
      '55c54357-fdc9-402e-9c31-1bb17978bb03'::uuid,
      'Pine Grove',
      'Carolina',
      'PR',
      'USA',
      18.4414,
      -66.0174,
      'beach',
      'beginner',
      ARRAY['rip currents', 'swimmers', 'shorebreak on windy days', 'crowds near hotels']::text[],
      ARRAY['beginner-friendly', 'longboard-friendly', 'sandbar peaks', 'surf schools nearby', 'airport access', 'Isla Verde hotels']::text[],
      0,
      90,
      190,
      45,
      12,
      10,
      0.5,
      2.0,
      'either',
      '{"tide": "mid", "primary_swell": {"dir_deg": 45, "period_s": 9}, "notes": "Small N-NE-E swell and light southerly flow create the cleanest beginner/longboard setup."}'::jsonb,
      45,
      45,
      45,
      ARRAY[11, 12, 1, 2, 3],
      'pine-grove',
      'San Juan Metro',
      'America/Puerto_Rico',
      'Pine Grove is the east-end Isla Verde sandbar that gives San Juan a practical beginner surf option. The wave is usually soft, accessible, and close to hotels, surf schools, rentals, and the airport. It is best for foam boards and longboards on small clean days; stronger wind or north swell can add backwash, rips, and enough punch that brand-new surfers should stay with an instructor.',
      'Street and paid parking options sit around the east end of Isla Verde and nearby hotels. Arrive early on weekends and keep valuables out of sight.',
      'Use the public beach access points around the east end of Isla Verde. Stay clear of swimmers and check local flags before paddling out.',
      'Look for the small rolling sandbar peaks and use a foam board or longboard. If the wave starts dumping near shore or backwash gets obvious, wait for a calmer window.',
      'Weekdays and early mornings are the easiest. Hotel traffic and lessons can crowd the best learner zone on weekends.',
      'Small N to E swell, light south-side wind, and knee- to waist-high sandbar waves are the beginner setup; winter brings the most consistent learner surf.',
      ARRAY['Respect lifeguard flags', 'Watch for swimmers', 'Backwash and rips increase with wind and swell', 'Best with a lesson for first-timers']::text[],
      'This is a mixed-use metro beach. Give lessons, swimmers, and families space, and do not crowd the soft-top takeoff zone.',
      'high',
      ARRAY['Best San Juan metro learner addition', 'Longboards and foam boards fit the wave', 'Close to hotels, rentals, and the airport']::text[],
      false,
      false
    ),
    (
      'bfcdd918-de0f-4b0f-b771-caca7a9c8baa'::uuid,
      'La Ocho',
      'San Juan',
      'PR',
      'USA',
      18.467,
      -66.085,
      'reef',
      'beginner',
      ARRAY['reef', 'rocks', 'sea urchins', 'long paddle', 'localism', 'runoff after rain']::text[],
      ARRAY['longboard-friendly', 'all-abilities on small days', 'reef peaks', 'protected from trades', 'board rentals nearby', 'Old San Juan access']::text[],
      315,
      45,
      180,
      45,
      12,
      8,
      0.0,
      1.5,
      'falling',
      '{"tide": "lower", "primary_swell": {"dir_deg": 0, "period_s": 11}, "notes": "NNW-N-NE swell with south wind; beginner call only when small and spread out."}'::jsonb,
      0,
      0,
      45,
      ARRAY[11, 12, 1, 2, 3],
      'la-ocho',
      'San Juan Metro',
      'America/Puerto_Rico',
      'La Ocho sits by Escambron just east of Old San Juan and gives the capital a real longboard reef option. The wave breaks over reef and rock, spreads across a large area, and can suit many ability levels when small. It is not as soft as Pine Grove, but its protected setup, board-rental access, and rolling rights make it a useful longboard and progressing-beginner page when size is manageable.',
      'Use the public parking around Luis Munoz Rivera Park, Escambron, or nearby streets. Spaces are easier early, and weekends can fill quickly.',
      'Paddle from the Escambron/La Ocho side and give yourself time; the main waves break farther out than they look from shore.',
      'On small days, longboards can pick off rolling reef peaks across the spread-out lineup. When the swell is head high or the reef is drawing shallow, this is no longer a beginner recommendation.',
      'The lineup can be localized, but the spread-out reef helps. Be patient, avoid paddling straight to the deepest peak, and respect surfers already in rotation.',
      'NNW to NE swell, south wind, and lower to mid tide. Early mornings are usually better before trades and crowd pressure build.',
      ARRAY['Reef and rocks under the wave', 'Long paddle for new surfers', 'Localized when good', 'Avoid after heavy rain runoff', 'Not beginner-friendly when head high or bigger']::text[],
      'Start wide, watch the rotation, and treat the reef with respect. Longboard cruisers and families share this zone on small days.',
      'moderate',
      ARRAY['Missing San Juan longboard reef candidate', 'All-abilities only when small', 'Stronger caveats than Pine Grove because it is reef-based']::text[],
      false,
      false
    )
)
INSERT INTO public.beaches (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preferred_tide_direction,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  timezone,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private,
  cdip_eligible
)
SELECT
  spot.id,
  spot.name,
  spot.city,
  spot.state,
  spot.country,
  spot.lat,
  spot.lon,
  spot.break_type,
  spot.skill_level,
  spot.hazards,
  spot.features,
  spot.swell_window_min_deg,
  spot.swell_window_max_deg,
  spot.wind_offshore_deg,
  spot.wind_offshore_tol_deg,
  spot.wind_cross_shore_ok_kt,
  spot.wind_onshore_bad_kt,
  spot.preferred_tide_ft_min,
  spot.preferred_tide_ft_max,
  spot.preferred_tide_direction,
  spot.preference_model,
  spot.aspect_deg,
  spot.swell_window_center_deg,
  spot.swell_window_halfwidth_deg,
  spot.best_months,
  spot.slug,
  spot.region,
  spot.timezone,
  spot.description,
  spot.parking_tips,
  spot.access_tips,
  spot.wave_tips,
  spot.crowd_tips,
  spot.best_conditions_prose,
  spot.warnings,
  spot.local_etiquette,
  spot.crowd_level,
  spot.real_takeaways,
  spot.is_private,
  spot.cdip_eligible
FROM new_spots AS spot
WHERE NOT EXISTS (
  SELECT 1
  FROM public.beaches AS existing
  WHERE existing.state = spot.state
    AND existing.city = spot.city
    AND existing.slug = spot.slug
    AND existing.deleted_at IS NULL
);

COMMIT;
