-- Add 7 Texas Gulf Coast surf spots with verified surf and NOAA tide coverage
-- Safe, idempotent insert using ON CONFLICT

BEGIN;

INSERT INTO public.beaches (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private
) VALUES
  -- 1. Galveston – 61st Street Pier (Galveston, TX)
  (
    '13ba376d-efd5-4e4e-af12-85bfeb2c17bc',
    'Galveston – 61st Street Pier',
    'Galveston',
    'TX',
    'USA',
    29.26477,
    -94.82505,
    'pier',
    'lower-intermediate',
    ARRAY['pier pilings', 'rip currents', 'fishing lines', 'shorebreak'],
    ARRAY['Parking nearby', 'Restrooms nearby', 'Surf shops nearby', 'Lessons available'],
    70,
    190,
    330,
    45,
    12,
    8,
    0.5,
    2.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 135, "period_s": 8}, "notes": "Most useful on E–S Gulf windswells with light N–NW wind."}'::jsonb,
    150,
    130,
    60,
    ARRAY[8,9,10,11,12,1,2,3],
    'galveston-61st-street-pier-galveston-tx',
    'Texas Gulf Coast',
    'The beach at 61st Street is one of Galveston''s established Seawall surf zones. The pier and nearby structures influence the sandbars, producing short lefts and rights when Gulf windswells reach the island. Smaller days suit longboards and learners, while storm-driven surf brings stronger currents and a more demanding paddle.',
    'Use legal Seawall parking or nearby paid lots and follow posted meter rules. Summer weekends fill early because the pier and surrounding beach are major visitor destinations.',
    'Enter from the public beach beside the pier. Stay outside posted pier restrictions and give the pilings and anglers a wide berth.',
    'Look for a defined sandbar rather than surfing directly against the structure. E to SE swell with light N to NW wind is the cleanest setup; afternoon onshore wind usually adds chop.',
    'This is a visible, easy-access Galveston break used by lessons, visitors, and local surfers. Dawn and weekdays offer the most room.',
    'Mid tide, N–NW wind, 2–5 ft E–SE swell',
    ARRAY['Stay clear of pier pilings and fishing lines', 'Storm surf can create strong rip currents', 'Obey lifeguard flags and posted surf zones'],
    'Yield to the surfer already riding, leave room for lessons and swimmers, and do not paddle through anglers'' lines.',
    'high',
    ARRAY['🏄 Established Galveston Seawall break', '🧑‍🎓 Multiple surf schools nearby', '⚠️ Keep clear of the fishing pier'],
    false
  ),

  -- 2. Galveston – Pleasure Pier (Galveston, TX)
  (
    'cc0b9ee8-0efc-4f78-9049-48a99e0d2c52',
    'Galveston – Pleasure Pier',
    'Galveston',
    'TX',
    'USA',
    29.28356,
    -94.78917,
    'pier',
    'intermediate',
    ARRAY['pier pilings', 'rip currents', 'crowded beach', 'debris after storms'],
    ARRAY['Seawall access', 'Parking nearby', 'Surf shops nearby', 'Lessons nearby'],
    70,
    190,
    335,
    45,
    12,
    8,
    0.5,
    2.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 130, "period_s": 8}, "notes": "E–SE windswell wraps into the pier sandbars; N–NW wind provides the cleanest faces."}'::jsonb,
    155,
    130,
    60,
    ARRAY[8,9,10,11,12,1,2,3],
    'galveston-pleasure-pier-galveston-tx',
    'Texas Gulf Coast',
    'Pleasure Pier is a named Galveston surf break along the central Seawall. Shifting sandbars around the pier can organize Gulf windswells into rideable peaks on either side. The waves are usually short-period and modest, but cold fronts and tropical systems can produce faster, stronger surf.',
    'Use metered Seawall parking or nearby commercial lots. Parking is busiest on weekends, holidays, and during events at the pier.',
    'Reach the water from the public beach beside the pier and observe all posted swimming and surfing zones. Do not enter beneath the pier deck or between its pilings.',
    'Check both sides from shore for the better sandbar and wind protection. Mid tide and a light northerly wind generally provide more shape than a strong afternoon sea breeze.',
    'The central Seawall draws surfers, swimmers, and visitors. Surf early and avoid forcing a takeoff near the pier structure.',
    'Mid tide, N–NW wind, 2–5 ft E–SE swell',
    ARRAY['Pier pilings are a collision hazard', 'Crowded swimming beach in warm weather', 'Check water quality and debris after heavy rain or storms'],
    'Stay out of posted restricted areas, share the sandbar peaks, and give swimmers and novice surfers extra space.',
    'high',
    ARRAY['🎡 Central Galveston landmark break', '🌊 Best with a clean E–SE windswell', '⚠️ Pilings and beach traffic require space'],
    false
  ),

  -- 3. Packery Channel Jetties (Corpus Christi, TX)
  (
    '55c7c5dd-1979-410a-bf39-ce3c52e29166',
    'Packery Channel Jetties',
    'Corpus Christi',
    'TX',
    'USA',
    27.616083,
    -97.200167,
    'jetty',
    'intermediate',
    ARRAY['jetty rocks', 'rip currents', 'fishing lines', 'crowded lineup'],
    ARRAY['Beach parking', 'Restrooms nearby', 'Surf shops nearby', 'Lessons available'],
    45,
    180,
    285,
    45,
    15,
    10,
    0.0,
    2.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 120, "period_s": 9}, "notes": "The north side favors S–SE swell; the south side improves on E–NE swell, with W–NW offshore wind."}'::jsonb,
    105,
    112,
    68,
    ARRAY[8,9,10,11,12,1,2,3,4],
    'packery-channel-jetties-corpus-christi-tx',
    'Texas Gulf Coast',
    'Packery Channel cuts between Mustang Island and North Padre Island, with jetties that interrupt the longshore current and help maintain surfable sandbars on both sides. North Packery at J.P. Luby Surf Park is the more common longboard and lesson zone, while South Packery can improve on east and northeast swell.',
    'Beach parking is available on both sides with a valid Nueces County beach permit where required. Paved access and facilities are available near the North Padre seawall and J.P. Luby area.',
    'Choose the side that is protected from the current wind and swell direction. Walk around the jetty by road; never try to cross the channel.',
    'South to southeast swell usually favors the north side; east to northeast swell can favor the south side. Use the jetty only as a visual reference and stay well away from the rocks and channel current.',
    'Packery is one of the most consistently crowded breaks on the central Texas coast, with longboarders, lessons, and anglers sharing the area.',
    'Mid tide, W–NW wind, 2–6 ft E–SE swell',
    ARRAY['Strong channel current beside both jetties', 'Slippery rocks and submerged structure', 'Fishing lines near the jetty', 'Beach vehicle traffic'],
    'Do not use the channel as a shortcut, keep clear of anglers, and give beginners room on the north-side inside peaks.',
    'very_high',
    ARRAY['🧱 Jetties stabilize sandbars on both sides', '🏄 North Packery is the main longboard zone', '⚠️ Channel current and rocks demand caution'],
    false
  ),

  -- 4. Bob Hall Pier (Corpus Christi, TX)
  (
    '04940f92-f611-448d-acd3-a6456ca8b6de',
    'Bob Hall Pier',
    'Corpus Christi',
    'TX',
    'USA',
    27.58,
    -97.2167,
    'pier',
    'intermediate',
    ARRAY['rip currents', 'pier structure', 'sharks', 'jellyfish'],
    ARRAY['County park', 'Parking nearby', 'Restrooms nearby', 'Surf shops nearby'],
    45,
    180,
    285,
    45,
    15,
    10,
    0.0,
    2.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 120, "period_s": 9}, "notes": "Exposed E–SE beach break with the best shape in light W–NW wind."}'::jsonb,
    105,
    112,
    68,
    ARRAY[8,9,10,11,12,1,2,3,4],
    'bob-hall-pier-corpus-christi-tx',
    'Texas Gulf Coast',
    'Bob Hall Pier at Padre Balli Park is a long-established Corpus Christi surf zone. The exposed sandbars produce lefts and rights from local windswells and stronger tropical swell, with more push than many protected Gulf beaches. Sandbar position and construction around the pier site can change the best peak.',
    'Use Padre Balli Park parking or permitted beach parking. Check current Nueces County notices because pier reconstruction can change parking and pedestrian routes.',
    'Enter from the public beach and respect all construction fencing or pier closures. Pick a sandbar with a clear path away from any remaining or rebuilt structure.',
    'E to SE swell and light W to NW wind are the most favorable combination. The break works through a range of tides, but a mid tide often gives the sandbars more shape.',
    'This is a recognized local performance break and gets busy when a clean swell arrives. Secondary peaks away from the main structure can offer more room.',
    'Mid tide, W–NW wind, 3–7 ft E–SE swell',
    ARRAY['Check current pier reconstruction closures', 'Rip currents strengthen on larger swell', 'Jellyfish and stingrays occur seasonally'],
    'Respect construction boundaries, wait your turn at the main peak, and keep clear of anglers and families using the county park.',
    'high',
    ARRAY['🌊 Exposed Corpus Christi beach break', '🏄 Faster, stronger peaks on good swell', '🚧 Verify pier-area access before visiting'],
    false
  ),

  -- 5. Mustang Island State Park (Corpus Christi, TX)
  (
    'd85492b8-31ed-4dd8-af53-4284e9456be9',
    'Mustang Island State Park',
    'Corpus Christi',
    'TX',
    'USA',
    27.67422,
    -97.16769,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'shorebreak', 'jellyfish', 'stingrays'],
    ARRAY['State park', 'Camping', 'Restrooms', 'Showers'],
    50,
    180,
    290,
    45,
    15,
    10,
    0.0,
    2.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 120, "period_s": 8}, "notes": "Open beach favors E–SE windswell with light W–NW wind; sandbar quality shifts along the park."}'::jsonb,
    110,
    115,
    65,
    ARRAY[8,9,10,11,12,1,2,3,4],
    'mustang-island-state-park-corpus-christi-tx',
    'Texas Gulf Coast',
    'Mustang Island State Park provides more than five miles of open Gulf beach where shifting sandbars create uncrowded left and right peaks. The surf is generally softer than Packery or Bob Hall, making smaller clean days useful for longboards and progressing surfers.',
    'A state park day-use fee applies, and reservations are recommended when the park is likely to reach capacity. Developed campsites, restrooms, and showers are set back from the beach.',
    'Use designated park roads and beach access points. Ask park staff about current driving conditions before taking a vehicle onto soft sand.',
    'Check several sandbars along the park instead of settling at the first access. E to SE swell with a light W to NW wind produces the cleanest open-beach peaks.',
    'The long shoreline spreads surfers out, though camp and day-use areas are busier on summer weekends.',
    'Mid tide, W–NW wind, 2–5 ft E–SE swell',
    ARRAY['Soft sand can trap vehicles', 'No lifeguard at many stretches', 'Rip currents and seasonal jellyfish'],
    'Protect the dunes, use established access routes, pack out all trash, and give swimmers and anglers a wide buffer.',
    'low',
    ARRAY['🏕️ Five miles of state-park shoreline', '🏄 Room to search for a working sandbar', '🚙 Check beach-driving conditions first'],
    false
  ),

  -- 6. Padre Island National Seashore – South Beach (Corpus Christi, TX)
  (
    '14907560-8c92-4d2e-997b-9661e97b0751',
    'Padre Island National Seashore – South Beach',
    'Corpus Christi',
    'TX',
    'USA',
    27.34829,
    -97.32651,
    'beach',
    'intermediate',
    ARRAY['rip currents', 'remote access', 'soft sand', 'jellyfish'],
    ARRAY['National seashore', 'Primitive camping', 'Remote beach', 'Open sandbars'],
    40,
    180,
    280,
    45,
    15,
    10,
    0.0,
    2.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 110, "period_s": 9}, "notes": "Open Gulf exposure accepts NE–S swell; light W–NW wind gives the cleanest faces."}'::jsonb,
    100,
    110,
    70,
    ARRAY[8,9,10,11,12,1,2,3,4],
    'padre-island-national-seashore-south-beach-corpus-christi-tx',
    'Texas Gulf Coast',
    'South Beach in Padre Island National Seashore is an undeveloped, exposed Gulf beach with miles of shifting sandbars. Surfing is allowed outside the visitor-center exclusion, and the remote shoreline can produce uncrowded left and right peaks when local windswell or tropical swell lines up with a favorable bar.',
    'Pay the national seashore entrance fee and check conditions at Malaquite Visitor Center. The first five miles of South Beach may be passable in two-wheel-drive vehicles, while travel farther south should be attempted only with four-wheel drive and emergency supplies.',
    'South Beach begins beyond the paved park road. Stay on authorized beach-driving routes, never drive on dunes or tidal flats, and choose a turnaround point well within the vehicle''s capability.',
    'Search for a defined outer bar and channel. Light W to NW wind cleans up E to SE swell; larger surf produces powerful longshore and rip currents with no lifeguard response nearby.',
    'Crowds thin rapidly away from the first few miles, but remoteness raises the consequence of equipment, vehicle, or medical problems.',
    'Mid tide, W–NW wind, 3–7 ft E–SE swell',
    ARRAY['No lifeguards', 'Four-wheel drive advised beyond mile 5', 'Cell service can be poor or unavailable', 'Protect seasonal sea-turtle nesting areas'],
    'Follow all National Park Service closures, slow down around people and wildlife, leave turtle nests undisturbed, and pack out everything brought onto the beach.',
    'low',
    ARRAY['🏝️ Remote open-coast sandbars', '🚙 Four-wheel drive advised beyond mile 5', '🐢 Strictly protect nesting wildlife'],
    false
  ),

  -- 7. Crystal Beach (Crystal Beach, TX)
  (
    'a3f9b33e-6b29-4b41-8024-3f7cf1eb66c8',
    'Crystal Beach',
    'Crystal Beach',
    'TX',
    'USA',
    29.4507,
    -94.63347,
    'beach',
    'lower-intermediate',
    ARRAY['rip currents', 'vehicle traffic', 'shorebreak', 'debris after storms'],
    ARRAY['Beach driving', 'Camping allowed', 'Surf shop nearby', 'Wide beach'],
    70,
    190,
    325,
    45,
    12,
    8,
    0.5,
    2.5,
    '{"tide": "mid", "primary_swell": {"dir_deg": 130, "period_s": 8}, "notes": "Open Bolivar beach works on E–SE Gulf windswell with light N–NW wind."}'::jsonb,
    145,
    130,
    60,
    ARRAY[8,9,10,11,12,1,2,3],
    'crystal-beach-crystal-beach-tx',
    'Texas Gulf Coast',
    'Crystal Beach is an open beach break on the Bolivar Peninsula with shifting sandbars and left and right peaks. It is usually small and wind-driven, but stronger east and southeast swells can produce workable surf along the broad shoreline.',
    'Vehicles may park and drive on designated beach sections with the required Galveston County permit. Rules and access conditions can change after storms, so check county notices before driving onto the sand.',
    'Use a signed public beach access road and keep vehicles in the established traffic lane. The ferry from Galveston can have long waits on busy weekends.',
    'Walk the beach to find a bar with a defined peak. E to SE swell and light N to NW wind are most favorable; strong onshore wind makes the broad beach choppy.',
    'Most days offer ample room, but holiday weekends and organized vehicle events can make the beach extremely busy.',
    'Mid tide, N–NW wind, 2–5 ft E–SE swell',
    ARRAY['Active vehicle traffic on the beach', 'Check access after storms', 'No consistent lifeguard coverage', 'Debris may be present after high water'],
    'Keep boards and children clear of the vehicle lane, respect private property behind the public beach, and pack out all trash.',
    'moderate',
    ARRAY['🏖️ Open Bolivar Peninsula beach break', '🏪 Long-running surf shop in town', '🚗 Watch for beach traffic'],
    false
  )

ON CONFLICT (id) DO NOTHING;

COMMIT;
