-- Hand-written, per-beach SEO titles, descriptions and editorial copy for the
-- 113 Mexico beach pages, plus five reviewed Wikimedia Commons area photos.
-- Source copy: docs/imports/baja-surf-spots/2026-09-16/mexico-beach-copy.json
-- seo_indexable and editorial_reviewed_at are intentionally unchanged; they
-- remain a separate human editorial approval step.

BEGIN;

CREATE TEMP TABLE _mexico_beach_copy (
  beach_id uuid,
  slug text NOT NULL,
  seo_title text NOT NULL,
  seo_description text NOT NULL,
  description text NOT NULL,
  wave_tips text NOT NULL,
  access_tips text NOT NULL,
  best_conditions_prose text NOT NULL
) ON COMMIT DROP;

INSERT INTO _mexico_beach_copy VALUES
  ('2394a731-17a2-58a6-ab5b-2b445b525f76'::uuid, 'san-antonio-del-mar-north-tijuana', 'San Antonio del Mar Surf Report: Tijuana Beach Break', 'Surf forecast for San Antonio del Mar, the first real beach break south of the border in Tijuana. Swell, wind, tide and rip current notes.', 'San Antonio del Mar is the stretch of sand just south of the border on the Tijuana side, below the bluffs of the San Antonio neighborhood. It is an open beach break that takes swell from the west and northwest, and like most of this coast it is at its best in the morning before the sea breeze arrives. Rip currents form between the sandbars, and the water here is affected by the same runoff problems as the rest of the border region.', 'Look for a west to northwest swell and light east or northeast wind. The banks shift, so walk the beach and pick the peak that is actually holding shape instead of the one closest to the stairs.', 'Access runs through residential streets off the free road and toll road near the San Antonio exit. Parking and beach access points change, so do not leave anything visible in the car.', 'Best on a clean west or northwest swell with a light offshore morning, especially outside the rainy season.'),
  ('ce8fc4b1-9d0c-549a-9946-fbebc2418faa'::uuid, 'baja-malibu', 'Baja Malibu Surf Report: Heavy Beach Break Near Rosarito', 'Baja Malibu surf forecast. A powerful beach break off the toll road north of Rosarito. Check swell, wind, tide and water quality before you go.', 'Baja Malibu is the beach break most San Diego surfers mean when they say the border beaches get heavy. It sits below the toll road north of Rosarito, and the sandbars here can turn a solid swell into thick, hollow peaks that break boards. It is not a mellow wave on a good day. Water quality is the other story: sewage from the Tijuana area reaches this coast, and surfing here in the days after rain is a bad idea.', 'Winter northwest swell and combination swells with some south in them tend to produce the best shape. Early mornings with east or northeast wind are the window; mid tide is usually the easiest read.', 'Take the San Antonio exit on the toll road. The streets down to the beach run through a private community, so access and parking can change. Lock the car and leave nothing in sight.', 'Best on a solid northwest or combination swell with offshore morning wind and several dry days behind it.'),
  ('886b4230-dfa0-5480-aed3-97f2b63bcb4f'::uuid, 'marisol', 'Marisol Surf Report: Rosarito Point Break Forecast', 'Surf forecast for Marisol, a point setup at the north end of Rosarito. Live swell, wind and tide, plus notes on the rocky entry.', 'Marisol is a rocky point at the north end of Rosarito, just below the San Antonio area. It is a less-visited alternative to the town beach and needs the swell to line up along the rocks to produce a proper wall. The bottom is rock, so entry and exit take some care, especially at lower tides.', 'Watch for a west to northwest swell with light east wind. If the point is only producing short sections, the town beach to the south may be the better call.', 'Access is through the Marisol area at the north end of Rosarito. Shoreline access and parking are not guaranteed, so check locally and secure the car.', 'Best when a west or northwest swell wraps along the rocks on a calm morning.'),
  ('a46175e6-4ba5-55fe-a73d-b4f5eef9c65d'::uuid, 'marisol-north-point', 'Marisol North Point Surf Report: North Rosarito Rocks', 'Marisol North Point surf forecast for the rocky point at the north end of Rosarito. Swell, wind and tide, plus rock and rip current notes.', 'Marisol North Point is the northern of the two rocky setups at Marisol, at the top end of Rosarito. It is a rock-bottom wave for surfers who are comfortable reading a shallow lineup and timing their entry. Currents can run along the point when the swell is up.', 'Treat this as a spot you check in person. The rocks and the current matter more than the exact tide, so watch a few sets before you paddle out.', 'Reach it through the Marisol area at the north end of Rosarito. Access and parking are informal and can change.', 'Best on a clean swell with light wind, surfed by people comfortable over rock.'),
  ('f0ddfc6a-7392-40c5-9211-836c05e449f1'::uuid, 'rosarito', 'Rosarito Surf Report: Pier and Town Beach Forecast', 'Rosarito surf forecast for the town beach and pier. Wave height, swell, wind and tide for Playas de Rosarito, plus water quality notes.', 'Rosarito''s town beach runs for several kilometers in front of the hotels, and the sandbars around the pier are where most people surf. It is an easy, walk-up beach break that handles small to medium swell well and closes out when it gets big. Beginners can find softer reform waves on the inside. The downside is water quality: the town beach is known for poor water after rain, and petty theft from cars is common.', 'Combination swells and mid-size northwest swell usually give the best banks. Check the peaks on either side of the pier and go early, before the wind turns onshore.', 'Easy access from Boulevard Benito Juárez with parking along the beach. Lock the car and do not leave valuables in it.', 'Best on small to mid-size swell with an offshore morning and clean water after a dry spell.'),
  ('294712f3-3c06-44bd-9bc6-17275675fe9a'::uuid, 'renes', 'Renes Surf Report: Popotla Beach Break Forecast', 'Surf forecast for Renes near Popotla, south of Rosarito. Swell direction, wind, tide and notes on the rocky shoreline.', 'Renes is a beach break near Popotla, the fishing village just south of Rosarito. The sand is broken up by rocks along the shore, so the takeoff and paddle-out need a quick look before you go in. It picks up the same swell as the better-known reefs nearby and is often a quieter option when they are crowded.', 'West to southwest swell with an east wind is the usual clean setup. Tide matters less than whether the rocks near the entry are covered.', 'Reached from the free road near Popotla. Shoreline access here is informal and can change.', 'Best on a clean south or west swell with a calm or offshore morning.'),
  ('6e083f22-4c11-46c5-9110-ac7500f6cba5'::uuid, 'alfonsos', 'Alfonsos Surf Report: Popotla Reef Forecast', 'Alfonsos surf forecast for the reef near Popotla, south of Rosarito. Live swell, wind and tide, with notes on the rocky lineup.', 'Alfonsos is a reef break near Popotla, a few kilometers south of Rosarito, with both lefts and rights depending on swell angle. The lineup is studded with rock, so it suits surfers who can read where the reef sits on the inside and pick a clean channel out. Summer south swells are when it is most reliable.', 'Southwest swell with an east wind is the classic setup. Spend a few minutes spotting the channel and the shallow patches before you paddle out.', 'Rosarito is the nearest town for food and supplies. Access to the shoreline near Popotla is informal, so check locally and secure your car.', 'Best on a summer southwest swell with light east wind in the morning.'),
  ('f3750657-2f49-5a07-a9c9-0c80c7d628ef'::uuid, 'popotla', 'Popotla Surf Report: Reef Break South of Rosarito', 'Popotla surf forecast for the reef in front of the fishing village south of Rosarito. Swell, wind and tide, plus low-tide rock notes.', 'Popotla is a small fishing village just south of Rosarito, known for its fresh seafood stalls on the sand. The reef in front of the village breaks on west swell and gets shallow and chunky at low tide, when the rocks become a bigger factor. It is an advanced reef, not a learn-to-surf beach.', 'West swell with a southeast wind is the cleanest window. Mid to high tide keeps more water over the reef.', 'The village sits right off the free road south of Rosarito. Parking is informal; ask before using private lots.', 'Best on a west swell at mid to high tide with light wind.'),
  ('63b839db-90fa-564a-8b3b-6ed53a00aa57'::uuid, 'calafia', 'Calafia Surf Report: Right-Hand Point Below Rosarito', 'Calafia surf forecast. The right-hand point below the Calafia hotel south of Rosarito, best on south swell at mid to high tide.', 'Calafia is the right-hand point below the Calafia hotel and restaurant on the cliffs south of Rosarito, and for many surfers it is the first stop on the drive down the free road. A solid south to southwest swell makes it work best, and it can handle the daily northwest wind better than the open beaches. The bottom is rock, the shorebreak can be awkward, and water quality is only fair.', 'Summer south and southwest swells are the main season. Mid to high tide is usually the best window; time your paddle-out between sets to avoid the rocks at the entry.', 'Located at the Calafia hotel on the free road south of Rosarito. A paid lot and a cliff path lead down to the water.', 'Best on a south or southwest swell at mid to high tide.'),
  ('6cbb1b4f-d25e-40a3-a78a-b138ebdf9e96'::uuid, 'el-morro-point-k37-5', 'El Morro (K-37.5) Surf Report: Rocky Point Forecast', 'El Morro surf forecast for the rocky point at kilometer 37.5, just north of K-38. Swell, wind and rising tide notes.', 'El Morro sits at kilometer 37.5, just north of the K-38 reef in the Popotla corridor. It is a rocky point that is easy to see from the road, which also means it fills up quickly when it is breaking. At low tide more rock is exposed and the wave gets less forgiving.', 'South to southwest swell with a north or northeast wind is the best setup. A rising tide toward mid or high gives the point more water over the rock.', 'Roadside access off the K-38 corridor. Park where you can see the car and keep valuables out of sight.', 'Best on a south swell and a rising mid tide with light offshore wind.'),
  ('77d286c5-87e9-4678-82d3-81d0125285fa'::uuid, 'k-38', 'K-38 Surf Report: Rosarito Reef Forecast Today', 'K-38 surf report and forecast. The most consistent reef in northern Baja, at kilometer 38 south of Rosarito. Live swell, wind and tide.', 'K-38 takes its name from the kilometer marker on the road south of Rosarito, and it is one of the most consistent waves in northern Baja. A right breaks over a rocky reef and can link into a long wall on a good day, with a left also working on some swells. It picks up swell from the south through the northwest, so there is usually something to ride. Expect a crowd when it is good, rocks and urchins on the entry, and water quality that drops after rain.', 'It works on most swell directions; northwest and west swells in winter and south swells in summer both produce good days. Mid to low tide tends to sharpen the bowl. East or northeast wind cleans it up.', 'The lots near the break are paid or guarded. Petty theft happens here, so take valuables with you. Wear booties if you are unsure about the urchins at the entry.', 'Best on a head-high to overhead swell from the west or south with offshore morning wind.'),
  ('de6575ce-4ee1-4c6b-a2cf-7009ba171c3b'::uuid, 'k-40', 'K-40 Surf Report: Puerto Nuevo Reef Forecast', 'Surf forecast for K-40, the rocky reef near Puerto Nuevo, the lobster village south of Rosarito. Swell, wind and tide conditions.', 'K-40 is a rocky reef near kilometer 40, around Puerto Nuevo, the village known for its lobster restaurants. It catches the same swells as K-38 just to the north and is usually worth a look when that spot is crowded. The reef is shallow in places, so it suits experienced surfers.', 'Check it on west to northwest swell with an east wind. Look for where the rock is covered before choosing a takeoff spot.', 'Off the free road near Puerto Nuevo. Access points are informal and can change.', 'Best on a clean west swell with light offshore wind.'),
  ('503196fa-71ee-5054-b178-1b20e6516eb8'::uuid, 'rancho-santini', 'Rancho Santini Surf Report: Puerto Nuevo Beach Forecast', 'Rancho Santini surf forecast near Puerto Nuevo, south of Rosarito. Swell, wind and tide for this beach break with a rocky shoreline.', 'Rancho Santini is a beach break in the Puerto Nuevo area south of Rosarito, backed by a residential development. The sand is mixed with rock along the shore, and the quality depends on how clean the wind is more than on the tide.', 'West swell with an east offshore wind gives the cleanest faces. If the beach is bumpy, the reefs nearby may be more sheltered.', 'Access is through a residential area, so public access and parking are not guaranteed. Check locally before you go.', 'Best on a west swell with offshore wind early in the day.'),
  ('965196e2-81c3-4c1a-8c2f-e5c9c0f8e3fd'::uuid, 'las-gaviotas', 'Las Gaviotas Surf Report: Gated Reef Near Rosarito', 'Las Gaviotas surf forecast. A soft right-hand reef inside a gated community south of Rosarito. Swell, wind, tide and access notes.', 'Las Gaviotas is a right-hand reef inside a gated community south of Rosarito. It is gentler than K-38 and suits longboards and improving surfers on smaller days. The catch is access: you generally need to be staying in the community or arrive with someone who is. The reef is flat and rocky, with urchins, and water quality can drop after rain.', 'South and southwest swells in summer and west swells in autumn both work. It handles all tides, so the wind and the crowd usually decide the session.', 'Entry is through the community''s security gate. There are no public facilities at the break, so bring what you need.', 'Best on a waist to head-high south or west swell with a calm morning.'),
  ('5c1c31ec-ad33-56f9-a865-a9cfdc8fe6c7'::uuid, 'primo-tapia', 'Primo Tapia Surf Report: Reef South of Puerto Nuevo', 'Primo Tapia surf forecast for the reef break south of Puerto Nuevo. Live swell, wind and tide, plus notes on urchins and access.', 'Primo Tapia is a small town on the free road between Puerto Nuevo and La Misión, with reef breaks in front of the residential developments along the coast. The bottom is rock with urchins, and much of the shoreline is behind private property.', 'West swell and a northeast wind are the clean combination. It works through most tides; the urchins are a good reason to wear booties.', 'Much of the coast here is fronted by private communities, so confirm access before you park.', 'Best on a west swell with a morning northeast wind.'),
  ('69f9f8d5-731c-5d2a-9f69-05eb22d00b49'::uuid, 'rauls', 'Raul''s Surf Report: Quiet Reef in Northern Baja', 'Raul''s surf forecast for a quieter reef in the Rosarito area. Swell, wind and tide, plus notes on the bluff trail and urchins.', 'Raul''s is a reef in the Rosarito area that sees far fewer surfers than the well-known breaks nearby. You park on the bluff and walk down a dirt path to the water. Expect rocks and urchins on the reef.', 'West swell, northeast wind and mid to high tide are the best combination.', 'Park on the bluff and take the dirt path down. Wear booties for the urchins.', 'Best on a west swell at mid to high tide with light offshore wind.'),
  ('985623dc-83c1-58fc-95f9-4dedaab370f9'::uuid, 'cantamar-settlement', 'Cantamar Surf Report: Beach Break by the Dunes', 'Cantamar surf forecast for the beach break near the Cantamar dunes on the Rosarito–Ensenada free road. Swell, wind, tide and rips.', 'Cantamar is a small settlement on the free road south of Puerto Nuevo, known for the big sand dunes nearby. The beach in front picks up southwest swell and can get fast and hollow when the sandbars line up. It is an open beach, so rip currents are the main hazard.', 'Southwest swell with a northeast offshore wind is the clean setup, and mid tide usually gives the best shape.', 'Reached from the free road at Cantamar. Parking is informal.', 'Best on a southwest swell at mid tide with offshore morning wind.'),
  ('5314f82b-b1b0-5777-83f3-06a76548996e'::uuid, 'dunes', 'Dunes Surf Report: Open Beach Break, Northern Baja', 'Surf forecast for Dunes, an open beach break in the La Misión area of northern Baja. Swell, wind, tide and rip current notes.', 'Dunes is an open beach break in the La Misión area, backed by sand dunes. It takes southwest and west swell and can produce punchy peaks when the sandbars are in good shape. With no reef or point to hold the sand in place, the banks move around, and rips are the main hazard.', 'Southwest swell and a northeast wind keep it cleanest. Walk the beach to find where the bank is holding shape and where the rip is running.', 'Access is informal and can change. There are no facilities at the beach.', 'Best on a southwest or west swell with offshore morning wind.'),
  ('803f0345-3d9d-5a3f-a356-083418d48884'::uuid, 'la-fonda', 'La Fonda Surf Report: K-58 Beach and Point Forecast', 'La Fonda surf forecast at kilometer 58 near La Misión. A popular beach break with a left point, below the hotel on the cliff.', 'La Fonda sits at around kilometer 58 on the toll road near La Misión, below the hotel and restaurant of the same name on the cliff. It is a beach break with a left off the point at the north end, and it is one of the most popular stops for San Diego day-trippers. It picks up a wide range of swell directions and gets heavy when the swell is big. Water quality is usually fair but drops after rain.', 'Southwest and west swells tend to give the best shape. Low to mid tide is the usual window, and east wind cleans it up.', 'Take the La Misión exit and follow the signs to the hotel and campground; a day-use fee may apply, and a cliff path leads down to the beach.', 'Best on a chest-high to overhead southwest or west swell at low to mid tide.'),
  ('97277108-adbf-5862-a941-7e489b8ebac9'::uuid, 'halfway-house', 'Halfway House Surf Report: Tijuana–Ensenada Reef', 'Halfway House surf forecast for the mixed reef and beach peaks halfway between Tijuana and Ensenada. Swell, wind and tide.', 'Halfway House takes its name from the old roadside stop roughly midway between Tijuana and Ensenada. It is a mix of rocky reef and sand, with lefts and rights across several peaks. It is a good intermediate wave, but the rocks keep it from being a beginner spot.', 'Southwest swell with a northeast wind is the best combination. It works across the tide; look for the peak where the rocks are covered.', 'Off the free road between Rosarito and Ensenada. Facilities are limited, so bring water. Rocky entries make booties useful.', 'Best on a southwest swell with a light offshore morning.'),
  ('21b6e258-cc57-5ae2-a28d-8c1ec006c3e6'::uuid, 'campo-lopez-k-55', 'Campo Lopez (K-55) Surf Report: Reef Forecast', 'Campo Lopez surf forecast at kilometer 55 on the Rosarito–Ensenada road. A consistent reef with swell, wind and tide conditions.', 'Campo Lopez is a campground and residential area at kilometer 55, with a consistent reef break out front. It is a reliable option on the stretch between Puerto Nuevo and La Misión, and it is often less crowded than the breaks closer to Rosarito.', 'Look for a west to northwest swell with an east-northeast wind. It is usually cleanest through the middle of the tide.', 'Access is through the Campo Lopez community. Ask about day access and parking.', 'Best on a west swell at mid tide with offshore wind.'),
  ('cbf331fa-1c8b-5b0c-b385-60a5ce2bc60d'::uuid, 'punta-piedra-rocky-point', 'Punta Piedra Surf Report: Rocky Point, La Misión', 'Punta Piedra (Rocky Point) surf forecast near La Misión. A fickle reef that needs a solid northwest swell. Wind and tide notes.', 'Punta Piedra, also called Rocky Point, is a reef in the La Misión area that does not break often. It needs a solid northwest swell to come alive, and when it does it is a wave for experienced surfers.', 'Wait for a solid northwest swell and east wind. Check the reef in person before trusting the forecast, since it is fickle.', 'Access is informal and can change.', 'Best on a solid northwest swell with offshore wind.'),
  ('e90e4374-d15c-5a11-9a06-e1836600fbd7'::uuid, 'k-55-1-2', 'K-55½ Surf Report: Point Break Near La Salina', 'K-55½ surf forecast for the point near La Salina on the Rosarito–Ensenada road. Swell, wind and tide conditions.', 'K-55½ is a point break just past the kilometer 55 marker, near La Salina. It sits close to the Campo Lopez reef and is one of the more consistent waves on this section of coast.', 'West to northwest swell and an east-northeast wind are the cleanest combination. Mid tide usually helps.', 'Access is informal and can change.', 'Best on a west swell at mid tide with light offshore wind.'),
  ('6fe598b7-a119-596b-acb7-a2371d3c2d61'::uuid, 'alisitos', 'Alisitos Surf Report: K-58 Campground Beach', 'Alisitos surf forecast near La Salina. A beach break by the K-58 campground, with swell, wind, tide and rocky bottom notes.', 'Alisitos is the campground area near kilometer 58, next to La Fonda. The beach break in front has a rocky bottom in places, so entry and exit need care. It is a convenient spot if you are camping on the bluff.', 'Southwest swell with a northeast wind is the clean window.', 'Access is through the campground; a day-use fee may apply.', 'Best on a southwest swell with a calm or offshore morning.'),
  ('15ca0535-e16b-5959-b19b-633355f70bdd'::uuid, 'la-mision', 'La Misión Surf Report: Beach and Reef Forecast', 'La Misión surf forecast for the beach and reef at the Guadalupe river mouth. Swell, wind, tide and current notes.', 'La Misión is the small town where the Guadalupe river meets the coast, just south of La Fonda. The beach and reef here are usually quiet, and it works best on winter northwest swell. Currents near the river mouth can be strong.', 'Northwest swell and a northeast wind are the cleanest combination; tide matters less than the wind.', 'Reached from the free road at La Misión. Parking is informal.', 'Best on a winter northwest swell with offshore wind.'),
  ('074022e2-2406-5f27-abbf-6ec2ac1256d8'::uuid, 'la-salina', 'La Salina Surf Report: Beach Break Near the Marina', 'La Salina surf forecast for the beach break near the marina south of La Misión. Swell, wind, tide and rip current notes.', 'La Salina is a beach break near the marina and residential developments south of La Misión. It works across the tide and can get crowded when it is good. Rip currents are the main hazard.', 'Southwest swell with an east wind gives the best shape.', 'Access is near the La Salina marina and residential area. Parking can be limited.', 'Best on a southwest swell with a light offshore morning.'),
  ('54252ee3-b3ad-5132-a154-77a7b6a917ca'::uuid, 'el-paso', 'El Paso Surf Report: Reef Break Near Ensenada', 'El Paso surf forecast for a rocky reef north of Ensenada. Live swell, wind and tide, plus booties and entry notes.', 'El Paso is a rocky reef on the coast north of Ensenada. It suits experienced surfers and works best at medium tide. The rocks are part of the lineup, so booties are a good idea.', 'Southwest swell with an east wind is the best setup. Aim for the middle of the tide.', 'Access is informal and can change.', 'Best on a southwest swell at medium tide with offshore wind.'),
  ('63092ce4-b394-5274-a70e-5bac21548139'::uuid, 'mirador-viewpoint', 'El Mirador Surf Report: Reef Below the Lookout', 'El Mirador surf forecast for the reef below the scenic lookout on the toll road north of Ensenada. Swell, wind and tide.', 'El Mirador is the scenic lookout on the toll road north of Ensenada, above the cliffs near Salsipuedes. The reefs below are for experienced surfers, and the rocks are the main hazard.', 'Southwest swell with an east wind is the best combination. A dropping tide can help, but look at how the reef is breaking on the day.', 'Getting to the water from the lookout is steep and not a formal route. Check access locally.', 'Best on a southwest swell with light offshore wind.'),
  ('66c07a7b-77ce-50f2-8838-856a84b78716'::uuid, 'salsipuedes', 'Salsipuedes Surf Report: Northern Baja Right Point', 'Salsipuedes surf forecast. The heavy right-hand point in the bay north of Ensenada, best on winter northwest swell. Access and tide notes.', 'Salsipuedes is the right-hand point tucked into a cliff-lined bay between Rosarito and Ensenada, and one of the best-known waves in northern Baja. It needs a solid winter northwest swell to wrap into the bay, and when it does it can be heavy and hollow over rock. The name means roughly "leave if you can", which gives a fair idea of how steep the access and the inside section can be. Land access to the bay has been restricted in recent years, so many surfers now arrive by boat from Ensenada.', 'Wait for a well-sized west-northwest winter swell and a north to northeast morning wind. Lower tides sharpen the point; check how much rock is showing on the inside before you commit.', 'Access rules for the bay have changed over time. Confirm the current route, by land or by boat from Ensenada, before you go.', 'Best on a solid winter northwest swell with offshore wind and a lower tide.'),
  ('92aa01cc-b2e8-576f-9156-d25ad8796dba'::uuid, 'islas-de-todos-santos', 'Todos Santos Island (Killers) Surf Report', 'Islas de Todos Santos surf forecast for Killers, the big-wave right off the island outside Ensenada. Northwest swell, wind and tide.', 'The Islas de Todos Santos sit off the entrance to Bahía de Todos Santos, outside Ensenada. The famous wave is Killers, a big-wave right off the northwest tip of the northern island, where deep water focuses winter northwest swell into a much bigger wave than the coast is getting. It is an expert-only wave that needs a boat, a partner and a rescue plan. Smaller, more manageable waves break elsewhere around the islands.', 'Killers comes alive on large, long-period northwest swell. Light east wind and lower tides are the classic combination.', 'Boat access only, arranged from the harbor in Ensenada. There are no facilities on the islands, so bring water, food and safety gear.', 'Best on a large, long-period winter northwest swell with light east wind.'),
  ('eceeb33f-1bc6-5fe4-b3b0-b6b5610849fe'::uuid, 'san-miguel', 'San Miguel Surf Report: Ensenada Right Point', 'San Miguel surf forecast. Northern Baja''s classic cobblestone right point, just north of Ensenada. Winter swell, wind, tide and water notes.', 'San Miguel is the cobblestone right-hand point at the north end of Ensenada, where the toll road ends at El Sauzal. It is the most consistent point in northern Baja and a standard stop for surfers heading south. West and northwest swells wrap into long walls, while south swell is mostly blocked by Punta Banda and the islands. The creek mouth at the point means the water is often poor after rain.', 'Winter west to northwest swell is the main season. Get there early before the wind shifts, and favor medium to high tide; lower tides expose more rock on the inside.', 'Right off the end of the toll road at San Miguel. Parking and camping are on site for a fee, and Ensenada has everything else nearby.', 'Best on a winter northwest swell with a morning northeast wind at medium to high tide.'),
  ('ab1d5a66-6c11-5b5c-bb81-27bd3e74c925'::uuid, '3ms', '3Ms Surf Report: El Sauzal Reef, Ensenada', '3Ms surf forecast for the reef in El Sauzal, Ensenada, next to San Miguel. Swell, wind and tide, plus water quality notes.', '3Ms is a reef break in El Sauzal, just south of San Miguel on the edge of Ensenada, and part of the Bahía de Todos Santos World Surfing Reserve. It offers lefts and rights that are more playful than the point next door, and it works on west and northwest swell through autumn and winter. The nearby industrial waterfront affects water quality, and the entry is over rock.', 'Northwest swell with a northeast to east wind is the cleanest setup. It works across the tide; booties help at the entry.', 'Park in front of the break in El Sauzal and paddle straight out.', 'Best on a winter northwest swell with offshore morning wind.'),
  ('af165901-5820-557d-8101-152f56f479d3'::uuid, 'cannery-stacks', 'Stacks Surf Report: El Sauzal Cannery Reef', 'Stacks surf forecast for the reef in front of the cannery in El Sauzal, Ensenada. Swell, wind, tide and water quality notes.', 'Stacks, also called Cannery, is the reef in front of the fish cannery''s smokestacks in El Sauzal. It sits between San Miguel and Ensenada and picks up the same winter swells. The water here is affected by the cannery and harbor, so it is not a spot to surf after rain.', 'West-northwest swell and an east-northeast wind are the best combination. Mid to high tide keeps it cleaner over the rocks.', 'In El Sauzal, next to the cannery. Parking is along the coast road.', 'Best on a west-northwest swell at mid to high tide with offshore wind.'),
  ('177aea59-debc-5dc8-a89b-0443fc3c0e16'::uuid, 'california-trailer-park', 'California Trailer Park Surf Report: Ensenada Reef', 'Surf forecast for California Trailer Park, a rocky reef in El Sauzal on the north edge of Ensenada. Swell, wind and tide.', 'California Trailer Park is a reef in the El Sauzal stretch between San Miguel and Ensenada, named for the old trailer park on the bluff. The rocks are a real factor here, so it suits experienced surfers.', 'West-northwest swell with an east-northeast wind is the clean setup. Medium to high tide gives more water over the reef.', 'Access is from the coast road in El Sauzal and can change with private property.', 'Best on a winter swell at medium to high tide with offshore wind.'),
  ('0d7e4de2-1b66-507a-9d93-c1a244beccbc'::uuid, 'ensenada-beaches', 'Ensenada Beaches Surf Report: City Beach Break', 'Ensenada surf forecast for the city beach breaks on Bahía de Todos Santos. Wave height, swell, wind, tide and water quality.', 'Ensenada''s beaches line the inside of Bahía de Todos Santos, which shelters them from much of the swell that hits the open coast. The waves are usually smaller and softer than at San Miguel or the outer reefs, which makes them a reasonable place for beginners on the right day. Ensenada has full services, including surf shops and rentals. Check water quality before you paddle out, especially after rain.', 'West to northwest swell in autumn and winter gives the most consistent surf, with an east-northeast wind cleaning it up.', 'Easy access from town with public parking near the beaches.', 'Best on a moderate west or northwest swell with a light morning offshore.'),
  ('da98b4fc-bfdf-5350-a75e-616543bd8bf2'::uuid, 'boca-de-santo-tomas', 'Boca de Santo Tomás Surf Report: La Bocana Point', 'Boca de Santo Tomás surf forecast. A right point and river mouth at La Bocana, south of Ensenada, reached by dirt road. Swell and wind.', 'Boca de Santo Tomás is at La Bocana, where the Santo Tomás valley reaches the coast south of Ensenada. There is a right-hand point, rocky beach peaks and a river mouth, and the headland and kelp can keep it cleaner than the open coast when the wind picks up. It is a camping trip more than a day trip.', 'Autumn and winter west swells with an east-northeast wind give the best sessions; south swells can also wrap in.', 'Follow the signs for La Bocana and Punta China off Highway 1 south of Ensenada. The dirt road is rough, so a high-clearance vehicle is recommended. Stock up on food and water in Ensenada.', 'Best on a west swell with light east wind, ideally with a camp setup.'),
  ('f9179d81-eb20-5863-844f-5a81ee33febb'::uuid, 'lighthouse-punta-san-jose', 'Punta San José Surf Report: Lighthouse Break', 'Punta San José (Lighthouse) surf forecast south of Ensenada. A remote, powerful break with strong currents. Swell, wind and tide.', 'Punta San José is the headland with the lighthouse south of Santo Tomás, down a long dirt road from Highway 1. The break here is powerful and exposed, with a strong current running along the point. Its remoteness keeps the crowd small.', 'West swell with an east-northeast wind is the best combination. Watch the current from shore and plan your exit before you paddle out.', 'Dirt road access from the Santo Tomás area. Services are very limited, so bring water and food.', 'Best on a moderate west swell with offshore wind.'),
  ('a29b713e-3d14-552b-85f5-a3e0a6066645'::uuid, 'punta-cabras', 'Punta Cabras Surf Report: Beach and Reef, Baja', 'Punta Cabras surf forecast north of Eréndira. A remote spread of beach and reef breaks reached by dirt road. Swell, wind and tide.', 'Punta Cabras is a stretch of reef and beach north of Eréndira, reached by dirt road from Highway 1. Rather than one defined wave, it has a spread of peaks that work on both northwest and south swell. It still feels remote, though it is busier than it used to be.', 'Southwest and northwest swells both work. Mid tide and an east wind usually give the cleanest shape.', 'Turn off Highway 1 toward Eréndira and follow the coast north. The road is dirt; carry a spare and bring everything you need.', 'Best on a moderate swell with light east wind at mid tide.'),
  ('0ad5bd52-d60d-5a76-b2ab-cec88f03c1fc'::uuid, 'k-181', 'K-181 Surf Report: Remote Reef Near Colonet', 'K-181 surf forecast for a remote reef near Punta Colonet, off Highway 1. Swell, wind and tide, plus notes on the rough access road.', 'K-181 is named for the Highway 1 kilometer marker near Colonet, where a rough road leads to a remote reef. It needs a decent swell to wake up, and the reef produces boils in the lineup. Few people surf it, which is the main appeal.', 'Look for a moderate west or northwest swell with an east wind. Mid to high tide smooths out the reef.', 'The road is unpaved and rough, so a high-clearance vehicle is recommended. There are no services, so bring water, food and a first-aid kit.', 'Best on a moderate west swell at mid to high tide.'),
  ('b695c8ce-f063-5971-9866-2b0396b6aebe'::uuid, 'san-antonio-del-mar-colonet-area', 'San Antonio del Mar (Colonet) Surf Report', 'San Antonio del Mar surf forecast west of Colonet. A quiet beach break with dunes and camping. Swell, wind, tide and water notes.', 'This San Antonio del Mar is a long, quiet beach west of Colonet, not the one in Tijuana. It is an open beach break with shifting sandbars, dunes and room to camp. The water can be affected by runoff from the nearby estuary after rain.', 'It picks up most west and northwest swells. An east wind cleans it up, and the banks work at different tides.', 'Dirt road access from Colonet. A vehicle with good clearance helps. Bring your own supplies for camping.', 'Best on a moderate west swell with a morning offshore.'),
  ('41b6841f-2f53-5f0c-bb8e-6ab25ed50246'::uuid, 'cabo-colonet', 'Cabo Colonet Surf Report: Cliffside Right Point', 'Cabo Colonet surf forecast for the long right point below the cliffs of Colonet. Needs a big swell. Wind and tide notes.', 'Cabo Colonet is the large, cliff-lined headland west of Colonet. On the right swell a long right wraps along the cliffs, but it needs real size to break and is dormant most of the time. It is a self-supported trip.', 'Wait for a large swell with some south or west in it and an offshore wind.', 'Dirt road access from Colonet. There are no services, so bring food, water and fuel.', 'Best on a large swell with offshore wind.'),
  ('592aab73-d0ca-5810-8de0-283339c775eb'::uuid, 'quatro-casas', 'Quatro Casas Surf Report: Right Reef, Northern Baja', 'Quatro Casas surf forecast. A right-hand reef on the bluffs of Baja''s Highway 1 corridor, popular with SoCal campers. Swell and wind.', 'Quatro Casas is a right-hand reef and semi-point below the bluffs south of Colonet, and a long-time favorite of Southern California surfers who camp on the cliffs. The bluffs and kelp help protect it from the wind. It works on both summer south swell and winter northwest swell.', 'Northeast wind is ideal. Head-high and bigger is when it really works.', 'Dirt roads lead to the bluffs above the break. Camping on the bluffs usually costs a small fee. Camp near others and keep valuables secure.', 'Best on a head-high south or northwest swell with a northeast wind.'),
  ('10db47bb-e976-53b5-85b1-fa2d04129800'::uuid, 'roberts-left', 'Robert''s Left Surf Report: Camalú Reef Forecast', 'Robert''s Left surf forecast for the reef near Camalú on Baja''s Highway 1 corridor. Winter swell, wind and tide notes.', 'Robert''s Left is a reef near Camalú, south of Colonet. It is mainly a winter wave, when west swell and a northeast wind line up. The rocks at the takeoff and exit need attention.', 'West swell with a northeast wind gives the cleanest shape; check how the reef is breaking before worrying about the tide.', 'Access is informal from the Camalú area and can change.', 'Best on a winter west swell with a northeast wind.'),
  ('e18bcae1-3f4e-5aca-af88-609ae5865609'::uuid, 'punta-san-jacinto-shipwrecks-baja-norte', 'Shipwrecks (San Jacinto) Surf Report: Baja Norte', 'Punta San Jacinto surf forecast. The right point by the rusting shipwreck south of Camalú. Swell, wind and tide notes.', 'Punta San Jacinto, better known as Shipwrecks, is the right point south of Camalú with the rusting hull of a wrecked ship on the beach. It is a well-known camping stop on the Highway 1 route. The wreck is a hazard in the lineup, so know where it is before you paddle out.', 'West swell with a northeast wind is the clean window. Higher tides put more water over the hazards.', 'Dirt road access from Highway 1 near San Jacinto. Camping is informal.', 'Best on a west swell with a northeast wind and a higher tide.'),
  ('e598eee7-5170-5f43-add1-8e3fc0d5065b'::uuid, 'rincon-de-baja', 'Rincón de Baja Surf Report: Sheltered Point, Camalú', 'Rincón de Baja surf forecast near Camalú. A sheltered point that rarely breaks but holds up when the wind picks up. Swell and tide.', 'Rincón de Baja is a sheltered point near Camalú. It does not break often, but its shape keeps it cleaner than the open beaches when the wind comes up.', 'Look for a west-southwest swell and a northeast wind. High tide is usually the cleanest.', 'Access is informal and can change.', 'Best on a west-southwest swell at high tide.'),
  ('22f7d737-2554-5acb-999a-20ddc111d5ef'::uuid, 'camalu', 'Camalú Surf Report: Point Break Forecast, Baja', 'Camalú surf forecast for the point at the farming town of Camalú on Highway 1. Swell, wind, tide and rocks.', 'Camalú is a farming town on Highway 1 in the San Quintín valley, with a rocky point on the coast nearby. It is a quieter stop than the better-known spots to the north.', 'Southwest swell with a northeast wind is the cleanest setup. Mid tide tends to read best.', 'Reached from the town of Camalú. Supplies are available in town.', 'Best on a southwest swell at mid tide with offshore wind.'),
  ('93109d1f-5135-58f4-8415-adfa9bb33088'::uuid, 'playa-san-ramon', 'Playa San Ramón Surf Report: San Quintín Valley', 'Playa San Ramón surf forecast near Emiliano Zapata in the San Quintín valley. Beach break swell, wind, tide and rips.', 'Playa San Ramón is a long sandy beach west of Emiliano Zapata in the San Quintín valley. It is an open beach break where the sandbars and the rips decide the session.', 'West swell with a northeast wind is the clean window. Mid tide keeps the banks lined up best.', 'Dirt road access from the valley towns. Services are in the towns along Highway 1.', 'Best on a west swell at mid tide with offshore wind.'),
  ('014c4eae-f383-5c8f-9b0a-b57a8524ea4b'::uuid, 'cabo-san-quintin', 'Cabo San Quintín Surf Report: Remote Right Point', 'Cabo San Quintín surf forecast for the remote cape below the San Quintín volcanic field. Swell, wind, tide, rocks and sharks.', 'Cabo San Quintín is the cape at the south end of the San Quintín peninsula, beyond the bay and the volcanic cones. A right-hand line forms off the cape on west swell. It is remote, with rocks and sharks to consider.', 'West swell and a northeast wind are the key checks; make sure there is enough water over the reef line.', 'Access around the bay is by rough dirt road or by boat. Bring everything you need.', 'Best on a west swell with offshore wind.'),
  ('f71eade0-4275-584d-ac67-e790a76d8c21'::uuid, 'playa-santa-maria', 'Playa Santa María Surf Report: San Quintín Beach', 'Playa Santa María surf forecast south of San Quintín. An open beach break that works on summer south swell. Wind, tide and rips.', 'Playa Santa María is the long beach south of San Quintín. It faces south swell better than most of this coast and works best in summer. Rip currents are the main hazard.', 'South swell with a northeast wind is the clean window. Mid tide usually gives the most organized faces.', 'Signed turnoff from Highway 1 south of San Quintín. Services are in town.', 'Best on a summer south swell at mid tide.'),
  ('2484c88a-f834-52da-89dc-c18efc234076'::uuid, 'cielito-lindo', 'Cielito Lindo Surf Report: South-Swell Beach Break', 'Cielito Lindo surf forecast near El Pabellón, south of San Quintín. A beach break for summer south swell with strong rips.', 'Cielito Lindo is an exposed beach south of San Quintín, near El Pabellón. It picks up south swell well and works best in summer, with lefts and rights over sand. Rip currents here are strong.', 'South to south-southwest swell with a northeast wind is the setup. Mid tide balances shape and ease.', 'Reached from the Santa María and El Pabellón area. Bring water and sun protection; there are no facilities at the break.', 'Best on a summer south swell with a morning offshore.'),
  ('3f39f6e4-410d-58ab-bfe7-50d285182384'::uuid, 'el-socorro', 'El Socorro Surf Report: Point South of San Quintín', 'El Socorro surf forecast for the point south of San Quintín. Swell, wind, tide and rock notes for a quiet lineup.', 'El Socorro is a small community on Highway 1 south of San Quintín, where the road runs close to the coast. The point here sees few surfers and has rocks in the lineup.', 'Southwest swell and an east-northeast wind give the cleanest shape. Mid to high tide is the safer window.', 'Short dirt road from Highway 1. Services are in San Quintín.', 'Best on a southwest swell at mid to high tide.'),
  ('a4a93ba5-33b9-5ed5-9c86-cfb16ac509a9'::uuid, 'casas', 'Casas Surf Report: Reef Near El Rosario', 'Casas surf forecast for the reef near El Rosario, Baja California. Swell, wind and tide, plus notes on remote access.', 'Casas is a remote reef on the coast near El Rosario, the last town before Highway 1 turns inland. It has lefts and rights, but onshore wind is common, so timing matters. The reef is sharp.', 'Southwest swell and an east-northeast wind are the clean combination; mid tide is a little easier over the reef.', 'Remote dirt road access. Bring water and supplies from El Rosario, and consider booties.', 'Best on a summer southwest swell with a rare offshore morning.'),
  ('64ed2560-ffcc-5f04-95f9-d722ab214a23'::uuid, 'punta-baja', 'Punta Baja Surf Report: Remote Point, El Rosario', 'Punta Baja surf forecast for the remote point and fishing camp west of El Rosario. Swell, wind and reef notes.', 'Punta Baja is the headland and fishing camp west of El Rosario, down a dirt road from Highway 1. It is a long point that needs the swell to line up, and it is inconsistent the rest of the time. The wind usually picks up in the afternoon.', 'West to northwest swell and an east wind are the key checks. Watch for submerged rock.', 'Take the dirt road west from El Rosario toward the fishing camp. Bring supplies from town.', 'Best on a well-aligned west swell with offshore morning wind.'),
  ('4baff8f0-1443-51d9-825e-65f00b3a9349'::uuid, 'punta-san-antonio', 'Punta San Antonio Surf Report: Remote Summer Point', 'Punta San Antonio surf forecast south of El Rosario. A remote point best on summer southwest swell. Wind, tide and rock notes.', 'Punta San Antonio is a remote point on the coast south of El Rosario. It is mainly a summer spot and sees few surfers.', 'Southwest swell with an east wind is the best combination. Check the reef and inside section before paddling out.', 'Remote dirt road access. Bring everything you need.', 'Best on a summer southwest swell with offshore wind.'),
  ('169c8722-4d0c-50a7-883d-52100164140f'::uuid, 'punta-san-carlos', 'Punta San Carlos Surf Report: Remote Right Point', 'Punta San Carlos surf forecast. A long right point on the remote coast south of El Rosario, known for surf and wind sports.', 'Punta San Carlos is a long right-hand point on a remote stretch of coast south of El Rosario, reached by a long dirt road. The strong afternoon northwest wind has made it a windsurfing and kiteboarding destination too, so surf sessions usually happen early. It picks up a wide range of swell directions.', 'South and southwest swells produce the longest rides. Mid to low tide and an early start before the wind are the usual plan. Watch for urchins.', 'It is a long, rough drive from Highway 1, and routes change after rain, so a 4x4 helps. There are no services; carry water, fuel and food.', 'Best on a south or southwest swell in the early morning before the wind.'),
  ('38f7ce57-d3e8-5e3c-8db2-5e7a708816ad'::uuid, 'punta-canoas', 'Punta Canoas Surf Report: Pacific Baja Point', 'Punta Canoas surf forecast on Baja''s remote central Pacific coast. A series of points that pick up southwest swell. Wind and tide.', 'Punta Canoas is on the remote Pacific coast of central Baja, at the northern end of the string of points that runs down toward Santa Rosalillita. The area has several setups, and it picks up southwest swell that much of northern Baja does not get. High cliffs help with the wind.', 'Southwest to west swell and a north-northeast wind are the main triggers. Low to mid tide usually gives the better shape.', 'Rough dirt road access. There are no services; camping only, with all food, water, fuel and repair gear brought in.', 'Best on a southwest swell with light north-northeast wind.'),
  ('24a94019-3bb2-5791-9a83-e4ea758706e2'::uuid, 'punta-blanca-seven-sisters', 'Punta Blanca Surf Report: Seven Sisters, Baja', 'Punta Blanca surf forecast, one of Baja''s Seven Sisters points north of Santa Rosalillita. Swell, wind, tide and access notes.', 'Punta Blanca is one of the Seven Sisters, the chain of right-hand points north of Santa Rosalillita on the central Pacific coast. It is a reef point for experienced surfers, reached by rough 4x4 tracks. Rips and sharks are part of the picture here.', 'West swell with a north-northeast wind is the main setup, and mid tide is the easier read.', 'Rough 4x4 access from the Santa Rosalillita area. There are no services, so bring fuel, water and spares.', 'Best on a solid west swell with light north-northeast wind.'),
  ('fc3cb924-1937-5194-8652-4025d82c1bb1'::uuid, 'punta-cono', 'Punta Cono Surf Report: Seven Sisters Point', 'Punta Cono surf forecast, one of the Seven Sisters points near Santa Rosalillita. Northwest swell, wind, tide and rocks.', 'Punta Cono is one of the Seven Sisters points north of Santa Rosalillita. It is a winter northwest swell spot and can get crowded quickly when it switches on, even out here.', 'Northwest swell and a north-northeast wind are the clean combination. Mid to higher tide keeps the reef cleaner.', 'Remote dirt road access; self-sufficient camping only.', 'Best on a winter northwest swell at mid to high tide.'),
  ('4799c0ab-c83e-5a06-9d80-a5e9585ca235'::uuid, 'punta-maria', 'Punta María Surf Report: Long Right, Central Baja', 'Punta María surf forecast. A long wrapping right point on Baja''s central Pacific coast that needs a big west swell. Wind and access.', 'Punta María is a long, wrapping right-hand point on the central Pacific coast, near Santa Rosalillita. It needs a proper west swell to wrap around, so it sits quiet during small spells and comes alive in winter.', 'West to northwest swell with a northeast wind is the setup; it works through most of the tide.', 'No facilities or formal parking. A capable vehicle and extra water, fuel and food are essential.', 'Best on a large winter west swell with a northeast wind.'),
  ('550d4ad3-bf26-5677-b98f-31ef73694cc4'::uuid, 'el-cardon', 'El Cardón Surf Report: Central Baja Point', 'El Cardón surf forecast for the small headland near Punta María on Baja''s central Pacific coast. Swell, wind and tide.', 'El Cardón is a smaller headland on the same stretch of coast as Punta María. Despite its size, it can produce longer rides than its neighbors on a good winter swell.', 'West to northwest swell with a northeast wind is the setup, and mid tide is the safer choice.', 'Rough dirt road access. Camping only; bring water, food and fuel.', 'Best on a winter west swell with offshore wind.'),
  ('59ab3455-db52-583f-9819-024a57730073'::uuid, 'punta-ositos', 'Punta Ositos Surf Report: Seven Sisters Point', 'Punta Ositos surf forecast for the point near Santa Rosalillita on Baja''s central coast. Swell, wind, tide and rip current notes.', 'Punta Ositos is one of the points on the coast north of Santa Rosalillita. It sees very few surfers and is a remote, self-supported spot.', 'West to west-northwest swell is the main trigger. Check the reef and entry before you commit.', 'Remote dirt road access. Bring everything you need.', 'Best on a west swell with light offshore wind.'),
  ('ffb233ec-d069-59a6-8892-f58b6d9bdb12'::uuid, 'punta-negra', 'Punta Negra Surf Report: Right Point, Central Baja', 'Punta Negra surf forecast for the right point on Baja''s central Pacific coast. Winter swell, wind and tide notes.', 'Punta Negra is a right point on the central Pacific coast of Baja. It works on winter west to northwest swell, and the cleanest conditions usually come early or late in the day.', 'West-northwest swell with a north-northeast wind is the main setup. Inspect the reef and current before paddling out.', 'The road is rough, so a high-clearance vehicle is the minimum. There are no facilities or water.', 'Best on a winter west-northwest swell in the early morning.'),
  ('98926bfd-98f3-505b-9e9c-a42fc591e743'::uuid, 'puerto-san-andres', 'Puerto San Andrés Surf Report: Hollow Right Point', 'Puerto San Andrés surf forecast north of Santa Rosalillita. A hollow right point for west swell. Wind, tide and access.', 'Puerto San Andrés is a hollow right-hand point just north of Santa Rosalillita. When a solid west swell lines up with offshore wind it is one of the better waves on this stretch, and it works through the tide.', 'West to northwest swell and light northeast wind are the main checks.', 'Rough road access; a high-clearance 4x4 is recommended. Camping is possible on site. Bring all supplies.', 'Best on a solid west swell with light offshore wind.'),
  ('dd131d2a-e3d2-50be-9d15-e177f3f7f313'::uuid, 'punta-santa-rosalillita', 'Santa Rosalillita Surf Report: Central Baja Point', 'Punta Santa Rosalillita surf forecast for the point at the fishing village on Baja''s central Pacific coast. Swell, wind and tide.', 'Santa Rosalillita is a small fishing village on the central Pacific coast, reached by a paved road from Highway 1. The point here is a reference for the area''s other breaks, including The Wall just to the south.', 'West swell and a north-northeast wind are the clean window. Check the reef cover and rips.', 'Paved road from Highway 1 to the village. Supplies are limited.', 'Best on a west swell with light offshore wind.'),
  ('f7505c91-f56c-555c-bf83-43c6c112de51'::uuid, 'punta-rosarito-the-wall', 'Punta Rosarito (The Wall) Surf Report', 'Punta Rosarito surf forecast for The Wall, the consistent reef near Santa Rosalillita in central Baja. Swell, wind and tide.', 'Punta Rosarito, better known as The Wall, is a set of west-facing reefs near Santa Rosalillita. It is known for being very consistent, and it is a good intermediate option on this remote coast. Campers build rock walls here as windbreaks.', 'West to northwest swell with a northeast wind is the setup; the tide makes little difference.', 'Dirt road access; a capable vehicle helps after rain. Free camping; bring supplies for several days.', 'Best on a moderate west swell with offshore wind.'),
  ('5a9125ab-695b-5951-baca-58721b7e312d'::uuid, 'millers-landing', 'Miller''s Landing Surf Report: El Tomatal Point', 'Miller''s Landing surf forecast at El Tomatal fish camp on Baja''s central coast. A cobblestone right point. Swell, wind and tide.', 'Miller''s Landing is a cobblestone right-hand point at El Tomatal fish camp on the central Pacific coast. It produces long walls when a west swell arrives, and there is a reef nearby with lefts and rights.', 'West swell with an east-northeast wind is the best combination; it works across the tide.', 'Rough dirt road through or near El Tomatal. A high-clearance 4x4 is recommended. Camping is available.', 'Best on a solid west swell with offshore wind.'),
  ('0a780a99-a5aa-59ec-932b-f45294da486c'::uuid, 'playa-elefante-isla-cedros', 'Playa Elefante Surf Report: Isla Cedros', 'Playa Elefante surf forecast on Isla Cedros, off Baja''s central Pacific coast. Swell, wind, tide and remote access notes.', 'Playa Elefante is on Isla Cedros, the large island off Punta Eugenia. It is a mixed sand and rock beach that picks up west and northwest swell, and getting there is a trip in itself.', 'West to northwest swell with a southeast wind is the clean window.', 'Isla Cedros is reached by small plane or boat. Plan logistics well ahead.', 'Best on a west swell with light wind.'),
  ('e1c9107d-e335-5a34-9243-17e09131840f'::uuid, 'open-doors-isla-natividad', 'Open Doors Surf Report: Isla Natividad', 'Open Doors surf forecast on Isla Natividad off Punta Eugenia, Baja California Sur. Swell, wind, tide and access notes.', 'Open Doors is on Isla Natividad, a small island off Punta Eugenia at the tip of the Vizcaíno peninsula. It is a remote wave, and access to the island is managed by the local fishing cooperative.', 'Southwest swell with a northwest wind is the setup. Plan entry and exit with the rips in mind.', 'Arrange access in advance; the island is reached by boat or small plane, and visitor access is controlled locally.', 'Best on a southwest swell with light wind.'),
  ('5aecd9cd-a3bd-572c-b245-988bbc4746b1'::uuid, 'bahia-tortugas-turtle-bay', 'Bahía Tortugas Surf Report: Turtle Bay, Baja Sur', 'Bahía Tortugas (Turtle Bay) surf forecast on the Vizcaíno peninsula. Beach break swell, wind, tide and road notes.', 'Bahía Tortugas, or Turtle Bay, is a fishing town on the Vizcaíno peninsula and a common stop for boats traveling the coast. The surf nearby is mostly small beach break that needs south swell.', 'South swell with a north wind is the clean window. Mid tide is the broadest read.', 'A long road from Highway 1 across the Vizcaíno peninsula. The town has basic services.', 'Best on a summer south swell.'),
  ('8d557db8-4bae-51a4-8aaa-26a41d023c79'::uuid, 'asuncion-bay', 'Bahía Asunción Surf Report: Pacific Baja Sur Reef', 'Bahía Asunción surf forecast on Baja California Sur''s Pacific coast. Reef swell, wind and tide, plus rocks and sharks.', 'Bahía Asunción is a fishing town on the Pacific coast of Baja California Sur, with reef breaks nearby that work on south and southwest swell.', 'Southwest swell with a north-northeast wind is the clean window. Pay attention to the rips, rocks and sharks.', 'Paved road from Highway 1. The town has basic services.', 'Best on a summer southwest swell.'),
  ('d56fc04f-f98d-5e09-9baa-fc1ca646f9a0'::uuid, 'san-hipolito', 'San Hipólito Surf Report: Pacific Baja Sur Reef', 'San Hipólito surf forecast for the reef near the fishing village on Baja California Sur''s Pacific coast. Swell, wind and tide.', 'San Hipólito is a small fishing village on the Pacific coast of Baja California Sur, south of Bahía Asunción. The reef sections around the bay work on south swell, and low tide exposes sharp rock.', 'South-southwest swell with a north-northeast wind is the clean setup. Avoid the lowest tides over the reef.', 'Reached by road from the Highway 1 turnoff toward the Pacific fishing towns. Services are basic.', 'Best on a summer south swell with light wind.'),
  ('61e90d3c-9e49-51f0-bbf5-4e554862b528'::uuid, 'la-bocana-abreojos-mulege-municipality', 'La Bocana Surf Report: Lagoon Mouth Near Abreojos', 'La Bocana surf forecast at the lagoon mouth northwest of Punta Abreojos, Baja Sur. Sandbar and point swell, wind and tide.', 'La Bocana is a small village at the mouth of a lagoon northwest of Punta Abreojos. The sandbars at the mouth produce shifting rights, with a left off the point on some swells. It is a quieter alternative to the Abreojos points.', 'South to southwest swell with a northeast wind is the setup. The sandbars move, so look before you paddle out.', 'Dirt road access; high clearance helps, especially after rain. No facilities at the break.', 'Best on a summer south swell with light offshore wind.'),
  ('a092afae-8606-5d0f-838c-ca56bf26e373'::uuid, 'campo-renes', 'Campo René Surf Report: Beach and Reef, Baja Sur', 'Campo René surf forecast on Baja California Sur''s Pacific coast. Beach and reef peaks for south swell. Wind, tide and hazards.', 'Campo René is a camp on the Pacific coast of Baja California Sur with a mix of beach and reef peaks in front. The rights and lefts change with the sand and the swell angle. Rips, rocks and urchins are all in play.', 'South and southwest swell with a northerly wind is the setup. Start with the middle of the tide and pick the peak that is holding shape.', 'Walk straight out from the beach. Find the channel before paddling, and consider booties for the reef sections.', 'Best on a chest-high to overhead south swell with offshore wind.'),
  ('6c2b7e38-dd41-5593-8123-dba5f9e759c2'::uuid, 'punta-abreojos', 'Punta Abreojos Surf Report: Remote Right Points', 'Punta Abreojos surf forecast. A fishing town with a long, multi-section right point on Baja Sur''s Pacific coast. Swell and wind.', 'Punta Abreojos is a fishing town on the Pacific coast of Baja California Sur, with a long right-hand point that breaks in several sections. South and southwest swells wrap into the bay, and the main point handles the most size. It is a destination for surfers willing to drive a long way for quiet waves.', 'South-southwest swell and a north-northwest wind are the setup. Rocks, rips and sharks are all part of the picture.', 'Road from the Highway 1 turnoff; expect some rough sections. Camping is available near the breaks; bring what you need.', 'Best on a summer south-southwest swell with light north wind.'),
  ('ad6e6d45-25ab-5b50-a67e-a34dbc204468'::uuid, 'punta-santo-domingo', 'Punta Santo Domingo Surf Report: Exposed Reef', 'Punta Santo Domingo surf forecast on Baja California Sur''s Pacific coast. A fickle, windy reef and beach. Swell and wind notes.', 'Punta Santo Domingo is an exposed stretch of reef and beach on the Pacific side of Baja California Sur. Onshore wind and strong currents are common, so it is only worth surfing on the rare calm days when the swell lines up.', 'Watch for light or offshore wind first; swell alone rarely makes it good.', 'Access is informal. There are no facilities, so bring water and sun protection.', 'Worth a look only on a calm morning with a clean swell.'),
  ('256f508b-004f-5591-9a18-fc897eac7b29'::uuid, 'la-laguna', 'La Laguna Surf Report: Remote Pacific Beach, Baja Sur', 'La Laguna surf forecast for a remote beach break on Baja California Sur''s Pacific coast. Swell, wind, tide, rips and sharks.', 'La Laguna is a remote beach break on the Pacific coast of Baja California Sur, in Mulegé municipality. It is an isolated spot with rocks, rips and sharks to consider.', 'Southwest swell with a northeast wind is the clean window.', 'Remote dirt road access. Bring everything you need.', 'Best on a summer southwest swell with offshore wind.'),
  ('ee68a84a-9e5e-5012-a8ae-cd6a45d3a110'::uuid, 'scorpion-bay-san-juanico', 'Scorpion Bay Surf Report: San Juanico Right Points', 'Scorpion Bay surf forecast for San Juanico''s long right points in Baja California Sur. South swell season, wind and tide notes.', 'Scorpion Bay is the surfers'' name for San Juanico, a small town on the Pacific coast of Baja California Sur with a series of right-hand points inside the bay. On a big south swell the points can connect into very long rides, which is why it is one of Baja''s best-known destinations. It needs a proper south swell, so it is mainly a summer and early autumn spot, and flat spells are common outside that window.', 'South to southwest swell is the main trigger, and swell size matters more than tide. A west-northwest wind blows offshore here.', 'It is a long drive from the border, with the last stretch off Highway 1 on secondary roads. The town has basic services and camping.', 'Best on a solid summer south swell.'),
  ('dee4c779-2670-5143-9372-ff9b0d8dc364'::uuid, 'punta-san-gregorio', 'Punta San Gregorio Surf Report: Comondú Coast', 'Punta San Gregorio surf forecast near San Juanico, Baja California Sur. Beach break swell, wind, tide and remote access notes.', 'Punta San Gregorio is a remote point south of San Juanico, on the Comondú coast. The waves break over sand and some rock, with urchins near the rocks.', 'West-southwest swell with a northeast wind is the clean window. Check the sandbar shape before paddling out.', 'Remote dirt road access from the San Juanico area.', 'Best on a southwest swell with offshore wind.'),
  ('250c4c39-de91-5235-8edc-54b8ae4032bf'::uuid, 'las-barrancas', 'Las Barrancas Surf Report: Reef, Baja California Sur', 'Las Barrancas surf forecast for the reef near the fishing village on Baja Sur''s Pacific coast. Swell, wind, tide and urchins.', 'Las Barrancas is a small fishing village on the Pacific coast of Comondú municipality, with a reef nearby that works across the tide. Urchins and rocks are the main hazards.', 'Southwest swell with a northeast wind is the setup.', 'Road access to the village; services are very limited.', 'Best on a southwest swell with offshore wind.'),
  ('c9daf288-10ae-5640-9b4f-c1b6efa6591c'::uuid, 'san-jorge', 'San Jorge Surf Report: Open Beach Near Las Barrancas', 'San Jorge surf forecast near Las Barrancas, Baja California Sur. Remote beach break swell, wind, tide and rip current notes.', 'San Jorge is a remote beach near Las Barrancas. It only works well when the sandbars are organized, and rips are the main hazard.', 'Southwest swell with an east-northeast wind is the clean setup.', 'Remote dirt road access. Bring everything you need.', 'Best on a southwest swell with organized sandbars.'),
  ('3a6bb36f-6a46-56cb-b6e9-69d6d4061d59'::uuid, 'punta-hughes', 'Punta Hughes Surf Report: Remote Point, Comondú', 'Punta Hughes surf forecast on the remote Comondú coast of Baja California Sur. Point swell, wind, tide and rocks.', 'Punta Hughes is a point on a remote stretch of the Comondú coast. The lineup sits over rocks, and it can be surfed through the tide.', 'Southwest swell and a northeast wind are the clean combination.', 'Remote access; bring all supplies.', 'Best on a southwest swell with offshore wind.'),
  ('15b1b54e-89c1-5b14-8943-67d1515ae7c0'::uuid, 'punta-conejo', 'Punta Conejo Surf Report: Pacific Point, La Paz', 'Punta Conejo surf forecast on the Pacific coast of La Paz municipality. A long point for south swell. Wind and dirt road notes.', 'Punta Conejo is a long point on the Pacific coast of La Paz municipality, north of Todos Santos. On a strong south or southwest swell it produces long rides, and it is also a popular spot for windsurfing. The prevailing north wind is not ideal here, so calm mornings are the target.', 'South-southwest swell with light wind is the setup; choose the section of the point that is holding shape.', 'The turnoff is signed from Highway 1, then about an hour on a rough dirt road. There are no facilities; bring water, food and fuel.', 'Best on a strong south swell with a calm morning.'),
  ('d7215651-a2be-5385-9ea1-6ea9faa9aeb7'::uuid, 'punta-marquez', 'Punta Márquez Surf Report: Quiet Point, La Paz', 'Punta Márquez surf forecast near Punta Conejo on Baja Sur''s Pacific coast. Swell, wind, tide and remote access notes.', 'Punta Márquez is a reef point near Punta Conejo on the Pacific coast of La Paz municipality. It rarely gets crowded, and it is remote.', 'Southwest swell with a northeast wind is the clean setup; it works through most of the tide.', 'Dirt road access. Bring all supplies.', 'Best on a southwest swell with offshore wind.'),
  ('aefc94c2-84fd-5016-a6e9-75f09b54b017'::uuid, 'beachbreak', 'Beachbreak Surf Report: Remote Sand, La Paz Coast', 'Surf forecast for Beachbreak on the Pacific coast of La Paz municipality. Beach peaks that work on mixed swells. Wind and tide.', 'This remote beach on the Pacific side of La Paz municipality produces punchy peaks that can work even on smaller days, especially when more than one swell is running. It is a camp-out spot with nothing on site.', 'It picks up swell from the southeast through the west-northwest; a northeast or east wind keeps it clean. It works at all tides.', '4x4 on rough dirt roads. There are no facilities, water or food. Avoid driving on soft sand.', 'Best on combined south and west swells with offshore wind.'),
  ('81e81dff-b9b9-5a5b-a1dc-24a38aed7bb1'::uuid, 'punta-colorado', 'Punta Colorado Surf Report: East Cape, La Ribera', 'Punta Colorado surf forecast near La Ribera on Baja Sur''s East Cape. A reef for southeast swell. Wind and tide notes.', 'Punta Colorado is on the East Cape near La Ribera, on the Sea of Cortez side of Baja California Sur. The reef needs a southeast to south swell, which usually means summer and tropical storm season, and it is inconsistent the rest of the year.', 'South-southeast swell with a southwest wind is the clean setup. The reef needs enough water to shape the face.', 'Reached from La Ribera on the East Cape road.', 'Best on a summer southeast swell.'),
  ('150891ea-c5b7-53c2-bc7e-213126708e8e'::uuid, 'la-bocana-todos-santos-area', 'La Bocana Surf Report: Todos Santos Beach Break', 'La Bocana surf forecast in the Todos Santos area, Baja California Sur. A consistent, powerful beach break. Swell, wind and rips.', 'La Bocana is a beach break in the Todos Santos area on the Pacific side of Baja California Sur. It is consistent and can be powerful, with rip currents to watch.', 'Southwest swell with a northeast wind gives the cleanest shape.', 'Reached from Todos Santos, which has full services.', 'Best on a southwest swell with offshore morning wind.'),
  ('50a7544f-4b5a-585e-abff-214f47151eb5'::uuid, 'punta-arenas', 'Punta Arenas Surf Report: Sand Point, East Cape', 'Punta Arenas surf forecast on Baja Sur''s East Cape near Cabo Pulmo. A sand point that needs a big south swell. Wind and tide.', 'Punta Arenas is a sand point on the East Cape near Cabo Pulmo. It needs a large south swell to produce waves and is flat much of the time. When it works, it gives short rights over sand.', 'A big south swell with a northwest wind is the setup.', 'Free roadside parking and basic camping. Bring water, food and fuel.', 'Best on a large summer south swell.'),
  ('aad65c42-a9f4-5104-807b-801a6524014c'::uuid, 'la-pastora', 'La Pastora Surf Report: Right Point, Todos Santos', 'La Pastora surf forecast for the right point north of Todos Santos. Winter and summer swell, wind, tide and rip current notes.', 'La Pastora is a right-hand point just north of Todos Santos, reached by a sandy road along the coast. It takes both winter northwest swell and summer south swell, and it is one of the more consistent waves near town.', 'Mid to low tide in the morning before the wind is usually the best time. A northeast or east wind is cleanest.', 'Sandy coast road north of Todos Santos. Town has full services.', 'Best on a morning with a west or south swell and a light offshore.'),
  ('4d0d90ab-8b06-5f06-8adc-9561cf1afa1f'::uuid, 'playa-san-pedro', 'Playa San Pedro Surf Report: Todos Santos Beach', 'Playa San Pedro surf forecast near Todos Santos, Baja California Sur. Winter beach break swell, wind, tide and rip notes.', 'Playa San Pedro is a beach break near Todos Santos that works best on winter northwest swell. The sandbars decide the shape, and rips are the main hazard.', 'Northwest swell with a northeast wind is the setup; mid tide keeps the bars lined up best.', 'Short drive from Todos Santos.', 'Best on a winter northwest swell at mid tide.'),
  ('d1c7eab1-51c9-5390-b5c5-53e9e2b13a9c'::uuid, 'el-rincon', 'El Rincón Surf Report: East Cape Rocky Point', 'El Rincón surf forecast on Baja California Sur''s East Cape. A rocky shoreline point near Cabo Pulmo. Swell, wind and tide.', 'El Rincón is a rocky shoreline point on the East Cape, near Cabo Pulmo. It works on south swell in summer and suits experienced surfers.', 'Summer south swell with a west-southwest wind is the setup; a higher tide gives more margin over the rocks.', 'Reached from the East Cape road. Services are limited.', 'Best on a summer south swell at higher tide.'),
  ('93b78607-4c26-51eb-b632-f1552805085f'::uuid, 'san-pedrito-el-pescadero', 'San Pedrito Surf Report: Right Reef Near Pescadero', 'San Pedrito surf forecast between Todos Santos and El Pescadero. A powerful right over reef, best on winter swell. Wind and tide.', 'San Pedrito is a powerful right-hand reef between Todos Santos and El Pescadero, framed by palm trees. It is at its best on winter northwest swell, when it produces long walls. The reef is sharp and there are urchins.', 'Northwest swell from late autumn to early spring with a northeast wind is the setup.', 'Follow the signed turnoff from Highway 19. Parking is right at the beach. Todos Santos is close for food and water. Booties are a good idea.', 'Best on a head-high to overhead winter northwest swell.'),
  ('438e6333-2043-5d02-8d6c-68eb99541f76'::uuid, 'cabo-pulmo', 'Cabo Pulmo Surf Report: East Cape Reef Forecast', 'Cabo Pulmo surf forecast on Baja Sur''s East Cape. A point inside the marine national park. Swell, wind, coral and rules.', 'Cabo Pulmo is the village and national marine park on the East Cape, protecting one of the few living coral reefs in the Gulf of California. The point here needs a south swell and suits experienced surfers. Treat the reef with care and follow park rules, since the coral is both a hazard and a protected resource.', 'South swell with a west-northwest wind is the clean setup. Water level and reef exposure matter more than swell size.', 'Reached by the East Cape road. Check park regulations before going in the water.', 'Best on a summer south swell with enough water over the reef.'),
  ('10f5842d-a2f5-5c44-b1e3-b5ca92ea9c58'::uuid, 'playa-las-palmas-palm-beach', 'Playa Las Palmas Surf Report: Palm Beach, Pescadero', 'Playa Las Palmas (Palm Beach) surf forecast near El Pescadero, Baja California Sur. Beach break swell, wind, tide and hazards.', 'Playa Las Palmas, also called Palm Beach, is a sheltered cove near El Pescadero backed by a palm grove. The surf here is consistent, with urchins, rips and rocks to keep in mind.', 'West-southwest swell with a northeast wind is the setup.', 'Reached from Highway 19 near El Pescadero. Walk in from the parking area.', 'Best on a west-southwest swell with offshore wind.'),
  ('abc5df3b-5290-5072-b1dc-06d984c73ebd'::uuid, 'los-frailes', 'Los Frailes Surf Report: East Cape Reef', 'Los Frailes surf forecast at the bay south of Cabo Pulmo on Baja Sur''s East Cape. Southeast swell, wind and tide notes.', 'Los Frailes is the bay just south of Cabo Pulmo on the East Cape, sheltered by the rocky headland of Cabo Frailes. The reef needs a southeast swell, which is most likely in summer and during tropical storm season.', 'Southeast swell with a west-northwest wind is the setup. Sharks and rocks are part of the read.', 'Reached by the East Cape dirt road. Services are very limited.', 'Best on a southeast swell with offshore wind.'),
  ('430bf8bc-4244-5e72-bb4f-0b2ea08d3c7d'::uuid, 'frailes-south', 'Frailes South Surf Report: East Cape Reef', 'Frailes South surf forecast south of Los Frailes on Baja Sur''s East Cape. Southeast swell, wind and reef notes.', 'Frailes South is the reef just south of Los Frailes on the East Cape. Like its neighbor, it needs a southeast swell to break.', 'Southeast swell with a west-northwest wind is the setup. Watch the reef edge.', 'East Cape dirt road access.', 'Best on a southeast swell.'),
  ('dd0c6e3e-6c47-5be2-804b-a9b4a49b603f'::uuid, 'el-pescadero', 'El Pescadero Surf Report: Beach Break, Baja Sur', 'El Pescadero surf forecast between Todos Santos and Cerritos. A-frame beach peaks for winter and summer swell. Wind and tide.', 'El Pescadero is the town between Todos Santos and Cerritos on the Pacific side of Baja California Sur. The beach in front produces A-frame peaks over sand and shallow reef, and it picks up both summer south swell and winter northwest swell. It can get crowded when it is good.', 'West-southwest swell with a northeast wind is the setup; it works across the tide. Watch for rips and rocks.', 'Right off Highway 19. Camping and services are nearby.', 'Best on a west-southwest swell with a morning offshore.'),
  ('0725f23e-04e1-5925-ba0a-34faf4280cfe'::uuid, 'boca-del-salado', 'Boca del Salado Surf Report: Los Cabos East Side', 'Boca del Salado surf forecast northeast of San José del Cabo. Beach and reef peaks for south swell. Wind, tide and hazards.', 'Boca del Salado is a mix of beach and reef peaks northeast of San José del Cabo. It is an easy trip from the Los Cabos airport area and works best on summer south swell. Urchins, rips and rocks are the main hazards.', 'South swell with a northwest wind is the setup.', 'Reachable by car from San José del Cabo. Bring water and sun protection.', 'Best on a solid summer south swell with offshore wind.'),
  ('6048ee62-b7f0-5ba0-bcb6-6f7ead7a6d6b'::uuid, 'cerritos-point', 'Cerritos Surf Report: Beginner-Friendly Beach, Baja', 'Cerritos surf forecast south of El Pescadero. A friendly beach break with a right off the point, lessons and board rentals.', 'Cerritos is the most beginner-friendly beach on this stretch of coast, south of El Pescadero. A right wraps off the headland at the north end on northwest swell, and the beach takes south swell in summer. Board rentals, lessons and food are available on the beach, and the area is developing quickly.', 'Northwest swell for the point and southwest swell for the beach. Mid tide usually gives the best shape. It gets busy on holidays.', 'Free parking at the beach, off Highway 19.', 'Best on a small to medium swell in the morning.'),
  ('6508954e-4e40-52b9-a6c0-bccf3b8a6c99'::uuid, 'punta-gasparino', 'Punta Gasparino Surf Report: Pacific Point, La Paz', 'Punta Gasparino surf forecast on the Pacific side of La Paz municipality. Northwest swell, wind and tide notes.', 'Punta Gasparino is a point on the Pacific coast of La Paz municipality. It is easy to reach by Baja standards but does not break often, mainly on winter northwest swell.', 'Northwest swell with an east wind is the setup; it can work at all tides.', 'Relatively easy access by Baja standards.', 'Best on a winter northwest swell.'),
  ('0fbe8bf2-76a8-5b59-8558-8b9fd66c9f92'::uuid, 'nine-palms', 'Nine Palms Surf Report: East Cape Right Point', 'Nine Palms surf forecast on Baja Sur''s East Cape. A long right point that fires on summer south swell. Wind and tide notes.', 'Nine Palms is a long right-hand point on the East Cape road, north of San José del Cabo, named for the palm trees above the break. It needs a south or southeast swell and is one of the best waves on the East Cape when it is on, with a northwest wind blowing offshore.', 'South to southeast swell is the trigger, and a mid incoming tide is usually the best call.', 'Park above the break on the East Cape road. There are no formal facilities.', 'Best on a head-high to overhead summer south swell.'),
  ('cbee6d3f-1532-58fa-9f1f-532ea23a9b26'::uuid, 'migrino', 'Migriño Surf Report: Point and Beach Near Cabo', 'Migriño surf forecast between Cerritos and Cabo San Lucas. A consistent point and beach on the Pacific side. Swell, wind and rips.', 'Migriño is a consistent point and beach between Cerritos and Cabo San Lucas, near a river mouth. It is a good alternative when Cerritos is crowded.', 'West-southwest swell with an east-northeast wind is the setup; tide is secondary.', 'Dirt road off Highway 19. Services are in Cabo San Lucas or Cerritos.', 'Best on a west-southwest swell with offshore wind.'),
  ('e5b82e11-0483-5cff-a76a-7bbfba9b7be5'::uuid, 'shipwrecks-east-cape', 'Shipwrecks Surf Report: East Cape, Los Cabos', 'Shipwrecks surf forecast on the East Cape north of San José del Cabo. A fast right point for south swell. Wind and tide notes.', 'Shipwrecks is a fast right-hand point on the East Cape road north of San José del Cabo, named for the wreck near the break. It is one of the most consistent spots on the East Cape during south swell season, from spring through autumn. The rides are long, and so is the paddle back.', 'South swell with a northwest wind is the setup; tide is secondary.', 'Park on the cliff and walk down. There are no facilities, so bring water.', 'Best on a summer south swell.'),
  ('f6ee6558-28e3-5e18-aad7-a06768b9741d'::uuid, 'san-jose-rivermouth', 'San José Rivermouth Surf Report: Los Cabos', 'San José del Cabo rivermouth surf forecast by the estuary. A rare, powerful A-frame for south swell. Water quality notes.', 'The San José rivermouth is at the estuary on the east end of San José del Cabo''s beach. It only breaks well when storms open the sand berm, and then it can be a powerful A-frame. Water quality near the estuary can be poor.', 'South swell with a north wind is the setup, with mid tide giving the best shape.', 'Park near La Playita or on the street by the estuary and walk over.', 'Best on a solid south swell after a storm has opened the river mouth.'),
  ('66c9fae0-ede7-50a2-8630-0d81ad9db8af'::uuid, 'acapulquito-costa-azul', 'Acapulquito (Old Man''s) Surf Report: Costa Azul', 'Acapulquito surf forecast, the gentle right at Costa Azul in San José del Cabo. A beginner-friendly reef. Swell, wind and tide.', 'Acapulquito, also called Old Man''s, is the gentle right in front of the Cabo Surf Hotel at Costa Azul. It is the most beginner-friendly wave in the San José del Cabo area, with soft walls that suit longboards and learners. Lessons and rentals are available nearby.', 'South to southwest swell with a north or northwest wind is the setup; it can be surfed from low through high tide.', 'Access from the Tourist Corridor at Costa Azul, with parking nearby.', 'Best on a small to medium south swell.'),
  ('a9806f0c-f403-568c-9b1e-7373a961d94b'::uuid, 'the-rock-la-roca-costa-azul', 'La Roca Surf Report: The Rock at Costa Azul', 'La Roca (The Rock) surf forecast at Costa Azul, near Zippers in San José del Cabo. A punchy, rocky right. Swell, wind and tide.', 'La Roca, or The Rock, is a punchy right along the beach from Zippers at Costa Azul. The lineup is full of boulders, so it is an expert wave. Mid to high tide is the safer window.', 'South and southwest swell is the setup; choose your takeoff carefully over the reef.', 'Park at Zippers and walk along the beach. You can check the break from the cliff first.', 'Best on a south swell at mid to high tide.'),
  ('1f4ca351-4452-5467-992d-3fa6992775c3'::uuid, 'zippers-costa-azul', 'Zippers Surf Report: Costa Azul, San José del Cabo', 'Zippers surf forecast at Costa Azul, San José del Cabo. The best-known wave in Los Cabos, best on summer south swell.', 'Zippers is the best-known wave in Los Cabos, a fast right over cobblestone and reef at Costa Azul, just west of San José del Cabo. It comes alive on summer south swell and gets crowded when it does. Rocks, urchins and a strong current are all part of the session.', 'South to southwest swell with a northwest wind is the setup. It works at most tides, though low to mid often gives the best shape.', 'Large parking lot at the break on the Tourist Corridor. San José del Cabo has everything else.', 'Best on a head-high to overhead summer south swell.'),
  ('91bc1063-c7eb-5345-8977-3009873dda34'::uuid, 'la-punta', 'La Punta Surf Report: Cabo San Lucas Reef', 'La Punta surf forecast in the Cabo San Lucas area. A reef for summer south swell. Wind, tide and crowd notes.', 'La Punta is a reef in the Cabo San Lucas area that works on south swell and can get crowded when it breaks.', 'South swell with a north-northwest wind is the setup.', 'Reached from the Cabo San Lucas area.', 'Best on a summer south swell.'),
  ('1373714a-b7be-502d-904d-8d450f2acbf7'::uuid, 'rancho-san-carlos', 'Rancho San Carlos Surf Report: Cabo Reef', 'Rancho San Carlos surf forecast in the Cabo San Lucas reef zone. South-southeast swell, wind and tide notes.', 'Rancho San Carlos is a reef in the Cabo San Lucas area that picks up south-southeast swell in summer.', 'South-southeast swell with a northwest wind is the setup. The reef cover matters more than the tide.', 'Reached from the Cabo San Lucas area.', 'Best on a summer south swell.'),
  ('0f42752c-36dd-5429-bf18-f947e7d086cd'::uuid, 'punta-palmilla', 'Punta Palmilla Surf Report: Los Cabos Right Point', 'Punta Palmilla surf forecast on the Tourist Corridor near San José del Cabo. A consistent right point for south swell.', 'Punta Palmilla is the right-hand point near the Palmilla resort on the Tourist Corridor, west of San José del Cabo. It is one of the more consistent spots in the area during south swell season.', 'South swell with a northwest wind is the setup; check the reef cover and how the shoulder is breaking.', 'Access is from the Tourist Corridor. Use public beach access points.', 'Best on a summer south swell.'),
  ('32902ed8-5a5e-57e5-9385-cc3eef938dcf'::uuid, 'monuments', 'Monuments Surf Report: Cabo San Lucas Left', 'Monuments surf forecast in Cabo San Lucas. A steep left that picks up west and southwest swell. Wind, tide and access.', 'Monuments is the steep left at the east end of Cabo San Lucas bay, where deep water near the headland focuses west and southwest swell. It is one of the few spots near Cabo that picks up winter swell, and it is close to town. The takeoff zone is tight, and afternoon wind often ruins it.', 'West and southwest swells are the main triggers, with a north or northeast wind. Go early.', 'Access runs through a gated resort area on the Tourist Corridor; surfers are usually let in. Park above and take the trail down.', 'Best on a west or southwest swell in the early morning.'),
  ('94e9fbaf-3fbf-546f-a682-6f8a7f73d633'::uuid, 'bahia-chileno', 'Bahía Chileno Surf Report: Tourist Corridor Bay', 'Bahía Chileno surf forecast on the Los Cabos Tourist Corridor. A snorkeling bay that occasionally breaks on south swell.', 'Bahía Chileno is a sheltered bay on the Tourist Corridor, better known for swimming and snorkeling. The reef only breaks on a strong south-southeast swell, and it is inconsistent.', 'South-southeast swell with a northwest wind is the setup.', 'Signed public access from the Tourist Corridor with parking close to the beach.', 'Worth a look only on a strong south swell.'),
  ('73174046-db66-5b82-86fe-64707b3cb7da'::uuid, 'backwash', 'Backwash Surf Report: Cabo San Lucas Beach', 'Backwash surf forecast in the Cabo San Lucas area. A beach that needs a solid southeast to south swell. Wind and tide.', 'Backwash is a beach in the Cabo San Lucas area that needs a solid southeast to south swell to break, so it is inconsistent.', 'South-southeast swell with a northwest wind is the setup. Skip it if the waves look soft.', 'Reached from the Cabo San Lucas area.', 'Best on a solid summer south swell.'),
  (NULL::uuid, 'teresas', 'Teresa''s Surf Report: Rosarito Break Forecast', 'Teresa''s surf forecast in Rosarito, Baja California, near K-38 and Popotla. Live swell, wind and tide, plus notes on the tide window.', 'Teresa''s is a lesser-known break in the Rosarito area, on the same stretch of coast as K-38 and Popotla. It gets overlooked because of its better-known neighbors, but it can be a good wave on the right tide. It suits experienced surfers.', 'It tends to be punchier on a lower tide. Onshore wind hurts the shape quickly, so aim for an early session.', 'Access is informal and can change. Rosarito has food and supplies.', 'Best on a clean swell at lower tide with a calm or offshore morning.');

-- Teresa's predates the Baja import and has no stable import id.
UPDATE _mexico_beach_copy c
SET beach_id = b.id
FROM public.beaches b
WHERE c.beach_id IS NULL
  AND b.slug = c.slug
  AND b.country = 'Mexico'
  AND b.deleted_at IS NULL;

DO $$
DECLARE
  unresolved integer;
  matched integer;
BEGIN
  SELECT count(*) INTO unresolved
  FROM _mexico_beach_copy c
  WHERE c.beach_id IS NULL
     OR NOT EXISTS (
       SELECT 1 FROM public.beaches b
       WHERE b.id = c.beach_id AND b.country = 'Mexico' AND b.slug = c.slug
     );
  IF unresolved <> 0 THEN
    RAISE EXCEPTION 'Mexico beach copy: % rows do not match a Mexico beach by id and slug', unresolved;
  END IF;

  UPDATE public.beaches b
  SET seo_title = c.seo_title,
      seo_description = c.seo_description,
      description = c.description,
      wave_tips = c.wave_tips,
      access_tips = c.access_tips,
      best_conditions_prose = c.best_conditions_prose
  FROM _mexico_beach_copy c
  WHERE b.id = c.beach_id;
  GET DIAGNOSTICS matched = ROW_COUNT;
  IF matched <> 113 THEN
    RAISE EXCEPTION 'Mexico beach copy: expected 113 updates, got %', matched;
  END IF;
END;
$$;

INSERT INTO public.beach_photos (
  beach_id, source, source_id, image_url, thumb_url, title,
  creator_name, creator_url, license_code, license_url, attribution_html,
  approved, fetched_at
)
SELECT v.beach_id, 'wikimedia', v.source_id, v.image_url, v.thumb_url, v.title,
       v.creator_name, v.creator_url, v.license_code, v.license_url, v.attribution_html,
       true, now()
FROM (VALUES
  ('2394a731-17a2-58a6-ab5b-2b445b525f76'::uuid, '47813259', 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Coastline_south_of_Tijuana_-_panoramio.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Coastline_south_of_Tijuana_-_panoramio.jpg/1280px-Coastline_south_of_Tijuana_-_panoramio.jpg', 'Coastline south of Tijuana, near San Antonio del Mar', 'Alistair Cunningham', 'https://commons.wikimedia.org/?curid=47813259', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0', 'Photo: <a href="https://commons.wikimedia.org/?curid=47813259">Coastline south of Tijuana - panoramio.jpg</a> by Alistair Cunningham, <a href="https://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>, via Wikimedia Commons. Shows the surrounding area, not necessarily the break.'),
  ('f3750657-2f49-5a07-a9c9-0c80c7d628ef'::uuid, '65581081', 'https://upload.wikimedia.org/wikipedia/commons/8/84/Popotla_fishing_village_2015.jpg', 'https://upload.wikimedia.org/wikipedia/commons/8/84/Popotla_fishing_village_2015.jpg', 'Popotla fishing village', 'FOODHOE', 'https://commons.wikimedia.org/?curid=65581081', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0', 'Photo: <a href="https://commons.wikimedia.org/?curid=65581081">Popotla fishing village 2015.jpg</a> by FOODHOE, <a href="https://creativecommons.org/licenses/by-sa/3.0">CC BY-SA 3.0</a>, via Wikimedia Commons. Shows the surrounding area, not necessarily the break.'),
  ('63092ce4-b394-5274-a70e-5bac21548139'::uuid, '47813294', 'https://upload.wikimedia.org/wikipedia/commons/9/96/Coastline_north_of_Ensenada_-_panoramio.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Coastline_north_of_Ensenada_-_panoramio.jpg/1280px-Coastline_north_of_Ensenada_-_panoramio.jpg', 'Coastline north of Ensenada', 'Alistair Cunningham', 'https://commons.wikimedia.org/?curid=47813294', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0', 'Photo: <a href="https://commons.wikimedia.org/?curid=47813294">Coastline north of Ensenada - panoramio.jpg</a> by Alistair Cunningham, <a href="https://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>, via Wikimedia Commons. Shows the surrounding area, not necessarily the break.'),
  ('eceeb33f-1bc6-5fe4-b3b0-b6b5610849fe'::uuid, '90169045', 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Piedras_apiladas_en_playa_San_Miguel%2C_Ensenada_Baja_California.jpg', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Piedras_apiladas_en_playa_San_Miguel%2C_Ensenada_Baja_California.jpg/1280px-Piedras_apiladas_en_playa_San_Miguel%2C_Ensenada_Baja_California.jpg', 'Cobblestone shore at Playa San Miguel, Ensenada', 'Alexandra Valtierra Soto', 'https://commons.wikimedia.org/?curid=90169045', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Photo: <a href="https://commons.wikimedia.org/?curid=90169045">Piedras apiladas en playa San Miguel, Ensenada Baja California.jpg</a> by Alexandra Valtierra Soto, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>, via Wikimedia Commons. Shows the surrounding area, not necessarily the break.'),
  ('dd0c6e3e-6c47-5be2-804b-a9b4a49b603f'::uuid, '34485264', 'https://upload.wikimedia.org/wikipedia/commons/6/6b/El_Pescadero_beach_2013-03-12.jpg', 'https://upload.wikimedia.org/wikipedia/commons/6/6b/El_Pescadero_beach_2013-03-12.jpg', 'El Pescadero beach', 'Andrea Tosatto from Torino, Italia', 'https://commons.wikimedia.org/?curid=34485264', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0', 'Photo: <a href="https://commons.wikimedia.org/?curid=34485264">El Pescadero beach 2013-03-12.jpg</a> by Andrea Tosatto from Torino, Italia, <a href="https://creativecommons.org/licenses/by/2.0">CC BY 2.0</a>, via Wikimedia Commons. Shows the surrounding area, not necessarily the break.')
) AS v(beach_id, source_id, image_url, thumb_url, title, creator_name, creator_url, license_code, license_url, attribution_html)
JOIN public.beaches b ON b.id = v.beach_id AND b.country = 'Mexico'
ON CONFLICT (beach_id, source, source_id) DO NOTHING;

COMMIT;
