-- UNAPPLIED FORWARD MIGRATION (2026-08-16)
--
-- Move inland beach coordinates onto the waterline.
--
-- A Mapbox water-layer audit of all 346 beaches found 99 whose stored point is
-- more than 120m from water; 247 were already fine. Del Mar sat 276m inland on
-- Camino Del Mar. beaches.lat/lon is not only the map pin — it feeds NOAA/CDIP
-- station selection and nearby-spot distance — so those beaches were reading
-- conditions from a point that is not the break.
--
-- Corrects 95 of them, every one verified to face open ocean. Candidates were
-- generated by stepping seaward until within 40m of water (along the beach's
-- aspect_deg where present, otherwise along the bearing to the nearest water
-- polygon), then each candidate was re-tested 1km and 3km further out. Only
-- points still in water at both distances are included here: open ocean stays
-- water for kilometres, an inland creek or lagoon does not.
--
-- 20 candidates initially FAILED that test, because walking toward the NEAREST
-- water found inland rivers and creeks and led away from the coast (confirmed
-- by eye: rosarito-beach went 800m east to a river, crystal-cove 1km north into
-- the hills). Those were re-solved by sweeping all 360 degrees in 20-degree
-- steps and accepting only a bearing whose water is still water at +1km and
-- +3km. 18 of the 20 resolved that way and are included; spot-checked on
-- rendered maps, rosarito-beach now lands on Playa de Rosarito and crystal-cove
-- on the shoreline at PCH.
--
-- Two remain excluded because no open ocean exists within 2km on any bearing,
-- meaning the stored point is wrong by more than a nudge:
--   scarborough-beach-scarborough-me
--   florence-south-jetty
--
-- Caveat on the large moves: corrections over ~1km place the beach on the
-- correct coastline, but not necessarily at the exact named break.
-- andrew-molera-river-mouth-big-sur-ca lands on the coast south of the river
-- mouth itself. Still a large improvement on 2km inland, and per-row reversible
-- from beach_coordinate_corrections.
--
-- Keyed on beaches.id: slug carries only non-unique indexes, so a duplicate
-- slug would silently update two rows.
--
-- Reversible: prior values are captured in beach_coordinate_corrections before
-- the UPDATE. Rollback statement at the bottom of this file.

BEGIN;

CREATE TABLE IF NOT EXISTS public.beach_coordinate_corrections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  beach_id uuid NOT NULL REFERENCES public.beaches(id) ON DELETE CASCADE,
  slug text NOT NULL,
  old_lat double precision NOT NULL,
  old_lon double precision NOT NULL,
  new_lat double precision NOT NULL,
  new_lon double precision NOT NULL,
  reason text NOT NULL,
  corrected_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.beach_coordinate_corrections ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.beach_coordinate_corrections IS
  'Audit + rollback source for beach lat/lon corrections. One row per changed beach.';

CREATE TEMP TABLE _coord_fix (beach_id uuid PRIMARY KEY, new_lat double precision, new_lon double precision) ON COMMIT DROP;

INSERT INTO _coord_fix (beach_id, new_lat, new_lon) VALUES
  ('80efa1c0-37a2-4879-819b-647ae3c3d749'::uuid, 33.019881, -117.285014),
  ('fb0ee60f-a269-47ed-b244-e8dc64fff891'::uuid, 40.175979, -74.009637),
  ('5e72b79d-a12d-4cd3-8da4-b7b92069efbf'::uuid, 32.959464, -117.2684),
  ('fea10ecf-6b55-4cc9-b29b-f215f923759d'::uuid, 36.022631, -75.659848),
  ('f84767c3-4c79-42ed-9e77-2351ab80d20e'::uuid, 40.313059, -73.975482),
  ('7a093b7e-2230-4bf1-abeb-9b31faa794d5'::uuid, 33.8841, -118.413064),
  ('77903282-042b-4294-b6b2-2e3815489513'::uuid, 18.515531, -67.090578),
  ('c02b4ede-69d9-440e-b8de-22ea4bde10ef'::uuid, 32.781986, -117.254657),
  ('deea2ae1-849d-47a1-9c27-b7bd505dbc07'::uuid, 33.0469, -117.297987),
  ('da8ad733-8e6b-4781-8b3f-0fe4ee492c3f'::uuid, 33.613186, -117.934125),
  ('2380adaa-a07c-44f4-9444-656ef51fa998'::uuid, 33.0257, -117.288029),
  ('6c4b160d-8aba-4078-aca7-9bde1bf81738'::uuid, 34.011715, -118.500836),
  ('3c8f272b-473a-4303-83b7-3081579a042b'::uuid, 43.11846, -124.432173),
  ('d264fbf8-0525-4d31-adb5-9a0742eaeb7e'::uuid, 35.226608, -75.523723),
  ('32c84ce9-ba42-464c-afad-58e4c8664d1e'::uuid, 21.66635, -158.05045),
  ('124c7751-a232-4c92-be53-3a750a315256'::uuid, 35.105, -120.624392),
  ('dc3e8490-9560-4713-8b87-dcc1a6a89c53'::uuid, 21.703356, -157.998747),
  ('e5fee219-672c-4113-a0bb-a86a5d97700f'::uuid, 33.186, -117.37704),
  ('902a215b-2a3d-40af-9391-16b0afed7dee'::uuid, 33.046, -117.298358),
  ('c0f23f4b-fcc4-4849-88f4-cb6da7206d80'::uuid, 36.690764, -121.812031),
  ('9b292a48-7a88-4d79-926f-16601515d7a0'::uuid, 32.840443, -117.282078),
  ('c62b7ad4-8deb-4275-889d-b0eb8ec7c5f0'::uuid, 42.052296, -124.299165),
  ('6932c9a6-bc1f-46b7-9493-51c587bf7eb0'::uuid, 33.757401, -118.146717),
  ('4836065b-e9a9-4568-912d-41ca148ddce0'::uuid, 43.248126, -70.596935),
  ('65809772-20bc-4009-b9b2-89c8ef3c4127'::uuid, 32.797429, -117.258157),
  ('ee2aad76-966d-4aa3-86a2-499fde59b271'::uuid, 35.142, -120.644197),
  ('c778cc0a-2094-4649-84cd-4c38ce864f23'::uuid, 38.964235, -123.708007),
  ('49739de1-95fb-4e26-b890-56fafd8d2622'::uuid, 37.593671, -122.519849),
  ('dca521c3-ab32-46c6-8045-8aa7477f59a8'::uuid, 36.972751, -121.948054),
  ('0e550715-3367-4829-8671-8f38bd5be34f'::uuid, 40.456517, -73.987021),
  ('09affcd2-1eca-4f7d-852e-413972ea4154'::uuid, 33.0238, -117.286228),
  ('e6602d4e-7b5a-456d-b675-230ca5501cde'::uuid, 33.737367, -118.106661),
  ('9ca1fa2f-2b90-4aa3-8784-48721e5463bb'::uuid, 29.47498, -81.123904),
  ('65d3a4de-1f4b-4a1d-8ce0-b5b67288ee08'::uuid, 32.9914, -117.274313),
  ('326941d7-6c39-4e82-b045-941b156f7897'::uuid, 33.862029, -118.403696),
  ('110a87b2-cb2c-4bb7-8e83-b895fb2f4940'::uuid, 33.856029, -118.401696),
  ('adcd7128-424e-46d3-b8d1-f3aad6dd5edb'::uuid, 43.565721, -70.281247),
  ('bd7a7984-d69a-4969-85b1-b97ea78d8fb7'::uuid, 43.332353, -124.374403),
  ('9e94759c-d531-4e5c-9bc2-d022acea9dcd'::uuid, 32.578072, -117.133005),
  ('ffc0dcae-83d7-4b90-ade3-03c14e789088'::uuid, 44.67365, -124.06345),
  ('a4472f56-626e-4905-b909-5f1dc27174a9'::uuid, 30.293218, -81.388387),
  ('b2286d82-0f40-45db-b4d1-3774950f6632'::uuid, 45.898312, -123.96348),
  ('005b0ba6-a2d9-4069-adbb-6571baffa698'::uuid, 34.034719, -118.681876),
  ('11467f21-5a69-430d-9eb9-05a46cd39990'::uuid, 33.992186, -118.481634),
  ('1279cf64-8ef0-4bb9-b786-6dd77fc2c201'::uuid, 40.217297, -74.00103),
  ('5c7c2a2e-3c7f-4a8c-8e8a-5cf2e9a0b101'::uuid, 35.369676, -120.870862),
  ('615ff20a-922f-4487-88d8-fa7d830ebacf'::uuid, 43.346619, -124.347969),
  ('281b7eef-bcc3-4ecd-998f-1faa190ed956'::uuid, 47.896963, -124.628836),
  ('94f1010b-c71f-4025-bda1-c26ed9467c85'::uuid, 32.644819, -117.148271),
  ('fa19107a-a276-4257-872d-c5331264d01b'::uuid, 26.069884, -97.154611),
  ('91df193c-f2c8-4e6c-984e-b859bd741061'::uuid, 32.806163, -117.263817),
  ('071db1df-b5ee-4af6-a022-ea8a09667cbe'::uuid, 33.655118, -118.004126),
  ('37ffa92a-d811-4791-afbb-b90a86dcdf49'::uuid, 33.860197, -118.401177),
  ('0f0a1339-f7d0-4b1a-ae95-61939998b4ef'::uuid, 34.397171, -119.732621),
  ('84564bea-a736-474e-a822-efa55be830ee'::uuid, 40.199531, -74.005707),
  ('ef5d9f02-6dfa-4513-92c2-c158dc8c17b5'::uuid, 38.933147, -74.907382),
  ('a57ae4c8-7a27-4d3f-91d5-6229350fb888'::uuid, 33.463768, -117.699309),
  ('8d4afe79-ac68-4508-84d5-9175282a3f2c'::uuid, 42.407026, -124.425803),
  ('71fa4843-1235-4f11-9184-fe1c87e8fbc5'::uuid, 22.222855, -159.563124),
  ('53cc78d5-a759-4153-8a2e-b13cf1bb6b4e'::uuid, 33.612183, -117.92774),
  ('a3344c6e-847a-4d85-84f4-6c8de7f7256f'::uuid, 40.15096, -74.023412),
  ('a956de46-b204-448e-a541-db427be7e85f'::uuid, 33.380086, -117.575655),
  ('f7ebea96-dc6c-4a32-b881-9969cce2f986'::uuid, 39.276596, -74.568319),
  ('336e967d-86a6-40db-9404-e398b057fefe'::uuid, 39.274708, -74.571012),
  ('cf59e55d-f146-4a72-8daf-5781a0693d13'::uuid, 45.202097, -123.964194),
  ('0f0dcd5a-be9d-4c0d-a7ba-d6f932f9b769'::uuid, 33.526549, -117.771456),
  ('1f8660f2-891d-4f79-8f16-cad8ebd59c79'::uuid, 33.531058, -117.774974),
  ('bec2d595-ed20-4c2b-93c7-4b880406332f'::uuid, 34.371224, -119.455292),
  ('294712f3-3c06-44bd-9bc6-17275675fe9a'::uuid, 32.263478, -116.998),
  ('4d6c17f9-5fd9-40d6-b9c3-cd0e25ce5bcb'::uuid, 40.195704, -74.013717),
  ('73bb4a48-3d53-42ba-bbd0-d89a7cf95711'::uuid, 33.471397, -117.720065),
  ('ec7b1ab4-5f43-4af3-b45f-325d29b8d5e6'::uuid, 32.262807, -116.997887),
  ('2a2195ef-27d1-4b35-a006-b7177b34dad2'::uuid, 33.533001, -117.777011),
  ('387c8c1c-d6e3-494e-96d9-e5b025aa995b'::uuid, 42.741567, -124.496054),
  ('6cbb1b4f-d25e-40a3-a78a-b138ebdf9e96'::uuid, 32.263307, -116.997746),
  ('81dac2f3-8646-4f01-b8e3-a863c421ba2a'::uuid, 40.288418, -73.982209),
  ('83572ce5-aa5d-4631-925c-9e4a19967a7c'::uuid, 40.156515, -74.019576),
  ('99c6a506-e4b7-42e4-be2d-c3afb303c22e'::uuid, 21.270372, -157.817797),
  ('5a5dc7b8-4d30-44af-9715-3dbb4dbc9859'::uuid, 37.897301, -122.642743),
  ('5c0969f9-8496-4291-830e-8caea021d7cc'::uuid, 37.910272, -122.684615),
  ('502bd50f-21c8-4cdc-ae96-1d53fcbc34de'::uuid, 33.635469, -117.9739),
  ('de6575ce-4ee1-4c6b-a2cf-7009ba171c3b'::uuid, 32.2024, -116.910026),
  ('3b2d3a98-7c91-4d8a-81a4-6e0d5d2b9a04'::uuid, 36.269144, -121.847326),
  ('3a0a42c0-85e0-47ef-938b-fc9c29fd030f'::uuid, 40.184514, -74.020116),
  ('e28bbce6-2ad8-478c-9271-3dc82461975d'::uuid, 40.169151, -74.020485),
  ('0e557ec4-355a-4176-8352-6ea50e379c13'::uuid, 33.560534, -117.8235),
  ('04ab6e6a-477f-49ab-b435-6b201134bcbf'::uuid, 46.972614, -124.152307),
  ('b9c4a949-4562-47db-ae7d-b2131e20d7a7'::uuid, 33.452956, -117.6668),
  ('a0e764f1-d0bb-4341-b397-7b21823cb93b'::uuid, 33.626591, -117.9533),
  ('f0ddfc6a-7392-40c5-9211-836c05e449f1'::uuid, 32.346908, -117.065553),
  ('f0d0c0d9-6c1a-4d2b-9f4e-9f7bb7b8c205'::uuid, 36.459286, -121.925338),
  ('839bab65-0ae4-443e-94a5-0d5bb4b4a5a8'::uuid, 46.35343, -124.066818),
  ('a83def7f-6b68-402f-a0ef-f78a5bcfbf81'::uuid, 46.900392, -124.095326),
  ('22d65140-1c40-4bbe-8790-5068fa6e5f22'::uuid, 19.925617, -155.887),
  ('260868de-b952-470b-a764-b95b3e7f6655'::uuid, 46.895783, -124.091925);

INSERT INTO public.beach_coordinate_corrections
  (beach_id, slug, old_lat, old_lon, new_lat, new_lon, reason)
SELECT b.id, b.slug, b.lat, b.lon, f.new_lat, f.new_lon,
       'inland-coordinate-audit-2026-08-16: stepped seaward to the waterline, open-ocean verified at +1km and +3km'
FROM public.beaches b
JOIN _coord_fix f ON f.beach_id = b.id
WHERE b.lat IS DISTINCT FROM f.new_lat OR b.lon IS DISTINCT FROM f.new_lon;

UPDATE public.beaches b
SET lat = f.new_lat,
    lon = f.new_lon
FROM _coord_fix f
WHERE f.beach_id = b.id
  AND (b.lat IS DISTINCT FROM f.new_lat OR b.lon IS DISTINCT FROM f.new_lon);

COMMIT;

-- ROLLBACK (run manually if these corrections need to be undone):
--
-- BEGIN;
-- UPDATE public.beaches b
-- SET lat = c.old_lat, lon = c.old_lon
-- FROM public.beach_coordinate_corrections c
-- WHERE c.beach_id = b.id
--   AND c.reason LIKE 'inland-coordinate-audit-2026-08-16%';
-- DELETE FROM public.beach_coordinate_corrections
-- WHERE reason LIKE 'inland-coordinate-audit-2026-08-16%';
-- COMMIT;
