BEGIN;

WITH spot_profiles (
  slug,
  city,
  region,
  description,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preferred_tide_direction,
  best_months,
  best_conditions_prose,
  wave_tips,
  parking_tips,
  access_tips,
  crowd_tips,
  local_etiquette,
  crowd_level,
  warnings,
  real_takeaways,
  cdip_station,
  cdip_eligible
) AS (
  VALUES
    (
      'church',
      'San Clemente',
      'Orange County',
      'Church sits in the San Onofre / Trestles-area south of San Mateo Creek, but public surf traffic usually approaches it from the San Clemente/Trestles side. It is a cobblestone beach and rivermouth setup with point-like right walls when west swell and enough tide line up. South pulses spread the lineup into multiple peaks, and bigger southwest swells can make the wave feel much more serious than its mellow reputation.',
      'beach',
      'intermediate',
      ARRAY['rocks', 'cobblestones', 'rip currents', 'crowds', 'storm runoff near San Mateo Creek']::text[],
      ARRAY['cobblestone bottom', 'rivermouth contours', 'public trail access', 'long right-hand walls', 'state park approach']::text[],
      180::numeric,
      285::numeric,
      45::numeric,
      30::numeric,
      2::numeric,
      4::numeric,
      NULL::text,
      ARRAY[6, 7, 8, 9, 10]::integer[],
      'Best on west to southwest swell with light northeast offshore wind and enough tide to smooth the cobblestones; straight south swells spread the lineup into more peaks.',
      'Look for the longer right when the point-like section lines up; weaker angles can section, while south energy creates more takeoff zones around the creek-mouth cobbles.',
      'There is no simple public drive-up lineup parking. Most public surfers use the Trestles/San Mateo approach and walk or bike in; Camp Pendleton-side San Onofre Beach access is restricted to eligible patrons.',
      'Treat Church as a Trestles-area long-walk spot. Public access comes via trail approaches rather than vehicle access to the sand.',
      'Usually less compressed than Lowers, but still busy when a lined-up swell hits. Average days and weekday mornings are easier.',
      'Respect the rotating peak and stay clear of surfers already trimming down the line.',
      'crowded',
      ARRAY['Long walk or bike access', 'Observe posted San Onofre and Trestles closure hours', 'Check water quality after storm runoff near San Mateo Creek']::text[],
      ARRAY['Border-zone San Onofre / Trestles-area wave with San Clemente public access context', 'Long-walk cobblestone setup that rewards the right west to southwest swell']::text[],
      '45'::text,
      true
    ),
    (
      'cottons',
      'San Clemente',
      'Orange County',
      'Cottons is the northern end of the Trestles cluster at San Mateo Point and is best understood as a Trestles / San Onofre border-zone wave with San Clemente surf taxonomy. The wave is a cobblestone point-and-reef style left that often breaks farther offshore than nearby peaks and can feel softer on average swells. Larger, longer-period south swells and lower tide add speed, shape, and more consequence through the inside.',
      'point',
      'intermediate',
      ARRAY['rocks', 'cobblestones', 'shorebreak', 'rip currents']::text[],
      ARRAY['cobblestone reef', 'left focus', 'occasional right', 'public trail access', 'San Mateo Point']::text[],
      160::numeric,
      225::numeric,
      45::numeric,
      30::numeric,
      1::numeric,
      4::numeric,
      NULL::text,
      ARRAY[6, 7, 8, 9, 10]::integer[],
      'Best on south to southwest groundswell with light northeast offshore wind; larger, longer-period south swells and lower tide make the left faster and more consequential.',
      'Think long left first. Average days can be softer and more cutback-oriented, but stronger south pulses push the outside point into faster walls and a more serious inside.',
      'There is no lineup parking at the point itself. Plan on the Trestles-style walk or bike approach from public San Onofre/San Mateo side access.',
      'Public access is by hiking or biking in along the Trestles approach rather than driving to the wave.',
      'Usually less compressed than Uppers or Lowers, but it gets busy when the south pulse is right because it becomes a real alternative to the famous peaks.',
      'Respect the left-point rotation and avoid paddling wide only to angle into the inside from under surfers already on line.',
      'moderate',
      ARRAY['Long walk or bike access', 'Rocks and shorebreak get more serious on bigger south swell']::text[],
      ARRAY['Trestles-zone point/reef with San Clemente taxonomy', 'Average days are softer; stronger south swell and lower tide sharpen the wave']::text[],
      '45'::text,
      true
    ),
    (
      'riviera',
      'San Clemente',
      'Orange County',
      'Riviera is a south San Clemente beachbreak reached from the Plaza a La Playa access and the coastal trail. It is more of a local beach setup than a marquee reef, and it tends to be less consistent than T-Street but less crowded when it turns on. The wave is a punchy, often rippy beachbreak that likes solid south to southwest swell, with enough shape for fun peaks when the sand cooperates.',
      'beach',
      'intermediate',
      ARRAY['rip currents', 'undertow', 'pollution after rain']::text[],
      ARRAY['sand bottom', 'public beach access', 'coastal trail access', 'Plaza a La Playa access']::text[],
      160::numeric,
      250::numeric,
      45::numeric,
      30::numeric,
      2::numeric,
      4::numeric,
      NULL::text,
      ARRAY[6, 7, 8, 9, 10]::integer[],
      'Best on solid south to southwest groundswell with light morning wind and mid tide; shape depends heavily on sandbars.',
      'Expect short, punchy peaks rather than long walls. Riviera is less consistent than T-Street, so sandbar quality and recent swell direction matter a lot.',
      'Use the Plaza a La Playa street approach. Parking is free on nearby streets, but spaces near the cul-de-sac are limited and there are no full facilities at the access.',
      'Public access is a neighborhood stair/path off Plaza a La Playa, with the San Clemente Coastal Trail passing the beach.',
      'Usually a step down from T-Street on crowd intensity. Weekdays and average south pulses are the easiest windows to find room.',
      'Keep the narrow neighborhood access clear and do not block the stair or path while suiting up.',
      'moderate',
      ARRAY['Check water quality after rain or visible runoff', 'No full facilities at the Riviera access itself']::text[],
      ARRAY['Local-access beachbreak, not a destination reef', 'Less crowded than T-Street, but also less consistent']::text[],
      '45'::text,
      true
    ),
    (
      't-street',
      'San Clemente',
      'Orange County',
      'T-Street is San Clemente''s best-known in-town surf spot and one of the most consistent everyday waves on this stretch. The setup blends beachbreak and reef influence, with local sub-zones commonly described around the Reef, Cropley''s, and Beach House. South to southwest swell drives the main consistency, while selective northwest winter energy can light up different corners.',
      'beach',
      'beginner-intermediate',
      ARRAY['rocks', 'reef', 'crowds', 'seasonal surf and swim zones']::text[],
      ARRAY['beach and reef setup', 'public stairs access', 'concessions', 'fire rings', 'coastal trail access']::text[],
      160::numeric,
      300::numeric,
      45::numeric,
      30::numeric,
      1::numeric,
      5::numeric,
      NULL::text,
      ARRAY[6, 7, 8, 9, 10]::integer[],
      'Most consistent on south to southwest groundswell with light northeast offshores; stronger pulses wake up the outside reef, while selective northwest swell can work Cropley''s in winter.',
      'Use the sub-zones in your read: the Reef for outside structure, Cropley''s for selective winter northwest energy, and Beach House for wedgier inside lefts and rights.',
      'Metered bluff-top parking sits close to the stairs, with free neighborhood parking farther out. The easy spaces fill quickly and meter enforcement runs into the evening.',
      'Primary access is by the stairs and overpass down to the beach. The coastal trail also links T-Street with the pier to the north and Calafia/State Beach to the south.',
      'Expect one of the tighter and more local-feeling lineups in town. Weekdays and less obvious wind or tide windows are the easiest times to find breathing room.',
      'Respect the rotation, especially at the Reef, and avoid paddling straight through the main takeoff zone from the stairs side.',
      'very_crowded',
      ARRAY['Verify current city surf/swim zoning and blackball postings', 'Parking demand is heavy near the stairs']::text[],
      ARRAY['Consistency plus multiple sub-breaks is the draw', 'Easy access keeps the lineup busy']::text[],
      '45'::text,
      true
    ),
    (
      'san-clemente-state-beach',
      'San Clemente',
      'Orange County',
      'San Clemente State Beach is the broad beachbreak below the campground bluffs at the south end of town. It is consistently surfable, more approachable than the high-pressure Trestles peaks, and often works as a lower-stress fallback when the marquee reefs are crowded. The beach offers a long stretch of sand-bottom peaks with room to spread out when the bars cooperate.',
      'beach',
      'beginner-intermediate',
      ARRAY['rip currents', 'rocks', 'unstable bluffs']::text[],
      ARRAY['sand bottom', 'campground', 'day-use lot', 'public trail access', 'beach trail connection']::text[],
      140::numeric,
      245::numeric,
      45::numeric,
      30::numeric,
      1::numeric,
      5::numeric,
      'either',
      ARRAY[6, 7, 8, 9, 10]::integer[],
      'Generally likes south to southwest groundswell with light northeast offshores and can stay workable through more of the tide range than the nearby reefier setups.',
      'Expect a long beachbreak canvas rather than one defined peak. Beginning board riders can find approachable corners, while better surfers still score on cresting sections when summer or fall swell lines up.',
      'Use the state beach day-use lot or campground parking rules rather than hunting for lineup-adjacent curb spots.',
      'Beach access comes from the bluff-top day-use area via ravine trails, and the beach links into the San Clemente Coastal Trail and Calafia side.',
      'Usually mellower than the Trestles magnets and useful as a fallback when Lowers is packed, though easy-access entries still get busy on summer weekends.',
      'Spread out on the open beachbreak instead of bunching at the first obvious peak below the access trail.',
      'moderate',
      ARRAY['Rip currents occur here', 'Bluffs are unstable; stay on designated trails', 'Dogs are not allowed on the beach or trails except service animals', 'Fires are not permitted on the beach']::text[],
      ARRAY['More beginner-usable than most nearby named spots', 'Better access and parking than Trestles make it a lower-pressure fallback']::text[],
      '45'::text,
      true
    )
)
UPDATE public.beaches AS b
SET
  city = profile.city,
  region = profile.region,
  description = profile.description,
  break_type = profile.break_type,
  skill_level = profile.skill_level,
  hazards = profile.hazards,
  features = profile.features,
  swell_window_min_deg = profile.swell_window_min_deg,
  swell_window_max_deg = profile.swell_window_max_deg,
  wind_offshore_deg = profile.wind_offshore_deg,
  wind_offshore_tol_deg = profile.wind_offshore_tol_deg,
  preferred_tide_ft_min = profile.preferred_tide_ft_min,
  preferred_tide_ft_max = profile.preferred_tide_ft_max,
  preferred_tide_direction = profile.preferred_tide_direction,
  best_months = profile.best_months,
  best_conditions_prose = profile.best_conditions_prose,
  wave_tips = profile.wave_tips,
  parking_tips = profile.parking_tips,
  access_tips = profile.access_tips,
  crowd_tips = profile.crowd_tips,
  local_etiquette = profile.local_etiquette,
  crowd_level = profile.crowd_level,
  warnings = profile.warnings,
  real_takeaways = profile.real_takeaways,
  cdip_station = profile.cdip_station,
  cdip_eligible = profile.cdip_eligible
FROM spot_profiles AS profile
WHERE b.slug = profile.slug
  AND b.deleted_at IS NULL;

COMMIT;
