BEGIN;

-- Comprehensive swell window fix derived from terrain ray-tracing data
-- Generated by scripts/derive-swell-windows.ts on 2026-02-11
-- Threshold: 0.15, Beaches updated: 251

-- Beach: K-40 (Puerto Nuevo) (Puerto Nuevo, BAJA CALIFORNIA)
-- Active swell access bins: 28-71 (140deg - 355deg)
-- Previous: min=270 max=315 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 355,
  swell_window_center_deg = 247.5,
  swell_window_halfwidth_deg = 107.5
WHERE id = 'de6575ce-4ee1-4c6b-a2cf-7009ba171c3b';

-- Beach: Alfonsos (Rosarito, BAJA CALIFORNIA)
-- Active swell access bins: 22-2 (110deg - 10deg) [WRAPS]
-- Previous: min=180 max=247 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 110,
  swell_window_max_deg = 10,
  swell_window_center_deg = 240,
  swell_window_halfwidth_deg = 130
WHERE id = '6e083f22-4c11-46c5-9110-ac7500f6cba5';

-- Beach: El Morro Point (K37.5) (Rosarito, BAJA CALIFORNIA)
-- Active swell access bins: 0-71 (0deg - 355deg)
-- Previous: min=180 max=225 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 355,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 177.5
WHERE id = '6cbb1b4f-d25e-40a3-a78a-b138ebdf9e96';

-- Beach: K-38 (Rosarito, BAJA CALIFORNIA)
-- Active swell access bins: 25-2 (125deg - 10deg) [WRAPS]
-- Previous: min=180 max=290 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 125,
  swell_window_max_deg = 10,
  swell_window_center_deg = 247.5,
  swell_window_halfwidth_deg = 122.5
WHERE id = '77d286c5-87e9-4678-82d3-81d0125285fa';

-- Beach: Las Gaviotas (Rosarito, BAJA CALIFORNIA)
-- Active swell access bins: 14-69 (70deg - 345deg)
-- Previous: min=180 max=225 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 70,
  swell_window_max_deg = 345,
  swell_window_center_deg = 207.5,
  swell_window_halfwidth_deg = 137.5
WHERE id = '965196e2-81c3-4c1a-8c2f-e5c9c0f8e3fd';

-- Beach: Renes (Rosarito, BAJA CALIFORNIA)
-- Active swell access bins: 13-2 (65deg - 10deg) [WRAPS]
-- Previous: min=180 max=247 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 65,
  swell_window_max_deg = 10,
  swell_window_center_deg = 217.5,
  swell_window_halfwidth_deg = 152.5
WHERE id = '294712f3-3c06-44bd-9bc6-17275675fe9a';

-- Beach: Rosarito Beach (Rosarito, BAJA CALIFORNIA)
-- Active swell access bins: 28-71 (140deg - 355deg)
-- Previous: min=200 max=315 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 355,
  swell_window_center_deg = 247.5,
  swell_window_halfwidth_deg = 107.5
WHERE id = 'f0ddfc6a-7392-40c5-9211-836c05e449f1';

-- Beach: Teresa's (Rosarito, BAJA CALIFORNIA)
-- Active swell access bins: 24-2 (120deg - 10deg) [WRAPS]
-- Previous: min=270 max=315 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 120,
  swell_window_max_deg = 10,
  swell_window_center_deg = 245,
  swell_window_halfwidth_deg = 125
WHERE id = 'ec7b1ab4-5f43-4af3-b45f-325d29b8d5e6';

-- Beach: Avila Beach (Avila Beach, CA)
-- Active swell access bins: 16-44 (80deg - 220deg)
-- Previous: min=160 max=240 center=200 half=40
UPDATE beaches SET
  swell_window_min_deg = 80,
  swell_window_max_deg = 220,
  swell_window_center_deg = 150,
  swell_window_halfwidth_deg = 70
WHERE id = '0e7a0a9f-3a0b-44a2-b81c-43a6f7b2a203';

-- Beach: Bodega Bay / Doran Beach (Bodega Bay, CA)
-- Active swell access bins: 13-47 (65deg - 235deg)
-- Previous: min=260 max=320 center=290 half=30
-- Secondary windows: 68-5 (340deg - 25deg) [WRAPS]
UPDATE beaches SET
  swell_window_min_deg = 65,
  swell_window_max_deg = 235,
  swell_window_center_deg = 150,
  swell_window_halfwidth_deg = 85
WHERE id = '92e18cf0-97c3-4c68-9cdf-800eb9ac4313';

-- Beach: Bolinas (Bolinas, CA)
-- Active swell access bins: 17-61 (85deg - 305deg)
-- Previous: min=260 max=330 center=295 half=35
UPDATE beaches SET
  swell_window_min_deg = 85,
  swell_window_max_deg = 305,
  swell_window_center_deg = 195,
  swell_window_halfwidth_deg = 110
WHERE id = '5c0969f9-8496-4291-830e-8caea021d7cc';

-- Beach: Capitola (Capitola, CA)
-- Active swell access bins: 13-48 (65deg - 240deg)
-- Previous: min=150 max=220 center=185 half=35
UPDATE beaches SET
  swell_window_min_deg = 65,
  swell_window_max_deg = 240,
  swell_window_center_deg = 152.5,
  swell_window_halfwidth_deg = 87.5
WHERE id = 'dca521c3-ab32-46c6-8045-8aa7477f59a8';

-- Beach: George's (Cardiff-by-the-Sea, CA)
-- Active swell access bins: 27-1 (135deg - 5deg) [WRAPS]
-- Previous: min=180 max=270 center=293 half=23
UPDATE beaches SET
  swell_window_min_deg = 135,
  swell_window_max_deg = 5,
  swell_window_center_deg = 250,
  swell_window_halfwidth_deg = 115
WHERE id = '7dca6429-25ee-4161-a2c2-800555ed8a6a';

-- Beach: Pipes (Cardiff-by-the-Sea, CA)
-- Active swell access bins: 28-0 (140deg - 0deg) [WRAPS]
-- Previous: min=180 max=270 center=293 half=23
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 0,
  swell_window_center_deg = 250,
  swell_window_halfwidth_deg = 110
WHERE id = '2380adaa-a07c-44f4-9444-656ef51fa998';

-- Beach: San Elijo State Beach (Cardiff-by-the-Sea, CA)
-- Active swell access bins: 28-1 (140deg - 5deg) [WRAPS]
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 5,
  swell_window_center_deg = 252.5,
  swell_window_halfwidth_deg = 112.5
WHERE id = '09affcd2-1eca-4f7d-852e-413972ea4154';

-- Beach: Carlsbad State Beach (Carlsbad, CA)
-- Active swell access bins: 30-49 (150deg - 245deg)
-- Previous: min=180 max=270 center=270 half=45
UPDATE beaches SET
  swell_window_min_deg = 150,
  swell_window_max_deg = 245,
  swell_window_center_deg = 197.5,
  swell_window_halfwidth_deg = 47.5
WHERE id = 'c0977bcd-5475-4745-b4b8-0ca1e16a7faf';

-- Beach: Ponto (Carlsbad, CA)
-- Active swell access bins: 32-2 (160deg - 10deg) [WRAPS]
-- Previous: min=180 max=270 center=245 half=65
UPDATE beaches SET
  swell_window_min_deg = 160,
  swell_window_max_deg = 10,
  swell_window_center_deg = 265,
  swell_window_halfwidth_deg = 105
WHERE id = 'badd7986-4609-421a-ab3d-81fcd8409a5b';

-- Beach: Tamarack (Carlsbad, CA)
-- Active swell access bins: 23-70 (115deg - 350deg)
-- Previous: min=180 max=350 center=265 half=85
UPDATE beaches SET
  swell_window_min_deg = 115,
  swell_window_max_deg = 350,
  swell_window_center_deg = 232.5,
  swell_window_halfwidth_deg = 117.5
WHERE id = 'b1b49703-2376-407d-b1fb-9df06130ac1d';

-- Beach: Terramar Point (Carlsbad, CA)
-- Active swell access bins: 29-71 (145deg - 355deg)
-- Previous: min=180 max=350 center=265 half=85
UPDATE beaches SET
  swell_window_min_deg = 145,
  swell_window_max_deg = 355,
  swell_window_center_deg = 250,
  swell_window_halfwidth_deg = 105
WHERE id = '1fe4bf73-c425-48a5-899d-a7e8ee2d67e3';

-- Beach: Rincon (Carpinteria, CA)
-- Active swell access bins: 40-62 (200deg - 310deg)
-- Previous: min=270 max=315 center=null half=null
-- Secondary windows: 20-37 (100deg - 185deg)
UPDATE beaches SET
  swell_window_min_deg = 200,
  swell_window_max_deg = 310,
  swell_window_center_deg = 255,
  swell_window_halfwidth_deg = 55
WHERE id = 'bec2d595-ed20-4c2b-93c7-4b880406332f';

-- Beach: Cayucos Pier (south side) (Cayucos, CA)
-- Active swell access bins: 32-60 (160deg - 300deg)
-- Previous: min=240 max=310 center=275 half=35
UPDATE beaches SET
  swell_window_min_deg = 160,
  swell_window_max_deg = 300,
  swell_window_center_deg = 230,
  swell_window_halfwidth_deg = 70
WHERE id = '1bd1a1f5-5c8a-4607-8d7b-0b8f0d2c9b02';

-- Beach: Shipwrecks (Coronado, CA)
-- Active swell access bins: 14-0 (70deg - 0deg) [WRAPS]
-- Previous: min=180 max=240 center=210 half=30
UPDATE beaches SET
  swell_window_min_deg = 70,
  swell_window_max_deg = 0,
  swell_window_center_deg = 215,
  swell_window_halfwidth_deg = 145
WHERE id = '5e8d07ff-786c-4b7e-ab19-53d2b3774e23';

-- Beach: Doheny (Dana Point, CA)
-- Active swell access bins: 17-59 (85deg - 295deg)
-- Previous: min=180 max=270 center=200 half=28
UPDATE beaches SET
  swell_window_min_deg = 85,
  swell_window_max_deg = 295,
  swell_window_center_deg = 190,
  swell_window_halfwidth_deg = 105
WHERE id = 'a57ae4c8-7a27-4d3f-91d5-6229350fb888';

-- Beach: Doheny State Beach (Dana Point, CA)
-- Active swell access bins: 19-47 (95deg - 235deg)
-- Previous: min=180 max=270 center=200 half=28
UPDATE beaches SET
  swell_window_min_deg = 95,
  swell_window_max_deg = 235,
  swell_window_center_deg = 165,
  swell_window_halfwidth_deg = 70
WHERE id = 'a4575b12-2bc3-44d4-ba53-4415707f3851';

-- Beach: Salt Creek (Dana Point, CA)
-- Active swell access bins: 29-50 (145deg - 250deg)
-- Previous: min=190 max=250 center=210 half=30
-- Secondary windows: 55-60 (275deg - 300deg)
UPDATE beaches SET
  swell_window_min_deg = 145,
  swell_window_max_deg = 250,
  swell_window_center_deg = 197.5,
  swell_window_halfwidth_deg = 52.5
WHERE id = '73bb4a48-3d53-42ba-bbd0-d89a7cf95711';

-- Beach: Strands (Dana Point, CA)
-- Active swell access bins: 13-65 (65deg - 325deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 65,
  swell_window_max_deg = 325,
  swell_window_center_deg = 195,
  swell_window_halfwidth_deg = 130
WHERE id = '80e4aada-7d4a-4df1-b11b-841a97603979';

-- Beach: Waddell Creek (Davenport, CA)
-- Active swell access bins: 33-59 (165deg - 295deg)
-- Previous: min=200 max=310 center=255 half=55
UPDATE beaches SET
  swell_window_min_deg = 165,
  swell_window_max_deg = 295,
  swell_window_center_deg = 230,
  swell_window_halfwidth_deg = 65
WHERE id = '1913d8a0-38f9-468f-bb4c-18789e92731d';

-- Beach: Del Mar (Del Mar, CA)
-- Active swell access bins: 27-70 (135deg - 350deg)
-- Previous: min=190 max=340 center=265 half=75
UPDATE beaches SET
  swell_window_min_deg = 135,
  swell_window_max_deg = 350,
  swell_window_center_deg = 242.5,
  swell_window_halfwidth_deg = 107.5
WHERE id = '5e72b79d-a12d-4cd3-8da4-b7b92069efbf';

-- Beach: Del Mar Rivermouth (Del Mar, CA)
-- Active swell access bins: 27-5 (135deg - 25deg) [WRAPS]
-- Previous: min=205 max=315 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 135,
  swell_window_max_deg = 25,
  swell_window_center_deg = 260,
  swell_window_halfwidth_deg = 125
WHERE id = '7fc84dd8-abcc-4d7c-9ade-3d1500c1c24c';

-- Beach: El Segundo Beach Jetty (El Segundo, CA)
-- Active swell access bins: 30-70 (150deg - 350deg)
-- Previous: min=200 max=300 center=250 half=50
UPDATE beaches SET
  swell_window_min_deg = 150,
  swell_window_max_deg = 350,
  swell_window_center_deg = 250,
  swell_window_halfwidth_deg = 100
WHERE id = 'be03bc6f-878a-4806-bff2-9cf870a9f241';

-- Beach: Beacons (Encinitas, CA)
-- Active swell access bins: 26-4 (130deg - 20deg) [WRAPS]
-- Previous: min=180 max=270 center=259 half=56
UPDATE beaches SET
  swell_window_min_deg = 130,
  swell_window_max_deg = 20,
  swell_window_center_deg = 255,
  swell_window_halfwidth_deg = 125
WHERE id = '22536002-c7d2-48ab-a676-9b489fd79874';

-- Beach: Cardiff Reef (Encinitas, CA)
-- Active swell access bins: 38-2 (190deg - 10deg) [WRAPS]
-- Previous: min=220 max=340 center=280 half=60
UPDATE beaches SET
  swell_window_min_deg = 190,
  swell_window_max_deg = 10,
  swell_window_center_deg = 280,
  swell_window_halfwidth_deg = 90
WHERE id = '80efa1c0-37a2-4879-819b-647ae3c3d749';

-- Beach: D Street (Encinitas, CA)
-- Active swell access bins: 32-64 (160deg - 320deg)
-- Previous: min=180 max=320 center=250 half=70
UPDATE beaches SET
  swell_window_min_deg = 160,
  swell_window_max_deg = 320,
  swell_window_center_deg = 240,
  swell_window_halfwidth_deg = 80
WHERE id = '902a215b-2a3d-40af-9391-16b0afed7dee';

-- Beach: Grandview (Encinitas, CA)
-- Active swell access bins: 27-2 (135deg - 10deg) [WRAPS]
-- Previous: min=180 max=270 center=245 half=65
UPDATE beaches SET
  swell_window_min_deg = 135,
  swell_window_max_deg = 10,
  swell_window_center_deg = 252.5,
  swell_window_halfwidth_deg = 117.5
WHERE id = 'f29ddb0a-6d46-4589-a4a4-da406ddd3d5c';

-- Beach: Moonlight State Beach (Encinitas, CA)
-- Active swell access bins: 32-63 (160deg - 315deg)
-- Previous: min=180 max=315 center=248 half=68
UPDATE beaches SET
  swell_window_min_deg = 160,
  swell_window_max_deg = 315,
  swell_window_center_deg = 237.5,
  swell_window_halfwidth_deg = 77.5
WHERE id = 'deea2ae1-849d-47a1-9c27-b7bd505dbc07';

-- Beach: Swami's (Encinitas, CA)
-- Active swell access bins: 41-58 (205deg - 290deg)
-- Previous: min=200 max=325 center=263 half=63
-- Secondary windows: 61-65 (305deg - 325deg)
UPDATE beaches SET
  swell_window_min_deg = 205,
  swell_window_max_deg = 290,
  swell_window_center_deg = 247.5,
  swell_window_halfwidth_deg = 42.5
WHERE id = 'b24c6fa9-9f82-4a1e-afcd-0d1fb0ce69d0';

-- Beach: Campus Point (UCSB) (Goleta, CA)
-- Active swell access bins: 9-62 (45deg - 310deg)
-- Previous: min=170 max=220 center=195 half=25
UPDATE beaches SET
  swell_window_min_deg = 45,
  swell_window_max_deg = 310,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 132.5
WHERE id = '8de2c2cf-2b8d-4a4e-8d5e-3e7b5d5c7d07';

-- Beach: Refugio State Beach (Goleta, CA)
-- Active swell access bins: 11-63 (55deg - 315deg)
-- Previous: min=250 max=310 center=280 half=30
UPDATE beaches SET
  swell_window_min_deg = 55,
  swell_window_max_deg = 315,
  swell_window_center_deg = 185,
  swell_window_halfwidth_deg = 130
WHERE id = 'a17f4c57-324d-4157-a641-fa935464302e';

-- Beach: Oceano / Grover Beach (Grover Beach, CA)
-- Active swell access bins: 32-71 (160deg - 355deg)
-- Previous: min=230 max=300 center=265 half=35
UPDATE beaches SET
  swell_window_min_deg = 160,
  swell_window_max_deg = 355,
  swell_window_center_deg = 257.5,
  swell_window_halfwidth_deg = 97.5
WHERE id = '124c7751-a232-4c92-be53-3a750a315256';

-- Beach: Mavericks (Half Moon Bay, CA)
-- Active swell access bins: 10-3 (50deg - 15deg) [WRAPS]
-- Previous: min=270 max=330 center=300 half=30
UPDATE beaches SET
  swell_window_min_deg = 50,
  swell_window_max_deg = 15,
  swell_window_center_deg = 212.5,
  swell_window_halfwidth_deg = 162.5
WHERE id = '033b5518-ee98-4014-9d81-114b936778af';

-- Beach: Hermosa Pier (Hermosa Beach, CA)
-- Active swell access bins: 29-66 (145deg - 330deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 145,
  swell_window_max_deg = 330,
  swell_window_center_deg = 237.5,
  swell_window_halfwidth_deg = 92.5
WHERE id = '37ffa92a-d811-4791-afbb-b90a86dcdf49';

-- Beach: HB Cliffs (Huntington Beach, CA)
-- Active swell access bins: 25-67 (125deg - 335deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 125,
  swell_window_max_deg = 335,
  swell_window_center_deg = 230,
  swell_window_halfwidth_deg = 105
WHERE id = 'd60dd5c8-d147-4042-a531-c2ec55c620af';

-- Beach: Huntington Beach Pier (Huntington Beach, CA)
-- Active swell access bins: 18-67 (90deg - 335deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 90,
  swell_window_max_deg = 335,
  swell_window_center_deg = 212.5,
  swell_window_halfwidth_deg = 122.5
WHERE id = '071db1df-b5ee-4af6-a022-ea8a09667cbe';

-- Beach: Huntington Beach Pier Northside (Huntington Beach, CA)
-- Active swell access bins: 41-62 (205deg - 310deg)
-- Previous: min=180 max=270 center=null half=null
-- Secondary windows: 19-35 (95deg - 175deg)
UPDATE beaches SET
  swell_window_min_deg = 205,
  swell_window_max_deg = 310,
  swell_window_center_deg = 257.5,
  swell_window_halfwidth_deg = 52.5
WHERE id = '72726bcb-bed0-4b76-8336-f90d7fb57159';

-- Beach: Huntington Beach Pier Southside (Huntington Beach, CA)
-- Active swell access bins: 19-62 (95deg - 310deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 95,
  swell_window_max_deg = 310,
  swell_window_center_deg = 202.5,
  swell_window_halfwidth_deg = 107.5
WHERE id = '025cfc18-8357-49d6-994e-e0abf0a16f6d';

-- Beach: Huntington St. (Huntington Beach, CA)
-- Active swell access bins: 17-0 (85deg - 0deg) [WRAPS]
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 85,
  swell_window_max_deg = 0,
  swell_window_center_deg = 222.5,
  swell_window_halfwidth_deg = 137.5
WHERE id = 'b57b32b9-0057-46f6-9fa9-cd35d5bd5319';

-- Beach: Huntington State Beach (Huntington Beach, CA)
-- Active swell access bins: 19-65 (95deg - 325deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 95,
  swell_window_max_deg = 325,
  swell_window_center_deg = 210,
  swell_window_halfwidth_deg = 115
WHERE id = '502bd50f-21c8-4cdc-ae96-1d53fcbc34de';

-- Beach: North HB Streets (Huntington Beach, CA)
-- Active swell access bins: 27-65 (135deg - 325deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 135,
  swell_window_max_deg = 325,
  swell_window_center_deg = 230,
  swell_window_halfwidth_deg = 95
WHERE id = '66ef3c08-a8a2-4cf1-9361-273489bac45b';

-- Beach: Imperial Beach (Imperial Beach, CA)
-- Active swell access bins: 28-47 (140deg - 235deg)
-- Previous: min=180 max=270 center=225 half=45
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 235,
  swell_window_center_deg = 187.5,
  swell_window_halfwidth_deg = 47.5
WHERE id = '9e94759c-d531-4e5c-9bc2-d022acea9dcd';

-- Beach: Devereux / Sands (Coal Oil Point) (Isla Vista, CA)
-- Active swell access bins: 16-66 (80deg - 330deg)
-- Previous: min=230 max=300 center=265 half=35
UPDATE beaches SET
  swell_window_min_deg = 80,
  swell_window_max_deg = 330,
  swell_window_center_deg = 205,
  swell_window_halfwidth_deg = 125
WHERE id = 'f7fbc2c4-7c4e-4c2c-8f8a-5e3bd1ee8e08';

-- Beach: Jalama Beach (Jalama, CA)
-- Active swell access bins: 23-60 (115deg - 300deg)
-- Previous: min=230 max=310 center=270 half=40
UPDATE beaches SET
  swell_window_min_deg = 115,
  swell_window_max_deg = 300,
  swell_window_center_deg = 207.5,
  swell_window_halfwidth_deg = 92.5
WHERE id = '1ec3682e-d993-4c60-a650-f630e1ea3b06';

-- Beach: Agate Street (Laguna Beach, CA)
-- Active swell access bins: 30-53 (150deg - 265deg)
-- Previous: min=180 max=270 center=null half=null
-- Secondary windows: 59-60 (295deg - 300deg)
UPDATE beaches SET
  swell_window_min_deg = 150,
  swell_window_max_deg = 265,
  swell_window_center_deg = 207.5,
  swell_window_halfwidth_deg = 57.5
WHERE id = '0f0dcd5a-be9d-4c0d-a7ba-d6f932f9b769';

-- Beach: Brooks Street (Laguna Beach, CA)
-- Active swell access bins: 22-64 (110deg - 320deg)
-- Previous: min=180 max=270 center=200 half=30
UPDATE beaches SET
  swell_window_min_deg = 110,
  swell_window_max_deg = 320,
  swell_window_center_deg = 215,
  swell_window_halfwidth_deg = 105
WHERE id = '1f8660f2-891d-4f79-8f16-cad8ebd59c79';

-- Beach: Rockpile (Laguna Beach, CA)
-- Active swell access bins: 36-67 (180deg - 335deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 180,
  swell_window_max_deg = 335,
  swell_window_center_deg = 257.5,
  swell_window_halfwidth_deg = 77.5
WHERE id = '79e8be90-df33-4b80-9d92-e79e26a67a69';

-- Beach: Thalia Street (Laguna Beach, CA)
-- Active swell access bins: 22-63 (110deg - 315deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 110,
  swell_window_max_deg = 315,
  swell_window_center_deg = 212.5,
  swell_window_halfwidth_deg = 102.5
WHERE id = '2a2195ef-27d1-4b35-a006-b7177b34dad2';

-- Beach: Big Rock (La Jolla, CA)
-- Active swell access bins: 19-5 (95deg - 25deg) [WRAPS]
-- Previous: min=200 max=310 center=255 half=55
-- Secondary windows: 9-9 (45deg - 45deg)
UPDATE beaches SET
  swell_window_min_deg = 95,
  swell_window_max_deg = 25,
  swell_window_center_deg = 240,
  swell_window_halfwidth_deg = 145
WHERE id = 'dbbafa09-3143-4f73-82e8-90a69a4121f5';

-- Beach: Birdrock (La Jolla, CA)
-- Active swell access bins: 23-69 (115deg - 345deg)
-- Previous: min=180 max=270 center=248 half=45
UPDATE beaches SET
  swell_window_min_deg = 115,
  swell_window_max_deg = 345,
  swell_window_center_deg = 230,
  swell_window_halfwidth_deg = 115
WHERE id = 'ca2b1d6f-2428-4273-ab02-7555eeec4323';

-- Beach: Horseshoe (La Jolla, CA)
-- Active swell access bins: 30-6 (150deg - 30deg) [WRAPS]
-- Previous: min=180 max=270 center=248 half=23
UPDATE beaches SET
  swell_window_min_deg = 150,
  swell_window_max_deg = 30,
  swell_window_center_deg = 270,
  swell_window_halfwidth_deg = 120
WHERE id = '30e68b00-c27d-4d22-ba57-2d92156964c6';

-- Beach: La Jolla Shores (La Jolla, CA)
-- Active swell access bins: 39-5 (195deg - 25deg) [WRAPS]
-- Previous: min=195 max=350 center=273 half=78
UPDATE beaches SET
  swell_window_min_deg = 195,
  swell_window_max_deg = 25,
  swell_window_center_deg = 290,
  swell_window_halfwidth_deg = 95
WHERE id = 'd291411d-d331-4bf1-ad1a-302da3c69de0';

-- Beach: Scripps (La Jolla, CA)
-- Active swell access bins: 36-5 (180deg - 25deg) [WRAPS]
-- Previous: min=195 max=345 center=270 half=75
UPDATE beaches SET
  swell_window_min_deg = 180,
  swell_window_max_deg = 25,
  swell_window_center_deg = 282.5,
  swell_window_halfwidth_deg = 102.5
WHERE id = '4b0cf129-c706-4e24-8210-2219defc5ea7';

-- Beach: Windansea (La Jolla, CA)
-- Active swell access bins: 30-4 (150deg - 20deg) [WRAPS]
-- Previous: min=180 max=340 center=260 half=80
UPDATE beaches SET
  swell_window_min_deg = 150,
  swell_window_max_deg = 20,
  swell_window_center_deg = 265,
  swell_window_halfwidth_deg = 115
WHERE id = '6f42d47d-215b-47cb-ac14-b83bf8c2a797';

-- Beach: County Line (Malibu, CA)
-- Active swell access bins: 46-68 (230deg - 340deg)
-- Previous: min=200 max=300 center=250 half=50
UPDATE beaches SET
  swell_window_min_deg = 230,
  swell_window_max_deg = 340,
  swell_window_center_deg = 285,
  swell_window_halfwidth_deg = 55
WHERE id = '71bdbe5a-67f6-429c-b1e4-80ec390ec4a3';

-- Beach: Malibu First Point (Surfrider) (Malibu, CA)
-- Active swell access bins: 9-61 (45deg - 305deg)
-- Previous: min=200 max=280 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 45,
  swell_window_max_deg = 305,
  swell_window_center_deg = 175,
  swell_window_halfwidth_deg = 130
WHERE id = '9841bdd0-e70f-4c10-bc54-135575006298';

-- Beach: Zuma Beach (Malibu, CA)
-- Active swell access bins: 12-63 (60deg - 315deg)
-- Previous: min=200 max=300 center=250 half=50
UPDATE beaches SET
  swell_window_min_deg = 60,
  swell_window_max_deg = 315,
  swell_window_center_deg = 187.5,
  swell_window_halfwidth_deg = 127.5
WHERE id = '836f218a-9471-46c9-b201-24da1dfe0f3a';

-- Beach: Point Arena / Manchester Beach (Manchester, CA)
-- Active swell access bins: 48-4 (240deg - 20deg) [WRAPS]
-- Previous: min=250 max=330 center=290 half=40
UPDATE beaches SET
  swell_window_min_deg = 240,
  swell_window_max_deg = 20,
  swell_window_center_deg = 310,
  swell_window_halfwidth_deg = 70
WHERE id = 'c778cc0a-2094-4649-84cd-4c38ce864f23';

-- Beach: El Porto (Manhattan) (Manhattan Beach, CA)
-- Active swell access bins: 27-0 (135deg - 0deg) [WRAPS]
-- Previous: min=180 max=270 center=260 half=60
UPDATE beaches SET
  swell_window_min_deg = 135,
  swell_window_max_deg = 0,
  swell_window_center_deg = 247.5,
  swell_window_halfwidth_deg = 112.5
WHERE id = '52879e4f-fc7f-4c02-a5e3-ea40b992ea80';

-- Beach: Manhattan Beach Pier (Manhattan Beach, CA)
-- Active swell access bins: 26-69 (130deg - 345deg)
-- Previous: min=200 max=300 center=250 half=50
UPDATE beaches SET
  swell_window_min_deg = 130,
  swell_window_max_deg = 345,
  swell_window_center_deg = 237.5,
  swell_window_halfwidth_deg = 107.5
WHERE id = '7a093b7e-2230-4bf1-abeb-9b31faa794d5';

-- Beach: Morro Rock / Sandspit (inside bend) (Morro Bay, CA)
-- Active swell access bins: 32-7 (160deg - 35deg) [WRAPS]
-- Previous: min=235 max=305 center=270 half=35
UPDATE beaches SET
  swell_window_min_deg = 160,
  swell_window_max_deg = 35,
  swell_window_center_deg = 277.5,
  swell_window_halfwidth_deg = 117.5
WHERE id = '5c7c2a2e-3c7f-4a8c-8e8a-5cf2e9a0b101';

-- Beach: 52nd Street (Newport Beach, CA)
-- Active swell access bins: 18-64 (90deg - 320deg)
-- Previous: min=200 max=310 center=255 half=55
UPDATE beaches SET
  swell_window_min_deg = 90,
  swell_window_max_deg = 320,
  swell_window_center_deg = 205,
  swell_window_halfwidth_deg = 115
WHERE id = '1207215c-f61d-4fe1-bbaa-a3db7d4e7d53';

-- Beach: 54th Street (Newport Beach, CA)
-- Active swell access bins: 17-65 (85deg - 325deg)
-- Previous: min=200 max=310 center=255 half=55
UPDATE beaches SET
  swell_window_min_deg = 85,
  swell_window_max_deg = 325,
  swell_window_center_deg = 205,
  swell_window_halfwidth_deg = 120
WHERE id = 'da8ad733-8e6b-4781-8b3f-0fe4ee492c3f';

-- Beach: Corona del Mar (Newport Beach, CA)
-- Active swell access bins: 21-59 (105deg - 295deg)
-- Previous: min=170 max=230 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 105,
  swell_window_max_deg = 295,
  swell_window_center_deg = 200,
  swell_window_halfwidth_deg = 95
WHERE id = '12e0096c-9826-443f-9131-53aaa646f789';

-- Beach: Newport 56th St (Newport Beach, CA)
-- Active swell access bins: 17-65 (85deg - 325deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 85,
  swell_window_max_deg = 325,
  swell_window_center_deg = 205,
  swell_window_halfwidth_deg = 120
WHERE id = '53cc78d5-a759-4153-8a2e-b13cf1bb6b4e';

-- Beach: Newport Lower Jetties (Newport Beach, CA)
-- Active swell access bins: 16-66 (80deg - 330deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 80,
  swell_window_max_deg = 330,
  swell_window_center_deg = 205,
  swell_window_halfwidth_deg = 125
WHERE id = 'bbe7f4eb-9807-4e65-8e69-e2cee28d6b24';

-- Beach: Newport Point (Newport Beach, CA)
-- Active swell access bins: 16-66 (80deg - 330deg)
-- Previous: min=180 max=270 center=175 half=15
UPDATE beaches SET
  swell_window_min_deg = 80,
  swell_window_max_deg = 330,
  swell_window_center_deg = 205,
  swell_window_halfwidth_deg = 125
WHERE id = '11662c67-a1bb-43a0-b0f7-0e4071b1c3f2';

-- Beach: Newport Upper Jetties (Newport Beach, CA)
-- Active swell access bins: 14-70 (70deg - 350deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 70,
  swell_window_max_deg = 350,
  swell_window_center_deg = 210,
  swell_window_halfwidth_deg = 140
WHERE id = 'e64001e6-e2bd-4596-8f24-d8064e7f5186';

-- Beach: River Jetties (Newport Beach, CA)
-- Active swell access bins: 15-65 (75deg - 325deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 75,
  swell_window_max_deg = 325,
  swell_window_center_deg = 200,
  swell_window_halfwidth_deg = 125
WHERE id = 'a0e764f1-d0bb-4341-b397-7b21823cb93b';

-- Beach: The Wedge (Newport Beach, CA)
-- Active swell access bins: 25-58 (125deg - 290deg)
-- Previous: min=180 max=270 center=200 half=20
UPDATE beaches SET
  swell_window_min_deg = 125,
  swell_window_max_deg = 290,
  swell_window_center_deg = 207.5,
  swell_window_halfwidth_deg = 82.5
WHERE id = 'c2c7cc01-4920-4fd9-941c-68df6b46ced0';

-- Beach: Crystal Cove (Newport Coast, CA)
-- Active swell access bins: 24-64 (120deg - 320deg)
-- Previous: min=180 max=270 center=200 half=30
UPDATE beaches SET
  swell_window_min_deg = 120,
  swell_window_max_deg = 320,
  swell_window_center_deg = 220,
  swell_window_halfwidth_deg = 100
WHERE id = '0e557ec4-355a-4176-8352-6ea50e379c13';

-- Beach: Forster St. Oceanside (Oceanside, CA)
-- Active swell access bins: 29-65 (145deg - 325deg)
-- Previous: min=180 max=325 center=253 half=73
UPDATE beaches SET
  swell_window_min_deg = 145,
  swell_window_max_deg = 325,
  swell_window_center_deg = 235,
  swell_window_halfwidth_deg = 90
WHERE id = 'e5fee219-672c-4113-a0bb-a86a5d97700f';

-- Beach: Oceanside Harbor (Oceanside, CA)
-- Active swell access bins: 22-5 (110deg - 25deg) [WRAPS]
-- Previous: min=180 max=270 center=250 half=70
UPDATE beaches SET
  swell_window_min_deg = 110,
  swell_window_max_deg = 25,
  swell_window_center_deg = 247.5,
  swell_window_halfwidth_deg = 137.5
WHERE id = 'a30b9870-aace-48ef-a3e6-e275ad9c28c1';

-- Beach: Oceanside Pier (Oceanside, CA)
-- Active swell access bins: 17-65 (85deg - 325deg)
-- Previous: min=180 max=340 center=240 half=80
UPDATE beaches SET
  swell_window_min_deg = 85,
  swell_window_max_deg = 325,
  swell_window_center_deg = 205,
  swell_window_halfwidth_deg = 120
WHERE id = 'cceecad1-7668-4ad8-88ff-ade893c605cd';

-- Beach: The Rock, Oceanside (Oceanside, CA)
-- Active swell access bins: 23-63 (115deg - 315deg)
-- Previous: min=180 max=315 center=248 half=68
UPDATE beaches SET
  swell_window_min_deg = 115,
  swell_window_max_deg = 315,
  swell_window_center_deg = 215,
  swell_window_halfwidth_deg = 100
WHERE id = '762fcfa2-8fd8-40ea-8955-b9cc6945a422';

-- Beach: Pacifica / Linda Mar (Pacifica, CA)
-- Active swell access bins: 35-6 (175deg - 30deg) [WRAPS]
-- Previous: min=210 max=300 center=255 half=45
UPDATE beaches SET
  swell_window_min_deg = 175,
  swell_window_max_deg = 30,
  swell_window_center_deg = 282.5,
  swell_window_halfwidth_deg = 107.5
WHERE id = 'f2cc331f-6569-40d9-a98b-9f50fb3da67f';

-- Beach: Rockaway Beach (Pacifica) (Pacifica, CA)
-- Active swell access bins: 28-13 (140deg - 65deg) [WRAPS]
-- Previous: min=230 max=320 center=275 half=45
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 65,
  swell_window_center_deg = 282.5,
  swell_window_halfwidth_deg = 142.5
WHERE id = '49739de1-95fb-4e26-b890-56fafd8d2622';

-- Beach: Pismo Pier (Pismo Beach, CA)
-- Active swell access bins: 27-48 (135deg - 240deg)
-- Previous: min=230 max=300 center=265 half=35
-- Secondary windows: 52-56 (260deg - 280deg)
UPDATE beaches SET
  swell_window_min_deg = 135,
  swell_window_max_deg = 240,
  swell_window_center_deg = 187.5,
  swell_window_halfwidth_deg = 52.5
WHERE id = 'ee2aad76-966d-4aa3-86a2-499fde59b271';

-- Beach: Redondo Breakwall (Redondo Beach, CA)
-- Active swell access bins: 61-6 (305deg - 30deg) [WRAPS]
-- Previous: min=260 max=320 center=290 half=30
-- Secondary windows: 27-44 (135deg - 220deg)
UPDATE beaches SET
  swell_window_min_deg = 305,
  swell_window_max_deg = 30,
  swell_window_center_deg = 347.5,
  swell_window_halfwidth_deg = 42.5
WHERE id = '13a91b0d-3e80-4140-b11e-2c1b12e00687';

-- Beach: 204s (San Clemente, CA)
-- Active swell access bins: 46-62 (230deg - 310deg)
-- Previous: min=180 max=270 center=180 half=180
-- Secondary windows: 35-37 (175deg - 185deg)
UPDATE beaches SET
  swell_window_min_deg = 230,
  swell_window_max_deg = 310,
  swell_window_center_deg = 270,
  swell_window_halfwidth_deg = 40
WHERE id = '047e61b4-b4a8-4042-a290-f2189b5a70ca';

-- Beach: Old Man's (SanO) (San Clemente, CA)
-- Active swell access bins: 18-68 (90deg - 340deg)
-- Previous: min=180 max=270 center=225 half=55
UPDATE beaches SET
  swell_window_min_deg = 90,
  swell_window_max_deg = 340,
  swell_window_center_deg = 215,
  swell_window_halfwidth_deg = 125
WHERE id = 'a956de46-b204-448e-a541-db427be7e85f';

-- Beach: Poche Beach (San Clemente, CA)
-- Active swell access bins: 31-52 (155deg - 260deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 155,
  swell_window_max_deg = 260,
  swell_window_center_deg = 207.5,
  swell_window_halfwidth_deg = 52.5
WHERE id = 'b9c4a949-4562-47db-ae7d-b2131e20d7a7';

-- Beach: San Clemente Pier, Northside (San Clemente, CA)
-- Active swell access bins: 23-57 (115deg - 285deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 115,
  swell_window_max_deg = 285,
  swell_window_center_deg = 200,
  swell_window_halfwidth_deg = 85
WHERE id = 'e99552bf-45bd-46a8-a716-4cdfff2061f2';

-- Beach: San Clemente State Beach (San Clemente, CA)
-- Active swell access bins: 28-49 (140deg - 245deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 245,
  swell_window_center_deg = 192.5,
  swell_window_halfwidth_deg = 52.5
WHERE id = '02dfc45e-f7f8-4fdc-8008-6ce14e2839f5';

-- Beach: T-Street (San Clemente, CA)
-- Active swell access bins: 22-60 (110deg - 300deg)
-- Previous: min=180 max=270 center=215 half=45
UPDATE beaches SET
  swell_window_min_deg = 110,
  swell_window_max_deg = 300,
  swell_window_center_deg = 205,
  swell_window_halfwidth_deg = 95
WHERE id = 'dfeecc16-6395-4600-89e6-baf8456e3d69';

-- Beach: Big Jetty (San Diego, CA)
-- Active swell access bins: 22-38 (110deg - 190deg)
-- Previous: min=180 max=270 center=280 half=20
-- Secondary windows: 51-67 (255deg - 335deg), 4-4 (20deg - 20deg)
UPDATE beaches SET
  swell_window_min_deg = 110,
  swell_window_max_deg = 190,
  swell_window_center_deg = 150,
  swell_window_halfwidth_deg = 40
WHERE id = 'ec73bb77-4be5-4126-8986-348929c1e7e9';

-- Beach: Blacks (San Diego, CA)
-- Active swell access bins: 39-71 (195deg - 355deg)
-- Previous: min=195 max=340 center=268 half=73
UPDATE beaches SET
  swell_window_min_deg = 195,
  swell_window_max_deg = 355,
  swell_window_center_deg = 275,
  swell_window_halfwidth_deg = 80
WHERE id = '01330afc-00d3-461b-88f3-b173774766f4';

-- Beach: Coronado North Jetty (San Diego, CA)
-- Active swell access bins: 20-59 (100deg - 295deg)
-- Previous: min=180 max=290 center=235 half=55
UPDATE beaches SET
  swell_window_min_deg = 100,
  swell_window_max_deg = 295,
  swell_window_center_deg = 197.5,
  swell_window_halfwidth_deg = 97.5
WHERE id = 'b29821f9-c91a-486f-981b-7085c6d86b68';

-- Beach: Crystal Pier (San Diego, CA)
-- Active swell access bins: 11-62 (55deg - 310deg)
-- Previous: min=180 max=270 center=275 half=20
UPDATE beaches SET
  swell_window_min_deg = 55,
  swell_window_max_deg = 310,
  swell_window_center_deg = 182.5,
  swell_window_halfwidth_deg = 127.5
WHERE id = 'cc7c0837-257c-42c3-9d98-634911e73a6a';

-- Beach: Hotel Del Coronado (San Diego, CA)
-- Active swell access bins: 17-7 (85deg - 35deg) [WRAPS]
-- Previous: min=180 max=290 center=235 half=55
-- Secondary windows: 10-14 (50deg - 70deg)
UPDATE beaches SET
  swell_window_min_deg = 85,
  swell_window_max_deg = 35,
  swell_window_center_deg = 240,
  swell_window_halfwidth_deg = 155
WHERE id = '84d3468b-c1ec-46ad-8621-d8507e5f167a';

-- Beach: Marine Street Beach (San Diego, CA)
-- Active swell access bins: 28-16 (140deg - 80deg) [WRAPS]
-- Previous: min=180 max=270 center=250 half=30
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 80,
  swell_window_center_deg = 290,
  swell_window_halfwidth_deg = 150
WHERE id = '9b292a48-7a88-4d79-926f-16601515d7a0';

-- Beach: Mission Beach (San Diego, CA)
-- Active swell access bins: 53-2 (265deg - 10deg) [WRAPS]
-- Previous: min=255 max=345 center=300 half=45
-- Secondary windows: 22-22 (110deg - 110deg)
UPDATE beaches SET
  swell_window_min_deg = 265,
  swell_window_max_deg = 10,
  swell_window_center_deg = 317.5,
  swell_window_halfwidth_deg = 52.5
WHERE id = 'c02b4ede-69d9-440e-b8de-22ea4bde10ef';

-- Beach: Mission Beach (Central) (San Diego, CA)
-- Active swell access bins: 60-4 (300deg - 20deg) [WRAPS]
-- Previous: min=255 max=340 center=298 half=43
UPDATE beaches SET
  swell_window_min_deg = 300,
  swell_window_max_deg = 20,
  swell_window_center_deg = 340,
  swell_window_halfwidth_deg = 40
WHERE id = 'cdcf733b-a704-45ef-affc-d8152ffde1e4';

-- Beach: New Break (Nubes) (San Diego, CA)
-- Active swell access bins: 60-4 (300deg - 20deg) [WRAPS]
-- Previous: min=180 max=270 center=300 half=20
-- Secondary windows: 20-36 (100deg - 180deg)
UPDATE beaches SET
  swell_window_min_deg = 300,
  swell_window_max_deg = 20,
  swell_window_center_deg = 340,
  swell_window_halfwidth_deg = 40
WHERE id = 'd920e1b9-9e23-4ba8-9f8e-776571435f6f';

-- Beach: Ocean Beach (San Diego, CA)
-- Active swell access bins: 57-1 (285deg - 5deg) [WRAPS]
-- Previous: min=200 max=310 center=255 half=55
UPDATE beaches SET
  swell_window_min_deg = 285,
  swell_window_max_deg = 5,
  swell_window_center_deg = 325,
  swell_window_halfwidth_deg = 40
WHERE id = '15c7337e-5258-4339-9dc3-c435c666926b';

-- Beach: Ocean Beach Pier (San Diego, CA)
-- Active swell access bins: 44-1 (220deg - 5deg) [WRAPS]
-- Previous: min=220 max=345 center=283 half=63
UPDATE beaches SET
  swell_window_min_deg = 220,
  swell_window_max_deg = 5,
  swell_window_center_deg = 292.5,
  swell_window_halfwidth_deg = 72.5
WHERE id = '65d177de-e75a-4ad8-aa0d-48a67c0851b0';

-- Beach: Osprey Point (San Diego, CA)
-- Active swell access bins: 59-34 (295deg - 170deg) [WRAPS]
-- Previous: min=180 max=270 center=295 half=15
UPDATE beaches SET
  swell_window_min_deg = 295,
  swell_window_max_deg = 170,
  swell_window_center_deg = 52.5,
  swell_window_halfwidth_deg = 117.5
WHERE id = 'c3b42f85-e650-445f-89b1-1debe661652e';

-- Beach: Pacific Beach (San Diego, CA)
-- Active swell access bins: 36-64 (180deg - 320deg)
-- Previous: min=190 max=310 center=250 half=60
-- Secondary windows: 13-33 (65deg - 165deg)
UPDATE beaches SET
  swell_window_min_deg = 180,
  swell_window_max_deg = 320,
  swell_window_center_deg = 250,
  swell_window_halfwidth_deg = 70
WHERE id = '65809772-20bc-4009-b9b2-89c8ef3c4127';

-- Beach: PB Point (San Diego, CA)
-- Active swell access bins: 29-67 (145deg - 335deg)
-- Previous: min=180 max=335 center=258 half=78
UPDATE beaches SET
  swell_window_min_deg = 145,
  swell_window_max_deg = 335,
  swell_window_center_deg = 240,
  swell_window_halfwidth_deg = 95
WHERE id = '13ef0aa1-c857-4d82-a40d-a83612110943';

-- Beach: Silver Strand State Beach (San Diego, CA)
-- Active swell access bins: 0-71 (0deg - 355deg)
-- Previous: min=180 max=270 center=200 half=40
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 355,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 177.5
WHERE id = '94f1010b-c71f-4025-bda1-c26ed9467c85';

-- Beach: Sunset Cliffs (Garbage) (San Diego, CA)
-- Active swell access bins: 42-1 (210deg - 5deg) [WRAPS]
-- Previous: min=220 max=300 center=270 half=40
-- Secondary windows: 18-34 (90deg - 170deg)
UPDATE beaches SET
  swell_window_min_deg = 210,
  swell_window_max_deg = 5,
  swell_window_center_deg = 287.5,
  swell_window_halfwidth_deg = 77.5
WHERE id = 'd305ba0d-47cd-4494-b790-f924dac7bf1f';

-- Beach: Sunset Cliffs – Garbage (San Diego, CA)
-- Active swell access bins: 55-2 (275deg - 10deg) [WRAPS]
-- Previous: min=200 max=300 center=250 half=50
-- Secondary windows: 21-37 (105deg - 185deg)
UPDATE beaches SET
  swell_window_min_deg = 275,
  swell_window_max_deg = 10,
  swell_window_center_deg = 322.5,
  swell_window_halfwidth_deg = 47.5
WHERE id = 'b939f928-2653-494a-831d-6394cb548190';

-- Beach: Sunset Cliffs – Luscombs (San Diego, CA)
-- Active swell access bins: 9-34 (45deg - 170deg)
-- Previous: min=200 max=300 center=250 half=50
-- Secondary windows: 51-69 (255deg - 345deg)
UPDATE beaches SET
  swell_window_min_deg = 45,
  swell_window_max_deg = 170,
  swell_window_center_deg = 107.5,
  swell_window_halfwidth_deg = 62.5
WHERE id = '34af0af5-b61c-4b86-9d9d-bf328f538a12';

-- Beach: Tijuana Sloughs (San Diego, CA)
-- Active swell access bins: 29-2 (145deg - 10deg) [WRAPS]
-- Previous: min=180 max=340 center=260 half=80
UPDATE beaches SET
  swell_window_min_deg = 145,
  swell_window_max_deg = 10,
  swell_window_center_deg = 257.5,
  swell_window_halfwidth_deg = 112.5
WHERE id = '929caa5e-c79f-4b60-8fe0-bec75c2df2d6';

-- Beach: Torrey Pines State Beach (San Diego, CA)
-- Active swell access bins: 28-4 (140deg - 20deg) [WRAPS]
-- Previous: min=180 max=345 center=263 half=83
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 20,
  swell_window_center_deg = 260,
  swell_window_halfwidth_deg = 120
WHERE id = '4bdbff9e-2c1f-4918-84a6-aed42fb6e42c';

-- Beach: Tourmaline (San Diego, CA)
-- Active swell access bins: 15-63 (75deg - 315deg)
-- Previous: min=180 max=315 center=248 half=68
UPDATE beaches SET
  swell_window_min_deg = 75,
  swell_window_max_deg = 315,
  swell_window_center_deg = 195,
  swell_window_halfwidth_deg = 120
WHERE id = '17628f35-9ed1-4257-aad6-070c4bd73bb8';

-- Beach: Tourmaline Surf Park (San Diego, CA)
-- Active swell access bins: 15-0 (75deg - 0deg) [WRAPS]
-- Previous: min=255 max=295 center=275 half=20
UPDATE beaches SET
  swell_window_min_deg = 75,
  swell_window_max_deg = 0,
  swell_window_center_deg = 217.5,
  swell_window_halfwidth_deg = 142.5
WHERE id = '91df193c-f2c8-4e6c-984e-b859bd741061';

-- Beach: Fort Point (San Francisco) (San Francisco, CA)
-- Active swell access bins: 33-27 (165deg - 135deg) [WRAPS]
-- Previous: min=250 max=310 center=280 half=30
UPDATE beaches SET
  swell_window_min_deg = 165,
  swell_window_max_deg = 135,
  swell_window_center_deg = 330,
  swell_window_halfwidth_deg = 165
WHERE id = '208cd792-7e94-419f-802c-09c9634ec6a9';

-- Beach: Ocean Beach SF – Middle (San Francisco, CA)
-- Active swell access bins: 27-7 (135deg - 35deg) [WRAPS]
-- Previous: min=240 max=320 center=280 half=40
UPDATE beaches SET
  swell_window_min_deg = 135,
  swell_window_max_deg = 35,
  swell_window_center_deg = 265,
  swell_window_halfwidth_deg = 130
WHERE id = 'e8a921b7-c2b5-4259-9e5c-bd06765f7ae4';

-- Beach: Ocean Beach SF – North (San Francisco, CA)
-- Active swell access bins: 28-18 (140deg - 90deg) [WRAPS]
-- Previous: min=240 max=320 center=280 half=40
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 90,
  swell_window_center_deg = 295,
  swell_window_halfwidth_deg = 155
WHERE id = 'eca7e91a-0e5e-40d5-acb4-59c6ff50d861';

-- Beach: Ocean Beach SF – Sloat (San Francisco, CA)
-- Active swell access bins: 26-7 (130deg - 35deg) [WRAPS]
-- Previous: min=240 max=320 center=280 half=40
UPDATE beaches SET
  swell_window_min_deg = 130,
  swell_window_max_deg = 35,
  swell_window_center_deg = 262.5,
  swell_window_halfwidth_deg = 132.5
WHERE id = 'd9524c9d-8315-4686-9d35-24ceb6db2a82';

-- Beach: Church (San Onofre, CA)
-- Active swell access bins: 20-67 (100deg - 335deg)
-- Previous: min=190 max=250 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 100,
  swell_window_max_deg = 335,
  swell_window_center_deg = 217.5,
  swell_window_halfwidth_deg = 117.5
WHERE id = 'a0332432-4877-48c5-855d-b30fd097ba38';

-- Beach: Cottons (San Onofre, CA)
-- Active swell access bins: 19-43 (95deg - 215deg)
-- Previous: min=190 max=250 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 95,
  swell_window_max_deg = 215,
  swell_window_center_deg = 155,
  swell_window_halfwidth_deg = 60
WHERE id = '2c1d7948-72c1-4787-93e8-f33ac9567db0';

-- Beach: Lower Trestles (San Onofre, CA)
-- Active swell access bins: 23-65 (115deg - 325deg)
-- Previous: min=180 max=325 center=253 half=73
UPDATE beaches SET
  swell_window_min_deg = 115,
  swell_window_max_deg = 325,
  swell_window_center_deg = 220,
  swell_window_halfwidth_deg = 105
WHERE id = '193a3f9a-66d0-4362-bf55-d25bb831dae4';

-- Beach: Middles (San Onofre, CA)
-- Active swell access bins: 22-66 (110deg - 330deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 110,
  swell_window_max_deg = 330,
  swell_window_center_deg = 220,
  swell_window_halfwidth_deg = 110
WHERE id = 'b5bcd27f-3399-4a0a-b5d5-da8147e43b9a';

-- Beach: San Onofre State Beach (San Onofre, CA)
-- Active swell access bins: 22-48 (110deg - 240deg)
-- Previous: min=180 max=270 center=225 half=55
-- Secondary windows: 65-69 (325deg - 345deg)
UPDATE beaches SET
  swell_window_min_deg = 110,
  swell_window_max_deg = 240,
  swell_window_center_deg = 175,
  swell_window_halfwidth_deg = 65
WHERE id = '8a47b323-0874-45d9-aa17-ced468f70f2d';

-- Beach: Trails (San Onofre, CA)
-- Active swell access bins: 10-69 (50deg - 345deg)
-- Previous: min=190 max=250 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 50,
  swell_window_max_deg = 345,
  swell_window_center_deg = 197.5,
  swell_window_halfwidth_deg = 147.5
WHERE id = '2f3e2136-b094-49d7-b90f-948160cbb854';

-- Beach: Upper Trestles (San Onofre, CA)
-- Active swell access bins: 22-67 (110deg - 335deg)
-- Previous: min=180 max=335 center=258 half=78
UPDATE beaches SET
  swell_window_min_deg = 110,
  swell_window_max_deg = 335,
  swell_window_center_deg = 222.5,
  swell_window_halfwidth_deg = 112.5
WHERE id = 'f924aa96-395f-41e0-b966-502b37def7ac';

-- Beach: El Capitan (Santa Barbara, CA)
-- Active swell access bins: 45-67 (225deg - 335deg)
-- Previous: min=250 max=310 center=280 half=30
-- Secondary windows: 14-31 (70deg - 155deg)
UPDATE beaches SET
  swell_window_min_deg = 225,
  swell_window_max_deg = 335,
  swell_window_center_deg = 280,
  swell_window_halfwidth_deg = 55
WHERE id = '4194e543-a87e-46ee-b317-56c5820c5567';

-- Beach: Leadbetter (Santa Barbara, CA)
-- Active swell access bins: 9-52 (45deg - 260deg)
-- Previous: min=150 max=210 center=180 half=30
UPDATE beaches SET
  swell_window_min_deg = 45,
  swell_window_max_deg = 260,
  swell_window_center_deg = 152.5,
  swell_window_halfwidth_deg = 107.5
WHERE id = 'e0dd3e3a-1a9e-4b7d-8c55-2d3b6f9b7f09';

-- Beach: Mesa Lane (Santa Barbara, CA)
-- Active swell access bins: 9-62 (45deg - 310deg)
-- Previous: min=240 max=300 center=270 half=30
UPDATE beaches SET
  swell_window_min_deg = 45,
  swell_window_max_deg = 310,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 132.5
WHERE id = '0f0a1339-f7d0-4b1a-ae95-61939998b4ef';

-- Beach: 38th Avenue (Santa Cruz) (Santa Cruz, CA)
-- Active swell access bins: 1-57 (5deg - 285deg)
-- Previous: min=200 max=300 center=250 half=50
UPDATE beaches SET
  swell_window_min_deg = 5,
  swell_window_max_deg = 285,
  swell_window_center_deg = 145,
  swell_window_halfwidth_deg = 140
WHERE id = '36a2d39e-64f1-4c7e-9618-ac8cc695af62';

-- Beach: Mitchell's Cove (Santa Cruz, CA)
-- Active swell access bins: 8-59 (40deg - 295deg)
-- Previous: min=240 max=300 center=270 half=30
UPDATE beaches SET
  swell_window_min_deg = 40,
  swell_window_max_deg = 295,
  swell_window_center_deg = 167.5,
  swell_window_halfwidth_deg = 127.5
WHERE id = 'abb56ca0-7dad-4026-960f-23412fa5cc8b';

-- Beach: Pleasure Point (Santa Cruz, CA)
-- Active swell access bins: 70-63 (350deg - 315deg) [WRAPS]
-- Previous: min=200 max=300 center=250 half=50
UPDATE beaches SET
  swell_window_min_deg = 350,
  swell_window_max_deg = 315,
  swell_window_center_deg = 152.5,
  swell_window_halfwidth_deg = 162.5
WHERE id = 'cdfb7e59-ce4e-4112-acc5-15fe56a8b6a3';

-- Beach: Rockview (Santa Cruz) (Santa Cruz, CA)
-- Active swell access bins: 2-54 (10deg - 270deg)
-- Previous: min=200 max=300 center=250 half=50
UPDATE beaches SET
  swell_window_min_deg = 10,
  swell_window_max_deg = 270,
  swell_window_center_deg = 140,
  swell_window_halfwidth_deg = 130
WHERE id = 'f3e1216f-2a17-47be-8c2e-67d8588ab065';

-- Beach: Steamer Lane (Santa Cruz, CA)
-- Active swell access bins: 3-58 (15deg - 290deg)
-- Previous: min=240 max=320 center=280 half=40
UPDATE beaches SET
  swell_window_min_deg = 15,
  swell_window_max_deg = 290,
  swell_window_center_deg = 152.5,
  swell_window_halfwidth_deg = 137.5
WHERE id = '2609a9ff-d247-4e0b-888f-a793ff7177a5';

-- Beach: Seaside Reef (Solana Beach, CA)
-- Active swell access bins: 38-0 (190deg - 0deg) [WRAPS]
-- Previous: min=180 max=270 center=280 half=30
UPDATE beaches SET
  swell_window_min_deg = 190,
  swell_window_max_deg = 0,
  swell_window_center_deg = 275,
  swell_window_halfwidth_deg = 85
WHERE id = '5a34b2ac-01b9-4b83-8c05-c47b1b55d923';

-- Beach: Solana Beach (Solana Beach, CA)
-- Active swell access bins: 28-2 (140deg - 10deg) [WRAPS]
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 10,
  swell_window_center_deg = 255,
  swell_window_halfwidth_deg = 115
WHERE id = '65d3a4de-1f4b-4a1d-8ce0-b5b67288ee08';

-- Beach: Stinson Beach (Stinson Beach, CA)
-- Active swell access bins: 22-63 (110deg - 315deg)
-- Previous: min=240 max=320 center=280 half=40
UPDATE beaches SET
  swell_window_min_deg = 110,
  swell_window_max_deg = 315,
  swell_window_center_deg = 212.5,
  swell_window_halfwidth_deg = 102.5
WHERE id = '5a5dc7b8-4d30-44af-9715-3dbb4dbc9859';

-- Beach: Venice Breakwater (Venice, CA)
-- Active swell access bins: 23-67 (115deg - 335deg)
-- Previous: min=220 max=300 center=260 half=40
UPDATE beaches SET
  swell_window_min_deg = 115,
  swell_window_max_deg = 335,
  swell_window_center_deg = 225,
  swell_window_halfwidth_deg = 110
WHERE id = '96fd7011-b894-4776-a68d-ff16fb1985d8';

-- Beach: C Street / Ventura Point (Ventura, CA)
-- Active swell access bins: 26-64 (130deg - 320deg)
-- Previous: min=190 max=300 center=245 half=55
UPDATE beaches SET
  swell_window_min_deg = 130,
  swell_window_max_deg = 320,
  swell_window_center_deg = 225,
  swell_window_halfwidth_deg = 95
WHERE id = '486dc095-4b21-4edb-838c-97f68b40d1df';

-- Beach: Emma Wood (Ventura, CA)
-- Active swell access bins: 42-58 (210deg - 290deg)
-- Previous: min=190 max=300 center=245 half=55
UPDATE beaches SET
  swell_window_min_deg = 210,
  swell_window_max_deg = 290,
  swell_window_center_deg = 250,
  swell_window_halfwidth_deg = 40
WHERE id = '21eae8b9-387c-438c-b144-55796bab5caa';

-- Beach: Solimar Reef (Ventura, CA)
-- Active swell access bins: 24-65 (120deg - 325deg)
-- Previous: min=190 max=300 center=245 half=55
UPDATE beaches SET
  swell_window_min_deg = 120,
  swell_window_max_deg = 325,
  swell_window_center_deg = 222.5,
  swell_window_halfwidth_deg = 102.5
WHERE id = '411b3825-c047-4628-997d-08712117ad56';

-- Beach: Boynton Inlet (Boynton Beach, FL)
-- Active swell access bins: 66-42 (330deg - 210deg) [WRAPS]
-- Previous: min=40 max=100 center=70 half=30
UPDATE beaches SET
  swell_window_min_deg = 330,
  swell_window_max_deg = 210,
  swell_window_center_deg = 90,
  swell_window_halfwidth_deg = 120
WHERE id = 'c06c6bd7-dbce-4df7-8479-73c44c1cb905';

-- Beach: Cocoa Beach Pier (Cocoa Beach, FL)
-- Active swell access bins: 0-71 (0deg - 355deg)
-- Previous: min=40 max=150 center=95 half=55
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 355,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 177.5
WHERE id = '99e50d6b-a1cf-458b-8fff-c199cd55b23c';

-- Beach: Deerfield Beach Pier (Deerfield Beach, FL)
-- Active swell access bins: 70-42 (350deg - 210deg) [WRAPS]
-- Previous: min=40 max=100 center=70 half=30
UPDATE beaches SET
  swell_window_min_deg = 350,
  swell_window_max_deg = 210,
  swell_window_center_deg = 100,
  swell_window_halfwidth_deg = 110
WHERE id = '1bd4ef4d-eb8e-4833-8679-8a13095a97d6';

-- Beach: Flagler Beach (Flagler Beach, FL)
-- Active swell access bins: 64-30 (320deg - 150deg) [WRAPS]
-- Previous: min=45 max=135 center=90 half=45
UPDATE beaches SET
  swell_window_min_deg = 320,
  swell_window_max_deg = 150,
  swell_window_center_deg = 55,
  swell_window_halfwidth_deg = 95
WHERE id = '9ca1fa2f-2b90-4aa3-8784-48721e5463bb';

-- Beach: Jacksonville Beach Pier (Jacksonville Beach, FL)
-- Active swell access bins: 52-38 (260deg - 190deg) [WRAPS]
-- Previous: min=45 max=135 center=90 half=45
UPDATE beaches SET
  swell_window_min_deg = 260,
  swell_window_max_deg = 190,
  swell_window_center_deg = 45,
  swell_window_halfwidth_deg = 145
WHERE id = 'a4472f56-626e-4905-b909-5f1dc27174a9';

-- Beach: Sebastian Inlet (Melbourne Beach, FL)
-- Active swell access bins: 2-36 (10deg - 180deg)
-- Previous: min=30 max=150 center=90 half=60
UPDATE beaches SET
  swell_window_min_deg = 10,
  swell_window_max_deg = 180,
  swell_window_center_deg = 95,
  swell_window_halfwidth_deg = 85
WHERE id = 'd0f77b47-ec94-4188-8dde-d52a10b7be49';

-- Beach: Spanish House (Melbourne Beach, FL)
-- Active swell access bins: 57-35 (285deg - 175deg) [WRAPS]
-- Previous: min=40 max=150 center=95 half=55
UPDATE beaches SET
  swell_window_min_deg = 285,
  swell_window_max_deg = 175,
  swell_window_center_deg = 50,
  swell_window_halfwidth_deg = 125
WHERE id = '53e8654a-a2bb-46a9-8153-83661af98fb1';

-- Beach: South Beach (Miami Beach, FL)
-- Active swell access bins: 1-34 (5deg - 170deg)
-- Previous: min=0 max=80 center=40 half=40
UPDATE beaches SET
  swell_window_min_deg = 5,
  swell_window_max_deg = 170,
  swell_window_center_deg = 87.5,
  swell_window_halfwidth_deg = 82.5
WHERE id = '55cc5dfa-6963-4e17-abfd-d2022a2dcd36';

-- Beach: Navarre Beach Pier (Navarre, FL)
-- Active swell access bins: 9-60 (45deg - 300deg)
-- Previous: min=150 max=240 center=195 half=45
-- Secondary windows: 67-6 (335deg - 30deg) [WRAPS]
UPDATE beaches SET
  swell_window_min_deg = 45,
  swell_window_max_deg = 300,
  swell_window_center_deg = 172.5,
  swell_window_halfwidth_deg = 127.5
WHERE id = '3b948da8-26a0-43f6-8ad3-e99e9cc5174b';

-- Beach: New Smyrna Beach (NSB) Inlet (New Smyrna Beach, FL)
-- Active swell access bins: 54-38 (270deg - 190deg) [WRAPS]
-- Previous: min=45 max=135 center=90 half=45
UPDATE beaches SET
  swell_window_min_deg = 270,
  swell_window_max_deg = 190,
  swell_window_center_deg = 50,
  swell_window_halfwidth_deg = 140
WHERE id = 'f5eec6e8-844a-41be-b3bf-4c47e0615545';

-- Beach: Pensacola Pier (Pensacola Beach, FL)
-- Active swell access bins: 5-54 (25deg - 270deg)
-- Previous: min=150 max=240 center=195 half=45
UPDATE beaches SET
  swell_window_min_deg = 25,
  swell_window_max_deg = 270,
  swell_window_center_deg = 147.5,
  swell_window_halfwidth_deg = 122.5
WHERE id = '3433ea8e-6528-4c18-8b16-c830bf642568';

-- Beach: Ponce Inlet (Ponce Inlet, FL)
-- Active swell access bins: 54-38 (270deg - 190deg) [WRAPS]
-- Previous: min=45 max=135 center=90 half=45
UPDATE beaches SET
  swell_window_min_deg = 270,
  swell_window_max_deg = 190,
  swell_window_center_deg = 50,
  swell_window_halfwidth_deg = 140
WHERE id = '9c6bdc37-68c3-4101-9c2f-d188384528b6';

-- Beach: Satellite Beach (Satellite Beach, FL)
-- Active swell access bins: 64-47 (320deg - 235deg) [WRAPS]
-- Previous: min=45 max=135 center=90 half=45
UPDATE beaches SET
  swell_window_min_deg = 320,
  swell_window_max_deg = 235,
  swell_window_center_deg = 97.5,
  swell_window_halfwidth_deg = 137.5
WHERE id = '307d7cb3-f235-4b32-9b42-8a375ac9f54f';

-- Beach: Tybee Island (Tybee Island, GA)
-- Active swell access bins: 0-71 (0deg - 355deg)
-- Previous: min=60 max=150 center=105 half=45
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 355,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 177.5
WHERE id = 'd3740aa5-3c96-4575-a60c-d8200023affe';

-- Beach: Anahola (Anahola, HI)
-- Active swell access bins: 65-34 (325deg - 170deg) [WRAPS]
-- Previous: min=50 max=100 center=75 half=25
UPDATE beaches SET
  swell_window_min_deg = 325,
  swell_window_max_deg = 170,
  swell_window_center_deg = 67.5,
  swell_window_halfwidth_deg = 102.5
WHERE id = 'c9659503-c562-4379-9177-fff60acdfb7f';

-- Beach: Haleiwa (Haleiwa, HI)
-- Active swell access bins: 46-12 (230deg - 60deg) [WRAPS]
-- Previous: min=300 max=340 center=320 half=20
UPDATE beaches SET
  swell_window_min_deg = 230,
  swell_window_max_deg = 60,
  swell_window_center_deg = 325,
  swell_window_halfwidth_deg = 95
WHERE id = '43cfaf0d-0376-45cb-a8bd-78087ba4ee15';

-- Beach: Pipeline (Haleiwa, HI)
-- Active swell access bins: 36-15 (180deg - 75deg) [WRAPS]
-- Previous: min=315 max=30 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 180,
  swell_window_max_deg = 75,
  swell_window_center_deg = 307.5,
  swell_window_halfwidth_deg = 127.5
WHERE id = '6a0674ac-3e6d-49f3-9fd4-a4f1857c408a';

-- Beach: Hanalei Bay (Kauai) (Hanalei, HI)
-- Active swell access bins: 53-11 (265deg - 55deg) [WRAPS]
-- Previous: min=315 max=30 center=0 half=38
UPDATE beaches SET
  swell_window_min_deg = 265,
  swell_window_max_deg = 55,
  swell_window_center_deg = 340,
  swell_window_halfwidth_deg = 75
WHERE id = 'b4202dc4-e308-4dc2-9844-665413a75cb1';

-- Beach: Hanalei (Wainiha) — Colony Resort (Hanalei, HI)
-- Active swell access bins: 48-25 (240deg - 125deg) [WRAPS]
-- Previous: min=300 max=30 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 240,
  swell_window_max_deg = 125,
  swell_window_center_deg = 2.5,
  swell_window_halfwidth_deg = 122.5
WHERE id = '71fa4843-1235-4f11-9184-fe1c87e8fbc5';

-- Beach: Ala Moana Bowls (Honolulu, HI)
-- Active swell access bins: 23-65 (115deg - 325deg)
-- Previous: min=180 max=230 center=205 half=25
UPDATE beaches SET
  swell_window_min_deg = 115,
  swell_window_max_deg = 325,
  swell_window_center_deg = 220,
  swell_window_halfwidth_deg = 105
WHERE id = '80fc2c1b-2d3f-4a94-bcc2-c8ea0e9b8fc5';

-- Beach: Diamond Head (Cliffs) (Honolulu, HI)
-- Active swell access bins: 4-71 (20deg - 355deg)
-- Previous: min=140 max=210 center=175 half=35
UPDATE beaches SET
  swell_window_min_deg = 20,
  swell_window_max_deg = 355,
  swell_window_center_deg = 187.5,
  swell_window_halfwidth_deg = 167.5
WHERE id = '8ee452f0-4043-4fe0-a049-207afbd95523';

-- Beach: Sandy Beach (Honolulu, HI)
-- Active swell access bins: 70-49 (350deg - 245deg) [WRAPS]
-- Previous: min=60 max=120 center=90 half=30
UPDATE beaches SET
  swell_window_min_deg = 350,
  swell_window_max_deg = 245,
  swell_window_center_deg = 117.5,
  swell_window_halfwidth_deg = 127.5
WHERE id = 'd663a525-f59d-4873-b67a-50898ca1c72c';

-- Beach: Waikiki (Aquarium) (Honolulu, HI)
-- Active swell access bins: 16-65 (80deg - 325deg)
-- Previous: min=180 max=220 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 80,
  swell_window_max_deg = 325,
  swell_window_center_deg = 202.5,
  swell_window_halfwidth_deg = 122.5
WHERE id = '880748ee-5423-4b2e-a5c3-b2faab5c4a7a';

-- Beach: Waikiki Beach (Honolulu, HI)
-- Active swell access bins: 18-60 (90deg - 300deg)
-- Previous: min=180 max=220 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 90,
  swell_window_max_deg = 300,
  swell_window_center_deg = 195,
  swell_window_halfwidth_deg = 105
WHERE id = '846ccff8-0e26-41f3-8496-5c5221109c6c';

-- Beach: Waikiki – Canoes (Honolulu, HI)
-- Active swell access bins: 27-53 (135deg - 265deg)
-- Previous: min=170 max=220 center=195 half=25
UPDATE beaches SET
  swell_window_min_deg = 135,
  swell_window_max_deg = 265,
  swell_window_center_deg = 200,
  swell_window_halfwidth_deg = 65
WHERE id = '2ac8b200-fdf2-4822-bcb1-3ec336b83d05';

-- Beach: Waikiki – Queens (Honolulu, HI)
-- Active swell access bins: 17-57 (85deg - 285deg)
-- Previous: min=170 max=220 center=195 half=25
UPDATE beaches SET
  swell_window_min_deg = 85,
  swell_window_max_deg = 285,
  swell_window_center_deg = 185,
  swell_window_halfwidth_deg = 100
WHERE id = 'ae2e2eee-897c-4198-80fa-04b2d47128d7';

-- Beach: Kahalu'u (Kahaluu-Keauhou, HI)
-- Active swell access bins: 28-0 (140deg - 0deg) [WRAPS]
-- Previous: min=190 max=290 center=240 half=50
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 0,
  swell_window_center_deg = 250,
  swell_window_halfwidth_deg = 110
WHERE id = '67996143-6e0e-4391-a810-9dec48e19963';

-- Beach: Banyans (Kailua-Kona, HI)
-- Active swell access bins: 28-71 (140deg - 355deg)
-- Previous: min=200 max=300 center=250 half=50
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 355,
  swell_window_center_deg = 247.5,
  swell_window_halfwidth_deg = 107.5
WHERE id = 'eadd2bf6-759a-46e4-a8af-8df1feb635cb';

-- Beach: Pine Trees (Kohanaiki) (Kailua-Kona, HI)
-- Active swell access bins: 24-2 (120deg - 10deg) [WRAPS]
-- Previous: min=200 max=300 center=250 half=50
UPDATE beaches SET
  swell_window_min_deg = 120,
  swell_window_max_deg = 10,
  swell_window_center_deg = 245,
  swell_window_halfwidth_deg = 125
WHERE id = 'fbe805b3-b9f5-40e0-afbb-3c5a8d45f67b';

-- Beach: Honolua Bay (Kapalua, HI)
-- Active swell access bins: 44-22 (220deg - 110deg) [WRAPS]
-- Previous: min=290 max=340 center=315 half=25
UPDATE beaches SET
  swell_window_min_deg = 220,
  swell_window_max_deg = 110,
  swell_window_center_deg = 345,
  swell_window_halfwidth_deg = 125
WHERE id = '4dd216b1-edc3-46b6-aabb-66beb467bcaf';

-- Beach: Poipu Beach (Kauai) (Koloa, HI)
-- Active swell access bins: 8-64 (40deg - 320deg)
-- Previous: min=180 max=220 center=157 half=33
UPDATE beaches SET
  swell_window_min_deg = 40,
  swell_window_max_deg = 320,
  swell_window_center_deg = 180,
  swell_window_halfwidth_deg = 140
WHERE id = '231d8635-6ae1-40e5-9112-88c26b0918ac';

-- Beach: Lahaina Harbor (Breakwall) (Lahaina, HI)
-- Active swell access bins: 24-4 (120deg - 20deg) [WRAPS]
-- Previous: min=180 max=225 center=202 half=22
UPDATE beaches SET
  swell_window_min_deg = 120,
  swell_window_max_deg = 20,
  swell_window_center_deg = 250,
  swell_window_halfwidth_deg = 130
WHERE id = '2c622571-c1fa-4c46-afd1-c0769c184570';

-- Beach: Kalapaki Beach (Lihue, HI)
-- Active swell access bins: 0-39 (0deg - 195deg)
-- Previous: min=45 max=120 center=82 half=37
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 195,
  swell_window_center_deg = 97.5,
  swell_window_halfwidth_deg = 97.5
WHERE id = 'b2b469ea-3d00-44df-88e8-621934c6926f';

-- Beach: Ho'okipa (Paia, HI)
-- Active swell access bins: 41-21 (205deg - 105deg) [WRAPS]
-- Previous: min=10 max=120 center=65 half=55
UPDATE beaches SET
  swell_window_min_deg = 205,
  swell_window_max_deg = 105,
  swell_window_center_deg = 335,
  swell_window_halfwidth_deg = 130
WHERE id = 'e6cec9c8-ab43-4ff8-9d79-cb297422b529';

-- Beach: Sunset Beach (Pupukea, HI)
-- Active swell access bins: 37-16 (185deg - 80deg) [WRAPS]
-- Previous: min=295 max=340 center=317 half=22
UPDATE beaches SET
  swell_window_min_deg = 185,
  swell_window_max_deg = 80,
  swell_window_center_deg = 312.5,
  swell_window_halfwidth_deg = 127.5
WHERE id = 'f52f2c49-342a-4694-b04a-d66503446736';

-- Beach: Waimea Bay (Pupukea, HI)
-- Active swell access bins: 44-12 (220deg - 60deg) [WRAPS]
-- Previous: min=290 max=330 center=310 half=20
UPDATE beaches SET
  swell_window_min_deg = 220,
  swell_window_max_deg = 60,
  swell_window_center_deg = 320,
  swell_window_halfwidth_deg = 100
WHERE id = '12431285-b73c-48e4-99b3-731594f6f98c';

-- Beach: Waikoloa Village Lagoon (Waikoloa, HI)
-- Active swell access bins: 38-14 (190deg - 70deg) [WRAPS]
-- Previous: min=180 max=220 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 190,
  swell_window_max_deg = 70,
  swell_window_center_deg = 310,
  swell_window_halfwidth_deg = 120
WHERE id = '22d65140-1c40-4bbe-8790-5068fa6e5f22';

-- Beach: Hapuna Beach (Kohala) (Waimea, HI)
-- Active swell access bins: 0-71 (0deg - 355deg)
-- Previous: min=180 max=220 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 355,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 177.5
WHERE id = '1ac4f5f1-94a1-4347-b4ca-6c9d62aee5d3';

-- Beach: Kekaha / Pakala (Infinities) (Waimea, HI)
-- Active swell access bins: 23-70 (115deg - 350deg)
-- Previous: min=180 max=225 center=202 half=22
UPDATE beaches SET
  swell_window_min_deg = 115,
  swell_window_max_deg = 350,
  swell_window_center_deg = 232.5,
  swell_window_halfwidth_deg = 117.5
WHERE id = '34e6e6d4-b640-4412-934f-4343b7dd8dfc';

-- Beach: Coast Guard Beach (Eastham, MA)
-- Active swell access bins: 66-41 (330deg - 205deg) [WRAPS]
-- Previous: min=60 max=150 center=105 half=45
UPDATE beaches SET
  swell_window_min_deg = 330,
  swell_window_max_deg = 205,
  swell_window_center_deg = 87.5,
  swell_window_halfwidth_deg = 117.5
WHERE id = '7c9ac9f8-a836-4ee4-b5bb-5fe5936d54b4';

-- Beach: Nantasket Beach (Hull, MA)
-- Active swell access bins: 69-65 (345deg - 325deg) [WRAPS]
-- Previous: min=40 max=130 center=85 half=45
UPDATE beaches SET
  swell_window_min_deg = 345,
  swell_window_max_deg = 325,
  swell_window_center_deg = 155,
  swell_window_halfwidth_deg = 170
WHERE id = '6693188e-80a0-4877-a618-d733ab4809b2';

-- Beach: Higgins Beach (Scarborough, ME)
-- Active swell access bins: 21-49 (105deg - 245deg)
-- Previous: min=80 max=150 center=115 half=35
UPDATE beaches SET
  swell_window_min_deg = 105,
  swell_window_max_deg = 245,
  swell_window_center_deg = 175,
  swell_window_halfwidth_deg = 70
WHERE id = 'adcd7128-424e-46d3-b8d1-f3aad6dd5edb';

-- Beach: Scarborough Beach (Scarborough, ME)
-- Active swell access bins: 7-23 (35deg - 115deg)
-- Previous: min=120 max=190 center=155 half=35
-- Secondary windows: 28-44 (140deg - 220deg)
UPDATE beaches SET
  swell_window_min_deg = 35,
  swell_window_max_deg = 115,
  swell_window_center_deg = 75,
  swell_window_halfwidth_deg = 40
WHERE id = 'a1566585-0143-4a1d-983f-c7fd195c5e55';

-- Beach: Cape Hatteras Lighthouse (Buxton, NC)
-- Active swell access bins: 67-62 (335deg - 310deg) [WRAPS]
-- Previous: min=45 max=170 center=107 half=62
UPDATE beaches SET
  swell_window_min_deg = 335,
  swell_window_max_deg = 310,
  swell_window_center_deg = 142.5,
  swell_window_halfwidth_deg = 167.5
WHERE id = 'd264fbf8-0525-4d31-adb5-9a0742eaeb7e';

-- Beach: Avalon Pier (Kill Devil Hills, NC)
-- Active swell access bins: 50-47 (250deg - 235deg) [WRAPS]
-- Previous: min=45 max=170 center=107 half=62
UPDATE beaches SET
  swell_window_min_deg = 250,
  swell_window_max_deg = 235,
  swell_window_center_deg = 62.5,
  swell_window_halfwidth_deg = 172.5
WHERE id = 'a797dcac-2507-4b2b-9d37-1f92dfd6af89';

-- Beach: Kill Devil Hills (Kill Devil Hills, NC)
-- Active swell access bins: 53-47 (265deg - 235deg) [WRAPS]
-- Previous: min=45 max=170 center=107 half=62
UPDATE beaches SET
  swell_window_min_deg = 265,
  swell_window_max_deg = 235,
  swell_window_center_deg = 70,
  swell_window_halfwidth_deg = 165
WHERE id = 'fea10ecf-6b55-4cc9-b29b-f215f923759d';

-- Beach: Nags Head (Nags Head, NC)
-- Active swell access bins: 0-71 (0deg - 355deg)
-- Previous: min=45 max=170 center=107 half=62
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 355,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 177.5
WHERE id = '872fdb8c-6e6b-459e-813c-e8fc6a9561bd';

-- Beach: S‑Turns (Rodanthe, NC)
-- Active swell access bins: 0-71 (0deg - 355deg)
-- Previous: min=45 max=170 center=107 half=62
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 355,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 177.5
WHERE id = '4c29c993-e769-414b-8539-7867c7e04772';

-- Beach: Wrightsville Beach (Wrightsville Beach, NC)
-- Active swell access bins: 70-51 (350deg - 255deg) [WRAPS]
-- Previous: min=45 max=160 center=102 half=57
UPDATE beaches SET
  swell_window_min_deg = 350,
  swell_window_max_deg = 255,
  swell_window_center_deg = 122.5,
  swell_window_halfwidth_deg = 132.5
WHERE id = '4b88f10a-c794-4144-b17a-133af9fee9f9';

-- Beach: Hampton Beach (Hampton, NH)
-- Active swell access bins: 0-45 (0deg - 225deg)
-- Previous: min=50 max=140 center=95 half=45
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 225,
  swell_window_center_deg = 112.5,
  swell_window_halfwidth_deg = 112.5
WHERE id = '8160745c-6322-45b0-8bad-81319574008b';

-- Beach: Asbury Park (Asbury Park, NJ)
-- Active swell access bins: 1-54 (5deg - 270deg)
-- Previous: min=90 max=160 center=125 half=35
UPDATE beaches SET
  swell_window_min_deg = 5,
  swell_window_max_deg = 270,
  swell_window_center_deg = 137.5,
  swell_window_halfwidth_deg = 132.5
WHERE id = '1279cf64-8ef0-4bb9-b786-6dd77fc2c201';

-- Beach: Belmar (Belmar, NJ)
-- Active swell access bins: 4-42 (20deg - 210deg)
-- Previous: min=90 max=180 center=135 half=45
-- Secondary windows: 54-60 (270deg - 300deg)
UPDATE beaches SET
  swell_window_min_deg = 20,
  swell_window_max_deg = 210,
  swell_window_center_deg = 115,
  swell_window_halfwidth_deg = 95
WHERE id = 'fb0ee60f-a269-47ed-b244-e8dc64fff891';

-- Beach: Long Branch (Long Branch, NJ)
-- Active swell access bins: 58-43 (290deg - 215deg) [WRAPS]
-- Previous: min=70 max=160 center=115 half=45
UPDATE beaches SET
  swell_window_min_deg = 290,
  swell_window_max_deg = 215,
  swell_window_center_deg = 72.5,
  swell_window_halfwidth_deg = 142.5
WHERE id = 'f84767c3-4c79-42ed-9e77-2351ab80d20e';

-- Beach: Manasquan Inlet (Manasquan, NJ)
-- Active swell access bins: 68-34 (340deg - 170deg) [WRAPS]
-- Previous: min=110 max=190 center=150 half=40
-- Secondary windows: 38-54 (190deg - 270deg), 59-60 (295deg - 300deg)
UPDATE beaches SET
  swell_window_min_deg = 340,
  swell_window_max_deg = 170,
  swell_window_center_deg = 75,
  swell_window_halfwidth_deg = 95
WHERE id = 'fb4fa0e0-328c-442b-b17a-82f95fbb6af5';

-- Beach: Sandy Hook (Sandy Hook, NJ)
-- Active swell access bins: 0-71 (0deg - 355deg)
-- Previous: min=130 max=190 center=160 half=30
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 355,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 177.5
WHERE id = '0e550715-3367-4829-8671-8f38bd5be34f';

-- Beach: Long Beach (Long Beach, NY)
-- Active swell access bins: 7-70 (35deg - 350deg)
-- Previous: min=90 max=190 center=140 half=50
UPDATE beaches SET
  swell_window_min_deg = 35,
  swell_window_max_deg = 350,
  swell_window_center_deg = 192.5,
  swell_window_halfwidth_deg = 157.5
WHERE id = '03dc4aef-c5e3-48a6-9563-39e0fe08c9b5';

-- Beach: Ditch Plains (Montauk, NY)
-- Active swell access bins: 61-50 (305deg - 250deg) [WRAPS]
-- Previous: min=110 max=190 center=150 half=40
UPDATE beaches SET
  swell_window_min_deg = 305,
  swell_window_max_deg = 250,
  swell_window_center_deg = 97.5,
  swell_window_halfwidth_deg = 152.5
WHERE id = '632e0e1c-a256-4d1f-8c6a-c1cbbc6ff2b6';

-- Beach: Turtle Cove (Montauk, NY)
-- Active swell access bins: 0-71 (0deg - 355deg)
-- Previous: min=130 max=180 center=155 half=25
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 355,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 177.5
WHERE id = 'fad234b3-4c14-4c02-a0fe-db1ba6e67bbe';

-- Beach: Rockaway Beach – 90th St (Queens, NY)
-- Active swell access bins: 17-67 (85deg - 335deg)
-- Previous: min=90 max=180 center=135 half=45
-- Secondary windows: 70-71 (350deg - 355deg)
UPDATE beaches SET
  swell_window_min_deg = 85,
  swell_window_max_deg = 335,
  swell_window_center_deg = 210,
  swell_window_halfwidth_deg = 125
WHERE id = '7e7b38b1-767f-4213-9314-538f51ab5084';

-- Beach: Rockaway Beach – 98th St (Queens, NY)
-- Active swell access bins: 70-52 (350deg - 260deg) [WRAPS]
-- Previous: min=90 max=180 center=135 half=45
UPDATE beaches SET
  swell_window_min_deg = 350,
  swell_window_max_deg = 260,
  swell_window_center_deg = 125,
  swell_window_halfwidth_deg = 135
WHERE id = '1a7ac53d-f3ac-4f78-a89a-8befb2fa69b7';

-- Beach: Short Sands (Oswald West) (Arch Cape, OR)
-- Active swell access bins: 30-7 (150deg - 35deg) [WRAPS]
-- Previous: min=180 max=270 center=225 half=68
UPDATE beaches SET
  swell_window_min_deg = 150,
  swell_window_max_deg = 35,
  swell_window_center_deg = 272.5,
  swell_window_halfwidth_deg = 122.5
WHERE id = '2c2dea98-280b-488c-9d46-ffed8226447b';

-- Beach: Bandon (Bandon, OR)
-- Active swell access bins: 34-67 (170deg - 335deg)
-- Previous: min=180 max=270 center=270 half=45
UPDATE beaches SET
  swell_window_min_deg = 170,
  swell_window_max_deg = 335,
  swell_window_center_deg = 252.5,
  swell_window_halfwidth_deg = 82.5
WHERE id = '3c8f272b-473a-4303-83b7-3081579a042b';

-- Beach: Brookings (Harris Beach) (Brookings, OR)
-- Active swell access bins: 27-66 (135deg - 330deg)
-- Previous: min=180 max=270 center=225 half=45
UPDATE beaches SET
  swell_window_min_deg = 135,
  swell_window_max_deg = 330,
  swell_window_center_deg = 232.5,
  swell_window_halfwidth_deg = 97.5
WHERE id = 'c62b7ad4-8deb-4275-889d-b0eb8ec7c5f0';

-- Beach: Cannon Beach (Ecola/Indian) (Cannon Beach, OR)
-- Active swell access bins: 30-1 (150deg - 5deg) [WRAPS]
-- Previous: min=180 max=270 center=248 half=45
UPDATE beaches SET
  swell_window_min_deg = 150,
  swell_window_max_deg = 5,
  swell_window_center_deg = 257.5,
  swell_window_halfwidth_deg = 107.5
WHERE id = 'b2286d82-0f40-45db-b4d1-3774950f6632';

-- Beach: Sunset Bay State Park (Charleston, OR)
-- Active swell access bins: 38-31 (190deg - 155deg) [WRAPS]
-- Previous: min=200 max=300 center=250 half=50
UPDATE beaches SET
  swell_window_min_deg = 190,
  swell_window_max_deg = 155,
  swell_window_center_deg = 352.5,
  swell_window_halfwidth_deg = 162.5
WHERE id = 'bd7a7984-d69a-4969-85b1-b97ea78d8fb7';

-- Beach: Bastendorff Beach (Coos Bay, OR)
-- Active swell access bins: 41-19 (205deg - 95deg) [WRAPS]
-- Previous: min=210 max=300 center=255 half=45
UPDATE beaches SET
  swell_window_min_deg = 205,
  swell_window_max_deg = 95,
  swell_window_center_deg = 330,
  swell_window_halfwidth_deg = 125
WHERE id = '615ff20a-922f-4487-88d8-fa7d830ebacf';

-- Beach: Florence South Jetty (Florence, OR)
-- Active swell access bins: 5-21 (25deg - 105deg)
-- Previous: min=180 max=270 center=225 half=45
UPDATE beaches SET
  swell_window_min_deg = 25,
  swell_window_max_deg = 105,
  swell_window_center_deg = 65,
  swell_window_halfwidth_deg = 40
WHERE id = '2b401051-cdbf-41a9-ac30-e636c33a42ef';

-- Beach: Gold Beach (South Jetty) (Gold Beach, OR)
-- Active swell access bins: 31-66 (155deg - 330deg)
-- Previous: min=180 max=270 center=270 half=30
UPDATE beaches SET
  swell_window_min_deg = 155,
  swell_window_max_deg = 330,
  swell_window_center_deg = 242.5,
  swell_window_halfwidth_deg = 87.5
WHERE id = '8d4afe79-ac68-4508-84d5-9175282a3f2c';

-- Beach: Nelscott Reef (Lincoln City, OR)
-- Active swell access bins: 26-10 (130deg - 50deg) [WRAPS]
-- Previous: min=230 max=310 center=270 half=40
UPDATE beaches SET
  swell_window_min_deg = 130,
  swell_window_max_deg = 50,
  swell_window_center_deg = 270,
  swell_window_halfwidth_deg = 140
WHERE id = '998e264e-3ad7-4875-bb19-04c25d1b173e';

-- Beach: Short Sands (Manzanita, OR)
-- Active swell access bins: 25-7 (125deg - 35deg) [WRAPS]
-- Previous: min=180 max=310 center=245 half=65
UPDATE beaches SET
  swell_window_min_deg = 125,
  swell_window_max_deg = 35,
  swell_window_center_deg = 260,
  swell_window_halfwidth_deg = 135
WHERE id = '6d3a734b-b051-490d-87e4-df83c3f49c42';

-- Beach: Agate Beach (Newport, OR)
-- Active swell access bins: 30-6 (150deg - 30deg) [WRAPS]
-- Previous: min=180 max=270 center=270 half=45
UPDATE beaches SET
  swell_window_min_deg = 150,
  swell_window_max_deg = 30,
  swell_window_center_deg = 270,
  swell_window_halfwidth_deg = 120
WHERE id = 'ffc0dcae-83d7-4b90-ade3-03c14e789088';

-- Beach: Otter Rock (Otter Rock, OR)
-- Active swell access bins: 27-6 (135deg - 30deg) [WRAPS]
-- Previous: min=180 max=300 center=240 half=60
UPDATE beaches SET
  swell_window_min_deg = 135,
  swell_window_max_deg = 30,
  swell_window_center_deg = 262.5,
  swell_window_halfwidth_deg = 127.5
WHERE id = '1fbbe6cc-783f-4b74-9664-a1996ca2649a';

-- Beach: Pacific City (Cape Kiwanda) (Pacific City, OR)
-- Active swell access bins: 41-2 (205deg - 10deg) [WRAPS]
-- Previous: min=180 max=270 center=270 half=30
-- Secondary windows: 20-36 (100deg - 180deg)
UPDATE beaches SET
  swell_window_min_deg = 205,
  swell_window_max_deg = 10,
  swell_window_center_deg = 287.5,
  swell_window_halfwidth_deg = 82.5
WHERE id = 'cf59e55d-f146-4a72-8daf-5781a0693d13';

-- Beach: Humbug Mountain (Port Orford) (Port Orford, OR)
-- Active swell access bins: 46-0 (230deg - 0deg) [WRAPS]
-- Previous: min=180 max=270 center=null half=null
-- Secondary windows: 35-38 (175deg - 190deg)
UPDATE beaches SET
  swell_window_min_deg = 230,
  swell_window_max_deg = 0,
  swell_window_center_deg = 295,
  swell_window_halfwidth_deg = 65
WHERE id = '387c8c1c-d6e3-494e-96d9-e5b025aa995b';

-- Beach: Seaside Cove (Seaside, OR)
-- Active swell access bins: 40-5 (200deg - 25deg) [WRAPS]
-- Previous: min=180 max=270 center=315 half=45
UPDATE beaches SET
  swell_window_min_deg = 200,
  swell_window_max_deg = 25,
  swell_window_center_deg = 292.5,
  swell_window_halfwidth_deg = 92.5
WHERE id = '4055099a-2e07-4a84-b17a-47a401ff749c';

-- Beach: Seaside Cove (Oregon) (Seaside, OR)
-- Active swell access bins: 41-12 (205deg - 60deg) [WRAPS]
-- Previous: min=200 max=310 center=255 half=55
UPDATE beaches SET
  swell_window_min_deg = 205,
  swell_window_max_deg = 60,
  swell_window_center_deg = 312.5,
  swell_window_halfwidth_deg = 107.5
WHERE id = '6f683baf-fd73-4a77-95b2-46f04050b136';

-- Beach: Crash Boat (Aguadilla, PR)
-- Active swell access bins: 26-7 (130deg - 35deg) [WRAPS]
-- Previous: min=300 max=359 center=330 half=30
UPDATE beaches SET
  swell_window_min_deg = 130,
  swell_window_max_deg = 35,
  swell_window_center_deg = 262.5,
  swell_window_halfwidth_deg = 132.5
WHERE id = 'acfad2b2-7d0c-4c42-9fba-e78fa73e4ae3';

-- Beach: Surfer's Beach (Aguadilla, PR)
-- Active swell access bins: 42-22 (210deg - 110deg) [WRAPS]
-- Previous: min=300 max=359 center=340 half=40
UPDATE beaches SET
  swell_window_min_deg = 210,
  swell_window_max_deg = 110,
  swell_window_center_deg = 340,
  swell_window_halfwidth_deg = 130
WHERE id = '4a0aac5b-86e5-433d-8a54-64c8e15197f9';

-- Beach: Wilderness (Aguadilla, PR)
-- Active swell access bins: 27-13 (135deg - 65deg) [WRAPS]
-- Previous: min=300 max=359 center=330 half=30
UPDATE beaches SET
  swell_window_min_deg = 135,
  swell_window_max_deg = 65,
  swell_window_center_deg = 280,
  swell_window_halfwidth_deg = 145
WHERE id = '2795319c-e680-45d0-a8af-f4c55631986e';

-- Beach: Jobos (Isabela, PR)
-- Active swell access bins: 48-24 (240deg - 120deg) [WRAPS]
-- Previous: min=300 max=359 center=330 half=30
UPDATE beaches SET
  swell_window_min_deg = 240,
  swell_window_max_deg = 120,
  swell_window_center_deg = 0,
  swell_window_halfwidth_deg = 120
WHERE id = '388bb737-5889-46d0-a182-d26567bf23f6';

-- Beach: Middles Isabela (Isabela, PR)
-- Active swell access bins: 51-20 (255deg - 100deg) [WRAPS]
-- Previous: min=300 max=359 center=330 half=30
UPDATE beaches SET
  swell_window_min_deg = 255,
  swell_window_max_deg = 100,
  swell_window_center_deg = 357.5,
  swell_window_halfwidth_deg = 102.5
WHERE id = '77903282-042b-4294-b6b2-2e3815489513';

-- Beach: Shacks (Isabela, PR)
-- Active swell access bins: 46-23 (230deg - 115deg) [WRAPS]
-- Previous: min=320 max=359 center=350 half=30
UPDATE beaches SET
  swell_window_min_deg = 230,
  swell_window_max_deg = 115,
  swell_window_center_deg = 352.5,
  swell_window_halfwidth_deg = 122.5
WHERE id = 'a240ccfc-d047-4471-a406-6ae5e92b0816';

-- Beach: La Pared (Luquillo, PR)
-- Active swell access bins: 50-30 (250deg - 150deg) [WRAPS]
-- Previous: min=0 max=60 center=30 half=30
UPDATE beaches SET
  swell_window_min_deg = 250,
  swell_window_max_deg = 150,
  swell_window_center_deg = 20,
  swell_window_halfwidth_deg = 130
WHERE id = '6c111c72-1773-490b-ae9e-fe6d81827989';

-- Beach: La Selva (Luquillo, PR)
-- Active swell access bins: 49-26 (245deg - 130deg) [WRAPS]
-- Previous: min=20 max=80 center=50 half=30
UPDATE beaches SET
  swell_window_min_deg = 245,
  swell_window_max_deg = 130,
  swell_window_center_deg = 7.5,
  swell_window_halfwidth_deg = 122.5
WHERE id = '7db87d82-4e66-4a48-9c8b-d5f95a282a4c';

-- Beach: Domes (Rincón, PR)
-- Active swell access bins: 23-18 (115deg - 90deg) [WRAPS]
-- Previous: min=280 max=350 center=315 half=35
UPDATE beaches SET
  swell_window_min_deg = 115,
  swell_window_max_deg = 90,
  swell_window_center_deg = 282.5,
  swell_window_halfwidth_deg = 167.5
WHERE id = '8a2b0951-38b4-4d7e-b5d5-6e076b58a5f0';

-- Beach: Indicators (Rincón, PR)
-- Active swell access bins: 21-15 (105deg - 75deg) [WRAPS]
-- Previous: min=280 max=350 center=315 half=35
UPDATE beaches SET
  swell_window_min_deg = 105,
  swell_window_max_deg = 75,
  swell_window_center_deg = 270,
  swell_window_halfwidth_deg = 165
WHERE id = 'f298d080-177b-4407-9e3a-be51bae58605';

-- Beach: María's (Rincón, PR)
-- Active swell access bins: 27-18 (135deg - 90deg) [WRAPS]
-- Previous: min=280 max=350 center=315 half=35
UPDATE beaches SET
  swell_window_min_deg = 135,
  swell_window_max_deg = 90,
  swell_window_center_deg = 292.5,
  swell_window_halfwidth_deg = 157.5
WHERE id = '5c879b55-26e6-4755-92f3-0291f4634f24';

-- Beach: Sandy Beach Rincón (Rincón, PR)
-- Active swell access bins: 28-19 (140deg - 95deg) [WRAPS]
-- Previous: min=280 max=340 center=310 half=30
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 95,
  swell_window_center_deg = 297.5,
  swell_window_halfwidth_deg = 157.5
WHERE id = 'f11ccd59-b778-4ea1-a8ff-88bffb447cd8';

-- Beach: The Point at Sandy (Rincón, PR)
-- Active swell access bins: 28-21 (140deg - 105deg) [WRAPS]
-- Previous: min=280 max=350 center=315 half=35
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 105,
  swell_window_center_deg = 302.5,
  swell_window_halfwidth_deg = 162.5
WHERE id = 'bfd3e168-f268-4692-901c-4b80b9b58dcb';

-- Beach: Tres Palmas (Rincón, PR)
-- Active swell access bins: 23-14 (115deg - 70deg) [WRAPS]
-- Previous: min=280 max=340 center=310 half=30
UPDATE beaches SET
  swell_window_min_deg = 115,
  swell_window_max_deg = 70,
  swell_window_center_deg = 272.5,
  swell_window_halfwidth_deg = 157.5
WHERE id = '88424465-0b1d-4f93-aa17-93dd1c4d03f3';

-- Beach: Narragansett Town Beach (Narragansett, RI)
-- Active swell access bins: 10-43 (50deg - 215deg)
-- Previous: min=80 max=180 center=130 half=50
UPDATE beaches SET
  swell_window_min_deg = 50,
  swell_window_max_deg = 215,
  swell_window_center_deg = 132.5,
  swell_window_halfwidth_deg = 82.5
WHERE id = '662cc0f6-4488-48dc-a820-47768a2e285b';

-- Beach: Point Judith (Narragansett, RI)
-- Active swell access bins: 60-55 (300deg - 275deg) [WRAPS]
-- Previous: min=130 max=190 center=160 half=30
UPDATE beaches SET
  swell_window_min_deg = 300,
  swell_window_max_deg = 275,
  swell_window_center_deg = 107.5,
  swell_window_halfwidth_deg = 167.5
WHERE id = '64cb1fb1-e5aa-4306-a6eb-87b9afd14e99';

-- Beach: Matunuck (South Kingstown, RI)
-- Active swell access bins: 28-60 (140deg - 300deg)
-- Previous: min=120 max=170 center=145 half=25
-- Secondary windows: 9-10 (45deg - 50deg), 18-19 (90deg - 95deg)
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 300,
  swell_window_center_deg = 220,
  swell_window_halfwidth_deg = 80
WHERE id = 'da7dc3e8-51c7-46a7-86f6-c3a90f4da036';

-- Beach: Folly Beach (Folly Beach, SC)
-- Active swell access bins: 4-57 (20deg - 285deg)
-- Previous: min=60 max=150 center=105 half=45
UPDATE beaches SET
  swell_window_min_deg = 20,
  swell_window_max_deg = 285,
  swell_window_center_deg = 152.5,
  swell_window_halfwidth_deg = 132.5
WHERE id = '76057acb-e6b4-46c0-ae0e-4110cd7a19d1';

-- Beach: Matagorda (Matagorda, TX)
-- Active swell access bins: 8-50 (40deg - 250deg)
-- Previous: min=90 max=180 center=135 half=45
UPDATE beaches SET
  swell_window_min_deg = 40,
  swell_window_max_deg = 250,
  swell_window_center_deg = 145,
  swell_window_halfwidth_deg = 105
WHERE id = 'd2d0b946-da8b-40ea-86ee-5ca2075d7851';

-- Beach: Port Aransas – Horace Caldwell Pier (Port Aransas, TX)
-- Active swell access bins: 71-52 (355deg - 260deg) [WRAPS]
-- Previous: min=90 max=180 center=135 half=45
UPDATE beaches SET
  swell_window_min_deg = 355,
  swell_window_max_deg = 260,
  swell_window_center_deg = 127.5,
  swell_window_halfwidth_deg = 132.5
WHERE id = '13febd14-22c1-41a8-a78d-09c436194c9f';

-- Beach: South Padre Island – Isla Blanca Park (South Padre Island, TX)
-- Active swell access bins: 65-34 (325deg - 170deg) [WRAPS]
-- Previous: min=90 max=180 center=135 half=45
-- Secondary windows: 44-45 (220deg - 225deg)
UPDATE beaches SET
  swell_window_min_deg = 325,
  swell_window_max_deg = 170,
  swell_window_center_deg = 67.5,
  swell_window_halfwidth_deg = 102.5
WHERE id = 'fa19107a-a276-4257-872d-c5331264d01b';

-- Beach: Surfside Beach (Surfside Beach, TX)
-- Active swell access bins: 25-45 (125deg - 225deg)
-- Previous: min=90 max=180 center=135 half=45
-- Secondary windows: 6-22 (30deg - 110deg)
UPDATE beaches SET
  swell_window_min_deg = 125,
  swell_window_max_deg = 225,
  swell_window_center_deg = 175,
  swell_window_halfwidth_deg = 50
WHERE id = '466b9671-93c6-402c-9de6-627367d9de6c';

-- Beach: La Push — First Beach (La Push, WA)
-- Active swell access bins: 31-58 (155deg - 290deg)
-- Previous: min=180 max=270 center=248 half=68
UPDATE beaches SET
  swell_window_min_deg = 155,
  swell_window_max_deg = 290,
  swell_window_center_deg = 222.5,
  swell_window_halfwidth_deg = 67.5
WHERE id = '058c415c-39da-41bb-aee9-c4942d79e95d';

-- Beach: La Push – Second Beach (La Push, WA)
-- Active swell access bins: 19-57 (95deg - 285deg)
-- Previous: min=200 max=300 center=250 half=50
UPDATE beaches SET
  swell_window_min_deg = 95,
  swell_window_max_deg = 285,
  swell_window_center_deg = 190,
  swell_window_halfwidth_deg = 95
WHERE id = '281b7eef-bcc3-4ecd-998f-1faa190ed956';

-- Beach: La Push – Third Beach (La Push, WA)
-- Active swell access bins: 23-65 (115deg - 325deg)
-- Previous: min=200 max=300 center=250 half=50
UPDATE beaches SET
  swell_window_min_deg = 115,
  swell_window_max_deg = 325,
  swell_window_center_deg = 220,
  swell_window_halfwidth_deg = 105
WHERE id = 'c03fc6d7-913e-4c99-b1f4-610d036b3cbf';

-- Beach: Long Beach (Boardwalk) (Long Beach, WA)
-- Active swell access bins: 33-5 (165deg - 25deg) [WRAPS]
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 165,
  swell_window_max_deg = 25,
  swell_window_center_deg = 275,
  swell_window_halfwidth_deg = 110
WHERE id = '839bab65-0ae4-443e-94a5-0d5bb4b4a5a8';

-- Beach: Hobuck Beach (Neah Bay) (Neah Bay, WA)
-- Active swell access bins: 31-65 (155deg - 325deg)
-- Previous: min=200 max=300 center=250 half=50
UPDATE beaches SET
  swell_window_min_deg = 155,
  swell_window_max_deg = 325,
  swell_window_center_deg = 240,
  swell_window_halfwidth_deg = 85
WHERE id = '44c9add8-cbd4-4e2f-8554-58a32b9b3c08';

-- Beach: Ocean Shores (Ocean Shores, WA)
-- Active swell access bins: 0-71 (0deg - 355deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 355,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 177.5
WHERE id = '04ab6e6a-477f-49ab-b435-6b201134bcbf';

-- Beach: Ocean Shores / North Beaches (Ocean Shores, WA)
-- Active swell access bins: 0-71 (0deg - 355deg)
-- Previous: min=180 max=270 center=null half=null
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 355,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 177.5
WHERE id = '60b6bb17-dc08-4f18-8241-33729bcbc742';

-- Beach: Seabrook (Pacific Beach area) (Pacific Beach, WA)
-- Active swell access bins: 28-1 (140deg - 5deg) [WRAPS]
-- Previous: no swell window set
UPDATE beaches SET
  swell_window_min_deg = 140,
  swell_window_max_deg = 5,
  swell_window_center_deg = 252.5,
  swell_window_halfwidth_deg = 112.5
WHERE id = '5079a9ab-8d43-433e-99ea-20d3667dd0a8';

-- Beach: Westport Beach (Westport, WA)
-- Active swell access bins: 0-71 (0deg - 355deg)
-- Previous: min=180 max=270 center=248 half=68
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 355,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 177.5
WHERE id = '260868de-b952-470b-a764-b95b3e7f6655';

-- Beach: Westport – Half Moon Bay (The Cove) (Westport, WA)
-- Active swell access bins: 48-45 (240deg - 225deg) [WRAPS]
-- Previous: min=200 max=310 center=255 half=55
UPDATE beaches SET
  swell_window_min_deg = 240,
  swell_window_max_deg = 225,
  swell_window_center_deg = 52.5,
  swell_window_halfwidth_deg = 172.5
WHERE id = '51180cd3-b83b-4cf8-99b2-8705c68b87ef';

-- Beach: Westport (Marina/Groins/Jetty) (Westport, WA)
-- Active swell access bins: 0-71 (0deg - 355deg)
-- Previous: min=180 max=270 center=248 half=68
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 355,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 177.5
WHERE id = 'a83def7f-6b68-402f-a0ef-f78a5bcfbf81';

-- Beach: Westport – The Groins (Westport, WA)
-- Active swell access bins: 0-71 (0deg - 355deg)
-- Previous: min=200 max=310 center=255 half=55
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 355,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 177.5
WHERE id = '4ec455fa-dab5-4cfa-884f-1f1d29154c74';

-- Beach: Westport – The Jetty (Westport, WA)
-- Active swell access bins: 0-71 (0deg - 355deg)
-- Previous: min=200 max=310 center=255 half=55
UPDATE beaches SET
  swell_window_min_deg = 0,
  swell_window_max_deg = 355,
  swell_window_center_deg = 177.5,
  swell_window_halfwidth_deg = 177.5
WHERE id = 'cb75834d-79cb-4b65-859b-d0a370bfc75e';

COMMIT;
