-- Add comprehensive LA beaches to expand /forecast/los-angeles coverage
-- Fixes Venice Breakwater city and adds 18 new beaches
-- Safe, idempotent using ON CONFLICT

BEGIN;

-- Fix Venice Breakwater: change city from 'Los Angeles' to 'Venice'
-- Note: This UPDATE is safe to run even if the record doesn't exist (0 rows affected).
-- The Venice Breakwater beach was added in 20251205000000_add_socal_beaches.sql with city='Los Angeles'.
-- This correction ensures it appears in the Venice city filter for the LA forecast region.
UPDATE public.beaches
SET city = 'Venice'
WHERE name = 'Venice Breakwater' AND city = 'Los Angeles';

INSERT INTO public.beaches (
  id,
  name,
  city,
  state,
  country,
  lat,
  lon,
  break_type,
  skill_level,
  hazards,
  features,
  swell_window_min_deg,
  swell_window_max_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  preference_model,
  aspect_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  best_months,
  slug,
  region,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  crowd_level,
  real_takeaways,
  is_private
) VALUES

-- ============================================================================
-- MALIBU COAST BEACHES
-- ============================================================================

-- 1. Malibu Surfrider (First Point)
(
  'afbd3aaf-099f-4147-b845-443590f0e148',
  'Malibu Surfrider (First Point)',
  'Malibu',
  'CA',
  'USA',
  34.0355,
  -118.6796,
  'point',
  'intermediate',
  ARRAY['crowds', 'rocks', 'localism'],
  ARRAY['Classic longboard wave', 'Cobblestone point', 'Iconic location', 'Lifeguards', 'Parking lot'],
  180,
  260,
  0,
  45,
  12,
  8,
  1.0,
  4.0,
  '{"tide": "mid", "primary_swell": {"dir_deg": 220, "period_s": 12}, "notes": "Best on SW swell with north winds; works most tides but mid is optimal."}'::jsonb,
  180,
  220,
  40,
  ARRAY[5,6,7,8,9],
  'malibu-surfrider-first-point-malibu-ca',
  'Los Angeles',
  'Malibu First Point is one of the most iconic surf breaks in the world. This cobblestone point produces long, peeling right-handers perfect for longboarding. On good days, rides can link from First Point through Second and Third Points for 200+ yard rides. The wave is incredibly consistent during summer SW swell season.',
  'Large paid parking lot at Surfrider Beach fills early on weekends. Arrive before 8am or use PCH shoulder parking.',
  'Easy access from the parking lot. Walk across the lagoon bridge or along the beach to the point.',
  'Sit on the inside for easier waves or paddle to the top of the point for longer rides. The wave peels predictably along the point.',
  'Extremely crowded - one of the busiest lineups in California. Respect the rotation and be prepared to wait.',
  'Mid tide with offshore north winds and 3-6 ft SW swell.',
  ARRAY['Very crowded', 'Localism', 'Rocks on inside'],
  'Classic longboard etiquette applies. Wait your turn, share waves, and respect the locals who surf here daily.',
  'very_heavy',
  ARRAY['Arrive before 8am for parking', 'Best on summer SW swells', 'Classic longboard wave - bring your log'],
  false
),

-- 2. Malibu Second Point
(
  '005b0ba6-a2d9-4069-adbb-6571baffa698',
  'Malibu Second Point',
  'Malibu',
  'CA',
  'USA',
  34.0365,
  -118.6815,
  'point',
  'upper-intermediate',
  ARRAY['rocks', 'localism', 'strong currents'],
  ARRAY['Extension of First Point', 'Faster sections', 'Shortboard friendly', 'Scenic'],
  180,
  260,
  0,
  45,
  12,
  8,
  1.5,
  4.5,
  '{"tide": "mid", "primary_swell": {"dir_deg": 220, "period_s": 13}, "notes": "Faster and more powerful than First Point; needs more size to connect."}'::jsonb,
  190,
  220,
  40,
  ARRAY[5,6,7,8,9],
  'malibu-second-point-malibu-ca',
  'Los Angeles',
  'Second Point is the middle section of the famous Malibu point break system. The wave here is faster and more powerful than First Point, making it better suited for shortboards and more experienced surfers. On bigger swells, you can catch waves at Second Point and ride through to First Point.',
  'Same parking situation as First Point - arrive early or be prepared to walk from PCH parking.',
  'Paddle from the main beach or work your way up from First Point during your session.',
  'Position yourself at the top of the section to catch sets. The wave speed increases here - be ready to pump.',
  'Less crowded than First Point but still busy. Shortboarders dominate when it''s working well.',
  'Mid tide, light north winds, 4-6 ft SW swell.',
  ARRAY['Faster sections require commitment', 'Rocks', 'Susceptible to tide/swell changes'],
  'Know your ability level - this section moves faster and requires quick reactions.',
  'heavy',
  ARRAY['Faster than First Point', 'Better for shortboards', 'Can connect to First Point on good days'],
  false
),

-- 3. Malibu Third Point
(
  'abd3b0fa-6de6-480a-a6cc-c5c83143a707',
  'Malibu Third Point',
  'Malibu',
  'CA',
  'USA',
  34.0375,
  -118.6835,
  'point',
  'advanced',
  ARRAY['powerful waves', 'rocks', 'localism', 'strong currents'],
  ARRAY['Outermost takeoff', 'Biggest waves', 'Left and right options', 'Challenging'],
  180,
  280,
  0,
  40,
  15,
  10,
  2.0,
  5.0,
  '{"tide": "mid", "primary_swell": {"dir_deg": 230, "period_s": 14}, "notes": "The heavy section - needs solid swell to break properly. Left and right options."}'::jsonb,
  200,
  230,
  50,
  ARRAY[5,6,7,8,9],
  'malibu-third-point-malibu-ca',
  'Los Angeles',
  'Third Point is the outermost and most powerful section of Malibu. When a solid SW swell arrives, Third Point produces the biggest and heaviest waves of the complex. Both lefts and rights are possible here, and on epic days, surfers can catch a wave at Third and ride it all the way through to First Point.',
  'Park in the main lot and prepare for a longer paddle out to reach Third Point.',
  'Paddle from the beach during a lull or work your way out through the channel on the north side.',
  'Position at the outermost point. Needs more swell to break - when it''s working, it''s the best wave at Malibu.',
  'Experienced crew when it''s on. Locals have priority and expect proper etiquette.',
  'Mid tide, north winds, 5-8 ft SW swell.',
  ARRAY['Powerful waves', 'Rocks', 'Strong currents on big days', 'Localism'],
  'Advanced spot with a tight crew. Don''t paddle out unless you can handle the power.',
  'heavy',
  ARRAY['Most powerful section at Malibu', 'Needs 5+ ft to really work', 'Can ride through all three points on epic days'],
  false
),

-- 4. Point Dume
(
  'bba95994-b2a3-4505-8e6f-1f85ccfbb0dc',
  'Point Dume',
  'Malibu',
  'CA',
  'USA',
  34.0015,
  -118.8065,
  'reef',
  'intermediate',
  ARRAY['rocks', 'long paddle', 'strong currents', 'private property access'],
  ARRAY['Scenic location', 'Less crowded', 'Rock/sand reef', 'State beach'],
  160,
  240,
  45,
  40,
  12,
  8,
  1.0,
  3.5,
  '{"tide": "mid", "primary_swell": {"dir_deg": 200, "period_s": 12}, "notes": "Best on pure S swell; draining tide provides the best shape."}'::jsonb,
  200,
  200,
  40,
  ARRAY[7,8,9],
  'point-dume-malibu-ca',
  'Los Angeles',
  'Point Dume is a scenic reef break at the southern end of Zuma Beach. The wave breaks over a mix of rock and sand and picks up south swells better than most LA spots. The hike down and paddle out keep crowds manageable, making it a good option for intermediate surfers looking for uncrowded waves.',
  'Park at Point Dume State Beach lot ($12) or along Westward Beach Road. The walk adds to the adventure.',
  'Hike down the trail from the parking area - expect a 10-15 minute walk and paddle.',
  'Position near the reef and watch for the S swell lines. Mid to low tide provides the best shape.',
  'The hike keeps crowds down. Mostly intermediate surfers and some locals.',
  'Mid tide, NE winds, 3-5 ft S swell.',
  ARRAY['Rocks', 'Long paddle', 'Strong currents', 'Private property nearby'],
  'Respect the natural area and other beach users. Pack out all trash.',
  'medium',
  ARRAY['Requires a hike - worth it', 'Best on summer S swells', 'Less crowded than nearby spots'],
  false
),

-- 5. Leo Carrillo State Beach
(
  'a13f108b-ad2a-43fa-8ea7-40577ebce66c',
  'Leo Carrillo State Beach',
  'Malibu',
  'CA',
  'USA',
  34.0445,
  -118.9355,
  'beach',
  'beginner',
  ARRAY['rip currents', 'rocks on north end'],
  ARRAY['Beginner friendly', 'State park facilities', 'Camping', 'Lifeguards', 'Tide pools'],
  180,
  270,
  0,
  45,
  12,
  8,
  1.5,
  4.0,
  '{"tide": "mid-rising", "primary_swell": {"dir_deg": 225, "period_s": 11}, "notes": "Forgiving beach break good for beginners; reef section on north end for more advanced."}'::jsonb,
  200,
  225,
  45,
  ARRAY[5,6,7,8,9],
  'leo-carrillo-state-beach-malibu-ca',
  'Los Angeles',
  'Leo Carrillo is a family-friendly state beach with a gentle beach break perfect for beginners. The main beach offers forgiving waves over sand, while the north end has a reef section for more advanced surfers. Great facilities including camping, restrooms, and lifeguards make this an ideal learning spot.',
  'State beach parking ($12) with ample spaces. Camping reservations fill months in advance.',
  'Easy access from the parking lot directly to the beach. Short walk to the main peaks.',
  'Beginners should stick to the main beach break. More advanced surfers can check the reef on the north end.',
  'Family beach vibe with surf schools and learners. Spread out along the beach to find space.',
  'Mid rising tide, north winds, 2-4 ft SW swell.',
  ARRAY['Rip currents', 'Rocks on north end'],
  'Family beach - be mindful of swimmers and surf school students.',
  'medium',
  ARRAY['Great beginner spot', 'State park with camping', 'Reef section for more advanced surfers'],
  false
),

-- 6. Latigo Point
(
  'ca9f0f1b-f4f5-4601-91c5-5e972c5f1a41',
  'Latigo Point',
  'Malibu',
  'CA',
  'USA',
  34.0325,
  -118.6545,
  'point',
  'intermediate',
  ARRAY['rocks', 'rip currents', 'difficult access', 'PCH parking'],
  ARRAY['Right-hand point', 'Less crowded', 'Scenic cliffs', 'Alternative to Malibu'],
  160,
  220,
  335,
  40,
  12,
  8,
  1.0,
  3.5,
  '{"tide": "low-mid", "primary_swell": {"dir_deg": 190, "period_s": 12}, "notes": "Best on S swell with NNW winds; low-mid tide for shape."}'::jsonb,
  200,
  190,
  30,
  ARRAY[6,7,8,9],
  'latigo-point-malibu-ca',
  'Los Angeles',
  'Latigo Point is a right-hand point break that offers a less crowded alternative to the main Malibu points. The wave breaks over a cobble/reef bottom and works best on south swells. PCH access can be tricky, but the reward is quality waves without the Surfrider crowds.',
  'Limited pullouts along PCH - be very careful with traffic. No formal parking lot.',
  'Access via unmarked trails from PCH pullouts. Scramble down to the beach and paddle out.',
  'Position at the top of the point for the longest rides. The wave wraps nicely on S swells.',
  'Less crowded due to difficult access. Locals appreciate the peace - keep it that way.',
  'Low-mid tide, NNW winds, 3-5 ft S swell.',
  ARRAY['Difficult PCH access', 'Rocks', 'Rip currents'],
  'Keep this spot under the radar. Respect the locals and the challenging access.',
  'low',
  ARRAY['Less crowded Malibu alternative', 'Difficult PCH access', 'Best on summer S swells'],
  false
),

-- ============================================================================
-- SANTA MONICA BAY BEACHES
-- ============================================================================

-- 7. Santa Monica Beach (Pier)
(
  '29fefd13-7472-4ce8-9c3c-be3dabcbb233',
  'Santa Monica Beach',
  'Santa Monica',
  'CA',
  'USA',
  34.0085,
  -118.4985,
  'beach',
  'beginner',
  ARRAY['crowds', 'swimmers', 'pier pilings'],
  ARRAY['Beginner friendly', 'Wide beach', 'Rental shops', 'Lifeguards', 'Iconic pier'],
  200,
  280,
  45,
  45,
  15,
  10,
  0.5,
  3.0,
  '{"tide": "low", "primary_swell": {"dir_deg": 240, "period_s": 11}, "notes": "Forgiving beach break; best at low tide when sandbars are shallower."}'::jsonb,
  250,
  240,
  40,
  ARRAY[11,12,1,2],
  'santa-monica-beach-santa-monica-ca',
  'Los Angeles',
  'Santa Monica Beach near the iconic pier offers a wide, forgiving beach break perfect for beginners. Multiple rental shops and surf schools operate here, making it easy to get started. The waves are generally small and mellow, best during winter west swells.',
  'Multiple paid lots near the pier ($10-20). Street parking available but limited. Bike share stations nearby.',
  'Easy access from the pier area. Walk down to the beach and find a peak away from swimmers.',
  'Look for sandbars forming peaks. Low tide exposes the best shapes. Stay away from the pier pilings.',
  'Very crowded with swimmers, surfers, and surf schools. Spread north or south of the pier for more space.',
  'Low tide, NE winds, 2-4 ft WSW swell.',
  ARRAY['Crowded with swimmers', 'Pier pilings', 'Small waves'],
  'Tourist beach - be patient with swimmers and surf school students.',
  'heavy',
  ARRAY['Great beginner spot', 'Surf rentals available', 'Best in winter'],
  false
),

-- 8. Bay Street (Santa Monica)
(
  '6c4b160d-8aba-4078-aca7-9bde1bf81738',
  'Bay Street',
  'Santa Monica',
  'CA',
  'USA',
  34.0125,
  -118.4955,
  'beach',
  'intermediate',
  ARRAY['breakwater', 'pollution', 'crowds'],
  ARRAY['Wedging waves', 'More power than main beach', 'Street parking'],
  200,
  280,
  45,
  40,
  12,
  8,
  0.5,
  3.0,
  '{"tide": "low-rising", "primary_swell": {"dir_deg": 240, "period_s": 12}, "notes": "Wedge near the breakwater creates more powerful peaks."}'::jsonb,
  260,
  240,
  40,
  ARRAY[11,12,1],
  'bay-street-santa-monica-ca',
  'Los Angeles',
  'Bay Street is the more powerful section of Santa Monica Beach, located near a small breakwater that creates wedging waves. The setup produces punchier peaks than the main beach, attracting intermediate surfers looking for more action.',
  'Street parking along Bay Street and Ocean Avenue. Metered spots - bring quarters.',
  'Walk down Bay Street to the beach. Enter near the breakwater for the best peaks.',
  'Position near the breakwater where swells refract and wedge. The wave has more push here.',
  'Less crowded than the main pier area but still busy on good days.',
  'Low rising tide, NE winds, 3-5 ft WSW swell.',
  ARRAY['Breakwater hazard', 'Pollution after rain', 'Crowds'],
  'Standard beach etiquette. Respect the small local crew.',
  'medium',
  ARRAY['More power than main Santa Monica', 'Wedging peaks near breakwater', 'Best in winter'],
  false
),

-- 9. Will Rogers State Beach
(
  '3f1eeb72-41c1-4f58-9621-fd13df129c1a',
  'Will Rogers State Beach',
  'Santa Monica',
  'CA',
  'USA',
  34.0285,
  -118.5325,
  'beach',
  'beginner',
  ARRAY['rip currents', 'crowds on weekends'],
  ARRAY['Family friendly', 'Gentle waves', 'Lifeguards', 'Large parking', 'Beach volleyball'],
  180,
  260,
  45,
  45,
  15,
  10,
  1.0,
  3.5,
  '{"tide": "mid", "primary_swell": {"dir_deg": 220, "period_s": 11}, "notes": "Gentle beach break for beginners; mid tide provides the best shape."}'::jsonb,
  250,
  220,
  40,
  ARRAY[11,12],
  'will-rogers-state-beach-santa-monica-ca',
  'Los Angeles',
  'Will Rogers State Beach offers a gentle, forgiving beach break ideal for beginners and families. The wide beach and mellow waves make it a popular spot for surf lessons. Best during winter when west swells push through.',
  'Large paid parking lots along PCH ($5-15). Plenty of space even on busy days.',
  'Easy access from the parking lots directly to the beach.',
  'Gentle waves best for learning. Look for the softer inside reform.',
  'Popular family beach with volleyball and sunbathers. Surf schools operate here.',
  'Mid tide, NE winds, 2-4 ft SW swell.',
  ARRAY['Rip currents', 'Weekend crowds'],
  'Family beach - be extremely careful around swimmers and children.',
  'medium',
  ARRAY['Great for beginners and families', 'Large parking lot', 'Best in winter'],
  false
),

-- 10. Venice Beach
(
  '11467f21-5a69-430d-9eb9-05a46cd39990',
  'Venice Beach',
  'Venice',
  'CA',
  'USA',
  33.9925,
  -118.4795,
  'beach',
  'beginner',
  ARRAY['crowds', 'swimmers', 'pollution'],
  ARRAY['Iconic boardwalk', 'Beach break', 'Rentals available', 'Lifeguards', 'Easy access'],
  200,
  280,
  45,
  45,
  15,
  10,
  0.5,
  3.0,
  '{"tide": "low-falling", "primary_swell": {"dir_deg": 240, "period_s": 11}, "notes": "Standard beach break with shifting sandbars; low tide is best."}'::jsonb,
  260,
  240,
  40,
  ARRAY[6,7,8,9],
  'venice-beach-venice-ca',
  'Los Angeles',
  'Venice Beach is an iconic LA surf spot with a classic beach break setup. The shifting sandbars produce lefts and rights over a sandy bottom. While not known for world-class waves, Venice offers consistent, accessible surf steps from the famous boardwalk.',
  'Paid lots near the boardwalk ($10-20) or metered street parking. Arrive early on weekends.',
  'Walk through the boardwalk area to the beach. Multiple access points along the strand.',
  'Sandbars shift - scout from the boardwalk to find the best peaks. Low falling tide often best.',
  'Crowded with swimmers, surfers, and tourists. Surf early morning for fewer people.',
  'Low falling tide, NE winds, 2-4 ft SW swell.',
  ARRAY['Very crowded', 'Swimmers', 'Pollution after rain'],
  'Tourist beach - be patient and aware of non-surfers in the water.',
  'heavy',
  ARRAY['Iconic LA beach', 'Best in early morning', 'Summer SW swells work well'],
  false
),

-- ============================================================================
-- SOUTH BAY BEACHES
-- ============================================================================

-- 11. Dockweiler State Beach
(
  '1376c3e3-d7b2-408d-b1d4-e6e004cbe063',
  'Dockweiler State Beach',
  'Playa del Rey',
  'CA',
  'USA',
  33.9525,
  -118.4455,
  'beach',
  'beginner',
  ARRAY['airplane noise', 'rip currents'],
  ARRAY['Uncrowded', 'Wide beach', 'Fire pits', 'Easy parking', 'Near LAX'],
  180,
  260,
  65,
  45,
  15,
  10,
  1.0,
  4.0,
  '{"tide": "mid", "primary_swell": {"dir_deg": 220, "period_s": 11}, "notes": "Uncrowded beach break near LAX; mid tide provides consistent shape."}'::jsonb,
  260,
  220,
  40,
  ARRAY[6,7,8,9],
  'dockweiler-state-beach-playa-del-rey-ca',
  'Los Angeles',
  'Dockweiler State Beach is a hidden gem for LA surfers looking to escape crowds. Located directly under the LAX flight path, the beach offers uncrowded waves on a wide stretch of sand. The trade-off for space is airplane noise, but many surfers consider it worthwhile.',
  'Large free parking lot with easy access. Rarely fills up.',
  'Walk from the parking lot to the beach. Pick a peak and paddle out.',
  'Standard beach break - look for sandbars forming peaks. Mid tide usually best.',
  'Often uncrowded due to location. Fire pits make it popular for evening bonfires.',
  'Mid tide, ENE winds, 2-4 ft SW swell.',
  ARRAY['Airplane noise', 'Rip currents'],
  'Relaxed vibe. Great spot to learn without crowds.',
  'low',
  ARRAY['Uncrowded - worth the airplane noise', 'Free parking', 'Great for beginners'],
  false
),

-- 12. El Porto
(
  '0bad04fb-2c2e-4d6f-b47d-ac77f7ce5836',
  'El Porto',
  'Manhattan Beach',
  'CA',
  'USA',
  33.9015,
  -118.4165,
  'beach',
  'intermediate',
  ARRAY['rip currents', 'closeouts', 'crowds'],
  ARRAY['Consistent waves', 'NW swell magnet', 'Street parking', 'Power plant backdrop'],
  260,
  320,
  90,
  35,
  12,
  8,
  1.5,
  4.0,
  '{"tide": "mid", "primary_swell": {"dir_deg": 290, "period_s": 13}, "notes": "The premier South Bay wave; NW swell magnet that''s best at mid tide."}'::jsonb,
  270,
  290,
  30,
  ARRAY[10,11,12,1,2,3,4],
  'el-porto-manhattan-beach-ca',
  'Los Angeles',
  'El Porto is the premier surf spot in the South Bay and one of the most consistent waves in Southern California. This beach break sits in front of the El Segundo power plant and magnetically attracts NW swell. When winter swells hit, El Porto delivers powerful, punchy peaks that draw crowds from across LA.',
  'Free street parking along 45th Street. Arrive early on swell days - competition for spots is fierce.',
  'Walk down 45th Street to the beach. Easy access to the main peaks.',
  'Sit where the power plant outflow meets the beach for the most consistent peaks. Mid tide shapes up best.',
  'Very crowded on any day with swell. Strong local crew that surfs here daily.',
  'Mid tide, E-SE winds, 4-8 ft WNW swell.',
  ARRAY['Very crowded', 'Strong rip currents', 'Closeouts on big days'],
  'Crowded lineup with experienced surfers. Know your ability and don''t drop in.',
  'very_heavy',
  ARRAY['Best wave in the South Bay', 'NW swell magnet', 'Arrive early or miss out'],
  false
),

-- 13. Hermosa Beach Pier
(
  '326941d7-6c39-4e82-b045-941b156f7897',
  'Hermosa Beach Pier',
  'Hermosa Beach',
  'CA',
  'USA',
  33.8625,
  -118.4005,
  'beach',
  'intermediate',
  ARRAY['crowds', 'rip currents', 'pier pilings'],
  ARRAY['Pier creates sandbars', 'Consistent', 'Downtown location', 'Lifeguards'],
  200,
  300,
  90,
  40,
  12,
  8,
  1.5,
  4.0,
  '{"tide": "mid-rising", "primary_swell": {"dir_deg": 250, "period_s": 12}, "notes": "Pier creates consistent sandbars; rising tide provides the best push."}'::jsonb,
  260,
  250,
  50,
  ARRAY[10,11,12,1,2,3],
  'hermosa-beach-pier-hermosa-beach-ca',
  'Los Angeles',
  'Hermosa Beach Pier produces consistent peaks on both sides of the pier. The structure creates sandbars that shape quality waves on most swells. Located in the heart of downtown Hermosa, the break is convenient but crowded.',
  'Paid lots near the pier or metered street parking. Bring quarters and arrive early.',
  'Walk from downtown Hermosa to the pier. Choose north or south side based on conditions.',
  'Sandbars form on both sides of the pier. North side often has better shape, south side gets more swell.',
  'Crowded with locals and visitors. Early mornings offer the best chance at uncrowded peaks.',
  'Mid rising tide, E winds, 3-6 ft SW/NW swell.',
  ARRAY['Pier pilings', 'Crowds', 'Rip currents'],
  'Respect the pier - don''t surf too close to the pilings.',
  'high',
  ARRAY['Consistent pier peaks', 'Best on rising tide', 'Heart of Hermosa'],
  false
),

-- 14. Hermosa Beach South
(
  '110a87b2-cb2c-4bb7-8e83-b895fb2f4940',
  'Hermosa Beach South',
  'Hermosa Beach',
  'CA',
  'USA',
  33.8565,
  -118.3985,
  'beach',
  'lower-intermediate',
  ARRAY['rip currents'],
  ARRAY['Less crowded than pier', 'Mellow waves', 'Residential area', 'Lifeguards'],
  260,
  320,
  90,
  40,
  15,
  10,
  1.5,
  4.0,
  '{"tide": "mid-rising", "primary_swell": {"dir_deg": 290, "period_s": 12}, "notes": "Mellower beach break south of the pier; less crowded alternative."}'::jsonb,
  260,
  290,
  30,
  ARRAY[6,9,10,11],
  'hermosa-beach-south-hermosa-beach-ca',
  'Los Angeles',
  'South Hermosa offers a mellower beach break experience compared to the pier area. The waves are generally smaller and less crowded, making it a good option for intermediate surfers or those wanting to avoid the pier crowd.',
  'Street parking in residential area. Be mindful of permit zones.',
  'Beach access via street ends south of the pier. Short walk to the water.',
  'Standard beach break with shifting peaks. Less consistent than the pier but also less crowded.',
  'Smaller crowd than the pier area. More relaxed vibe.',
  'Mid rising tide, E winds, 2-4 ft WNW swell.',
  ARRAY['Rip currents'],
  'Residential area - keep noise down and respect the neighbors.',
  'medium',
  ARRAY['Less crowded than the pier', 'Good intermediate option', 'Autumn often best'],
  false
),

-- 15. Torrance Beach (RAT Beach)
(
  'a3e9d10c-92e9-4302-b808-a3de0c2eca22',
  'Torrance Beach (RAT Beach)',
  'Torrance',
  'CA',
  'USA',
  33.8125,
  -118.3925,
  'beach',
  'beginner',
  ARRAY['rip currents'],
  ARRAY['Hidden gem', 'Less crowded', 'Bike path access', 'Lifeguards', 'Scenic cliffs'],
  240,
  310,
  90,
  45,
  15,
  10,
  2.5,
  5.0,
  '{"tide": "high", "primary_swell": {"dir_deg": 275, "period_s": 12}, "notes": "Works best at higher tides when the beach gets more push."}'::jsonb,
  250,
  275,
  35,
  ARRAY[10,11,12,1,2,3],
  'torrance-beach-rat-beach-torrance-ca',
  'Los Angeles',
  'RAT Beach (Right After Torrance) is a hidden gem at the south end of the Strand bike path. The beach break here is more mellow than neighboring spots, making it ideal for beginners. The scenic Palos Verdes cliffs provide a beautiful backdrop.',
  'Small parking lot at the beach or park along the Strand and bike in.',
  'Access via the bike path or from the small parking area. Easy walk to the water.',
  'Higher tides work best here. Look for peaks forming near the lifeguard tower.',
  'Less crowded than other South Bay spots. Local regulars but generally friendly.',
  'High tide, E winds, 2-4 ft WNW swell.',
  ARRAY['Rip currents'],
  'Mellow spot - share waves and enjoy the scenery.',
  'low',
  ARRAY['Hidden gem of the South Bay', 'Best at higher tides', 'Scenic PV cliffs backdrop'],
  false
),

-- 16. Palos Verdes Cove
(
  '9a3da3b5-e25b-45a4-b9dd-3ba6bc75a9fa',
  'Palos Verdes Cove',
  'Palos Verdes',
  'CA',
  'USA',
  33.7865,
  -118.4125,
  'reef',
  'upper-intermediate',
  ARRAY['rocks', 'localism', 'powerful waves', 'difficult access'],
  ARRAY['Multiple breaks', 'Scenic location', 'Less crowded', 'Variety of waves'],
  240,
  300,
  135,
  40,
  12,
  8,
  1.0,
  3.5,
  '{"tide": "low-mid", "primary_swell": {"dir_deg": 270, "period_s": 13}, "notes": "Multiple reef breaks with varying difficulty; low-mid tide for shape."}'::jsonb,
  240,
  270,
  30,
  ARRAY[11,12,1,2],
  'palos-verdes-cove-palos-verdes-ca',
  'Los Angeles',
  'Palos Verdes Cove encompasses several reef breaks along the PV coastline. The various spots range from intermediate to advanced difficulty. Access requires hiking down trails and the powerful waves demand respect. When the swell is up, PV Cove delivers some of the best waves in LA County.',
  'Limited street parking along Paseo del Mar. Respect private property boundaries.',
  'Multiple access points via trails. Research your specific break before going - some require rope descents.',
  'Each break has its own character. Study the lineup before paddling out. Low-mid tide usually best.',
  'Local crew that knows the rocks intimately. Respect the pecking order.',
  'Low-mid tide, SE winds, 4-8 ft W swell.',
  ARRAY['Shallow reef', 'Rocks', 'Localism', 'Powerful on big swells'],
  'Earn your waves and respect the locals. Don''t paddle out if you can''t handle the power.',
  'medium',
  ARRAY['Multiple reef breaks', 'Requires hiking', 'Can be world-class when on'],
  false
),

-- ============================================================================
-- SOUTHEAST LA / ORANGE COUNTY BORDER
-- ============================================================================

-- 17. 72nd Place (Long Beach)
(
  '6932c9a6-bc1f-46b7-9493-51c587bf7eb0',
  '72nd Place',
  'Long Beach',
  'CA',
  'USA',
  33.7625,
  -118.1445,
  'beach',
  'beginner',
  ARRAY['small waves', 'crowds on good days'],
  ARRAY['Best in Long Beach area', 'Near Seal Beach', 'Parking available', 'Lifeguards'],
  180,
  240,
  0,
  45,
  15,
  10,
  1.5,
  4.0,
  '{"tide": "mid", "primary_swell": {"dir_deg": 210, "period_s": 11}, "notes": "Best spot in the Long Beach area; east of the breakwater shadow."}'::jsonb,
  200,
  210,
  30,
  ARRAY[5,6,7,8,9],
  '72nd-place-long-beach-ca',
  'Los Angeles',
  '72nd Place is the best surf spot in the Long Beach area. Located east of the breakwater shadow that blocks most swell from central Long Beach, this beach break actually receives waves. Summer south swells provide the most consistent surf.',
  'Street parking along Ocean Boulevard. Watch for permit restrictions.',
  'Walk down 72nd Place to the beach. Easy access to the water.',
  'Position where the sandbars are breaking. The breakwater effect diminishes here, allowing more swell.',
  'Gets crowded when it''s working since it''s the only real surf spot in Long Beach.',
  'Mid tide, N winds, 2-4 ft S-SW swell.',
  ARRAY['Generally small waves', 'Crowds when good'],
  'Share waves - this is the only decent spot in the area.',
  'medium',
  ARRAY['Only real surf spot in Long Beach', 'East of breakwater shadow', 'Best on summer S swells'],
  false
),

-- 18. Seal Beach Pier
(
  'e6602d4e-7b5a-456d-b675-230ca5501cde',
  'Seal Beach Pier',
  'Seal Beach',
  'CA',
  'USA',
  33.7405,
  -118.1045,
  'beach',
  'intermediate',
  ARRAY['pier pilings', 'crowds', 'oil platforms'],
  ARRAY['Consistent pier peaks', 'Classic pier break', 'Main Street access', 'Lifeguards'],
  180,
  260,
  45,
  40,
  12,
  8,
  1.0,
  5.0,
  '{"tide": "all", "primary_swell": {"dir_deg": 220, "period_s": 12}, "notes": "Works on all tides; consistent pier break that picks up SW swells well."}'::jsonb,
  210,
  220,
  40,
  ARRAY[5,6,7,8,9],
  'seal-beach-pier-seal-beach-ca',
  'Los Angeles',
  'Seal Beach Pier is a classic pier break at the northern edge of Orange County. The pier creates consistent sandbars on both sides, and the wave works on nearly all tides. Summer SW swells provide the best conditions, with peaks forming reliably around the structure.',
  'Paid lots near Main Street or metered street parking. Arrive early on weekends.',
  'Walk from Main Street through the quaint downtown area to the pier. Enter on either side.',
  'Sandbars on both sides of the pier. South side often more powerful, north side more protected.',
  'Popular with locals and visitors. The small-town vibe keeps aggression low.',
  'All tides, NE winds, 3-5 ft SW swell.',
  ARRAY['Pier pilings', 'Crowds', 'Oil platforms offshore'],
  'Friendly local scene. Standard pier etiquette - don''t surf too close to the structure.',
  'medium',
  ARRAY['Consistent pier peaks', 'Works all tides', 'Classic small-town surf vibe'],
  false
)

ON CONFLICT (id) DO NOTHING;

COMMIT;
