-- Verified beach identities with documented access from the webcam catalog-gap review.
-- Searchable catalog rows only: scoring inputs and forecast runtime verification
-- remain incomplete. Do not promote to SEO/recommendations or write terrain here.
BEGIN;

CREATE TEMP TABLE _catalog_gap_beaches (
  id uuid PRIMARY KEY, name text NOT NULL, slug text NOT NULL,
  city text NOT NULL, state text NOT NULL, region text NOT NULL,
  timezone text NOT NULL, lat double precision NOT NULL, lon double precision NOT NULL,
  break_type text, description text NOT NULL, access_tips text NOT NULL,
  hazards text[], editorial_sources jsonb NOT NULL, camera_url text
) ON COMMIT DROP;

INSERT INTO _catalog_gap_beaches VALUES
  ('ab8127ed-3653-505b-968f-b0a5bbf074a4', 'Kamakahonu Beach', 'kamakahonu-beach-kailua-kona-hi', 'Kailua-Kona', 'HI', 'Big Island', 'Pacific/Honolulu', 19.63934, -155.99748, 'beach', 'A small sandy cove beside Kailua Pier in historic Kailua Village.', 'Use the public approach beside Kailua Pier from Aliʻi Drive and Palani Road.', NULL::text[], '[{"url": "https://www.planning.hawaiicounty.gov/resources/shoreline-public-access/north-kona", "fields": ["name", "city", "description", "access_tips"]}, {"url": "https://gis.hawaiicounty.gov/public/downloads/plhyperlinks/SMA_Major/year2009/09-000032.PDF", "fields": ["access_tips"]}, {"url": "https://mapcarta.com/24041648", "fields": ["coordinate_reference"]}, {"url": "https://www.timeanddate.com/time/zone/usa/hawaii", "fields": ["timezone"]}, {"url": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=-156.00188%2C19.63666%2C-155.99388000000002%2C19.64266&bboxSR=4326&imageSR=4326&size=1000%2C750&format=png&f=image", "fields": ["lat", "lon", "pin_meaning"]}]'::jsonb, NULL),
  ('58a2b3e5-6a3a-541c-8d4d-afacfd26dab1', 'Turtle Bay West', 'turtle-bay-west-kahuku-hi', 'Kahuku', 'HI', 'Oahu', 'Pacific/Honolulu', 21.705403, -158.00333, 'reef', 'A reef surf break on the west side of the Turtle Bay resort area.', 'Use designated public shoreline access and trails.', ARRAY['Reef']::text[], '[{"url": "https://www.surfline.com/surf-report/turtle-bay-west/5842041f4e65fad6a7708df2/spot-guide", "fields": ["name", "description", "beach_type", "hazards"]}, {"url": "https://breakfinder.surf/surf_spots/turtle-bay-west", "fields": ["lat", "lon"]}, {"url": "https://www.tpl.org/our-work/kahuku-kawela-forever", "fields": ["access_tips"]}, {"url": "https://www.timeanddate.com/time/zone/usa/hawaii", "fields": ["timezone"]}, {"url": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=-158.01133000000002%2C21.699403%2C-157.99533%2C21.711403&bboxSR=4326&imageSR=4326&size=1000%2C750&format=png&f=image", "fields": ["lat", "lon", "pin_meaning"]}]'::jsonb, NULL),
  ('6270f847-045d-5be4-b8ab-e98d7fdfdd5e', 'Lawai Beach', 'lawai-beach-koloa-hi', 'Koloa', 'HI', 'Kauai', 'Pacific/Honolulu', 21.8812, -159.4763, 'beach', 'A small beach beside the Beach House Restaurant on Kauai’s south coast.', 'Approach from Lawai Road; the adjacent resort identifies this public shoreline destination.', ARRAY['No lifeguard']::text[], '[{"url": "https://www.hawaii-guide.com/kauai/beaches/lawai-beach", "fields": ["name", "description", "hazards", "coordinate_reference"]}, {"url": "https://www.lawaibeach.org/", "fields": ["city", "description", "access_tips"]}, {"url": "https://www.timeanddate.com/time/zone/usa/hawaii", "fields": ["timezone"]}, {"url": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=-159.4803%2C21.8782%2C-159.47230000000002%2C21.8842&bboxSR=4326&imageSR=4326&size=1000%2C750&format=png&f=image", "fields": ["lat", "lon", "pin_meaning"]}]'::jsonb, 'https://www.youtube.com/watch?v=3ATYHKN2hIg'),
  ('75e0bd7d-f25d-54eb-b455-af99eb561200', 'Kaanapali Beach', 'kaanapali-beach-lahaina-hi', 'Lahaina', 'HI', 'Maui', 'Pacific/Honolulu', 20.922221, -156.6963, 'beach', 'A long sandy beach on West Maui’s resort coast, south of Black Rock.', 'Use marked public beach access along Kaanapali Parkway.', ARRAY['No lifeguard','Stronger currents near Black Rock']::text[], '[{"url": "https://www.aquaaston.com/vacation-inspiration/activities/relax-on-kaanapali-beach", "fields": ["name", "city", "description", "access_tips", "hazards", "coordinate_reference"]}, {"url": "https://www.timeanddate.com/time/zone/usa/hawaii", "fields": ["timezone"]}, {"url": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=-156.699895%2C20.919221%2C-156.69189500000002%2C20.925221&bboxSR=4326&imageSR=4326&size=1000%2C750&format=png&f=image", "fields": ["lat", "lon", "pin_meaning"]}]'::jsonb, NULL),
  ('d640e904-4a17-597a-98e7-11c42e9c8166', 'Pohaku Park (S-Turns)', 'pohaku-park-s-turns-lahaina-hi', 'Lahaina', 'HI', 'Maui', 'Pacific/Honolulu', 20.96708, -156.68165, 'reef', 'A West Maui surf park with rocky shoreline and a small sandy southern section.', 'Use the public park entrance on Lower Honoapiilani Road.', ARRAY['Rocky shoreline','Drainage culvert']::text[], '[{"url": "https://www.mauicounty.gov/Facilities/Facility/Details/Pohaku-Park-113", "fields": ["name", "city", "aliases", "access_tips"]}, {"url": "https://health.hawaii.gov/cwb/files/2013/06/SampleSite_Maui724.pdf", "fields": ["description", "hazards", "coordinate_reference"]}, {"url": "https://www.timeanddate.com/time/zone/usa/hawaii", "fields": ["timezone"]}, {"url": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=-156.68514%2C20.96496%2C-156.67714%2C20.97096&bboxSR=4326&imageSR=4326&size=1000%2C750&format=png&f=image", "fields": ["lat", "lon", "pin_meaning"]}]'::jsonb, NULL),
  ('313e745b-4521-57d4-9d33-808acaca4761', 'Kaunaoa Beach', 'kaunaoa-beach-waimea-hi', 'Waimea', 'HI', 'Big Island', 'Pacific/Honolulu', 20.0045643, -155.8253, 'beach', 'A crescent of white sand at Kaunaʻoa Bay beside Mauna Kea Beach Hotel.', 'Request a public beach parking pass at the resort entrance; spaces are limited.', ARRAY['Strong currents and waves','Uneven footing']::text[], '[{"url": "https://www.planning.hawaiicounty.gov/resources/shoreline-public-access/south-kohala", "fields": ["name", "description", "access_tips", "hazards"]}, {"url": "https://www.topozone.com/hawaii/hawaii-hi/beach/kaunaoa-beach/", "fields": ["coordinate_reference"]}, {"url": "https://www.timeanddate.com/time/zone/usa/hawaii", "fields": ["timezone"]}, {"url": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=-155.8287995%2C20.0015643%2C-155.82079950000002%2C20.0075643&bboxSR=4326&imageSR=4326&size=1000%2C750&format=png&f=image", "fields": ["lat", "lon", "pin_meaning"]}]'::jsonb, 'https://marriott.ozolio.com/mauna-kea-beach-hotel/'),
  ('0922be9c-e437-5f0a-90a8-82588f429564', 'Napili Bay Beach', 'napili-bay-beach-lahaina-hi', 'Lahaina', 'HI', 'Maui', 'Pacific/Honolulu', 20.99554, -156.667, 'beach', 'A sandy crescent along Nāpili Bay on Maui’s northwest coast.', 'Use signed public beach access from Napili Place or Hui Drive.', NULL::text[], '[{"url": "https://www.mauicounty.gov/DocumentView.asp?DID=8198", "fields": ["name", "access_tips"]}, {"url": "https://pubs.usgs.gov/of/2001/0308/MDATA/Maui_Profiles.pdf", "fields": ["coordinate_reference"]}, {"url": "https://mapcarta.com/24048452", "fields": ["name", "coordinate_reference"]}, {"url": "https://www.timeanddate.com/time/zone/usa/hawaii", "fields": ["timezone"]}, {"url": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=-156.67%2C20.99329%2C-156.66400000000002%2C20.99779&bboxSR=4326&imageSR=4326&size=1000%2C750&format=png&f=image", "fields": ["lat", "lon", "pin_meaning"]}]'::jsonb, 'https://www.napilisunset.com/live-webcam/'),
  ('67def85b-7500-5ccb-bd86-7141652da53e', 'Kamaole Beach Park II', 'kamaole-beach-park-ii-kihei-hi', 'Kihei', 'HI', 'Maui', 'Pacific/Honolulu', 20.7164722, -156.4473, 'beach', 'A sandy beach between Kamaʻole Beach Parks I and III in Kīhei.', 'Reopened August11,2026 after storm repairs; respect barricades around restoration areas.', ARRAY['Stormwater runoff']::text[], '[{"url": "https://www.mauicounty.gov/facilities/facility/details/Kamaole-Park-II-232", "fields": ["name", "city", "description", "beach_type"]}, {"url": "https://www.mauicounty.gov/m/NewsFlash/Home/Detail/19144", "fields": ["access_tips"]}, {"url": "https://health.hawaii.gov/cwb/files/2013/06/SampleSite_Maui682.pdf", "fields": ["coordinate_reference", "hazards"]}, {"url": "https://www.timeanddate.com/time/zone/usa/hawaii", "fields": ["timezone"]}, {"url": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=-156.45075%2C20.7134722%2C-156.44275000000002%2C20.7194722&bboxSR=4326&imageSR=4326&size=1000%2C750&format=png&f=image", "fields": ["lat", "lon", "pin_meaning"]}]'::jsonb, NULL),
  ('52a9f0a9-7252-55c7-837d-8843e60bd43f', 'Wailea Beach', 'wailea-beach-wailea-hi', 'Wailea', 'HI', 'Maui', 'Pacific/Honolulu', 20.6829994, -156.44365, 'beach', 'A sandy crescent on South Maui’s Wailea resort coastline.', 'Use signed public beach access and the coastal beachwalk.', NULL::text[], '[{"url": "https://www.mauicounty.gov/DocumentView.asp?DID=8198", "fields": ["name", "access_tips"]}, {"url": "https://www.gohawaii.com/islands/maui/regions/south-maui/Wailea", "fields": ["city", "description"]}, {"url": "https://www.topozone.com/hawaii/maui-hi/beach/wailea-beach/", "fields": ["coordinate_reference"]}, {"url": "https://www.timeanddate.com/time/zone/usa/hawaii", "fields": ["timezone"]}, {"url": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=-156.4470594%2C20.6799994%2C-156.43905940000002%2C20.6859994&bboxSR=4326&imageSR=4326&size=1000%2C750&format=png&f=image", "fields": ["lat", "lon", "pin_meaning"]}]'::jsonb, NULL),
  ('ac6d886e-7326-5710-91e7-0bc3c7f21e70', 'Kihei Cove', 'kihei-cove-kihei-hi', 'Kihei', 'HI', 'Maui', 'Pacific/Honolulu', 20.727759, -156.450398, 'reef', 'A small surfing cove at the south end of Kalama Park in Kīhei.', 'Use the public Cove Park shoreline entrance.', NULL::text[], '[{"url": "https://www.mauicounty.gov/facilities/facility/details/Cove-Park-196", "fields": ["name", "city", "access_tips", "description"]}, {"url": "https://openswells.com/surf-spots/kihei-cove", "fields": ["lat", "lon"]}, {"url": "https://health.hawaii.gov/cwb/files/2013/06/SampleSite_Maui703.pdf", "fields": ["coordinate_reference"]}, {"url": "https://www.rentalsmaui.com/maui-web-cam/", "fields": ["camera_status"]}, {"url": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=-156.453398%2C20.725509%2C-156.44739800000002%2C20.730009&bboxSR=4326&imageSR=4326&size=1000%2C750&format=png&f=image", "fields": ["lat", "lon", "pin_meaning"]}]'::jsonb, NULL),
  ('090f4927-d319-53fb-990c-9c6bca55289b', 'Sharp Park Beach', 'sharp-park-beach-pacifica-ca', 'Pacifica', 'CA', 'San Francisco Peninsula', 'America/Los_Angeles', 37.6324357, -122.494697, 'beach', 'Sharp Park Beach is the public Pacifica shoreline between the municipal pier and Mori Point. The pier and beach form one coastal area, distinct from Linda Mar and Rockaway Beach.', 'Use Beach Boulevard access and the coastal promenade. Follow posted pier and beach notices; no lifeguard is on duty.', ARRAY['no lifeguard']::text[], '[{"url": "https://www.cityofpacifica.org/departments/parks-beaches-recreation/parks-and-beaches-locations-maps-safety-guides", "publisher": "City of Pacifica", "retrievedAt": "2026-09-03", "fields": ["identity", "access", "hazards"]}, {"url": "https://www.cityofpacifica.org/home/showpublisheddocument/17180/638415314988430000", "publisher": "City of Pacifica", "retrievedAt": "2026-09-03", "fields": ["identity", "public_access", "description"]}, {"url": "https://www.topozone.com/california/san-mateo-ca/beach/sharp-park-beach/", "publisher": "TopoZone / USGS GNIS", "retrievedAt": "2026-09-03", "fields": ["lat", "lon"]}, {"url": "https://www.pacificbeachcoalition.org/take-action/monthly-adopt-a-beach-cleanups/sharp-park-beach-cleanup/", "publisher": "Pacific Beach Coalition", "retrievedAt": "2026-09-03", "fields": ["hazards_context"]}]'::jsonb, 'https://www.youtube.com/watch?v=QYRIc4LcvqQ'),
  ('41637008-fad6-53f2-92ac-3377df9aec36', 'Santa Cruz Main Beach', 'santa-cruz-main-beach-santa-cruz-ca', 'Santa Cruz', 'CA', 'Santa Cruz', 'America/Los_Angeles', 36.962058, -122.02219, 'beach', 'Santa Cruz Main Beach, also called Boardwalk Beach, is the sandy public shoreline east of the municipal wharf and west of the San Lorenzo River.', 'Use public pedestrian access from Beach Street. Check current city water-quality and ocean-safety notices and ask an on-duty lifeguard about conditions.', ARRAY[]::text[], '[{"url": "https://www.slc.ca.gov/Programs/Granted_Lands/Forms/2014/16-01SantaCruzCityof.pdf", "publisher": "City of Santa Cruz / California State Lands Commission", "retrievedAt": "2026-09-03", "fields": ["identity", "description", "public_access"]}, {"url": "https://www.santacruzca.gov/Government/City-Departments/Fire-Department/Marine-Safety-Division", "publisher": "City of Santa Cruz", "retrievedAt": "2026-09-03", "fields": ["access", "lifeguards", "water_quality_checks"]}, {"url": "https://www.waterqualitydata.us/provider/STORET/CABEACH_WQX/CABEACH_WQX-Main-A/", "publisher": "Water Quality Portal / California State Water Resources Control Board", "retrievedAt": "2026-09-03", "fields": ["lat", "lon", "coordinate_datum", "pin_meaning"]}]'::jsonb, NULL),
  ('ae84ce3a-25ed-5600-804c-cd1d8aa5ca00', 'Roads End Beach', 'roads-end-beach-lincoln-city-or', 'Lincoln City', 'OR', 'Central Oregon Coast', 'America/Los_Angeles', 45.00827, -124.0105, 'beach', 'Roads End Beach is the public ocean shoreline reached through Roads End State Recreation Site in northern Lincoln City.', 'Use the state recreation site beach path and required day-use parking permit. Check tides before walking around Roads End Point; rising water can cut off the cove.', ARRAY['rising tides can cut off headland access']::text[], '[{"url": "https://stateparks.oregon.gov/index.cfm?do=park.profile&parkId=163", "publisher": "Oregon Parks and Recreation Department", "retrievedAt": "2026-09-03", "fields": ["identity", "description", "access", "hazards"]}, {"url": "https://www.waterqualitydata.us/provider/STORET/21ORBCH/21ORBCH-29261/", "publisher": "Water Quality Portal / Oregon Beach Monitoring Program", "retrievedAt": "2026-09-03", "fields": ["source_coordinates", "coordinate_datum", "source_pin_meaning"]}, {"url": "https://www.google.com/maps?q=45.00827,-124.0105&t=k&z=17", "publisher": "Google Maps satellite imagery; reviewer-derived representative surf pin", "retrievedAt": "2026-09-03", "fields": ["lat", "lon", "visual_geometry"]}]'::jsonb, NULL),
  ('f73cea3d-d7c7-57cf-b2d1-9a4370f75123', 'Muir Beach', 'muir-beach-muir-beach-ca', 'Muir Beach', 'CA', 'Marin County', 'America/Los_Angeles', 37.8594, -122.57728, 'beach', 'Muir Beach is a Pacific coastal cove at the mouth of Redwood Creek in Golden Gate National Recreation Area.', 'Reach the beach over the pedestrian bridge from the parking lot. The lagoon and surrounding riparian habitat are closed to access; stay on established beach access routes.', ARRAY['no lifeguard']::text[], '[{"url": "https://home.nps.gov/goga/planyourvisit/muirbeach.htm", "publisher": "National Park Service", "retrievedAt": "2026-09-03", "fields": ["identity", "description", "access", "hazards"]}, {"url": "https://www.waterqualitydata.us/provider/STORET/21CABCH/21CABCH-1365/", "publisher": "Water Quality Portal / Southern California Coastal Water Research Project", "retrievedAt": "2026-09-03", "fields": ["source_coordinates", "coordinate_datum", "source_pin_meaning"]}, {"url": "https://www.nps.gov/goga/planyourvisit/upload/MUBE-sb_web_17e.pdf", "publisher": "National Park Service", "retrievedAt": "2026-09-03", "fields": ["map", "historical_alias"]}, {"url": "https://www.google.com/maps?q=37.8594,-122.57728&t=k&z=17", "publisher": "Google Maps satellite imagery; reviewer-derived representative surf pin", "retrievedAt": "2026-09-03", "fields": ["lat", "lon", "visual_geometry"]}]'::jsonb, 'https://www.sigward.com/'),
  ('90df1267-5d2e-51b6-ba06-21e89405166c', 'Cowell Beach', 'cowell-beach-santa-cruz-ca', 'Santa Cruz', 'CA', 'Santa Cruz', 'America/Los_Angeles', 36.960806, -122.0243, 'beach', 'Cowell Beach is the sandy public beach west of the Santa Cruz Municipal Wharf, below the Dream Inn and West Cliff Drive.', 'Use public beach access west of the wharf. Check current water-quality notices and ocean conditions with an on-duty lifeguard before entering.', ARRAY[]::text[], '[{"url": "https://www.slc.ca.gov/Programs/Granted_Lands/Forms/2014/16-01SantaCruzCityof.pdf", "publisher": "City of Santa Cruz / California State Lands Commission", "retrievedAt": "2026-09-03", "fields": ["identity", "description", "public_access"]}, {"url": "https://www.santacruzca.gov/Government/City-Departments/Fire-Department/Marine-Safety-Division", "publisher": "City of Santa Cruz", "retrievedAt": "2026-09-03", "fields": ["access", "lifeguards", "water_quality_checks"]}, {"url": "https://www.waterqualitydata.us/provider/STORET/CABEACH_WQX/CABEACH_WQX-Cowell/", "publisher": "Water Quality Portal / California State Water Resources Control Board", "retrievedAt": "2026-09-03", "fields": ["lat", "lon", "coordinate_datum", "pin_meaning"]}]'::jsonb, NULL),
  ('0a76eb21-c49a-562a-ad1a-19240b44b543', 'Dillon Beach', 'dillon-beach-dillon-beach-ca', 'Dillon Beach', 'CA', 'Marin County', 'America/Los_Angeles', 38.249, -122.9698, 'beach', 'Dillon Beach is the ocean-facing sandy shoreline at the northern entrance to Tomales Bay. Lawson’s Landing provides one route to its southern frontage.', 'Day-use beach parking is offered by Lawson’s Landing, subject to current hours, rates and availability. Follow marked routes and restrictions protecting dunes and wetlands.', ARRAY[]::text[], '[{"url": "https://www.lawsonslanding.com/dayuse.html", "publisher": "Lawson’s Landing", "retrievedAt": "2026-09-03", "fields": ["identity", "description", "access"]}, {"url": "https://www.lawsonslanding.com/environment.html", "publisher": "Lawson’s Landing", "retrievedAt": "2026-09-03", "fields": ["access_restrictions"]}, {"url": "https://www.waterqualitydata.us/provider/STORET/CABEACH_WQX/CABEACH_WQX-DILLON/", "publisher": "Water Quality Portal / California State Water Resources Control Board", "retrievedAt": "2026-09-03", "fields": ["identity", "source_coordinates", "coordinate_datum", "source_pin_meaning"]}, {"url": "https://www.google.com/maps?q=38.249,-122.9698&t=k&z=17", "publisher": "Google Maps satellite imagery; reviewer-derived representative surf pin", "retrievedAt": "2026-09-03", "fields": ["lat", "lon", "visual_geometry"]}]'::jsonb, NULL),
  ('a7a94616-4d60-5965-b1be-568890d162e8', 'North Salmon Creek Beach', 'north-salmon-creek-beach-bodega-bay-ca', 'Bodega Bay', 'CA', 'Sonoma Coast', 'America/Los_Angeles', 38.3573, -123.0681, 'beach', 'North Salmon Creek Beach is the sandy Sonoma Coast State Park shoreline north of the Salmon Creek mouth, with public access from Highway 1.', 'Use the signed North Salmon Creek parking area and beach paths. Follow posted habitat and ocean warnings; do not trample dunes.', ARRAY['strong rip currents','heavy surf','sudden ground swells']::text[], '[{"url": "https://limpets.org/monitoring-site/north-salmon-creek-beach/", "publisher": "LiMPETS coastal monitoring program", "retrievedAt": "2026-09-03", "fields": ["identity", "lat", "lon", "access", "pin_meaning"]}, {"url": "https://www.parks.ca.gov/pages/451/files/SonomaCoastSP_Infosheet_8.5x11_010125_FINAL.pdf", "publisher": "California State Parks", "retrievedAt": "2026-09-03", "fields": ["identity", "description", "public_access", "surfing"]}, {"url": "https://www.sonomacounty.com/outdoor-activities/north-salmon-creek-beach/", "publisher": "Sonoma County Tourism", "retrievedAt": "2026-09-03", "fields": ["identity", "access_restrictions"]}, {"url": "https://www.parks.ca.gov/?page_id=451", "publisher": "California State Parks", "retrievedAt": "2026-09-03", "fields": ["hazards", "surfing_use", "access_restrictions"]}]'::jsonb, NULL),
  ('5f857910-8ba3-555a-992d-7180018ea486', 'Kalaloch Beach', 'kalaloch-beach-kalaloch-wa', 'Kalaloch', 'WA', 'Olympic Coast', 'America/Los_Angeles', 47.605564, -124.378775, 'beach', 'Kalaloch Beach is the sandy Olympic National Park shoreline around Kalaloch Creek on the southwest Olympic Peninsula.', 'Use designated coastal access from Highway 101 and check current park notices and tides. Stay off logs that waves can move and avoid routes that rising tides can close.', ARRAY['powerful waves','moving beach logs','rip currents','tidal cutoff']::text[], '[{"url": "https://www.nps.gov/olym/planyourvisit/visiting-kalaloch-and-ruby-beach.htm", "publisher": "National Park Service", "retrievedAt": "2026-09-03", "fields": ["identity", "description", "public_access"]}, {"url": "https://www.nps.gov/olym/planyourvisit/kalaloch-area-brochure.htm", "publisher": "National Park Service", "retrievedAt": "2026-09-03", "fields": ["access", "hazards"]}, {"url": "https://repository.si.edu/bitstream/handle/10088/33774/Ruiz_Gregory_M_-20170807-aao1498_SupplementalMaterial_v2.pdf", "publisher": "Smithsonian repository / Carlton et al. study supplement", "retrievedAt": "2026-09-03", "fields": ["lat", "lon", "survey_location"]}]'::jsonb, NULL),
  ('34e148b8-08cc-50cb-908f-012464b7fa74', 'Virginia Beach Oceanfront', 'virginia-beach-oceanfront-virginia-beach-va', 'Virginia Beach', 'VA', 'Virginia Beach', 'America/New_York', 36.853333, -75.973056, 'beach', 'Atlantic Ocean beach beside the Virginia Beach resort boardwalk. Surfing access varies by season, time and designated area.', 'Use public oceanfront access and check current city surfing restrictions and lifeguard instructions.', ARRAY[]::text[], '[{"url": "https://cvb.virginiabeach.gov/resort-management/beach-rules", "publisher": "City of Virginia Beach", "retrievedAt": "2026-09-03", "fields": ["name", "city", "state", "description", "access_tips"]}, {"url": "https://www.govinfo.gov/content/pkg/FR-2008-04-15/pdf/FR-2008-04-15.pdf", "publisher": "Federal Register", "retrievedAt": "2026-09-03", "fields": ["lat", "lon"]}, {"url": "https://vbbound.com/webcams/courtyard-virginia-beach-boardwalk-webcam/", "publisher": "Camera provider", "retrievedAt": "2026-09-03", "fields": ["camera_url"], "verification": "Browser provider page identifies Courtyard Oceanfront/South and Norwegian Lady statue. Two screenshots show flags in changed positions with sand/ocean behind plaza; playback active. Broad Oceanfront match, limited surf-detail view."}, {"url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer", "publisher": "Esri World Imagery", "retrievedAt": "2026-09-03", "fields": ["lat", "lon"], "verification": "Federal Register 24th–25th Street shoreline reference 36°51′12″N 75°58′23″W. Imagery center is ocean approximately 150 m offshore. Broad oceanfront row; preserve distinct existing pier and 1st Street Jetty."}]'::jsonb, 'https://vbbound.com/webcams/courtyard-virginia-beach-boardwalk-webcam/'),
  ('c5cb000f-c684-5fa6-8e71-52ca2ff71cfe', 'Jenkinson’s Beach', 'jenkinsons-beach-point-pleasant-beach-nj', 'Point Pleasant Beach', 'NJ', 'Jersey Shore', 'America/New_York', 40.09355, -74.03434, 'beach', 'Sandy Atlantic beach beside Jenkinson’s Boardwalk in Point Pleasant Beach. The privately operated beach admits visitors through seasonal paid access.', 'Check current daily admission or season-pass requirements. Swim only when lifeguards are on duty.', ARRAY[]::text[], '[{"url": "https://jenkinsons.com/beach/", "publisher": "Jenkinson’s", "retrievedAt": "2026-09-03", "fields": ["name", "city", "state", "description", "access_tips"]}, {"url": "https://www.waterqualitydata.us/provider/STORET/21NJBCH/21NJBCH-OC1002/", "publisher": "NJDEP via Water Quality Portal", "retrievedAt": "2026-09-03", "fields": ["lat", "lon", "name"]}, {"url": "https://video.nest.com/live/JKTTcsayyN", "publisher": "Camera provider", "retrievedAt": "2026-09-03", "fields": ["camera_url"], "verification": "Nest page titled Jenks Beach Cam; Play Video clicked. Two subsequent screenshots show walking people changing positions on sand and boardwalk, visible ocean. Jenkinson’s branded beach facility visible. External provider link only; not embed approval."}, {"url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer", "publisher": "Esri World Imagery", "retrievedAt": "2026-09-03", "fields": ["lat", "lon"], "verification": "NJDEP Central Avenue source 40.09355,-74.03494 was on sand. Selected pin shifted east 0.00060 degrees into visible nearshore water; point-pleasant-final.png. Privately owned with paid public admission."}]'::jsonb, 'https://video.nest.com/live/JKTTcsayyN'),
  ('008db74c-cddf-50c7-802d-80f039ad0868', 'TOBAY Beach', 'tobay-beach-massapequa-ny', 'Massapequa', 'NY', 'Long Island', 'America/New_York', 40.6078, -73.4333, 'beach', 'Town of Oyster Bay ocean beach on Ocean Parkway, separate from the bayside TOBAY beach. Vehicle access is subject to town residency and permit rules.', 'Confirm Town of Oyster Bay residency eligibility and parking-permit requirements before visiting.', ARRAY[]::text[], '[{"url": "https://oysterbaytown.com/tobay/", "publisher": "Town of Oyster Bay", "retrievedAt": "2026-09-03", "fields": ["name", "city", "state", "description", "access_tips"]}, {"url": "https://www.waterqualitydata.us/provider/STORET/21NYBCH/21NYBCH-NY610050-01/", "publisher": "New York State Department of Health via Water Quality Portal", "retrievedAt": "2026-09-03", "fields": ["lat", "lon", "name"]}, {"url": "https://www.youtube.com/watch?v=Qzcvhq34p6w", "publisher": "Camera provider", "retrievedAt": "2026-09-03", "fields": ["camera_url"], "verification": "Town of Oyster Bay official channel TOBAY Beach Live Stream. Two screenshots show moving people and changing ocean waves beside beach pavilion; ocean side confirmed, not bay."}, {"url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer", "publisher": "Esri World Imagery", "retrievedAt": "2026-09-03", "fields": ["lat", "lon"], "verification": "Official ocean monitoring coordinate, visually at nearshore ocean edge; not bay or marina. Town ownership; restricted public access does not imply private ownership."}]'::jsonb, 'https://www.youtube.com/watch?v=Qzcvhq34p6w'),
  ('b1831be4-6333-5c39-9d69-6624d40c2175', 'Atlantic City Beach', 'atlantic-city-beach-atlantic-city-nj', 'Atlantic City', 'NJ', 'Jersey Shore', 'America/New_York', 39.35813, -74.4178, 'beach', 'Atlantic beach along the Atlantic City Boardwalk, represented near Virginia Avenue and Steel Pier. Surfing is limited to designated areas and beach-patrol instructions.', 'Use public boardwalk beach access. Check the beach patrol’s permitted surf areas before entering with a board.', ARRAY['Pier structures']::text[], '[{"url": "https://www.atlanticcitybeachpatrol.com/surf-beaches", "publisher": "Atlantic City Beach Patrol", "retrievedAt": "2026-09-03", "fields": ["name", "city", "state", "description", "access_tips"]}, {"url": "https://www.visitatlanticcity.com/things-to-do/beaches-boardwalk/access-facilities/", "publisher": "Visit Atlantic City", "retrievedAt": "2026-09-03", "fields": ["name", "city", "state", "description", "access_tips"]}, {"url": "https://www.waterqualitydata.us/provider/STORET/21NJBCH/21NJBCH-AC1183S/", "publisher": "NJDEP via Water Quality Portal", "retrievedAt": "2026-09-03", "fields": ["lat", "lon", "name"]}, {"url": "https://www.youtube.com/watch?v=vVyBOU9Huvo", "publisher": "Camera provider", "retrievedAt": "2026-09-03", "fields": ["camera_url"], "verification": "Resorts Casino Hotel Beach Camera official channel. Two screenshots show moving boardwalk pedestrians, Steel Pier structures, sand and breaking ocean visible. Broad Atlantic City Beach match; beach area partly obstructed."}, {"url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer", "publisher": "Esri World Imagery", "retrievedAt": "2026-09-03", "fields": ["lat", "lon"], "verification": "Virginia Avenue station 39.35813,-74.41861 adjusted east 0.00081 degrees to nearshore swash in atlantic-city-final.png. Broad beach identity; this pin is not a claim that Virginia Avenue is a designated surf zone."}]'::jsonb, 'https://www.youtube.com/watch?v=vVyBOU9Huvo'),
  ('fea81a34-3a55-5a3c-9656-1de099818e07', 'Main Beach (East Hampton)', 'main-beach-east-hampton-east-hampton-ny', 'East Hampton', 'NY', 'Long Island', 'America/New_York', 40.9424, -72.1944, 'beach', 'Atlantic beach at the end of Ocean Avenue in the Village of East Hampton. Village beach-parking permit rules apply.', 'Check Village of East Hampton parking permit requirements; Town of East Hampton permits are a separate system.', ARRAY[]::text[], '[{"url": "https://easthampton.thepermitportal.com/Home/", "publisher": "Village of East Hampton", "retrievedAt": "2026-09-03", "fields": ["name", "city", "state", "description", "access_tips"]}, {"url": "https://www.waterqualitydata.us/provider/STORET/21NYBCH/21NYBCH-NY540972-01/", "publisher": "New York State Department of Health via Water Quality Portal", "retrievedAt": "2026-09-03", "fields": ["lat", "lon", "name"]}, {"url": "https://www.youtube.com/watch?v=E8fp7TDgQUk", "publisher": "Camera provider", "retrievedAt": "2026-09-03", "fields": ["camera_url"], "verification": "EEOR East Hampton NY Main Beach by ErdmanVideoSystems. Description identifies Main Beach and East End Ocean Rescue. Two screenshots show walking people, changing waves and flag position. Live badge."}, {"url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer", "publisher": "Esri World Imagery", "retrievedAt": "2026-09-03", "fields": ["lat", "lon"], "verification": "Official monitoring point 40.943,-72.1944 on dry sand adjusted south 0.0006 degrees to visible surf edge; east-hampton-final.png."}]'::jsonb, 'https://www.youtube.com/watch?v=E8fp7TDgQUk'),
  ('c018c79c-ece5-5140-9d2c-50a664c6d493', 'Rehoboth Beach', 'rehoboth-beach-rehoboth-beach-de', 'Rehoboth Beach', 'DE', 'Delaware Coast', 'America/New_York', 38.7202, -75.0756, 'beach', 'Atlantic Ocean beach alongside Rehoboth Beach’s boardwalk. Surfing is subject to city restrictions and designated areas.', 'Use public beach access and check current city beach conditions and surfing-area rules.', ARRAY[]::text[], '[{"url": "https://www.rehobothbeachde.gov/beach-conditions/", "publisher": "City of Rehoboth Beach", "retrievedAt": "2026-09-03", "fields": ["name", "city", "state", "description", "access_tips"]}, {"url": "https://ecode360.com/32105697", "publisher": "City of Rehoboth Beach code", "retrievedAt": "2026-09-03", "fields": ["access_tips", "description"]}, {"url": "https://www.waterqualitydata.us/provider/STORET/21DEBCH/21DEBCH-DE133779/", "publisher": "Delaware DNREC via Water Quality Portal", "retrievedAt": "2026-09-03", "fields": ["lat", "lon", "name"]}, {"url": "https://www.youtube.com/watch?v=lq15dNFXISw", "publisher": "Camera provider", "retrievedAt": "2026-09-03", "fields": ["camera_url"], "verification": "Rehoboth Boardwalk Plaza Hotel Cam. Browser two screenshots show pedestrians moving along boardwalk, sand and Atlantic water visible. Hotel branding in video. Broad Rehoboth beach match."}, {"url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer", "publisher": "Esri World Imagery", "retrievedAt": "2026-09-03", "fields": ["lat", "lon"], "verification": "Official Virginia Avenue ocean monitoring site; imagery confirms nearshore water. Do not alias separate Deauville Beach."}]'::jsonb, 'https://www.youtube.com/watch?v=lq15dNFXISw'),
  ('f950d05c-2a78-5bcd-8d5f-01fcc7c51633', 'St. Augustine Beach Pier', 'st-augustine-beach-pier-st-augustine-beach-fl', 'St. Augustine Beach', 'FL', 'Northeast Florida', 'America/New_York', 29.8576, -81.264, 'beach', 'Ocean beach adjoining the St. Johns County Ocean and Fishing Pier on Anastasia Island. The county beach access includes parking, restrooms and showers.', 'Use county pier beach access. Check current pier conditions separately; beach access does not guarantee the pier itself is open.', ARRAY['Pier structures']::text[], '[{"url": "https://www.sjcfl.us/beach-services/beach-access/", "publisher": "St. Johns County", "retrievedAt": "2026-09-03", "fields": ["name", "city", "state", "description", "access_tips"]}, {"url": "https://www.sjcfl.us/fishing-piers/", "publisher": "St. Johns County", "retrievedAt": "2026-09-03", "fields": ["name", "city", "state", "description", "access_tips"]}, {"url": "https://maps.app.goo.gl/zxwwHxKsKC88AcC96", "publisher": "Google Maps linked by St. Johns County", "retrievedAt": "2026-09-03", "fields": ["lat", "lon"]}, {"url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer", "publisher": "Esri World Imagery", "retrievedAt": "2026-09-03", "fields": ["lat", "lon"], "verification": "County map destination 29.8569986,-81.2659358 is parking. Imagery-derived pin 29.8576,-81.2640 is nearshore water north of pier; st-augustine-final.png."}]'::jsonb, NULL),
  ('0bc849fa-7e06-5600-8176-d2fda5ecfbf0', 'Ocean City Beach (Maryland)', 'ocean-city-beach-maryland-ocean-city-md', 'Ocean City', 'MD', 'Maryland Coast', 'America/New_York', 38.370114, -75.067683, 'beach', 'Atlantic beach along Ocean City, Maryland. Summer surfing uses designated rotating beach sections and other areas identified by the beach patrol.', 'Check the current surf-beach schedule and marked surfing areas; hotel-front beach sections are not permanently designated surf zones.', ARRAY['Rip currents']::text[], '[{"url": "https://oceancitymd.gov/oc/surf-beaches/", "publisher": "Town of Ocean City", "retrievedAt": "2026-09-03", "fields": ["name", "city", "state", "description", "access_tips"]}, {"url": "https://www.waterqualitydata.us/provider/NWIS/USGS-MD/USGS-382212075040501/", "publisher": "USGS Maryland Water Science Center", "retrievedAt": "2026-09-03", "fields": ["lat", "lon", "name"]}, {"url": "https://www.youtube.com/watch?v=zCEiot7sEWY", "publisher": "Camera provider", "retrievedAt": "2026-09-03", "fields": ["camera_url"], "verification": "Gateway Subaru Camera at The Commander Hotel. Two browser screenshots show changing breaking waves and moving people. Commander official hotel webcam page establishes 1401 Atlantic Ave Ocean City Maryland beachfront. Broad beach match, not 44th Street exact view."}, {"url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer", "publisher": "Esri World Imagery", "retrievedAt": "2026-09-03", "fields": ["lat", "lon"], "verification": "Official 44th Street ocean station 38.37011386,-75.0676825; imagery nearshore water. One broad beach row for 21st Street, Commander and Days Inn research entries; pin does not locate those hotels."}, {"url": "https://www.commanderhotel.com/webcam/", "publisher": "Commander Hotel", "retrievedAt": "2026-09-03", "fields": ["camera_url"], "verification": "Official site identifies beach webcam and hotel address at 1401 Atlantic Ave, Ocean City Maryland."}]'::jsonb, 'https://www.youtube.com/watch?v=zCEiot7sEWY'),
  ('fa504123-92e2-59fd-a0b5-0c4a85cca27a', 'East Beach (St. Simons Island)', 'east-beach-st-simons-island-st-simons-island-ga', 'St. Simons Island', 'GA', 'Golden Isles', 'America/New_York', 31.1439, -81.3688, 'beach', 'Public ocean beach accessed through Coast Guard Park on St. Simons Island. Facilities include beach parking, restrooms and accessible beach mats.', 'Use the Coast Guard beach access at 4100 First Street and observe the beach warning light system.', ARRAY[]::text[], '[{"url": "https://www.glynncounty.org/government/departments/recreation-parks/beaches/coast-guard-east-beach", "publisher": "Glynn County", "retrievedAt": "2026-09-03", "fields": ["name", "city", "state", "description", "access_tips"]}, {"url": "https://www.saltchef.com/catch_fish/GA/Glynn/beaches.html", "publisher": "Saltchef", "retrievedAt": "2026-09-03", "fields": ["coordinate_reference"]}, {"url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer", "publisher": "Esri World Imagery", "retrievedAt": "2026-09-03", "fields": ["lat", "lon"], "verification": "Access reference 31.145364,-81.372025 is parking. Proposed imagery-derived nearshore pin 31.1439,-81.3688 southeast of access; final imagery shows wet nearshore sand/swash at center, adjacent to ocean. st-simons-final.png. Consider slight east shift for all-water sampling."}]'::jsonb, NULL),
  ('91a6c7f9-ae5d-5a26-89b1-fd7587e1fee4', 'Cherie Down Park Beach', 'cherie-down-park-beach-cape-canaveral-fl', 'Cape Canaveral', 'FL', 'Space Coast', 'America/New_York', 28.39179, -80.59513, 'beach', 'Atlantic beach at Cherie Down Park in Cape Canaveral. The county park provides public beach access from Ridgewood Avenue.', 'Use Cherie Down Park’s public beach access and follow posted county beach rules.', ARRAY[]::text[], '[{"url": "https://www.brevardfl.gov/ParksAndRecreation/ParkDirectory", "publisher": "Brevard County", "retrievedAt": "2026-09-03", "fields": ["name", "city", "state", "description", "access_tips"]}, {"url": "https://www.visitspacecoast.com/profile/cape-canaveral/beaches/cherie-down-park/", "publisher": "Space Coast Office of Tourism", "retrievedAt": "2026-09-03", "fields": ["name", "city", "state", "description", "access_tips"]}, {"url": "https://breakfinder.surf/nl/surf_spots/cherie-down-park", "publisher": "Breakfinder", "retrievedAt": "2026-09-03", "fields": ["lat", "lon"]}, {"url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer", "publisher": "Esri World Imagery", "retrievedAt": "2026-09-03", "fields": ["lat", "lon"], "verification": "Surf-location coordinate crosschecked against imagery and official park address; nearshore water east of park. Cape Canaveral generic webcam cannot automatically map to this park."}]'::jsonb, NULL);

DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM _catalog_gap_beaches p JOIN public.beaches b
    ON b.id <> p.id AND (lower(b.name) = lower(p.name) OR lower(b.slug) = lower(p.slug))
  ) THEN RAISE EXCEPTION 'Catalog gap import conflicts with existing name or slug'; END IF;
  IF EXISTS (
    SELECT 1 FROM _catalog_gap_beaches p JOIN public.beaches b USING (id)
    WHERE b.name IS DISTINCT FROM p.name OR b.slug IS DISTINCT FROM p.slug
       OR b.lat IS DISTINCT FROM p.lat OR b.lon IS DISTINCT FROM p.lon
       OR b.deleted_at IS NOT NULL
  ) THEN RAISE EXCEPTION 'Catalog gap import UUID identity or coordinate conflict'; END IF;
END $$;

INSERT INTO public.beaches (
  id,name,slug,city,state,country,region,timezone,lat,lon,break_type,
  description,access_tips,hazards,warnings,editorial_sources,editorial_reviewed_at,
  seo_indexable,recommendation_eligible,is_private,terrain_enabled
)
SELECT id,name,slug,city,state,'USA',region,timezone,lat,lon,break_type,
  description,access_tips,hazards,hazards,editorial_sources,'2026-09-03T00:00:00Z',
  false,false,false,false
FROM _catalog_gap_beaches p
WHERE NOT EXISTS (SELECT 1 FROM public.beaches b WHERE b.id=p.id);

INSERT INTO public.beach_sources (beach_id,forecast_source_id,camera_url)
SELECT id,'open_meteo',camera_url FROM _catalog_gap_beaches
ON CONFLICT (beach_id) DO NOTHING;

WITH photos (beach_id,source_id,image_url,thumb_url,title,creator_name,creator_url,license_code,license_url,attribution_html) AS (VALUES
  ('90df1267-5d2e-51b6-ba06-21e89405166c'::uuid,'File:View of Cowel Beach towards Lighthouse Point -Santa Cruz - panoramio.jpg','https://upload.wikimedia.org/wikipedia/commons/6/6d/View_of_Cowel_Beach_towards_Lighthouse_Point_-Santa_Cruz_-_panoramio.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original','https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6d/View_of_Cowel_Beach_towards_Lighthouse_Point_-Santa_Cruz_-_panoramio.jpg/960px-View_of_Cowel_Beach_towards_Lighthouse_Point_-Santa_Cruz_-_panoramio.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail','Cowell Beach','loboford220','https://web.archive.org/web/20161022111025/http://www.panoramio.com/user/748109?with_photo_id=53996745','CC BY-SA 3.0','https://creativecommons.org/licenses/by-sa/3.0','Photo by loboford220, licensed CC BY-SA 3.0 (https://creativecommons.org/licenses/by-sa/3.0). Source: https://commons.wikimedia.org/w/index.php?curid=53565370.'),
  ('0922be9c-e437-5f0a-90a8-82588f429564'::uuid,'File:Sunset at Napili Bay, Maui.jpg','https://upload.wikimedia.org/wikipedia/commons/3/34/Sunset_at_Napili_Bay%2C_Maui.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original','https://thumb.wikimedia.org/wikipedia/commons/thumb/3/34/Sunset_at_Napili_Bay%2C_Maui.jpg/960px-Sunset_at_Napili_Bay%2C_Maui.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail','Napili Bay Beach','KAP03','https://commons.wikimedia.org/wiki/User:KAP03','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0','Photo by KAP03, licensed CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0). Source: https://commons.wikimedia.org/w/index.php?curid=75171828.'),
  ('67def85b-7500-5ccb-bd86-7141652da53e'::uuid,'File:Kamaole Beach II Kihei Maui Hawaii (30800124747).jpg','https://upload.wikimedia.org/wikipedia/commons/5/55/Kamaole_Beach_II_Kihei_Maui_Hawaii_%2830800124747%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original','https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/Kamaole_Beach_II_Kihei_Maui_Hawaii_%2830800124747%29.jpg/960px-Kamaole_Beach_II_Kihei_Maui_Hawaii_%2830800124747%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail','Kamaole Beach Park II','dronepicr','https://www.flickr.com/people/132646954@N02','CC BY 2.0','https://creativecommons.org/licenses/by/2.0','Photo by dronepicr, licensed CC BY 2.0 (https://creativecommons.org/licenses/by/2.0). Source: https://commons.wikimedia.org/w/index.php?curid=74172811.'),
  ('75e0bd7d-f25d-54eb-b455-af99eb561200'::uuid,'File:Kaanapali Beach Maui.jpg','https://upload.wikimedia.org/wikipedia/commons/3/38/Kaanapali_Beach_Maui.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original','https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Kaanapali_Beach_Maui.jpg/960px-Kaanapali_Beach_Maui.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail','Kaanapali Beach','John P Salvatore','https://commons.wikimedia.org/w/index.php?title=User:John_P_Salvatore&action=edit&redlink=1','CC BY-SA 4.0','https://creativecommons.org/licenses/by-sa/4.0','Photo by John P Salvatore, licensed CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0). Source: https://commons.wikimedia.org/w/index.php?curid=102333339.'),
  ('0bc849fa-7e06-5600-8176-d2fda5ecfbf0'::uuid,'File:Ocean City MD beach looking north from pier.jpeg','https://upload.wikimedia.org/wikipedia/commons/5/52/Ocean_City_MD_beach_looking_north_from_pier.jpeg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original','https://thumb.wikimedia.org/wikipedia/commons/thumb/5/52/Ocean_City_MD_beach_looking_north_from_pier.jpeg/960px-Ocean_City_MD_beach_looking_north_from_pier.jpeg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail','Ocean City Beach (Maryland)','User:Dough4872','https://commons.wikimedia.org/wiki/User:Dough4872','CC BY-SA 3.0','https://creativecommons.org/licenses/by-sa/3.0','Photo by User:Dough4872, licensed CC BY-SA 3.0 (https://creativecommons.org/licenses/by-sa/3.0). Source: https://commons.wikimedia.org/w/index.php?curid=27599434.')
)
INSERT INTO public.beach_photos (
  beach_id,source,source_id,image_url,thumb_url,title,creator_name,creator_url,
  license_code,license_url,attribution_html,approved
)
SELECT beach_id,'wikimedia',source_id,image_url,thumb_url,title,creator_name,creator_url,
  license_code,license_url,attribution_html,true FROM photos
ON CONFLICT (beach_id,source,source_id) DO NOTHING;

DO $$
DECLARE n integer; source_n integer; photo_n integer; camera_n integer;
BEGIN
  SELECT count(*) INTO n FROM public.beaches WHERE id IN (SELECT id FROM _catalog_gap_beaches);
  SELECT count(*) INTO source_n FROM public.beach_sources WHERE beach_id IN (SELECT id FROM _catalog_gap_beaches) AND forecast_source_id='open_meteo';
  SELECT count(*) INTO photo_n FROM public.beach_photos WHERE (beach_id,source_id) IN (VALUES ('90df1267-5d2e-51b6-ba06-21e89405166c'::uuid,'File:View of Cowel Beach towards Lighthouse Point -Santa Cruz - panoramio.jpg'),('0922be9c-e437-5f0a-90a8-82588f429564'::uuid,'File:Sunset at Napili Bay, Maui.jpg'),('67def85b-7500-5ccb-bd86-7141652da53e'::uuid,'File:Kamaole Beach II Kihei Maui Hawaii (30800124747).jpg'),('75e0bd7d-f25d-54eb-b455-af99eb561200'::uuid,'File:Kaanapali Beach Maui.jpg'),('0bc849fa-7e06-5600-8176-d2fda5ecfbf0'::uuid,'File:Ocean City MD beach looking north from pier.jpeg')) AND source='wikimedia' AND approved AND deleted_at IS NULL;
  SELECT count(*) INTO camera_n FROM _catalog_gap_beaches p JOIN public.beach_sources s ON s.beach_id=p.id WHERE p.camera_url IS NOT NULL AND s.camera_url=p.camera_url;
  IF n <> 28 OR source_n <> 28 OR photo_n <> 5 OR camera_n <> 12 THEN
    RAISE EXCEPTION 'Catalog gap import count mismatch: beaches %, sources %, photos %, cameras %',n,source_n,photo_n,camera_n;
  END IF;
END $$;
COMMIT;
