BEGIN;

CREATE TEMP TABLE temp_monterey_big_sur_spots (
  insert_if_missing boolean NOT NULL,
  target_slug text NOT NULL,
  name text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  country text NOT NULL,
  timezone text NOT NULL,
  lat double precision NOT NULL,
  lon double precision NOT NULL,
  region text NOT NULL,
  break_type text NOT NULL CHECK (break_type IN ('beach', 'point', 'reef', 'river-mouth')),
  skill_level text NOT NULL,
  crowd_level text NOT NULL CHECK (crowd_level IN ('light', 'moderate', 'crowded', 'very_crowded')),
  aspect_deg integer NOT NULL,
  swell_window_min_deg integer,
  swell_window_max_deg integer,
  swell_window_center_deg integer,
  swell_window_halfwidth_deg integer,
  wind_offshore_deg integer,
  wind_offshore_tol_deg integer,
  wind_cross_shore_ok_kt integer,
  wind_onshore_bad_kt integer,
  preferred_tide_ft_min numeric,
  preferred_tide_ft_max numeric,
  best_months integer[] NOT NULL,
  hazards text[] NOT NULL,
  features text[] NOT NULL,
  description text NOT NULL,
  parking_tips text NOT NULL,
  access_tips text NOT NULL,
  wave_tips text NOT NULL,
  crowd_tips text NOT NULL,
  best_conditions_prose text NOT NULL,
  warnings text[] NOT NULL,
  local_etiquette text NOT NULL,
  real_takeaways text[] NOT NULL,
  preference_model jsonb NOT NULL,
  is_private boolean NOT NULL
) ON COMMIT DROP;

INSERT INTO temp_monterey_big_sur_spots (
  insert_if_missing,
  target_slug,
  name,
  city,
  state,
  country,
  timezone,
  lat,
  lon,
  region,
  break_type,
  skill_level,
  crowd_level,
  aspect_deg,
  swell_window_min_deg,
  swell_window_max_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  best_months,
  hazards,
  features,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  real_takeaways,
  preference_model,
  is_private
) VALUES
  (
    true,
    'carmel-beach-carmel-ca',
    'Carmel Beach',
    'Carmel-by-the-Sea',
    'CA',
    'USA',
    'America/Los_Angeles',
    36.55,
    -121.93,
    'Monterey Peninsula',
    'beach',
    'intermediate',
    'moderate',
    250,
    220,
    300,
    260,
    40,
    70,
    45,
    8,
    12,
    1.5,
    5.0,
    ARRAY[10,11,12,1,2,3,4],
    ARRAY['Rip currents', 'Cold water', 'Shorebreak', 'Crowds', 'Occasional kelp'],
    ARRAY['Multiple peaks', 'Scenic beach', 'Easy town access', 'Works on west swell', 'Wind shelter possible near kelp and cove edges'],
    'Main Carmel-by-the-Sea surf zone with several shifting beach-break peaks along the white-sand beach. Better for research as the core local spot, but conditions can change quickly with sandbars, tide, and wind.',
    'Use Ocean Avenue beach access or nearby street parking along Scenic Road and surrounding streets. Parking can fill on weekends and sunny afternoons.',
    'Easy beach access from town stairways and ramps. Dogs are commonly present on the beach, so account for extra activity near takeoff zones.',
    'Check peaks near 4th, 8th, and 11th. Look for clean west to northwest swell, light offshore east wind, and manageable tide.',
    'Expect mixed-use beach traffic and local surfers when it is clean. Spread out between peaks.',
    'Clean west to northwest swell with light east or northeast wind. Mid tide is usually a reasonable starting point, then adjust by sandbar.',
    ARRAY['Not a beginner default when swell is solid. Watch for rips, shorebreak, cold-water fatigue, and shifting sandbars.'],
    'Respect existing peaks, avoid paddling straight into the tightest takeoff, and keep space from swimmers, dogs, and beachgoers.',
    ARRAY['🏄 Primary Carmel-by-the-Sea surf listing.', '🌊 Multiple beach-break peaks, not one fixed takeoff.', '🧭 Best with clean west/NW swell and offshore easterly wind.', '🐕 Busy beach activity; watch for dogs and pedestrians near access points.', '⚠️ Sandbars and rips change quickly.'],
    jsonb_build_object('swell_primary', 'W-NW', 'wind_primary', 'E-NE', 'tide_primary', 'Mid', 'season_primary', 'Fall through spring'),
    false
  ),
  (
    false,
    'carmel-river-state-beach-carmel-ca',
    'Carmel River State Beach / Rivermouth',
    'Carmel',
    'CA',
    'USA',
    'America/Los_Angeles',
    36.535,
    -121.93,
    'Monterey Peninsula',
    'river-mouth',
    'advanced',
    'light',
    250,
    220,
    300,
    260,
    40,
    70,
    40,
    7,
    10,
    1.0,
    4.0,
    ARRAY[11,12,1,2,3],
    ARRAY['Severe rip currents', 'Sudden drop-offs', 'Pounding shorebreak', 'Cold water', 'Rogue or sleeper waves', 'Lagoon and river flow changes'],
    ARRAY['Rivermouth setup', 'Powerful sandbar potential', 'Scenic state beach', 'Birding lagoon nearby'],
    'A hazardous Carmel-area rivermouth and sandbar zone at Carmel River State Beach. Include for research completeness, but this is not a casual surf recommendation.',
    'Use Carmel River State Beach access. Parking and access can vary by season and beach or lagoon conditions.',
    'Scout carefully from shore. Avoid crossing unstable lagoon or river areas during flow or high surf.',
    'Only consider when sandbar shape, swell size, and current are manageable. West to northwest winter energy is the most relevant swell window.',
    'Less of a casual crowd than Carmel Beach, but experienced locals may be present when it is working.',
    'Clean west to northwest swell, light east wind, and a shaped rivermouth sandbar. Needs live local verification.',
    ARRAY['State and visitor sources emphasize dangerous swimming and wading conditions near Carmel River State Beach and Monastery-area shorelines, including sudden drop-offs, pounding shorebreak, rip currents, and sleeper waves.'],
    'Treat as advanced-only. Do not encourage novice use. Give priority to surfers already positioned on the peak.',
    ARRAY['⚠️ Advanced-only research listing, not a beginner recommendation.', '🌊 Rivermouth sandbar can be powerful and current-prone.', '🧭 Best considered on clean W/NW winter swell with light offshore wind.', '🚫 Strong safety language should stay in the app.', '🔎 Needs human review before broad surf exposure.'],
    jsonb_build_object('swell_primary', 'W-NW', 'wind_primary', 'E-NE', 'tide_primary', 'Low to mid', 'season_primary', 'Winter'),
    false
  ),
  (
    true,
    'monastery-beach-san-jose-creek-beach-carmel-ca',
    'Monastery Beach / San Jose Creek Beach',
    'Carmel',
    'CA',
    'USA',
    'America/Los_Angeles',
    36.525,
    -121.927,
    'Monterey Peninsula',
    'beach',
    'expert',
    'light',
    250,
    220,
    300,
    260,
    40,
    70,
    35,
    6,
    10,
    1.0,
    4.0,
    ARRAY[11,12,1,2,3],
    ARRAY['Extremely dangerous shorebreak', 'Severe rip currents', 'Sudden drop-off', 'Rogue or sleeper waves', 'Cold water', 'Frequent scuba and diver activity'],
    ARRAY['Part of Carmel River State Beach', 'Known scuba area', 'Very steep beach profile', 'High hazard rating'],
    'Monastery Beach is included only as an expert and hazard research entry. Reliable public sources emphasize scuba use and dangerous water conditions more than ordinary surf use.',
    'Roadside and state beach access near Highway 1. Parking can be tight and conditions should be checked before stopping.',
    'Do not treat this as a normal beach-break access. Shorebreak and drop-off can make entry and exit dangerous.',
    'Not recommended as a standard Quiver surf spot without local expert validation.',
    'Expect divers and coastal visitors rather than a typical surf lineup.',
    'Only advanced or expert local review should determine whether this is surfable on a given day.',
    ARRAY['Keep this listing safety-forward. Public sources warn against swimming and wading near Monastery because of unpredictable rips, severe drop-offs, and dangerous shorebreak.'],
    'Avoid interfering with scuba entry and exit zones and do not encourage inexperienced surfers to enter.',
    ARRAY['🚫 Do not surface as a normal beginner/intermediate surf recommendation.', '⚠️ The defining feature is hazard level, not consistency.', '🤿 Known more for scuba and diving access than regular surf use.', '🌊 Steep beach and shorebreak make entry and exit dangerous.', '🔎 Requires human review before publishing.'],
    jsonb_build_object('swell_primary', 'W-NW', 'wind_primary', 'E-NE', 'tide_primary', 'Variable / expert-only', 'season_primary', 'Winter'),
    false
  ),
  (
    true,
    'ghost-tree-pebble-beach-ca',
    'Ghost Tree',
    'Pebble Beach',
    'CA',
    'USA',
    'America/Los_Angeles',
    36.56,
    -121.967,
    'Monterey Peninsula',
    'reef',
    'expert',
    'light',
    250,
    245,
    285,
    265,
    20,
    65,
    35,
    5,
    8,
    2.0,
    6.0,
    ARRAY[12,1,2],
    ARRAY['Big-wave reef', 'Rocks', 'Sharks', 'Strong currents', 'Kelp', 'Long hold-downs', 'Limited access'],
    ARRAY['Rare big-wave setup', 'Exposed reef', 'Pescadero Point', 'Advanced safety requirements'],
    'Rare, expert-only big-wave reef off Pescadero Point. This should be treated as a research-only listing unless Quiver has a dedicated expert and big-wave context.',
    'Access is tied to Pebble Beach and 17-Mile Drive. Vehicle entrance rules and fees may apply.',
    'Not a casual paddle-out. Access, rescue planning, equipment, and local knowledge are critical.',
    'Needs rare large west swell and clean offshore conditions. It breaks infrequently and demands expert judgment.',
    'Low numbers but very serious lineup. Do not encourage casual drop-ins or spectating from unsafe zones.',
    'Large west groundswell, clean ENE/E wind, and expert-level safety support.',
    ARRAY['Expert-only big-wave reef with rocks, sharks, serious water, and access constraints.'],
    'Only experienced big-wave surfers with local knowledge and safety support should consider this spot.',
    ARRAY['🌊 Big-wave research entry, not a normal surf recommendation.', '🪨 Reef and rock hazard is central to the listing.', '🧭 Needs rare large W swell and offshore wind.', '🚗 Pebble Beach and 17-Mile Drive access details matter.', '🔎 Keep human review enabled.'],
    jsonb_build_object('swell_primary', 'Large W', 'wind_primary', 'ENE-E', 'tide_primary', 'Mid to high', 'season_primary', 'Winter'),
    false
  ),
  (
    true,
    'spanish-bay-south-moss-beach-pebble-beach-ca',
    'Spanish Bay / South Moss Beach',
    'Pebble Beach',
    'CA',
    'USA',
    'America/Los_Angeles',
    36.62,
    -121.95,
    'Monterey Peninsula',
    'beach',
    'intermediate',
    'moderate',
    265,
    230,
    300,
    265,
    35,
    115,
    40,
    8,
    12,
    0.5,
    3.5,
    ARRAY[10,11,12,1,2,3],
    ARRAY['Rocks', 'Rip currents', 'Sharks', 'Cold water', 'Pebble Beach access fee'],
    ARRAY['Beach-break peaks', 'Lefts and rights', '17-Mile Drive access', 'Scenic coastline'],
    'Exposed Pebble Beach beach break with lefts and rights. Southeast wind, west swell, and low tide are the favorable research inputs.',
    'Access is generally via 17-Mile Drive. Pebble Beach gate fees and rules may apply, with vehicle access typically open sunrise to sunset.',
    'Plan for paid vehicle access unless already inside Pebble Beach. Motorcycles are prohibited on 17-Mile Drive.',
    'Look for west swell, southeast or east wind, and lower tides. Avoid rocky areas when swell is strong.',
    'Can get crowded when conditions line up, especially with limited quality windows nearby.',
    'West swell with southeast offshore flow and lower tide.',
    ARRAY['Rocks, rips, cold water, sharks, and access constraints should be included in app notes.'],
    'Respect private-community access rules and share peaks when sandbars concentrate the crowd.',
    ARRAY['🌊 Useful Pebble Beach beach-break listing.', '🧭 W swell plus SE wind plus lower tide is the key combo.', '🚗 17-Mile Drive access and fee should be surfaced.', '🪨 Rocks are part of the risk profile.', '🔎 Good candidate, but human review recommended.'],
    jsonb_build_object('swell_primary', 'W', 'wind_primary', 'SE-ESE', 'tide_primary', 'Low', 'season_primary', 'Fall through winter'),
    false
  ),
  (
    true,
    'asilomar-state-beach-pacific-grove-ca',
    'Asilomar State Beach',
    'Pacific Grove',
    'CA',
    'USA',
    'America/Los_Angeles',
    36.63,
    -121.94,
    'Monterey Peninsula',
    'beach',
    'intermediate-advanced',
    'moderate',
    265,
    230,
    300,
    265,
    35,
    115,
    45,
    8,
    12,
    1.0,
    5.0,
    ARRAY[10,11,12,1,2,3,4],
    ARRAY['Rocks', 'Reef', 'Rip currents', 'Sharks', 'Cold water', 'Can hold large surf'],
    ARRAY['Consistent exposed setup', 'Beach and reef options', 'Named zones include Roadsides, Middles, and Reef', 'Can handle bigger surf'],
    'Consistent Pacific Grove surf zone with exposed beach and reef options. Asilomar can handle size and includes named zones such as Roadsides, Middles, and Reef.',
    'Street and state beach parking along Sunset Drive and nearby pullouts. Arrive early during clean winter windows.',
    'Scout from the coastal path and use established beach access points. Avoid walking over sensitive dunes.',
    'West swell and southeast offshore wind are the key research inputs. Size can jump quickly because the coast is exposed.',
    'Popular with Monterey Peninsula surfers. Spread between named zones when possible.',
    'West swell with light southeast or east wind and a mid-range tide. Bigger days are for advanced surfers.',
    ARRAY['Rocks, reef, rips, cold water, and sharks are meaningful hazards. Not a protected beginner beach.'],
    'Respect local peaks, do not crowd reef takeoffs, and use established paths through dune areas.',
    ARRAY['🏄 One of the strongest Monterey Peninsula candidates.', '🌊 More consistent and exposed than Carmel Beach.', '🪨 Beach and reef hazards need explicit tagging.', '🧭 W swell and SE wind are the baseline condition model.', '✅ Good Quiver entry with medium-high support.'],
    jsonb_build_object('swell_primary', 'W', 'wind_primary', 'SE-ESE', 'tide_primary', 'Mid', 'season_primary', 'Fall through spring'),
    false
  ),
  (
    true,
    'lovers-point-pacific-grove-ca',
    'Lovers Point',
    'Pacific Grove',
    'CA',
    'USA',
    'America/Los_Angeles',
    36.63,
    -121.92,
    'Monterey Peninsula',
    'point',
    'intermediate-advanced',
    'moderate',
    315,
    285,
    335,
    310,
    25,
    180,
    45,
    8,
    12,
    2.0,
    6.0,
    ARRAY[11,12,1,2,3],
    ARRAY['Rocks', 'Rip currents', 'Cold water', 'Tight takeoff zone', 'Crowds when working'],
    ARRAY['Left point', 'Rocky cove', 'Winter consistency', 'Protected Pacific Grove setting'],
    'A left point and cove setup at Pacific Grove. Winter is the most consistent window, with the wave wrapping into a rocky cove.',
    'Use Lovers Point and Pacific Grove street or lot parking. Expect tourist and recreation traffic.',
    'Rocky access and cove geometry require careful entry and exit. Scout before paddling.',
    'Best on northwest swell with south or offshore wind. More relevant in winter than summer.',
    'Tighter lineup than an open beach break. Be patient and avoid back-paddling.',
    'Northwest swell with south/offshore wind and a tide that keeps the rocky takeoff covered.',
    ARRAY['Rocky cove and point setup. Not a forgiving beginner wave.'],
    'Point-break etiquette matters: wait your turn, do not sit inside the main pack, and avoid burning the first rider on the left.',
    ARRAY['⬅️ Left point and cove setup.', '❄️ Winter is the most reliable season.', '🪨 Rocks are the main hazard.', '🧭 NW swell plus S/offshore wind is the model.', '✅ Good Quiver entry with human-review note for tide and access.'],
    jsonb_build_object('swell_primary', 'NW', 'wind_primary', 'S', 'tide_primary', 'Mid to high', 'season_primary', 'Winter'),
    false
  ),
  (
    true,
    'del-monte-beach-monterey-ca',
    'Del Monte Beach',
    'Monterey',
    'CA',
    'USA',
    'America/Los_Angeles',
    36.6,
    -121.88,
    'Monterey Bay',
    'beach',
    'beginner-intermediate',
    'moderate',
    315,
    285,
    335,
    310,
    25,
    150,
    45,
    8,
    12,
    2.0,
    5.5,
    ARRAY[11,12,1,2,3],
    ARRAY['Rip currents', 'Cold water', 'Sharks', 'Longshore drift', 'Crowds near access'],
    ARRAY['Sandbar beach break', 'Monterey town access', 'Lefts and rights', 'More approachable than exposed reef spots'],
    'Monterey beach-break and sandbar zone. Del Monte is an exposed beach break and sandbar with winter as the favored season.',
    'Use Del Monte Beach access points in Monterey. Parking can be limited near residential access streets.',
    'Straightforward beach access, but respect residential parking and dune paths.',
    'Northwest swell with south-southeast offshore wind and mid-to-rising tide is the baseline model.',
    'Can draw learners and local surfers because access is easier than more rugged spots.',
    'Clean northwest swell, light SSE wind, and mid-rising tide.',
    ARRAY['Still cold-water Monterey surf with rips and possible shark risk; do not over-label as safe.'],
    'Give space to learners and do not crowd the best sandbar when multiple peaks are working.',
    ARRAY['🏄 More approachable Monterey beach-break option.', '🌊 Sandbar-dependent with lefts and rights.', '🧭 NW swell plus SSE wind plus mid-rising tide.', '🚶 Easy access, but respect residential parking.', '✅ Good Quiver entry.'],
    jsonb_build_object('swell_primary', 'NW', 'wind_primary', 'SSE-SE', 'tide_primary', 'Mid-rising', 'season_primary', 'Winter'),
    false
  ),
  (
    true,
    'marina-state-beach-marina-ca',
    'Marina State Beach',
    'Marina',
    'CA',
    'USA',
    'America/Los_Angeles',
    36.69,
    -121.81,
    'Monterey Bay',
    'beach',
    'intermediate-advanced',
    'moderate',
    295,
    250,
    320,
    285,
    35,
    110,
    45,
    8,
    12,
    2.0,
    5.5,
    ARRAY[11,12,1,2,3],
    ARRAY['Rip currents', 'Sharks', 'Cold water', 'Powerful beachbreak', 'Wind exposure'],
    ARRAY['Consistent exposed beach break', 'Lefts and rights', 'Can barrel when lined up', 'Less crowded than town spots'],
    'Exposed Monterey Bay beach break north of Monterey. It can produce challenging beach-break barrels when conditions line up.',
    'Use Marina State Beach parking and access. Wind and sand movement can make conditions feel exposed.',
    'Straight beach access, but check surf size and current before paddling out.',
    'Look for west to northwest swell with east-southeast wind and mid-to-high tide.',
    'Usually less packed than the Peninsula, but quality peaks can still cluster surfers.',
    'W to NW swell, ESE/SE offshore wind, and mid-rising to higher tide.',
    ARRAY['Powerful, exposed beach break with rips and shark risk. Better for intermediate and advanced surfers.'],
    'Choose a peak with space and avoid drifting into other surfers in longshore current.',
    ARRAY['🌊 Consistent exposed beach-break option north of Monterey.', '🧭 W/NW swell plus ESE wind plus mid/high tide.', '💨 Wind exposure matters a lot.', '⚠️ Rips and shark risk should stay visible.', '✅ Good Quiver entry for intermediate/advanced filters.'],
    jsonb_build_object('swell_primary', 'W-NW', 'wind_primary', 'ESE-SE', 'tide_primary', 'Mid-rising to high', 'season_primary', 'Winter'),
    false
  ),
  (
    true,
    'moss-landing-moss-landing-ca',
    'Moss Landing',
    'Moss Landing',
    'CA',
    'USA',
    'America/Los_Angeles',
    36.81,
    -121.79,
    'Monterey Bay',
    'beach',
    'intermediate-advanced',
    'moderate',
    290,
    250,
    320,
    285,
    35,
    110,
    45,
    8,
    12,
    2.0,
    5.5,
    ARRAY[11,12,1,2,3],
    ARRAY['Rip currents', 'Sharks', 'Cold water', 'Localism', 'Harbor and river influence', 'Powerful surf'],
    ARRAY['Consistent beach break', 'Lefts and rights', 'Winter reliability', 'North Monterey Bay exposure'],
    'Consistent exposed beach break near the Moss Landing harbor and river area. It often works, with winter favored and ESE wind plus NW swell as the model.',
    'Use public beach and harbor-area access and confirm any posted restrictions.',
    'Scout currents, wind, and sandbars before paddling. Conditions can be stronger than they look from the lot.',
    'Northwest swell with east-southeast offshore flow and mid-rising tide.',
    'Can get crowded and has local presence when good. Avoid peak-hopping into a packed takeoff.',
    'NW swell, ESE wind, and mid-rising tide during winter windows.',
    ARRAY['Rips, sharks, cold water, localism, and strong surf should be included as app hazards.'],
    'Respect locals, do not drop in, and choose less crowded peaks when possible.',
    ARRAY['🌊 Reliable north Monterey Bay beach-break candidate.', '🧭 NW swell plus ESE wind plus mid-rising tide.', '⚠️ Rips, sharks, and localism all need tagging.', '❄️ Winter is the main season.', '✅ Good Quiver entry for experienced-user filters.'],
    jsonb_build_object('swell_primary', 'NW', 'wind_primary', 'ESE-SE', 'tide_primary', 'Mid-rising', 'season_primary', 'Winter'),
    false
  ),
  (
    false,
    'garrapata-southern-coves-carmel-ca',
    'Garrapata State Park',
    'Carmel Highlands / Big Sur',
    'CA',
    'USA',
    'America/Los_Angeles',
    36.42,
    -121.92,
    'North Big Sur',
    'beach',
    'advanced',
    'light',
    250,
    220,
    300,
    260,
    40,
    115,
    40,
    7,
    10,
    1.0,
    4.5,
    ARRAY[10,11,12,1,2,3],
    ARRAY['Strong rips', 'Undertow', 'Rocks', 'Sharks', 'Remote access', 'Cold water', 'Limited services'],
    ARRAY['Remote Big Sur coastline', 'Uncrowded potential', 'Exposed beach break', 'State park setting'],
    'Remote, exposed beach-break zone on the north Big Sur coast. Garrapata is a coastal state park surf zone with meaningful rips, undertow, rocks, and shark risk.',
    'Use legal Highway 1 pullouts and signed state park access points. Avoid blocking gates or private property.',
    'Stay on designated trails and account for bluff, surf, and road hazards. Services are limited.',
    'West groundswell and ESE/SE offshore wind are the baseline. Needs careful visual assessment because exposure is high.',
    'Usually uncrowded, but do not surf alone due to remoteness and hazards.',
    'W groundswell, light ESE/SE wind, and a manageable tide and swell size.',
    ARRAY['Remote, advanced-only setting with rips, undertow, rocks, sharks, and limited rescue access.'],
    'Respect state park trails, private-property boundaries, and leave-no-trace coastal access.',
    ARRAY['🏞️ Remote north Big Sur state-park surf zone.', '🌊 Exposed beach break, not a sheltered learner spot.', '🧭 W swell plus ESE wind is the condition baseline.', '⚠️ Rips, undertow, rocks, and sharks are major hazards.', '🔎 Human review recommended before broad surf-app exposure.'],
    jsonb_build_object('swell_primary', 'W', 'wind_primary', 'ESE-SE', 'tide_primary', 'Low to mid', 'season_primary', 'Fall through winter'),
    false
  ),
  (
    false,
    'andrew-molera-river-mouth-big-sur-ca',
    'Andrew Molera State Park / Big Sur Rivermouth',
    'Big Sur',
    'CA',
    'USA',
    'America/Los_Angeles',
    36.28,
    -121.87,
    'North Big Sur',
    'river-mouth',
    'intermediate-advanced',
    'moderate',
    260,
    220,
    300,
    260,
    40,
    45,
    45,
    7,
    10,
    0.5,
    4.0,
    ARRAY[11,12,1,2,3],
    ARRAY['Rips', 'Rocks', 'Sharks', 'Remote access', 'River crossing and access changes', 'Cold water', 'Long walk-in'],
    ARRAY['Big Sur rivermouth', 'Right-breaking potential', 'Scenic state park', 'Walk-in access', 'Can be high quality with correct swell'],
    'Big Sur rivermouth and point-style setup inside Andrew Molera State Park. It has right-breaking potential and meaningful access complexity.',
    'Use Andrew Molera State Park day-use parking. Account for park hours, fees, trail status, and any river crossing or access changes.',
    'Expect a walk to the beach and rivermouth area. Stay on state park trails and avoid private ranch boundaries.',
    'West to northwest swell with northeast offshore wind and lower tide is the baseline model. Needs enough swell to wrap and shape along the rivermouth and point.',
    'Can still draw surfers when good despite the walk. Respect the main right and wait turns.',
    'Solid W/NW swell, light NE wind, and low-to-rising tide.',
    ARRAY['Remote Big Sur surf with rips, rocks, sharks, cold water, and access complexity. Not a beginner listing.'],
    'Respect park rules, private-property boundaries, and the established takeoff order when the right is working.',
    ARRAY['🏞️ Strong north Big Sur research candidate.', '➡️ Right and rivermouth potential, not just generic beach break.', '🚶 Walk-in access should be tagged.', '🧭 W/NW swell plus NE wind plus lower tide.', '🔎 Good listing, but keep human review enabled for access and safety.'],
    jsonb_build_object('swell_primary', 'W-NW', 'wind_primary', 'NE', 'tide_primary', 'Low-rising', 'season_primary', 'Winter'),
    false
  );

INSERT INTO public.beaches (
  name,
  slug,
  city,
  state,
  country,
  timezone,
  lat,
  lon,
  region,
  break_type,
  skill_level,
  crowd_level,
  aspect_deg,
  swell_window_min_deg,
  swell_window_max_deg,
  swell_window_center_deg,
  swell_window_halfwidth_deg,
  wind_offshore_deg,
  wind_offshore_tol_deg,
  wind_cross_shore_ok_kt,
  wind_onshore_bad_kt,
  preferred_tide_ft_min,
  preferred_tide_ft_max,
  best_months,
  hazards,
  features,
  description,
  parking_tips,
  access_tips,
  wave_tips,
  crowd_tips,
  best_conditions_prose,
  warnings,
  local_etiquette,
  real_takeaways,
  preference_model,
  is_private
)
SELECT
  spot.name,
  spot.target_slug,
  spot.city,
  spot.state,
  spot.country,
  spot.timezone,
  spot.lat,
  spot.lon,
  spot.region,
  spot.break_type,
  spot.skill_level,
  spot.crowd_level,
  spot.aspect_deg,
  spot.swell_window_min_deg,
  spot.swell_window_max_deg,
  spot.swell_window_center_deg,
  spot.swell_window_halfwidth_deg,
  spot.wind_offshore_deg,
  spot.wind_offshore_tol_deg,
  spot.wind_cross_shore_ok_kt,
  spot.wind_onshore_bad_kt,
  spot.preferred_tide_ft_min,
  spot.preferred_tide_ft_max,
  spot.best_months,
  spot.hazards,
  spot.features,
  spot.description,
  spot.parking_tips,
  spot.access_tips,
  spot.wave_tips,
  spot.crowd_tips,
  spot.best_conditions_prose,
  spot.warnings,
  spot.local_etiquette,
  spot.real_takeaways,
  spot.preference_model,
  spot.is_private
FROM temp_monterey_big_sur_spots spot
WHERE spot.insert_if_missing
  AND NOT EXISTS (
    SELECT 1
    FROM public.beaches b
    WHERE b.deleted_at IS NULL
      AND lower(b.slug) = lower(spot.target_slug)
  );

UPDATE public.beaches AS b
SET
  description = spot.description,
  hazards = spot.hazards,
  features = spot.features,
  warnings = spot.warnings,
  parking_tips = spot.parking_tips,
  access_tips = spot.access_tips,
  wave_tips = spot.wave_tips,
  crowd_tips = spot.crowd_tips,
  best_conditions_prose = spot.best_conditions_prose,
  local_etiquette = spot.local_etiquette,
  real_takeaways = spot.real_takeaways,
  best_months = spot.best_months
FROM temp_monterey_big_sur_spots spot
WHERE NOT spot.insert_if_missing
  AND b.deleted_at IS NULL
  AND lower(b.slug) = lower(spot.target_slug);

COMMIT;
