-- Widen user_events.event_type CHECK to accept native analytics events that the
-- app already emits but the database rejects.
--
-- Native `trackEvent()` inserts straight into user_events via the Supabase
-- client (src/lib/analytics.ts `insertEvent`), so the web `VALID_EVENTS`
-- taxonomy never gates it — this CHECK constraint is the only gate. Eleven
-- event types in `NativeAnalyticsEventType` are absent from the constraint, so
-- every insert raises 23514. `dispatchTrackEvent` retries once, fails, and
-- drops the event; `trackEvent` is `void`-dispatched, so no caller ever learns.
-- All eleven have zero rows in production despite being emitted from shipped
-- builds (1.0.1 / 1.0.2).
--
-- Six are the onboarding purchase funnel from `trial-prompt-step.tsx`. Ten of
-- the eleven are emitted alongside an allowed sibling at the same call site
-- (`paywall_opened`, `paywall_purchase_started`/`_success`/`_failed`,
-- `onboarding_paywall_skipped`), so the underlying signal did survive them.
-- `onboarding_restore_result` is the exception: it has no sibling, so
-- onboarding restore outcomes were never recorded at all.
--
-- The ongoing cost is the failure path — every onboarding paywall view runs
-- two rejected inserts plus a Sentry diagnostic — and the structural risk that
-- the next native event without a sibling is dropped the same silent way.
--
-- Preserve the live CHECK expression dynamically so prior event additions
-- remain accepted. Idempotent: only appends event types not already present.
--
-- APPLIED to production via direct psql 2026-08-12 14:19 UTC. Verified after
-- apply: 11 of 11 present in the live constraint; all 11 insert successfully
-- (in a rolled-back transaction, nothing persisted); an unknown event type is
-- still rejected by user_events_event_type_check, so the constraint was
-- widened and not neutered; a second run reports "no change".
--
-- Do NOT edit this file to change behaviour — it has run. Editing an applied
-- migration changes the file and not the database. Write a superseding
-- migration instead.

BEGIN;

DO $$
DECLARE
  current_check text;
  candidate_events text[] := ARRAY[
    -- Onboarding paywall funnel (trial-prompt-step.tsx)
    'onboarding_paywall_viewed',
    'onboarding_free_selected',
    'onboarding_purchase_started',
    'onboarding_purchase_success',
    'onboarding_purchase_failed',
    'onboarding_purchase_cancelled',
    'onboarding_restore_result',
    -- Other native emitters rejected by the same gap
    'community_filter_selected',
    'siri_shortcut_opened',
    'garmin_connect_viewed',
    'garmin_designated_activity_set'
  ];
  missing_events text[];
BEGIN
  SELECT regexp_replace(pg_get_constraintdef(oid), '^CHECK \((.*)\)$', '\1')
    INTO current_check
  FROM pg_constraint
  WHERE conrelid = 'public.user_events'::regclass
    AND conname = 'user_events_event_type_check';

  IF current_check IS NULL THEN
    RAISE EXCEPTION 'user_events_event_type_check constraint not found';
  END IF;

  SELECT array_agg(event_name)
    INTO missing_events
  FROM unnest(candidate_events) AS event_name
  WHERE current_check NOT LIKE '%' || event_name || '%';

  IF missing_events IS NULL OR array_length(missing_events, 1) IS NULL THEN
    RAISE NOTICE 'All native onboarding events already present; no change.';
    RETURN;
  END IF;

  ALTER TABLE public.user_events
    DROP CONSTRAINT user_events_event_type_check;

  EXECUTE format(
    'ALTER TABLE public.user_events ADD CONSTRAINT user_events_event_type_check CHECK ((%s) OR event_type = ANY (%L::text[]))',
    current_check,
    missing_events
  );

  RAISE NOTICE 'Added % native event type(s): %',
    array_length(missing_events, 1), missing_events;
END $$;

NOTIFY pgrst, 'reload schema';

COMMIT;
