/**
 * Swell Quality Analyzer — /tools/swell-analyzer
 *
 * Interactive swell period explainer + beach swell window checker.
 * Reuses analyzeSwellMatch() from lib/analyzers/swell-analyzer.ts.
 */

import type { Metadata } from "next";
import { buildPageMetadata } from "@/lib/seo/meta";
import { BreadcrumbStructuredData } from "@/components/seo/breadcrumb-schema";
import { FAQSchema } from "@/components/seo/faq-schema";
import { SITE_URL } from "@/lib/constants/seo";
import { capitalize } from "@/lib/utils/text-utils";
import { SwellAnalyzerClient } from "@/components/tools/swell-analyzer-client";
import { getSwellAnalyzerData } from "@/actions/tools/swell-analyzer-actions";

export const revalidate = 3600;

interface Props {
  searchParams: Promise<{ beach?: string }>;
}

export async function generateMetadata({ searchParams }: Props): Promise<Metadata> {
  const params = await searchParams;
  const beachSlug = params.beach;

  if (beachSlug) {
    return buildPageMetadata({
      title: `Swell Quality at ${capitalize(beachSlug)} | Swell Analyzer`,
      description: `Is the current swell in ${capitalize(beachSlug)}'s sweet spot? Check swell direction, period, and quality.`,
      path: `/tools/swell-analyzer?beach=${beachSlug}`,
      image: "/images/tools/golden-tube.jpg",
    });
  }

  return buildPageMetadata({
    title: "Swell Quality Analyzer — Is 8 Second Swell Period Good?",
    description:
      "Understand how swell period and direction affect wave quality. Interactive tool shows groundswell vs windswell, and checks any beach's swell window. Free.",
    path: "/tools/swell-analyzer",
    image: "/images/tools/golden-tube.jpg",
    keywords: [
      "swell period good",
      "groundswell vs windswell",
      "swell quality analyzer",
      "what is swell period",
      "8 second swell period",
      "swell direction surf",
      "reading surf forecast",
    ],
  });
}

export default async function SwellAnalyzerPage({ searchParams }: Props) {
  const params = await searchParams;
  const beachSlug = params.beach;

  let initialData = undefined;
  if (beachSlug) {
    const result = await getSwellAnalyzerData(beachSlug);
    if (result.success) {
      initialData = result.data;
    }
  }

  const SWELL_FAQ_ITEMS = [
    {
      question: "Is an 8-second swell period good for surfing?",
      answer:
        "An 8-second period is on the borderline between wind swell and groundswell. You\u2019ll get rideable waves, but they lack the power of longer-period swells. For most breaks, 10s+ starts to feel significantly better \u2014 12s+ is where things get exciting.",
    },
    {
      question: "What is the difference between groundswell and windswell?",
      answer:
        "Groundswell (12s+ period) is generated by distant storms and arrives as clean, organized energy that breaks powerfully and predictably. Windswell (under 8s) is created by local winds, producing choppy, close-together waves. Beach breaks can still be fun in windswell, but reef breaks need groundswell to fire.",
    },
    {
      question: "Why does swell direction matter for surfing?",
      answer:
        "Every beach has a geographic orientation that determines which swell directions it receives. A swell from outside a beach\u2019s exposure window may be blocked by headlands or arrive at a bad angle, causing closeouts instead of clean, peeling waves.",
    },
    {
      question: "What does a swell window mean?",
      answer:
        "A swell window is the range of directions that produce the best waves at a specific break. For example, a west-facing point break might fire on swells from 250\u2013310 degrees but be poor on south swells. Quiver maps each beach\u2019s swell window from geographic data.",
    },
    {
      question: "Can I surf in windswell conditions?",
      answer:
        "Yes \u2014 especially for beginners and longboarders. Short-period swells still produce surfable waves, just less powerful and consistent. It\u2019s reef breaks and hollow waves that really need long-period groundswell to show their best.",
    },
  ];

  return (
    <>
      <BreadcrumbStructuredData
        items={[
          { name: "Home", url: SITE_URL },
          { name: "Free Tools", url: `${SITE_URL}/tools` },
          {
            name: "Swell Quality Analyzer",
            url: `${SITE_URL}/tools/swell-analyzer`,
          },
        ]}
      />
      <FAQSchema items={SWELL_FAQ_ITEMS} />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebApplication",
            name: "Quiver Swell Quality Analyzer",
            url: `${SITE_URL}/tools/swell-analyzer`,
            description:
              "Understand how swell period and direction affect wave quality. Interactive tool shows groundswell vs windswell, and checks any beach's swell window.",
            applicationCategory: "SportsApplication",
            operatingSystem: "Any",
            offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
            publisher: {
              "@type": "Organization",
              name: "Quiver",
              url: SITE_URL,
            },
          }),
        }}
      />
      <div className="min-h-screen" style={{ background: "#0F1535" }}>
        <SwellAnalyzerClient initialData={initialData} />

        <div className="container mx-auto max-w-4xl px-4 pb-12">
          <section
            className="rounded-2xl border p-6 space-y-4"
            style={{
              background: "rgba(30, 37, 88, 0.7)",
              borderColor: "rgba(64,76,146,0.4)",
            }}
          >
            <h2 className="font-heading text-lg font-bold text-white">
              Understanding swell quality
            </h2>
            <div className="space-y-3 text-sm text-[#B8C7E0] leading-relaxed">
              <p>
                Swell quality is determined by two key factors:{" "}
                <strong className="text-white">period</strong> (seconds between
                waves) and <strong className="text-white">direction</strong>{" "}
                (where the swell is coming from). Longer periods mean more
                organized energy &mdash; a 15-second groundswell from a distant
                storm produces far cleaner waves than an 8-second windswell from
                local winds.
              </p>
              <p>
                <strong className="text-white">Groundswell (12s+)</strong> is
                generated by storms hundreds or thousands of miles away. The long
                travel time organizes wave energy into consistent, well-spaced
                sets.{" "}
                <strong className="text-white">Windswell (under 8s)</strong> is
                created by nearby winds and arrives disorganized &mdash; often
                choppy, crumbly, or prone to closeouts.
              </p>
              <p>
                Direction matters because every beach has a{" "}
                <strong className="text-white">swell window</strong> &mdash; the
                range of angles that produce quality waves at that specific
                break. A swell arriving outside the window may be blocked by
                headlands or refract poorly. This tool lets you dial in period,
                height, and direction, then check any beach to see if conditions
                fall in its sweet spot.
              </p>
            </div>
          </section>

          <section className="mt-6">
            <h2 className="font-heading text-xl font-bold text-white mb-4">
              Frequently asked questions
            </h2>
            <div className="space-y-2">
              {SWELL_FAQ_ITEMS.map((item) => (
                <details
                  key={item.question}
                  className="rounded-xl border group"
                  style={{
                    background: "rgba(30, 37, 88, 0.7)",
                    borderColor: "rgba(64, 76, 146, 0.4)",
                  }}
                >
                  <summary className="flex cursor-pointer items-center justify-between px-5 py-4 text-sm font-medium text-white list-none">
                    {item.question}
                    <span
                      className="ml-4 text-[#7A8CC0] transition-transform group-open:rotate-180 shrink-0"
                      aria-hidden
                    >
                      &darr;
                    </span>
                  </summary>
                  <div className="px-5 pb-4 text-sm text-[#B8C7E0] leading-relaxed">
                    {item.answer}
                  </div>
                </details>
              ))}
            </div>
          </section>
        </div>
      </div>
    </>
  );
}
