/**
 * Swell Quality Analyzer — /tools/swell-analyzer
 *
 * Interactive swell period explainer + beach swell window checker.
 * Reuses analyzeSwellMatch() from lib/analyzers/swell-analyzer.ts.
 */

import type { Metadata } from "next";
import { buildPageMetadata } from "@/lib/seo/meta";
import { BreadcrumbStructuredData } from "@/components/seo/breadcrumb-schema";
import { FAQSchema } from "@/components/seo/faq-schema";
import { SITE_URL } from "@/lib/constants/seo";
import { SwellAnalyzerClient } from "@/components/tools/swell-analyzer-client";
import { getSwellAnalyzerData } from "@/actions/tools/swell-analyzer-actions";

export const revalidate = 3600;

interface Props {
  searchParams: Promise<{ beach?: string }>;
}

export async function generateMetadata({ searchParams }: Props): Promise<Metadata> {
  const params = await searchParams;
  const beachSlug = params.beach;

  if (beachSlug) {
    return buildPageMetadata({
      title: `Swell Quality at ${beachSlug.replace(/-/g, " ")} | Swell Analyzer`,
      description: `Is the current swell in ${beachSlug.replace(/-/g, " ")}'s sweet spot? Check swell direction, period, and quality.`,
      path: `/tools/swell-analyzer?beach=${beachSlug}`,
    });
  }

  return buildPageMetadata({
    title: "Swell Quality Analyzer — Is 8 Second Swell Period Good?",
    description:
      "Understand how swell period and direction affect wave quality. Interactive tool shows groundswell vs windswell, and checks any beach's swell window. Free.",
    path: "/tools/swell-analyzer",
    keywords: [
      "swell period good",
      "groundswell vs windswell",
      "swell quality analyzer",
      "what is swell period",
      "8 second swell period",
      "swell direction surf",
      "reading surf forecast",
    ],
  });
}

export default async function SwellAnalyzerPage({ searchParams }: Props) {
  const params = await searchParams;
  const beachSlug = params.beach;

  let initialData = undefined;
  if (beachSlug) {
    const result = await getSwellAnalyzerData(beachSlug);
    if (result.success) {
      initialData = result.data;
    }
  }

  const SWELL_FAQ_ITEMS = [
    {
      question: "Is an 8-second swell period good for surfing?",
      answer:
        "An 8-second period is borderline between wind swell and groundswell. You'll get rideable waves, but they lack the power of longer-period swells. For most breaks, 10s+ starts to feel significantly better — 12s+ is where things get exciting.",
    },
    {
      question: "What is the difference between groundswell and windswell?",
      answer:
        "Groundswell (12s+ period) is generated by distant storms and arrives as clean, organized energy. Windswell (under 8s) is created by local winds, producing choppy, close-together waves. Groundswell breaks more powerfully and predictably.",
    },
    {
      question: "Why does swell direction matter for surfing?",
      answer:
        "Every beach has a geographic orientation that determines which swell directions it receives. A swell from outside a beach's exposure window may be blocked by headlands or arrive at a bad angle, causing closeouts instead of clean, peeling waves.",
    },
    {
      question: "What does a swell window mean?",
      answer:
        "A swell window is the range of directions that produce the best waves at a specific break. For example, a point break might fire on swells from 270-315 degrees (W to NW) but be poor on south swells. Quiver maps each beach's swell window from local knowledge.",
    },
  ];

  return (
    <>
      <BreadcrumbStructuredData
        items={[
          { name: "Home", url: SITE_URL },
          { name: "Free Tools", url: `${SITE_URL}/tools` },
          { name: "Swell Quality Analyzer", url: `${SITE_URL}/tools/swell-analyzer` },
        ]}
      />
      <FAQSchema items={SWELL_FAQ_ITEMS} />
      <SwellAnalyzerClient initialData={initialData} />
    </>
  );
}
